### ISSUE TITLE
IE bug

### ISSUE THREAD

**Issue by aliarshad9691** [zenorocha/clipboard.js#103]
when we use this library in IE, it asks for user permission *I know we can disable it, but by-default its enabled*
if the user deny access to clipboard, the API show trigger error, instead it trigger success even nothing is copied in clipboard...

**Comment by zenorocha** [comment]
Thanks @aliarshad9691, this problem is already described in the [Known Issues](https://github.com/zenorocha/clipboard.js/wiki/Known-Issues) wiki
