### ISSUE TITLE
v1.5.0 broken on Firefox

### ISSUE THREAD

**Issue by craigjennings11** [zenorocha/clipboard.js#104]
- Clipboard version: `1.5.0`
- Browser: Firefox `41.0.2`
- Bug: Doesn't copy the text. Checked in latest Chrome & IE11 and it still works. If I revert to `1.4.2` of the library, it works on Firefox.
- Reproduction: Open up http://clipboardjs.com/ and try the examples in Firefox, none work.

**Comment by zenorocha** [comment]
Thank you so much for reporting this @craigjennings11!

Just released [1.5.1](https://github.com/zenorocha/clipboard.js/releases/tag/v1.5.1) which fixes this bug.

**Comment by craigjennings11** [comment]
Thanks for the quick turn-around!

**Comment by zenorocha** [comment]
:tada:
