### ISSUE TITLE
Review "main" and "browser" entries on package.json

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/clipboard.js#105]
Both browserify and webpack relies on `main`and `browser` fields and we want to improve the user experience when requiring this module.

> Related to #15 #27

**Comment by zenorocha** [comment]
This includes moving `browserify` and `babelify` out from  `dependencies` to `devDependencies` https://github.com/zenorocha/clipboard.js/blob/master/package.json#L25-L26

**Comment by Vekat** [comment]
So, as far as I know, the `browser` field is only used by module bundlers in its simplest form (a string value pointing to the alternative main file).

If for some reason module bundler users prefer to work with unbundled files, then as pointed out by @daviferreira, we could add a folder with babel compiled sources (not yet bundled), and set the `browser` field to point to those files.
