### ISSUE TITLE
Copy from hidden field in Chrome not working

### ISSUE THREAD

**Issue by harrislapiroff** [zenorocha/clipboard.js#107]
I'm having an issue where I can't get Chrome to copy from a "hidden" field, including fields that have been hidden using a technique like setting the parent container CSS to `height: 0; width: 0;`. I'll try to whip up an example case shortly, but I wanted to make a ticket in case I don't get around to it.

**Comment by zenorocha** [comment]
Yes, that is for security reasons. You can do that by using the imperative API:

```js
new Clipboard('.btn', {
    text: function() {
        return document.querySelector('input').value;
    }
});
```

**Comment by harrislapiroff** [comment]
Okay, thanks. It might be worth a note in the docs if a workaround won't be implemented in the library. It was a trick that surprised me and took a fair amount of time to track down its cause. (I was particularly surprised that it was affected by hiding via the sizing of parent elements! Very unexpected, but good security.)
