### ISSUE TITLE
cancel and custom trigger?

### ISSUE THREAD

**Issue by janusch** [zenorocha/clipboard.js#109]
Hey,
thank you for creating this library, it solves so many problems of the past with the clipboard api.

I am using it to clipboarding stuff from a table.

Was wondering about three small issue or shortcomings:

* How do you cancel the event if the selection is empty? 
right now I have to return a space character, is there another way to set `nothing` as text or simply return nothing and leave the clipboard undisturbed?

* When the text returned is empty, or some arbitrary string that should not go into the clipboard, how can that be prevented? I have tried using `e.clearSelection()` in the `success` handler and the function is being called, but does not clear the clipboard.

* Is it possible to specify another event trigger than `click`, could be nice with `Alt + click`?

Thank you again for this tiny little gem of usefulness!

**Comment by vekat** [comment]
I think you have a good point about "empty" selections, and the modifier key during `click` could be implemented as an additional option for the `Clipboard` constructor.

**Comment by zenorocha** [comment]
Hey @janusch,

1,2) Have you tried using the [imperative API](https://github.com/zenorocha/clipboard.js#advanced-options)? This seems to be related to how your markup is defined and what selectors you're using. Please provide an isolated code using JSFiddle (or any other tool) so we can better help you.

3) At this moment, we do not offer the possibility to change the event trigger. A solution would be using @vekat's fork https://github.com/vekat/clipboard.js/commit/90968ce7900f9eda4dc7b92527e443d605477e97 which fixes that for you but beware that this is not going to work on mobile devices.
