### ISSUE TITLE
data-clipboard-target copies selection from outside target

### ISSUE THREAD

**Issue by Fantasterei** [zenorocha/clipboard.js#111]
The attribute data-clipboard-target isnt working correctly. I set the target to a modal-window but clipboard also contains content from outside of the target. Target is the "#modal blockquote" you can see in the screenshot, but it also selects content (NÄCHSTE RESULTATE) from the button in the footer (dark gray selected).

<img width="1410" alt="" src="https://cloud.githubusercontent.com/assets/9024849/10849126/79a2fd9c-7f1f-11e5-950b-9bfcf8aecc82.png">

**Comment by zenorocha** [comment]
Could you share a JSFiddle reproducing that error?

**Comment by Fantasterei** [comment]
Right button inside the modal is linked to your scripts.
On click there is the text of the two buttons outside the modal:

https://jsfiddle.net/akstv6Lm/2/

**Comment by zenorocha** [comment]
Awesome! ;)
