### ISSUE TITLE
Perform copy on double click

### ISSUE THREAD

**Issue by benhanks040888** [zenorocha/clipboard.js#112]
Hi, is it possible to perform the copy only on double click?

I want to use a span, not a button, with value in it and perform copy if user double clicks on the span. Something like this:

`<span data-clipboard-text="Something to copy">Double click to copy</span>`

**Comment by zenorocha** [comment]
Hey @benhanks040888,

At this moment, we do not offer the possibility to change the event trigger.

A solution would be forking this project and changing from `click` to `dblclick` at https://github.com/zenorocha/clipboard.js/blob/master/src/clipboard.js#L37 but beware that this is not going to work on mobile devices.
