### ISSUE TITLE
'Discontiguous selection is not supported' error

### ISSUE THREAD

**Issue by rolka** [zenorocha/clipboard.js#114]
Hi,

I get a "Discontiguous selection is not supported." error in console.

![clipboard js error](https://cloud.githubusercontent.com/assets/1561437/10910175/9595f7c8-8246-11e5-81b3-5b73abdf0006.png)

The weird part is that I don't get that error on every "Copy" button click. You can try it here: http://rolka.github.io/fb/dev/

Source: https://github.com/rolka/fb/blob/gh-pages/dev/index.html

Browser: latest Chrome.

OS: Windows 7.

Thanks in advance :)

**Comment by zenorocha** [comment]
@rolka you're loading an older version because RawGit has a very aggressive cache.

Try specifying the latest version: https://github.com/zenorocha/clipboard.js/wiki/CDN-Providers

**Comment by rolka** [comment]
@zenorocha, obrigado por sua ajuda :)

**Comment by kafeltz** [comment]
Usar o RawGit não né! Nem dropbox pra um fim como esse!

**Comment by zenorocha** [comment]
Não tem problema nenhum em usar o RawGit, eles usam MaxCDN por baixo.
