### ISSUE TITLE
Copy the Data at Two different Places

### ISSUE THREAD

**Issue by jt4000** [zenorocha/clipboard.js#116]
Hello!

This tool is great I need help with one thing!

Is it possible to make make a copy of two object (located in different place) at the same time?

Please take a look at the link below. I would like to copy "#foooo1" and "#foooo2" with the button "third button" 
In my context I cannot have the data of "#foooo1" and "#foooo2" in one place. Sorry.

http://jsbin.com/lewuqamoca/edit?html,js,console,output

Thanks!

**Comment by zenorocha** [comment]
Hey @jt4000,

You can easily do that by using the imperative API documented at: https://github.com/zenorocha/clipboard.js#advanced-options

Here's the result: http://jsbin.com/muripibozo/1/edit?html,console,output

**Comment by jt4000** [comment]
Thank your for your help!

I might have not been pedagogical of my message.

I have a list (based on the link below) that is changing continuously, you can retrieve the list between 20 and 300 rows.

Is it possible to copy the specific data when you press the button without doing any hard coding in the javascript?

Thanks!

http://jsbin.com/betokuxego/1/edit?html,console,output

**Comment by zenorocha** [comment]
Ok, this is a general JavaScript problem, that could be resolved using [previousSibling](https://developer.mozilla.org/en-US/docs/Web/API/Node/previousSibling) or any other DOM traversal command.

```
var clipboard = new Clipboard('.btn', {
    text: function(trigger) {
        return trigger.previousSibling.previousSibling.textContent;
    }
});
```

**Comment by jt4000** [comment]
I don't understand how "trigger" comes from?. How do you apply "trigger" in html?
