### ISSUE TITLE
custom delegate

### ISSUE THREAD

**Issue by ocombe** [zenorocha/clipboard.js#117]
Hello,

I have a problem with the event delegation: my element to click is wrapped into another element that prevents propagation of all click events. Since ClipboardJS delegates on body, my click never propagates to body and the clipboard action doesn't work.

I'd like to be able to disable event delegation or configure which element should be the parent on which delegation should be applied.

Do you think the could be possible ?

**Comment by zenorocha** [comment]
Hey @ocombe,

At this moment, you can't do that. A solution would be passing a NodeList in the constructor.

```js
new Clipboard(document.querySelectorAll('.btn'));
```
