### ISSUE TITLE
Copy the Data at Two different Places (Cont.)

### ISSUE THREAD

**Issue by jt4000** [zenorocha/clipboard.js#118]
Thank your for your help!

I might have not been pedagogical from y previous message.

I have a list (based on the link below) that is changing continuously, you can retrieve the list between 20 and 300 rows.

Is it possible to copy the specific data when you press the button without doing any hard coding in the javascript?

Thanks!

http://jsbin.com/betokuxego/1/edit?html,console,output

**Comment by zenorocha** [comment]
Ok, this is a general JavaScript question, that could be resolved using [previousSibling](https://developer.mozilla.org/en-US/docs/Web/API/Node/previousSibling) or any other DOM traversal command.

```js
var clipboard = new Clipboard('.btn', {
    text: function(trigger) {
        return trigger.previousSibling.previousSibling.textContent;
    }
});
```

**Comment by jt4000** [comment]
I don't understand how "trigger" comes from?. How do you apply "trigger" in html?

**Comment by zenorocha** [comment]
`trigger` is the button you clicked.

**Comment by kafeltz** [comment]
"trigger" example could be renamed to "dom", would be lightning speed intuitive =D

**Comment by zenorocha** [comment]
it doesn't matter how you're gonna call it, you just need to know that it's the element you clicked
