### ISSUE TITLE
Add feature detection method

### ISSUE THREAD

**Issue by anasnakawa** [zenorocha/clipboard.js#12]
it would be nice if there's a method that can tell us wither clipboard.js will work on current browser or not, as I don't want the copy button to show up to the end user when he cannot actually use this feature.

**Comment by zenorocha** [comment]
Hey @anasnakawa,

The API for feature detection, `document.queryCommandSupported("copy")`, is pretty messy. But you can try to use it, here's more info:

* https://developers.google.com/web/updates/2015/04/cut-and-copy-commands (Known bugs section)
* https://hacks.mozilla.org/2015/09/flash-free-clipboard-for-the-web/ (Feature detection)

You can always send a PR as well :)

But I'm curious, why the graceful degradation section described in the docs doesn't work for you?

**Comment by jekuno** [comment]
@zenorocha The graceful degradatation works. But if a user sees an input field with a copy button he expects it to copy the text from the input field with one *single click*. If one click copy doesn't work it is better to hide the copy button (selecting all text of the input field when clicking into it can be done for convenience anyway).
Therefore I agree that it would be good to have a function in `clipboard.js` which can be asked whether one click copy is possible or not.

**Comment by anasnakawa** [comment]
totally agree with @jekuno 
although the graceful degradation is a good option, but I had a cases where such user experience was not accepted, and the client preferred to either have the full functionality or nothing.

**Comment by zenorocha** [comment]
It is a valid use case, I'm pretty sure about that. The problem is that browser have not implemented it correctly yet. As pointed before, there are known bugs on Chrome and Firefox.

**Comment by zenorocha** [comment]
Here are some approaches I've found.

https://gist.github.com/jonrohan/81085b119d16cdd7868a#file-supports_copy-rb
https://github.com/zeroclipboard/zeroclipboard/issues/171#issuecomment-143791927

**Comment by tzoky07** [comment]
So basically they both check the browser version.
ZeroClipboard does an additional flash checking, preferring it over native JS method.

Since _queryCommandSupported_ is buggy and can't be relied on, we can follow the other's path and set a todo for when the API will at least stabilize a bit.

@zenorocha: should I try to approach this with a PR ?

**Comment by zenorocha** [comment]
Hey guys,

I decided to write a separate thing to fix this problem. Here's a [polyfill for document.queryCommandSupported](https://github.com/zenorocha/document.queryCommandSupported).
