### ISSUE TITLE
Can't see to get content to copy

### ISSUE THREAD

**Issue by brandonhilkert** [zenorocha/clipboard.js#121]
I've setup the library per the documentation and I'm getting everything in the output:

<img width="715" alt="screen shot 2015-11-08 at 3 36 27 pm" src="https://cloud.githubusercontent.com/assets/744212/11022483/aa8f4300-862e-11e5-8595-563a692f3042.png">

When I go to paste, the text isn't there and the previous buffer is pasted. I'm on Chrome 46 and OSX. 

Any thoughts on why I'd be getting the console output, but the text not be copied?

**Comment by zenorocha** [comment]
Hey @brandonhilkert, can you provide a JSFiddle?

**Comment by brandonhilkert** [comment]
https://jsfiddle.net/qL80e2nc/1/

**Comment by zenorocha** [comment]
You can't select a disabled element. Try using `readonly` instead.

**Comment by brandonhilkert** [comment]
Ah, that was it. Thanks!

**Comment by zenorocha** [comment]
;D
