### ISSUE TITLE
Issue when submitting an HTML element

### ISSUE THREAD

**Issue by louisameline** [zenorocha/clipboard.js#122]
Hi, I think there is an issue when doing this:

```$('.button').each(function(i, el){
    var clipboard = new Clipboard(el);
});```

I get this error: `Uncaught Error: Missing required attributes, use either "target" or "text"`

The attribute is however well defined and it works when I submit the selector of the element instead.

Thanks

**Comment by pawlufelice** [comment]
I posted about the same issue (the other open issue). What happens is that you have an element inside the element you are attaching clipboard to, and you are clicking on it :)

**Comment by louisameline** [comment]
Damn, shame on me! I looked briefly at the issue titles and assumed it was something different. I'll leave open for the incentive though ;)

References #119

**Comment by pawlufelice** [comment]
no probs :) yes that's good. If you want, until the issue is resolved you can apply the fix I posted on the other issue :P maybe it works :)

**Comment by zenorocha** [comment]
Moving discussion to #119.
