### ISSUE TITLE
Update Readme to clarify that selection doesn't work in Safari on iOS

### ISSUE THREAD

**Issue by agwells** [zenorocha/clipboard.js#124]
From reading through Issue #26, and from testing http://clipboardjs.com/ on an iPad running iOS 9.0, it seems that clipboard.js's current behavior in Safari on iOS is that it moves the text cursor into the copyable element (if it's an editable element, like an input or a textarea).

This runs contrary to how I interpreted the Readme, which says "Although copy/cut operations with execCommand aren't supported on Safari yet (including mobile), it gracefully degrades because Selection is supported."

I see there is some development towards getting text selection working on Safari mobile, but until that gets added into clipboard.js it would be helpful to clarify that the fallback behavior in iOS is cursor placement, not text selection.

**Comment by zenorocha** [comment]
Hey @agwells,

Thanks for pointing this out. Selection now works on iOS Safari `<input>` and `<textarea>` elements: https://github.com/zenorocha/clipboard.js/releases/tag/v1.5.5

**Comment by zenorocha** [comment]
Moved this information for [Known Limitations](https://github.com/zenorocha/clipboard.js/wiki/Known-Limitations)
