### ISSUE TITLE
Imperative API does not work 

### ISSUE THREAD

**Issue by avindra** [zenorocha/clipboard.js#127]
```
new Clipboard('', {
    text: function(trigger) {
        return "TEST1234";
    }
});
```

This does not set my clipboard to ```TEST1234```. Am I missing something?

**Comment by kafeltz** [comment]
Missing some *dom* element to work with? I would rather make a global function to do this job than installing a plugin for this. What am I missing?

**Comment by zenorocha** [comment]
Hey @avindra, the first argument is missing.

Here's a simple working example: http://jsfiddle.net/zenorocha/5b8r8hg5/1/

**Comment by avindra** [comment]
I don't understand - are you saying that some abritrary DOM element is required? If so... why?

**Comment by zenorocha** [comment]
Yes, user interaction is required for security reasons. That's how the browser works, not my fault ;)

**Comment by FagnerMartinsBrack** [comment]
> Yes, user interaction is required for security reasons. That's how the browser works, not my fault ;)

@zenorocha I suggest documenting those things, to prevent [abstraction leak](https://en.wikipedia.org/wiki/Leaky_abstraction), see #130.
