### ISSUE TITLE
preserve html formatting?

### ISSUE THREAD

**Issue by spovich** [zenorocha/clipboard.js#128]
This is a really nice library!  Thank you!

Question: I want to preserve html formatting (not escaped) for content copied to clipboard.  This works when I have a `data-clipboard-target`, but if I put the same content in `data-clipboard-text`, it comes out like `<b>bold</b>` rather than **bold**.  Is this a limitation of using `data-clipboard-text` vs `data-clipboard-target`?

**Comment by kafeltz** [comment]
For me, coming scaped makes sense. How or What you going to do with the content is beyond the scope of the purpose the plugin. Check some javascript code/decode html entities, it may help.

**Comment by spovich** [comment]
Ok, thanks!

**Comment by zenorocha** [comment]
Hey @spovich, `text` copies a string whereas `target` copies an HTML element.
