### ISSUE TITLE
Not really 2KB. ;-)

### ISSUE THREAD

**Issue by lgarron** [zenorocha/clipboard.js#129]
`clipboard.min.js` is more like 9KB in the latest release.

(Disclaimer: I'm trying to create a comparison between this project and [another of the same name](https://github.com/lgarron/clipboard.js) right now. I want to be charitable, but accurate.)

**Comment by zenorocha** [comment]
Duplicated #69

**Comment by lgarron** [comment]
oic. How am I supposed to tell from the landing page?

**Comment by zenorocha** [comment]
Now you know ;)

**Comment by lgarron** [comment]
> Now you know ;)

Thanks; much clearer! :-)

**Comment by kafeltz** [comment]
dejavu!
