### ISSUE TITLE
Why export a global?

### ISSUE THREAD

**Issue by ibc** [zenorocha/clipboard.js#13]
Being a npm library it would really make sense that the exported object/class would not be global, but instead the user should call `var clipboard = require('clipboard')` as usual.

Please don't pollute the brower's `window` namespace if a JS loader is detected.

**Comment by ibc** [comment]
NOTE: The problem is in https://github.com/zenorocha/clipboard.js/blob/master/src/clipboard.js#L87

```js
global.Clipboard = Clipboard;
```

**Comment by mauriciosoares** [comment]
Hey @ibc, I think this PR will fix your problem:

https://github.com/zenorocha/clipboard.js/pull/16

what you think?

**Comment by ibc** [comment]
Not exactly. Indeed, when using this library within a classic `<script>` tag (without a JS loader such as requireJS, etc) the `--standalone` option of browserify is needed. Otherwise the library would not export anything to the `window` namespace and the rest of the JS code could not use this lib.

However, if I load this lib within a Node project (via `require()`) or use requireJS or any other JS loader within a browser app, this lib will still export `window.Clipboard` due to the [line above](https://github.com/zenorocha/clipboard.js/blob/master/src/clipboard.js#L87).

What I mean is that such a line should just be removed.

**Comment by jaydson** [comment]
Plus one for that.
As the library is already using ES6 modules, it would be nice just import it from the app.
```
import Clipboard from './clipboard';
```

**Comment by cironunes** [comment]
+1 for ES6 modules

**Comment by mauriciosoares** [comment]
@ibc In this PR I removed the line you mentioned...

:)

**Comment by ibc** [comment]
Sorry, I missed it :)

**Comment by eduardolundgren** [comment]
Agreed. Would be good to provide different build outputs, globals/amd/es6.

**Comment by zenorocha** [comment]
@ibc could you confirm that this solution works for you?

Thanks for another contribution @mauriciosoares, you rock! :fire:

**Comment by ibc** [comment]
Sorry, I've not even tested the lib yet. Will do soon.

**Comment by mauriciosoares** [comment]
@zenorocha, I tested locally and it seems to work... Also the tests are passing, I think that'll do the trick :)

But take your time to merge the PR.

**Comment by zenorocha** [comment]
Merged and published! https://github.com/zenorocha/clipboard.js/releases

Thanks @ibc for reporting and @mauriciosoares for fixing it ;)

**Comment by zenorocha** [comment]
By the way, does this close #15?

**Comment by mauriciosoares** [comment]
Unfortunately not... I was testing it, but it still have some bugs.

I'm having the same problem with my library, as soon as I find a solution for my project, I'll also PR here.

:)
