### ISSUE TITLE
The input element's type ('hidden') does not support selection.

### ISSUE THREAD

**Issue by andreaValenzi** [zenorocha/clipboard.js#133]
It doesn't work with type="hidden" on input element,
this is the error:
"Uncaught InvalidStateError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('hidden') does not support selection."

**Comment by oskarcieslik** [comment]
Hi, what browser do you use (version)?

This example works on Chrome 46 for me:
https://jsbin.com/mapibilino/edit?html,js,console,output

**Comment by zenorocha** [comment]
Yes, that's for security reasons. You can make a workaround by using the imperative API:

```js
new Clipboard('.btn', {
    text: function() {
        return document.querySelector('input').value;
    }
});
```

**Comment by Mecanik** [comment]
This solution does not work anymore...

**Comment by igneosaur** [comment]
This will copy the `value` property if it's available and will fall back to the element's `innerHTML`.

```js
new Clipboard('.btn', {
                text: ({ dataset: { clipboardTarget } }) => {
                    const { value, innerHTML } = document.querySelector(clipboardTarget);
                    return value || innerHTML;
                }
            });
```
