### ISSUE TITLE
Making work with this program...

### ISSUE THREAD

**Issue by 2braincells2go** [zenorocha/clipboard.js#135]
I know this is not a real issue, more a plead for assistance:)

Trying to use https://github.com/ssokurenko/jquery-mobile-password-generator in a classroom project and need a copy to clipboard function.

Have tried for days to get clipboard.js working with above but failed over and over.

Anyone have time to look at and see if clipboard.js will work with above?

I and students would appreciate more than you know:)

Cheers!

**Comment by zenorocha** [comment]
Hey @2braincells2go, we provide a lot of examples under the `demo` folder so you can try and adapt them to your needs: https://github.com/zenorocha/clipboard.js/tree/master/demo

Good luck with your project!
