### ISSUE TITLE
Maven minify syntax error

### ISSUE THREAD

**Issue by hmontazeri** [zenorocha/clipboard.js#136]
Hi, 

i tried to use clipboard.js in my JSF2.2 project. Maven tries to minify all js files and fails with syntax error issue. Can you help me with that?

thx hm

**Comment by zenorocha** [comment]
Sorry @hmontazeri, I don't think I can help you with that.

**Comment by cbeyer** [comment]
Same problem for me with the clipboard.js file in a Symfony2 project with YUI Compressor and yui_js filter. 

    Error Output:
    [ERROR] in /private/var/folders/1z/t8rym08s63g8gnjgf53tf0780000gn/T/assetic_yui_input1A6La8                                                                            
    150:17:il manque un nom après un opérateur '.'
    [ERROR] in /private/var/folders/1z/t8rym08s63g8gnjgf53tf0780000gn/T/assetic_yui_input1A6La8                                                                            
    154:2:il manque ']' après une liste d'éléments
    [ERROR] in /private/var/folders/1z/t8rym08s63g8gnjgf53tf0780000gn/T/assetic_yui_input1A6La8                                                                            
    156:5:il manque ')' après une liste d'arguments
    [...]
For what reason ?

**Comment by rodnaph** [comment]
Reason: https://github.com/zenorocha/clipboard.js/issues/204
