### ISSUE TITLE
Not working on Chrome despite success error firing

### ISSUE THREAD

**Issue by majestic-rweaver** [zenorocha/clipboard.js#137]
I've implemented this and it's working brilliantly in browsers as documented, except Chrome (46). The success event fires and using console I can see that e.Text contains the right text but nothing is actually added to the clipboard (I'm on Windows ).

![image](https://cloud.githubusercontent.com/assets/10864226/11394590/f7648136-935d-11e5-896a-e477c3958b5d.png)

I ran document.queryCommandSupported('copy') in console and it reported false but then Googled and saw Chromium bug 476508 and your polyfill. I've added the polyfill into my page and whilst document.queryCommandSupported('copy') now reports true, clipboard adding still doesn't work.

**Comment by suddenelfilio** [comment]
I have somthing similar in IE 11. It worked once, but after that it never works again although I get a succes event fired

**Comment by zenorocha** [comment]
Everything seems to be working fine here. Please share a minimal JSFiddle [like this](http://jsfiddle.net/zenorocha/n5pLh1rk/) so we can investigate properly.

**Comment by zenorocha** [comment]
Closing this one since there was no response. Let me know if you're still facing this error or not.
