### ISSUE TITLE
Get the original click event in the 'success' / 'error' events

### ISSUE THREAD

**Issue by a-k-g** [zenorocha/clipboard.js#138]
Hey,

This is a pretty cool library and it's working quite nicely for me. I have a use case where I'd like to stop propagation of the click event depending on whether the copy succeeded/failed. To be able to do that, I have one feature request - in the 'success' / 'error' events, it would be nice to get the original click event.

Thanks!

**Comment by zenorocha** [comment]
Hey @a-k-g,

In order to do that, instead of a string you can pass [an element](https://github.com/zenorocha/clipboard.js/blob/master/demo/constructor-node.html#L16-L19) or a [list of elements](https://github.com/zenorocha/clipboard.js/blob/master/demo/constructor-nodelist.html#L16-L19).

**Comment by seriyps** [comment]
I need the same thing and I can't make it work - I pass result of querySelectorAll (NodeList) to Clipboard constructor and the only argument I got in 'success' callback still contains only 3 elements: 'action', 'text' and 'trigger'

**Comment by zenorocha** [comment]
What exactly are you looking for in the click event?

**Comment by seriyps** [comment]
I want to stop event propagation, because clicking on area, surrounding 'copy' button, has another very different meaning and event handler.

**Comment by raphaelyancey** [comment]
@zenorocha Passing an element to Clipboard constructor doesn't bring the original click event as previsouly said. What did you mean by that? Thanks for your library anyway.
