### ISSUE TITLE
Does this not work in safari anyone?

### ISSUE THREAD

**Issue by mattietea** [zenorocha/clipboard.js#139]
Hi!

I could be doing something wrong but I've tried using both your website and mine in safari and it doesn't work. 

Is there something i need to add or does it not work in safari for now?

Thanks!

**Comment by zenorocha** [comment]
Hey @mattietea, you can find more info about browser support at https://github.com/zenorocha/clipboard.js#browser-support or http://clipboardjs.com/#browser-support

**Comment by mattietea** [comment]
Oh wow, that was stupid of me ahah. Sorry about that! Thanks for the reply
