### ISSUE TITLE
Bind not working on new elements

### ISSUE THREAD

**Issue by magroski** [zenorocha/clipboard.js#140]
I'm trying to use clipboard with elements included via ajax, but it's not working.

```
$.ajax({
   type : 'post',
   data : data,
   url : url,
   success : function(data){
      $('#container').append(data); //Let's suppose that data is <span class="copy" data-clipboard-text="text">copy me!</span>
      new Clipboard('.copy');
   }
});

```

What am I missing?

**Comment by zenorocha** [comment]
Have you fixed it?

**Comment by magroski** [comment]
Yeah, after digging through my code I realized that I was blocking - stopPropagation() - the click event elsewhere. Your plugin works fine :)

**Comment by zenorocha** [comment]
;)
