### ISSUE TITLE
Work around Firefox "mutating the [[Prototype]] of an object..." warning

### ISSUE THREAD

**Issue by jonkri** [zenorocha/clipboard.js#141]
Hi!

Thanks for a nice library!

I have found that [this line](https://github.com/zenorocha/clipboard.js/blob/c12c610b22a0d696bb170ecdb50996d5cc189070/dist/clipboard.js#L594) results in the following warning getting printed in the Firefox console:

<blockquote>mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create</blockquote>

Is there perhaps some way in which clipboard.js could be refactored so that this warning would not be generated?

Cheers!

**Comment by zenorocha** [comment]
Hey @jonkri, thanks for reporting.

It's an unavoidable side-effect of using Babel's transpilation for classes. https://github.com/zenorocha/clipboard.js/blob/3188ffbce3ba6404c8ae0584d028ff1a26a42ebc/dist/clipboard.js#L594

**Comment by jonkri** [comment]
Could a solution be to not use use the output of Babel's transpilation in that particular area of the code?

**Comment by zenorocha** [comment]
The only way to prevent that would not be using classes which is not gonna happen. This is an issue that should be reported to Babel.

**Comment by voidstate** [comment]
Also getting this error.

**Comment by zenorocha** [comment]
Nothing to do here... it's a core-js (which is a babel dependency) issue.

https://github.com/zloirock/core-js/issues/46

https://phabricator.babeljs.io/T1099
https://github.com/yahoo/fluxible/issues/318
https://github.com/reactjs/react-router/issues/1155
