### ISSUE TITLE
Open source snippets.js and tooltips.js

### ISSUE THREAD

**Issue by nasht00** [zenorocha/clipboard.js#144]
On your demo site, in addition to clipboard.js I see you wrote 2 javascript files:

- https://zenorocha.github.io/clipboard.js/assets/scripts/snippets.js
- https://zenorocha.github.io/clipboard.js/assets/scripts/tooltips.js

Are they open source as well with the same license?

**Comment by zenorocha** [comment]
Yep, feel free to use it ;)

https://github.com/zenorocha/clipboard.js/tree/gh-pages
