### ISSUE TITLE
Expose `ClipboardAction`

### ISSUE THREAD

**Issue by sandstrom** [zenorocha/clipboard.js#151]
This is an excellent library! :boat: 

Would be great if one could interface directly with `ClipboardAction`. With a SPA action-handling etc. is already taken care of by the framework.

**Comment by zenorocha** [comment]
Hey @sandstrom, thanks!

Here are some alternatives for React, Angular, etc: https://github.com/zenorocha/clipboard.js/wiki#have-you-built-a-clipboardjs-wrapper

Duplicated from #66

**Comment by sandstrom** [comment]
@zenorocha thanks!

I ended up using vanilla js (in this situation I only needed support for  evergreen browsers). Copied below in case it helps someone.

```js
var el = document.querySelector('#myEl');
el.focus();
el.setSelectionRange(0, el.value.length);

var result = document.execCommand('copy');
if (result) {
  # notify here...
  document.activeElement.blur(); # clear focus
}
```

**Comment by zenorocha** [comment]
Awesome ;)
