### ISSUE TITLE
How to simply copy a text to clipboard via JS?

### ISSUE THREAD

**Issue by Bluscream** [zenorocha/clipboard.js#153]
How do i execute a simple "copy this text to clipboard" function?

Like
```js
var _text = "This text will be in your clipboard now.";
new Clipboard(_text);
```

**Comment by Bluscream** [comment]
I already tried almost everthing:

```js
				$.jAlert({
					'title': username +'\'s Info',
					'content': '<table style="width:100%"><tr><td><b>Name: </b></td><td>'+username+'</td></tr><tr><td><b>UID: </b></td><td>'+id+'</td></tr><tr><td><b>Name by ID: </b></td><td>'+name+'</td></tr></table></>',
					'theme': 'blue',
					// 'class': 'ja_body',
					'id': 'ja_body',
					'btns': [ {
						'text': 'Copy',
						'class': 'btn_copy',
						'onClick': function(e, btn) { new Clipboard('ja_body'); BetterAPI.log(1, "log", userInfo.prototype.getName()+": ",'Copied \"'+$('.ja_body').html()+'\" to clipboard.'); },
						// 'data-clipboard-target': '.ja_body'
					}, {
						'text': 'Close'
					} ]
				});
```

**Comment by zenorocha** [comment]
There are a bunch of working examples in the demo folder, check them out: https://github.com/zenorocha/clipboard.js/blob/master/demo/function-text.html

**Comment by Bluscream** [comment]
That does not really help me, sorry :)

**Comment by zenorocha** [comment]
clipboard.js has an internal click handler and that needs to be triggered in order to work.

If this lib doesn't fit your use case, you can always use the native API which is pretty simple. https://github.com/zenorocha/clipboard.js/blob/master/src/clipboard-action.js#L102
