### ISSUE TITLE
Copy failing when text is null

### ISSUE THREAD

**Issue by Nothing4You** [zenorocha/clipboard.js#154]
Hey there,

suppose I have the following code:
```html
<button id="copy-link" onclick="return false;">Copy link</button>
```
with
```js
var clipboard;
var clipboardText = null;;
clipboard = new Clipboard('button#copy-link', {
    text: function() {
        return clipboardText;
    }
});
clipboard.on('success', function(e) {
    // success animation
});
clipboard.on('error', function(e) {
    // Custom error-catching prompt wrapper
    tryPrompt("You can copy the link with Control+C", clipboardText);
});
```
The content of `clipboardText` is dynamically set depending on what is currently needed.
Sometimes there is no link available, in which case I want to inform the user about that and run some other js stuff, prompting the user to provide a link.
However, due to the current check for text being set, when I return `null` it checks the same way as it would for `undefined` or even an empty string.
Is there currently any way to implement this feature?

**Comment by loter** [comment]
just make it 
return clipboardText || ' ';

**Comment by Nothing4You** [comment]
As the comment in the other issue already tells, I'd rather not copy an empty string if there is null, since clearing the clipboard isn't what I'm looking for there.

**Comment by zenorocha** [comment]
Fixed at https://github.com/zenorocha/clipboard.js/commit/7a5a910bcd83aa44718dc30caea503d9da37d4b9. Please use `v1.5.10` in order to benefit from this.

**Comment by Nothing4You** [comment]
Thanks :)
