### ISSUE TITLE
Exception with use tag inside inline svg in IE11 

### ISSUE THREAD

**Issue by rooks** [zenorocha/clipboard.js#159]
Clipboard version: `1.5.5`
IE version: `11.0.9600.18125`

Inline `svg` with `use` tag in it should be on the page. Once you created an instance of `Clipboard`, any click on such `svg` element will throw an exception in IE.
![matches-selector-error](https://cloud.githubusercontent.com/assets/878189/12182652/9050d7f6-b59a-11e5-97c9-ca56b1e4c348.png)
The actual exception occurs in [matches-selector](https://github.com/ForbesLindesay/matches-selector/blob/master/index.js#L23) module, but I'm not really sure which module it should be fixed. Dependency chain is pretty big:
`clipboard` → `good-listener` → `delegate` → `closest` → `matches-selector`

Here is a [demo](http://codepen.io/rooks/pen/wMdaEr).

Quick workaround: wrap clickable svg in a `<button>` (may not always be suitable).

**Comment by zenorocha** [comment]
Hey @rooks, thanks for reporting!

This looks like a bug either on matches-selector dependency or IE11. Please fill an issue with them.

**Comment by tedtate** [comment]
@zenorocha I've created a PR on `matches-selector` to fix this issue. However, I'm wondering if maybe it is easier for you to point your `delegate` module to https://github.com/component/closest instead. It has the necessary fix to `matches-selector` and looks to be more actively maintained.

If that sounds good to you, I will create a PR for the change.

Thanks for your work on this awesome project 👏 !

**Comment by zenorocha** [comment]
Hey @tedtate, I totally agree with you. You can go ahead and open this pull request on `delegate`. Is this https://github.com/ForbesLindesay/matches-selector/pull/2 the same error as this https://github.com/ForbesLindesay/matches-selector/pull/1?
