### ISSUE TITLE
Fallback doesn't work if the click target is nested within the trigger element

### ISSUE THREAD

**Issue by emirotin** [zenorocha/clipboard.js#160]
First, thanks for the great library.

Second, I think I've hit a bug.
My trigger (an element the clipboard instance is created with) is a span, and within it sits a clickable icon. When I debug the behavior in Safari I see the following happening in order:
* a fake textarea is created for selection
* the click event from the _icon_ reaches the body element
* the fake textarea is instantly removed

As a result Safari fallback never works for me.
Adding a click event trap on the trigger span element (catch clicks and stop propagation) after instantiating the clipboard helps. 

Third, I think you could add trivial feature detection and expose a static flag on the Clipboard class. That can be used to replicate github behavior (it hides the clip button in unsupported browser completely making it intuitive one should click into the text box).

**Comment by johnny88** [comment]
I have also been able to replicate this.

**Comment by zenorocha** [comment]
Hey @emirotin,

Could you please provide a [minimal example](http://stackoverflow.com/help/mcve) on JSFiddle that simulates this behavior?

**Comment by zenorocha** [comment]
In the meanwhile you can check an example that doesn't require delegation (https://github.com/zenorocha/clipboard.js/blob/master/demo/constructor-node.html) and this [polyfill for document.queryCommandSupported](https://github.com/zenorocha/document.queryCommandSupported).

**Comment by e-oz** [comment]
thank you very much, @emirotin, `stopPropagation()` solved my issue with Safari too.

**Comment by e-oz** [comment]
and this code allows me to display "Copied" notification:
```js
        try {
          let els = $("textarea[readonly]");
          if (els.length) {
            let t = els[(els.length-1)];
            $(t).on('keydown', (e)=> {
              if (e.keyCode===67) {
                let notify = new Notify();
                notify.success('Copied!');
                setTimeout(()=> {
                  $(els).remove();
                }, 1);
              }
            });
          }
        } catch (e) {}
```
it's from my code so it should be adapted for your project, dear reader, but I hope you got the idea.
