### ISSUE TITLE
t is null

### ISSUE THREAD

**Issue by bravo14** [zenorocha/clipboard.js#162]
I have installed clipboard.js on a website, but when the page loads I get the following error in firebug

The relevant code is as follows 

<script src="http://www.ginomanzaresracing.com/fullthrottle/library/clipboard.js"></script>

<script>
    var clipboard = new Clipboard('.copyBtn');
    </script>

<input type="button" class="button copyBtn" data-clipboard-text="http://www.ginomanzaresracing.com/news/1/manzares-launches-new-website" value="Copy Link" />

**Comment by zenorocha** [comment]
Closing this one since no code has been provided, but I'm assuming it's duplicated from https://github.com/zenorocha/clipboard.js/issues/141

**Comment by emorozov** [comment]
@zenorocha Ah, sorry, I got it. I should move initialization to the end of the body element. You may emphasize this moment in the documentation or use live handlers...
