### ISSUE TITLE
Is there flag to check if current browser support `copy` or not?

### ISSUE THREAD

**Issue by jeyraof** [zenorocha/clipboard.js#165]
I must show copy button if copy command enabled. But if not, i do not want to show button for end-user.

Any ways to deal with this?

**Comment by zenorocha** [comment]
You must use the [document.queryCommandSupported](https://developer.mozilla.org/en-US/docs/Web/API/Document/queryCommandSupported) and here's a [polyfill](https://github.com/zenorocha/document.queryCommandSupported) that normalizes its behavior on other browsers.

**Comment by jeyraof** [comment]
@zenorocha Thanks!
