### ISSUE TITLE
Copying Doesn't Work on First Click

### ISSUE THREAD

**Issue by x2adrew** [zenorocha/clipboard.js#166]
A second click copies, but not on first click. This is copying via the `data-clipboard-text` attribute. The element is dynamically generated. Here's a rundown of the code I'm using...

```
<a title="Some title" data-clipboard-text="current_url" onclick="copyToClipboard(event, this)"></a>

<script>
    function copyToClipboard(event, selector) {
            event.preventDefault();
            clipboard = new Clipboard(selector);
        }
</script>
```

**Comment by zenorocha** [comment]
That's because you don't another event listener. See https://github.com/zenorocha/clipboard.js/blob/master/demo/constructor-selector.html.

**Comment by x2adrew** [comment]
Took me a moment to understand what you meant, but my mistake! You don't need another event listener because the constructor itself is an event listener. Thank you.
