### ISSUE TITLE
Safari Issue for ClipBoard.js: Not allowing COPY

### ISSUE THREAD

**Issue by rahul2tiw** [zenorocha/clipboard.js#168]
I would like to ask you for the issue i am facing with safari browser, as safari does not support "copy",.
In your opinion what could be the best possible solution to achieve "copy" in safari browser?

**Comment by zenorocha** [comment]
I already provide a fallback in the demos. I recommend opening https://clipboardjs.com on safari and then check the source code at: https://github.com/zenorocha/clipboard.js/tree/gh-pages/assets/scripts
