### ISSUE TITLE
Please update meteor package to 1.5.5

### ISSUE THREAD

**Issue by welelay** [zenorocha/clipboard.js#169]
I'm missing the ability to pass a node to `new ClipBoard()` in the 1.4.2 release.

**Comment by zenorocha** [comment]
Done! https://atmospherejs.com/zenorocha/clipboard

**Comment by zenorocha** [comment]
Thanks for reporting @welelay ;)

**Comment by welelay** [comment]
Thank you !
That was fast :-)
