### ISSUE TITLE
"Discontiguous selection is not supported"error when calling Selection.addRange()

### ISSUE THREAD

**Issue by supritashankar** [zenorocha/clipboard.js#17]
Line 350 in clipboard.js 

Seems like it works perfectly fine on firefox. On chrome though it gives me this error and does not copy.
@zenorocha any idea on what to do?

**Comment by zenorocha** [comment]
Yes, I have an idea on how to fix it. But for now, try running `window.getSelection().removeAllRanges();` on your `success` event.

**Comment by supritashankar** [comment]
@zenorocha nope that does not fix it :(

**Comment by zenorocha** [comment]
Could you share a JSFiddle reproducing that error?

**Comment by supritashankar** [comment]
I use data-target-text instead and it works. Though I still see the problem with data-clipboard-target. Yes will send you an a fiddle.

**Comment by nkbt** [comment]
Fixed here: https://github.com/sudodoki/copy-to-clipboard/pull/5/files

**Comment by zenorocha** [comment]
Hey @nkbt, could you send a PR?

**Comment by nkbt** [comment]
Yeah, sure, will do it today after work then.

**Comment by nkbt** [comment]
@zenorocha added PR #32
