### ISSUE TITLE
exports.function throws "unexpected token function" in Android

### ISSUE THREAD

**Issue by MarkOGDev** [zenorocha/clipboard.js#170]
Hello,

My Android phone throws this error "unexpected token function" when loading the clipboard.js script file.
This is on line 150 of clipboard.js. 
Which looks like this: 
exports.function = function(value)

I think you are naming a function 'function'.
It looks to me like android does not want you to use the word 'function' as a function name.
Is it possible for this to be changed to a different name?

Regards,
Mark.

**Comment by zenorocha** [comment]
Thanks for reporting @MarkOGDev! This was a bug fixed in https://github.com/zenorocha/good-listener/pull/5.

A new version will be released shortly.
