### ISSUE TITLE
unable to download clipboard via bower

### ISSUE THREAD

**Issue by thecodejack** [zenorocha/clipboard.js#172]
When I am trying to download clipboard via bower I am getting following error. Can you please help me here.

`bower ENOTFOUND     Package clipboard not found`

**Comment by zenorocha** [comment]
Everything seems to be working over here.

```
$ bower info clipboard

bower clipboard#*           not-cached git://github.com/zenorocha/clipboard.js.git#*
bower clipboard#*              resolve git://github.com/zenorocha/clipboard.js.git#*
bower clipboard#*             download https://github.com/zenorocha/clipboard.js/archive/v1.5.5.tar.gz
bower clipboard#*              extract archive.tar.gz
bower clipboard#*             resolved git://github.com/zenorocha/clipboard.js.git#1.5.5

{
  name: 'clipboard',
  version: '1.5.5',
  description: 'Modern copy to clipboard. No Flash. Just 2kb',
  license: 'MIT',
  main: 'dist/clipboard.js',
  ignore: [
    '/.*/',
    '/demo/',
    '/test/',
    '/.*',
    '/bower.json',
    '/karma.conf.js',
    '/src',
    '/lib'
  ],
  keywords: [
    'clipboard',
    'copy',
    'cut'
  ],
  homepage: 'https://github.com/zenorocha/clipboard.js'
}

Available versions:
  - 1.5.5
  - 1.5.4
  - 1.5.3
  - 1.5.2
  - 1.5.1
  - 1.5.0
  - 1.4.3
  - 1.4.2
  - 1.4.1
  - 1.4.0
  - 1.3.1
  - 1.3.0
  - 1.2.0
  - 1.1.0
  - 1.0.0

You can request info for a specific version with 'bower info clipboard#<version>'
```

**Comment by meetjonblack** [comment]
I am currently getting this error.  It is only happening within my specific project.  If I try to use bower install outside of the project, then everything works fine.  This has only happened with this specific plugin.  It may have something to do with my configuration, but the fact that somebody else has had this problem and also this error only occurs with clipboard.js, makes me feel like it could have something to do with the bower package.

**Comment by zenorocha** [comment]
Could you share your bower.json and the error trace?

**Comment by meetjonblack** [comment]
bower.json
```
{
  "name": "test",
  "version": "1.0.0",
  "authors": [
    "jon-claude@aurastudiosdc.com"
  ],
  "description": "app platform",
  "main": "index.html",
  "moduleType": [
    "amd"
  ],
  "keywords": [
    "app"
  ],
  "license": "MIT",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "clipboard": "~1.5.9"
  }
}

```
Error Trace
`bower clipboard#~1.5.9       ENOTFOUND Package clipboard not found`

FYI, I have gotten this message no matter how I have configured my bower.json.

**Comment by zenorocha** [comment]
Just tested your bower json and ran bower install. Everything seems to be working here.

Make sure you're using the latest bower version or open an issue with bower.

```
bower cached        git://github.com/zenorocha/clipboard.js.git#1.5.9
bower validate      1.5.9 against git://github.com/zenorocha/clipboard.js.git#~1.5.9
bower install       clipboard#1.5.9

clipboard#1.5.9 bower_components/clipboard
```

**Comment by meetjonblack** [comment]
I'm definitely using the most recent version of bower.  I've done a lot of different things, and coming here was my very last resort.  It just seems pretty weird that it only happens with this package and nothing else.  Sadly, I guess I'll have to look for an alternate solution.  Anyways thanks for your help!

**Comment by zenorocha** [comment]
Sorry about that, there's no way for me to reproduce this bug.

**Comment by meetjonblack** [comment]
Okay I figured it out.  I am using a private registry and apparently it has a limited amount of packages that I am receiving.  If anybody else is having the same error, definitely make sure to check your bower configuration registry.
