### ISSUE TITLE
Copy to clipboard doesn't seem to work when performed after webrequest (or after more than 1sec delay)

### ISSUE THREAD

**Issue by merijndejonge** [zenorocha/clipboard.js#173]
Hi,
I'm looking for a way to copy the result of a web-service call on the clipboard. This doesn't seem to work with clipboard.js. I tried with a dummy div in my html which I pass to the constructor of Clipboard. After the user presses a button, I send a request to my web server. When I receive the response, I call the click() method on the div. This does not work. Without the web service call it does work however. My guess is that this is caused by the time delay between calling the web service and receiving the response.

Does anyone know a way to tackle this? I've created a fiddle that demonstrates the problem: http://jsfiddle.net/mdejonge/d5v86w59/.

Thanks in advance!

Merijn

**Comment by lgarron** [comment]
Browsers require the copy event to be triggered directly by a user gesture. There might be a grace period, but unfortunately it's not directly intended that this use case is not supported.

**Comment by zenorocha** [comment]
@lgarron is right. If you need any asynchronous operation to be done, you'll have to make it and store the result somewhere before the user clicks.
