### ISSUE TITLE
Copying brings the viewport back to the top

### ISSUE THREAD

**Issue by alligatorio** [zenorocha/clipboard.js#174]
Running into a small issue. Wherever I copy something with Clipboard.js, the page goes right back to the top. You can see the problem on that page: https://alligator.io/css/font-shorthand/

If you scroll a little and then click on the copy button, the page goes right back to top. I even added something like this, but it doesn’t help:

$( '.copy-to-clipboard' ).click(function( event ) {
    event.preventDefault();
});

Maybe it has nothing to do with clipboard.js, but I wanted to ask just in case.

**Comment by zenorocha** [comment]
It's not related to clipboard.js. You're using a `href="#"` attribute on a button. Links contain this type of attribute, not buttons.

**Comment by zenorocha** [comment]
P.S.: Congratulations on this project, looks pretty nice!

**Comment by alligatorio** [comment]
Thanks for the good words @zenorocha !

And thanks for realizing that I left the href="#" in there by mistake. That's because I tried to make it work with an anchor instead of a button, but I had the same problem.

Even after removing the href="#", the problem still seems to happen. Here's an example of where it happens: https://alligator.io/jquery/document-ready/

Thanks again for looking into this!

**Comment by zenorocha** [comment]
Are you using the latest version?

**Comment by alligatorio** [comment]
Yes, I'm using v1.5.5

**Comment by kafeltz** [comment]
@alippai you have 7 onclick event bound in this <a>. I can't understand why it would needed so much. Your prevent-default is correct, but other 6 events maybe is not.

Is ugly, but you could try to unbind all events in this dom and then attach $( '.copy-to-clipboard' )

**Comment by kandebonfim** [comment]
@kafeltz :point_up: :+1:

**Comment by alligatorio** [comment]
I figured it out!

I had **overflow-x: hidden;** and **overflow-y: scroll;** on the html element, and somehow that's what was causing this. I've now been about to remove those overflow properties on the html element and keep them on the body element only, and boom it works perfectly!

Thanks so much for the help in trying to figure that one out!
