### ISSUE TITLE
Doesn't work on Firefox

### ISSUE THREAD

**Issue by corysimmons** [zenorocha/clipboard.js#175]
FF console throws this and the button simply doesn't copy anything to clipboard:

```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
```

I've init'd clipboard with `new Clipboard('.btn-clipboard')`

**Comment by zenorocha** [comment]
This is not an error, it's a warning message (duplicated from #141).

Please share a [minimal example](http://stackoverflow.com/help/mcve) in a JSFiddle or something so we can debug it.

**Comment by corysimmons** [comment]
Oh I'm sorry for the duplicate Issue. I should've checked before reporting. Thanks
