### ISSUE TITLE
clipboard.js and RequireJS

### ISSUE THREAD

**Issue by chrismetcalf** [zenorocha/clipboard.js#176]
I've been racking my brain on it, but I can't figure out the right way to wrap `clipboard.js` to work with RequireJS. Has anybody pulled that off before?

**Comment by zenorocha** [comment]
Could you be more specific?

**Comment by alexanderbird** [comment]
I'm also having an issue with this, maybe it's the same problem: 

## Works: require explicitly without requirejs
### index.html:
        <script src="js/lib/clipboard.min.js"></script>
        <script src="/js/require.js" data-main="/js/main"></script>

### js file that uses clipboardjs:
    define(['jquery'], function($) {

## Doesn't work: use requirejs; require after jQuery
don't include it in index.html, instead use the normal requirejs way:
    define(['jquery', 'lib/clipboard.min'], function($) {

Error: Uncaught ReferenceError: Clipboard is not defined

## Doesn't work: use requirejs; require before jQuery
    define(['lib/clipboard.min', 'jquery'], function($) {

Error: require.js:19 TypeError: $.extend is not a function(…)
clipboard.min.js:7 Uncaught TypeError: Cannot call a class as a function


@chrismetcalf, is this the sort of issue you're experiencing?

**Comment by chrismetcalf** [comment]
@alexanderbird Yep! Thank you for filing a much better bug report than me! :beers:

**Comment by zenorocha** [comment]
Feel free to send a pull request guys, I don't really use require.js.

**Comment by alexanderbird** [comment]
Thanks for the response. 

I won’t have any time to work on this in the near future, but I may circle back and take a look at it some time down the road.

**Comment by kafeltz** [comment]
I think it's a matter to wrap the code with UMD, right?

**Comment by albabsaifi** [comment]
Here's the fix: [https://github.com/zenorocha/clipboard.js/issues/296#issuecomment-381124824](https://github.com/zenorocha/clipboard.js/issues/296#issuecomment-381124824)

**Comment by waterfan312** [comment]
Maybe the parameter u named is the function which u can called

**Comment by varphper** [comment]
> I've been racking my brain on it, but I can't figure out the right way to wrap `clipboard.js` to work with RequireJS. Has anybody pulled that off before?

requirejs.config({
    appDir: '.',
    paths: {
        'clipboard': ['js/path/clipboard.min']
    }
});

require(['clipboard'], function(Clipboard) {
    var clipboard = new Clipboard('.btn');//selector

    clipboard.on('success', function(e) {
        console.log(e);
    });

    clipboard.on('error', function(e) {
        console.log(e);
    });
});
