### ISSUE TITLE
Scrolls body 10px up if using data-clipboard-text

### ISSUE THREAD

**Issue by jayphelps** [zenorocha/clipboard.js#179]
In Chrome and Safari (but not Firefox), when I use the `data-clipboard-text` attribute, it goes down the different code path of creating a `<textarea>` named `fakeElem` and inserts it into the DOM, which in my case for some reason causes the page to shift up 10px when the call to select.js causes `textarea.focus()`.

When I try to create an isolated example, I cannot reproduce it so my guess is: 1. My code is the issue, or 2. the [`top` value of the fake element](https://github.com/zenorocha/clipboard.js/blob/31e3622e17f3d2fce7621fe480a85d53ec8a87e7/src/clipboard-action.js#L63) is not correct in my case.

Trying to use either `data-clipboard-target` or pass in a target option getter is not an option for me because the text they see and the text they want in the clipboard is slightly different and hiding my own textarea off screen causes the eventual `textarea.focus()` to scroll the page to the top.

Here's a video of me reproducing it: https://www.dropbox.com/s/ig0b5lwj6s1s40h/scroll%20bug.mov?dl=0

In the video, I "attempt" to prove that no other code is causing it since the select.js `focus() call triggers the change in scroll position.

Contrived example code using my exact configuration, but this code does not reproduce it outside of the whole app. I realize not being able to provide a reproducible example makes it really tough for anyone else to debug, but hoping for some spitball ideas on where I should be looking.

```js
class Example extends Component {
  componentDidMount() {
    const element = ReactDOM.findDOMNode(this);
    this.clipboard = new Clipboard(element);
  }

  componentWillUnmount() {
    this.clipboard.destroy();
  }

  render() {
    return (
      <i
        className="cell-clipboard-icon mini grey copy icon"
        title="Copy Raw to Clipboard"
        data-clipboard-text={this.props.renderedData}
      />
    );
  }
}
```
I didn't report this on https://github.com/zenorocha/select because I believe this behavior is simply the browser scrolling to the textarea, which would not be a bug with that project.

*I really hope I'm just missing something and having a bad day*

**Comment by jayphelps** [comment]
I'm going to dig into theory number 2, that the `top` position isn't what we think it is in this case, still wanted to report my findings here for others who may keyword search later.

**Comment by jayphelps** [comment]
For reasons I cannot figure out, all the numbers check out, but the textarea is indeed not at the exact top of the viewport, its top is 14px above it, seemingly explaining why this is happening, although 14px !== 10px, perhaps Chrome doesn't scroll to to the exact top of the element and instead scrolls to the visual top of the text inside it? I'm totally guessing at this point.

![image](https://cloud.githubusercontent.com/assets/762949/12809680/dccb7cb2-cad5-11e5-9e94-37de0eb526d9.png)

After I set `left: 0px`

![image](https://cloud.githubusercontent.com/assets/762949/12809825/f83ac966-cad6-11e5-85c5-6f5841a071d0.png)

After I move it down 14px

![image](https://cloud.githubusercontent.com/assets/762949/12809804/d6b6c0c4-cad6-11e5-8e0f-b00f571cc6a7.png)

**Comment by jayphelps** [comment]
Figured it out. We're using https://github.com/Semantic-Org/Semantic-UI which has a grid system we use with classes. One of those classes is:

```css
.ui.grid {
  margin-top: -1rem;
  margin-bottom: -1rem;
  margin-left: -1rem;
  margin-right: -1rem;
}
```

Even though this `.ui.grid` element is numerous levels deep in the tree, this style causes the `<textarea>` at the top of the tree to also be shifted by it. Why, I cannot explain. I've admittedly never understood the complex interactions of negative margins collapsing things.

Perhaps @jlukic has a recommended work around?

**Comment by jayphelps** [comment]
Solved using `ui padded grid` variant that doesn't use negative margins, so going to close. However, in my opinion this is still something clipboard.js should attempt to prevent from happening; some how realizing the textarea is being shifted up via negative margins and compensating for it.

Hopefully this ticket will save someone time when they run into a similar issue in the future.

**Comment by zenorocha** [comment]
Hey @jayphelps, we should definitely reset paddings and margins to prevent cases like yours. Thanks for reporting each of your steps ;)

**Comment by jayphelps** [comment]
@zenorocha just to clarify, the margin was not actually "applied" to the textarea as in, it would not show up in any inspector nor would it return if you compute its style. There's no css selector matching textarea and applying the margin to it. It's change in location seems to be one of the weird interactions of having negative margins on other elements and how it affects visual flow.

I'm not sure how one would detect this since the offsets all register it at the top of the viewport, even though it is not.

**Comment by zenorocha** [comment]
Could you try [v1.5.8](https://github.com/zenorocha/clipboard.js/releases/tag/v1.5.8)?

**Comment by jayphelps** [comment]
@zenorocha No change. Your change certainly would fix bugs people might encounter when a style selector is indeed matching that invisible textarea, in my case the negative margin isn't being applied to the textarea directly. It is applied to an element lower in an unrelated tree, but the negative margin shifts every parent-> siblings elements above it for reasons I cannot explain. I assume it's a quirk of negative margins in general on how they impact the visual flow of the document.

The textarea shows no margin, padding and correct offsetTop. I can't see anything on itself that would tip us off it's not where it should be except visually where the compositor ends up rendering it.

![image](https://cloud.githubusercontent.com/assets/762949/12827411/74977e52-cb34-11e5-8915-8727b2fa7f2e.png)

![image](https://cloud.githubusercontent.com/assets/762949/12827420/88854430-cb34-11e5-9cfb-150f2e408f8a.png)

**I figured out how you can detect this happening!**

`getBoundingClientRect()` correctly returns a top value of `478px`, which is indeed where it ends up, 14px above the viewport. I'm wrapping up a PR that detects and compensates for this.

![image](https://cloud.githubusercontent.com/assets/762949/12827466/bd6c97a2-cb34-11e5-8833-3f0ee0dfc495.png)

**Comment by jlukic** [comment]
14px is exactly `1em` which corresponds with the negative margins on the grid. Negative margins are pretty _yuck_ but are the only reasonable way to handle content that needs to set flush on outer elements but have space between. Flex has `align-content: space-between;`, but mixing `flex` and non flex items can be _extremely awkward_ because flex items do not have margin-collapse. So having items that aren't sure if they are in a flex container means you may end up doubling space between items by accident.

I'd recommend using `vertically padded grid` which removes negative margins on top and bottom of grid, and making sure to account for margin when accessing positioning.

**Comment by zenorocha** [comment]
Nice. Thanks for the input @jayphelps ;)

**Comment by zenorocha** [comment]
Good job on all the investigation that lead to this issue @jayphelps :)
