### ISSUE TITLE
Textarea Should Be Set to 12pt to Avoid Zoom-In On Phones

### ISSUE THREAD

**Issue by speedplane** [zenorocha/clipboard.js#180]
On phones, if you select text less than 12pt, the page automatically zooms in so you can have a closer look.  Because clipboard.js selects a `textarea` text to do the copy, this also occurs. I understand that the user experience is less than stellar on a phone, but this would fix one corner case.

It can also be easily fixed in `clipboard-action.js`:

```
        this.fakeElem = document.createElement('textarea');
        this.fakeElem.style.position = 'absolute';
        this.fakeElem.style.fontSize = '12pt'; // <---- ADD THIS LINE
        this.fakeElem.style[ isRTL ? 'right' : 'left' ] = '-9999px';
        this.fakeElem.style.top = (window.pageYOffset || document.documentElement.scrollTop) + 'px';
        this.fakeElem.setAttribute('readonly', '');
        this.fakeElem.value = this.text;
```

**Comment by zenorocha** [comment]
Could you be more specific about which phones causes this problem? I tested on Android and it works fine.

**Comment by speedplane** [comment]
Sorry... iPhone 6. This behavior is the source of much confusion:
http://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone

**Comment by zenorocha** [comment]
Gotcha! I was able to reproduce this bug now. Could you send a PR?

**Comment by zenorocha** [comment]
Thanks @speedplane!
