### ISSUE TITLE
Hidden textarea get's instantly removed on Safari

### ISSUE THREAD

**Issue by herkyl** [zenorocha/clipboard.js#184]
I'm getting a weird bug where [this](https://github.com/zenorocha/clipboard.js/blob/master/src/clipboard-action.js#L58) click event gets instantly called giving no time for user to copy the text when using Safari.

It is working on Clipboard's website but not in my project. Any idea on what could be causing this?

**Comment by zenorocha** [comment]
If it's working on the website than it's probably another issue. Could you share a JSFiddle? Remember to check [demos](https://github.com/zenorocha/clipboard.js/tree/master/demo) for more examples.

**Comment by Tims101** [comment]
Hello, @zenorocha.

Seems I have same issue and I've found way to reproduce it again.

Take a look https://jsfiddle.net/ce0ykjhu/10/ in Safari.

When I initialize `Clipboard` using selected element and press on that element, I get two calls of [removeFake](https://github.com/zenorocha/clipboard.js/blob/master/src/clipboard-action.js#L85) method. So, textarea doesn't exist and Cmd-C doesn't do anything.

```javascript

var element = document.getElementById('clipboard-doesnt-work');

var clipboard = new Clipboard(element, {
  text: function() {
    return 'hello';
  }
});

```

But if I initialize `Clipboard` using class name, it works good.

```javascript
var clipboard2 = new Clipboard('.clipboard-work', {
  text: function() {
    return 'work';
  }
});
```

Is it a bug? Is it possible to initialize `Clipboard` using HTML Element? 

My safari version: 9.0.2 (11601.3.9).
Cheers.

**Comment by HugoCrd** [comment]
This is related to #330
