### ISSUE TITLE
Error in IE8

### ISSUE THREAD

**Issue by asantos** [zenorocha/clipboard.js#185]
I know this plugin doesn't support IE8, but still, the browser throws this js error in IE8 if the plugin is present:

**Object doesn't support this action**

This refers to this line:

`Object.defineProperty(target, descriptor.key, descriptor);`

Any way to avoid this issue?

**Comment by zenorocha** [comment]
Not really. We use Babel to transpile ES6 and Babel doesn't support IE8 too.

**Comment by asantos** [comment]
Thanks for the quick answer. I'll guess the best way to avoid the issue is not loading the script when using IE8-
