### ISSUE TITLE
Firefox - Dynamic content jQuery Dialog - the text is not copied to clipboard

### ISSUE THREAD

**Issue by loter** [zenorocha/clipboard.js#187]
Hi,

I have it in jquery dialog - when I press copy, the console displays
Action: copy
Text: "MyText"
Trigger: <button type="button" id="generate_copy_button" name="generate_copy_button">

but the result ("MyText") doesn't go to clipboard for some reason. Any hints?

**Comment by loter** [comment]
Sorry, tried to replicate on jsFiddle, looks like something is interfering, so not a clipboard.js issue.

**Comment by zenorocha** [comment]
Cool, thanks for coming back and letting me know ;)

**Comment by kafeltz** [comment]
@loter I see something strange in fiddler, with textarea you get the value by method .val() and not by .text(). The latter is used with dom element which is not forms.

**Comment by loter** [comment]
On firefox browser only, using JQuery 1.9 and Jquery UI - COPY WORKS
https://jsfiddle.net/0rab1zxL/24/
Same code, On firefox browser only, using JQuery 2.1 and Jquery UI - COPY DOESN'T WORK
https://jsfiddle.net/0rab1zxL/25/

**Comment by kafeltz** [comment]
Indeed in firefox has a problem with jQuery 2.1.x
It seems to be related to jQuery UI with some preventDefault somewhere.

**Comment by zenorocha** [comment]
Still no idea why this is happening. If you find a solution, feel free to send a PR. 

> Added to [Known Limitations](https://github.com/zenorocha/clipboard.js/wiki/Known-Limitations) wiki page

**Comment by CharlotteDunois** [comment]
@zenorocha Is there any reason why you removed the notice on the "Known Limitations" wiki page? It have the same issue with newest version of jquery, jquery ui and clipboard.js, so I'm really curious if there is a fix, or at least a workaround, for it.

https://github.com/zenorocha/clipboard.js/wiki/Known-Limitations/_compare/e388b93b954b4db12e527477e2e8276e4c39a4b2...4cdc6501dfc6d746b5ee5d8fef48bc4ca819a4f0

**Comment by zenorocha** [comment]
Hey @CharlotteDunois, we found the solution for Bootstrap's Modal so I moved that part to "Known Issues".

For jQueryUI's Dialog, I found a very similar solution. Try adding this line to your code:

```js
$.ui.dialog.prototype._focusTabbable = $.noop;
```

More info at: https://github.com/zenorocha/clipboard.js/wiki/Known-Issues

**Comment by zenorocha** [comment]
Check the new `container` option introduced by #368 on `v1.7.0`
