### ISSUE TITLE
How to copy string with js?

### ISSUE THREAD

**Issue by Diokuz** [zenorocha/clipboard.js#188]
I'm a little bit confused about how to copy with `Clipboard.js` a JavaScript string? I dont want to use html markup: textarea, input, data-attributes... I just want to place string to clipboard.

Can I do that with `Clipboard.js`?

**Comment by Diokuz** [comment]
I have no access to html markup, I just have an event handler.

**Comment by zenorocha** [comment]
Sure, see: 

* https://github.com/zenorocha/clipboard.js#advanced-options
* https://github.com/zenorocha/clipboard.js/blob/master/demo/function-text.html
