### ISSUE TITLE
Ctrl + C event with custom action

### ISSUE THREAD

**Issue by lfnavess** [zenorocha/clipboard.js#189]
Hi, how can copy some custom text to clipboar at ctrl + c?

i have a table but nothing is selected, it acts like Excel, where there is only a box sorrounding the selection. I want to pass a custom text whan this action is called

or i have to depend in a button to do the work?

**Comment by zenorocha** [comment]
This type of question belongs to StackOverflow. If you have any bugs to report to clipboard.js, please open another issue.

**Comment by kafeltz** [comment]
@zenorocha do you know if is possible to copy anything just by some keyboard combination (no ctrl/cmd+c of course) and no mouse interaction? I ask because i think this could lead some browse security.

**Comment by zenorocha** [comment]
https://github.com/zenorocha/clipboard.js/wiki/Known-Limitations
