### ISSUE TITLE
not copping whole text and console error

### ISSUE THREAD

**Issue by chinds185a** [zenorocha/clipboard.js#191]
### Expected behaviour

Clicking the copy button should copy a URL saved in a PHP variable.

Here is the variable:
`$custURL = "http://localhost/web-address/customer.php?custid=453";`

### Actual behaviour

Clipboard outputs:

`/web-address/customer.php?custid=453`
 
along with a console error of:
`Uncaught Error: Missing required attributes, use either "target" or "text"`

Code used:
```
$custURL = "http://localhost/scotts-rewards-system/customer.php?custid=" . $custData->custID;

<a href="#" class="btn" data-clipboard-text="<?php echo $custURL; ?>">
                      <i class="fa fa-credit-card-alt fa-2x"></i>
                      <p>Issue New Reward card</p>
                    </a>

<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.5/clipboard.min.js"></script>

<script>
    var clipboard = new Clipboard('.btn');
    clipboard.on('success', function(e) {
        console.log(e);
    });
    clipboard.on('error', function(e) {
        console.log(e);
    });
    </script>
```

**Comment by loter** [comment]
Hi, 

Please provide JSFiddle ;-)

Thank you, D.

**Comment by zenorocha** [comment]
Closing this one since a JSFiddle was not provided.
