### ISSUE TITLE
element is null

### ISSUE THREAD

**Issue by bravo14** [zenorocha/clipboard.js#193]
I have tried to use clipboard and have a fiddle set up [https://jsfiddle.net/bravo14/j466a188/]

When I load the page I get the following error in firebug

TypeError: element is null
	

element.addEventListener(type, listenerFn);

**Comment by zenorocha** [comment]
You're not using the latest version of clipboard.js and JSFiddle does not accept HTTP scripts anymore.

https://jsfiddle.net/zenorocha/pbqwy5rL/1/
