### ISSUE TITLE
how do you show the "Copied!" tooltip

### ISSUE THREAD

**Issue by drorsun** [zenorocha/clipboard.js#195]
In the demos I see a "Copied!" tooltip flashing but no extra code that seems to do that.
In my implementation at least I don't get that tooltip.
my code (ReactJS with browserify) looks something like this:
   

    var Clipboard = require('clipboard');
    var MyComponent = React.createClass({
    ...
    componentDidMount() {
    		this.userIdClipboard = new Clipboard('#userIdBox');
    	}, 
    render() {
       return( ....
            <div id="userIdBox" data-clipboard-text={vid.performerId} data-clipboard-action="copy" className="pull-right">[{vid.performerId}]</div>);
      }
    }

What am I missing or is a bit of extra code needed?

**Comment by zenorocha** [comment]
Tooltips are not included in the library. You can check the website's source code for some inspiration: https://github.com/zenorocha/clipboard.js/tree/gh-pages/assets/scripts

**Comment by zenorocha** [comment]
I just wrote an example using Bootstrap's tooltip: http://stackoverflow.com/questions/37381640/tooltips-highlight-animation-with-clipboard-js-click/37395225

**Comment by alexweissman** [comment]
@zenorocha you should really add this to the front page docs.  A lot of people use Bootstrap, and this took me over an hour to find!

**Comment by vvo** [comment]
Ultimately I would even just put this inside the library or provide an option to do so.

**Comment by drorsun** [comment]
Finally - used the advices here. 
I had to adjust to React and that was a bit tricky but it works 😄 
Thanks
