### ISSUE TITLE
Manipulate string before copy?

### ISSUE THREAD

**Issue by CodeBeeNiagara** [zenorocha/clipboard.js#196]
hiya! I am using your script to copy table rows using  data-clipboard-target="#export" 
It's great because I can paste the copied results into a spreadsheet.  The problem for me is: I need to trim the leading whitespace before copying i.e..

`copiedstring.replace(/^\s/, '')`

Can you point me to where I could do that?

**Comment by zenorocha** [comment]
Sure, see: https://github.com/zenorocha/clipboard.js#advanced-options
