### ISSUE TITLE
Copy does not work for FF44.0.2 when the input tag has attribute "disabled"

### ISSUE THREAD

**Issue by woraser** [zenorocha/clipboard.js#198]
#### code
  ```
<input type="text"  disabled id="btn" value="copy name" />
<input type="button" class="copy_btn" data-clipboard-action="copy" data-clipboard-target="#btn" value="copy">
new Clipboard('.copy_btn');
 ```

**Comment by kafeltz** [comment]
https://github.com/zenorocha/clipboard.js/issues/41

**Comment by zenorocha** [comment]
You cannot copy text from `disabled` inputs, try using `readonly`.

**Comment by zenorocha** [comment]
Fixed at https://github.com/zenorocha/clipboard.js/commit/07a1f8456b219feae3fbaf4db1e6fee1ad48d530. Please use `v1.5.10` in order to benefit from this.
