### ISSUE TITLE
Not working with Webpack

### ISSUE THREAD

**Issue by vahnag** [zenorocha/clipboard.js#199]
### Expected behaviour

To return `{ default: ... }` when requiring via Webpack.

### Actual behaviour

Instead of getting that object, I get an empty object (`{}`).

This was working before version `1.5.9`. The problem is probably in the build step.

**Comment by vahnag** [comment]
This may be only Webpack 2 issue.

**Comment by zenorocha** [comment]
@heldr, any ideas?

**Comment by heldr** [comment]
Happens because ``exports default`` was replaced with ``module.exports`` instead, Babel 6 treat this differently. 

Seems to be a webpack 2 issue, I just tested on a ``1.12.14`` project and it works.

**Comment by heldr** [comment]
That's a thing:
https://gist.github.com/sokra/27b24881210b56bbaff7#babel-and-webpack

However webpack 2 is supposed to map module.exports.
https://gist.github.com/sokra/27b24881210b56bbaff7#mixing-es6-with-amd-and-commonjs


### Temporarily workaround
use [**babel-preset-es2015-webpack**](http://npm.im/babel-preset-es2015-webpack) and ignore node_modules/clipboard on Babel ... Then:

```js
import clipboard from 'clipboard/src/clipboard';
// or make an alias in webpack config
```

**Comment by vahnag** [comment]
Thanks.
