### ISSUE TITLE
Firefox - Doesn't copy from disabled textfields

### ISSUE THREAD

**Issue by michaelkoper** [zenorocha/clipboard.js#200]
Hi!

The script isn't working in Firefox when from a disabled textfield. Here a JSFiddle: https://jsfiddle.net/0rab1zxL/33/

**Comment by michaelkoper** [comment]
After scanning the source I changed to readonly instead of disabled. It is working now, but it didn't fire an error.

**Comment by kafeltz** [comment]
https://github.com/zenorocha/clipboard.js/issues/198

**Comment by zenorocha** [comment]
Fixed at https://github.com/zenorocha/clipboard.js/commit/07a1f8456b219feae3fbaf4db1e6fee1ad48d530. Please use `v1.5.10` in order to benefit from this.

**Comment by alexweissman** [comment]
Is this a technical limitation, or a semantic decision?  It isn't always possible to interchange `readonly` for `disabled`, as they are functionally different.

**Comment by zenorocha** [comment]
Unfortunately, this is a technical limitation opposed by browser vendors.

**Comment by alexweissman** [comment]
Ah, ok.  That must only be a problem with the `data-*` usage, then.  I was able to get it work by manually initializing the `Clipboard` object.  Take a look at my example here: http://stackoverflow.com/a/41671732/2970321
