### ISSUE TITLE
Programmatically Copy Items to Clipboard

### ISSUE THREAD

**Issue by nickaversano** [zenorocha/clipboard.js#203]
Add the ability to programmatically copy elements to the clipboard. I know this could potentially be malicious, but a good use case for this is a keyboard shortcut to copy a certain block of text.

For example:
`clipboard.copy("some text")`

**Comment by zenorocha** [comment]
You can do that, check the documentation: https://github.com/zenorocha/clipboard.js#advanced-options

**Comment by zenorocha** [comment]
Hey guys, I added a proposal for this feature. Can you check #518?

Thanks!
