### ISSUE TITLE
Syntax error on token "default", Identifier/String Literal expected

### ISSUE THREAD

**Issue by alainpannetier** [zenorocha/clipboard.js#204]
Including the dist js files in eclipse raises a number of syntax errors messages - all related to misuse of reserved keyword 'default'. release 1.5.9. :(
But no error any more on keyword 'function' (was 1.5.5). :)

**Comment by thomasklein** [comment]
Please use another property name than 'default' as it is a reserved keyword since Ecmascript 1 (it still is in version 5 https://mathiasbynens.be/notes/reserved-keywords#ecmascript-5 though). Otherwise this will continue being a potential source of problems in build processes.

**Comment by zenorocha** [comment]
We use Babel to transpile ES6 to ES5. Feel free to open an issue with them in order to fix this.
