### ISSUE TITLE
Not degrading gracefully on iOS 9.x  - select() no longer works

### ISSUE THREAD

**Issue by dumb** [zenorocha/clipboard.js#206]
I realize Safari and Mobile Safari aren't fully supported, but I've noticed clipboard.js no longer degrades gracefully on Mobile Safari.

It seems that Apple has neutered the `select()` function as of iOS 9.x, which clipboard.js uses. I've read that a more browser-inclusive option is to use `setSelectionRange()`, eg:

`targetElement.setSelectionRange(0, targetElement.value.length)`

See the note here under the section **_Programmatically selecting a portion of a field's value_**:
http://www.javascriptkit.com/javatutors/copytoclipboard.shtml

I'll experiment with this and post an update here if I can get it working.

**Comment by zenorocha** [comment]
Interesting, if you have a solution please send a pull request to https://github.com/zenorocha/select.

**Comment by Rafass** [comment]
Unfortunately the problem is not only Safari, this script simply doesn't work on all the browsers running on IOS9.2.1.

**Comment by chevereto** [comment]
> Unfortunately the problem is not only Safari, this script simply doesn't work on all the browsers running on IOS9.2.1.

It doesn't work in all the iOS browsers because in iOS every browser runs a Safari webview.

**Comment by zenorocha** [comment]
Tested the clipboardjs.com page on both iPad and iPhone (iOS v9.3.1) and select is working. If you're still facing this error, please share a JSFiddle so we can reproduce it.

**Comment by Rafass** [comment]
This site is using clipboardjs: http://demo.chevereto.com/
would be great if you take a look and test, because it doesn't copy the codes after upload the files. that's the problem. (only in my IOS devices) (Already tried with 3 devices on 9.3.1, doesn't work)

**Comment by Rafass** [comment]
Actually I've also checked even in your own site with the same results on my ios devices with 9.3.1
![issue](https://cloud.githubusercontent.com/assets/8238880/14956728/d38cd708-10b3-11e6-859f-3e1fc4e9e908.jpeg)

**Comment by zenorocha** [comment]
We're talking about the selection, not the support. As showed in the documentation and the website, clipboard.js doesn't work on Safari.

**Comment by rdunk** [comment]
Also seeing this issue on an iOS 9.3.2 on iPad, not functioning or degrading on Chrome or Safari.

See this JSFiddle: https://jsfiddle.net/amhwjm69/
