### ISSUE TITLE
How I can return false on button click if data was invalid? And dont overwrite user clipboard?

### ISSUE THREAD

**Issue by jack-fdrv** [zenorocha/clipboard.js#207]
### Expected behaviour Clipboard doesnt overwrite if after clicking on data user have missed some fields.

I thought that by going to the page '...' and pressing the button '...' then '...' would happen. 
local sever

### Actual behaviour

Instead of 'my clipboard before clicking have text, after clicking it should be there bc data not valid from fields', what I saw was that 'i can return only text or target, but i want return false and dont ovewrite clip board' happened instead.

**Comment by zenorocha** [comment]
Fixed at https://github.com/zenorocha/clipboard.js/commit/7a5a910bcd83aa44718dc30caea503d9da37d4b9. Please use `v1.5.10` in order to benefit from this.
