### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'webkitMatchesSelector' 

### ISSUE THREAD

**Issue by Dielz98** [zenorocha/clipboard.js#208]
Sorry can't reproduce as I use this with Meteor. Don't know how to reproduce.

```js
var c = Template.parentData(1)._id // 4WNfGokpZAeBgwZDp
var b = $(".content."+c).html().replace(/\n/g, "").replace(/[\t ]+\</g, "<").replace(/\>[\t ]+\</g, "><").replace(/\>[\t ]+$/g, ">")
if (b) {
  var cli = new Clipboard('.approve.'+c, {
    text: function() {
      return b;
    }
  });
  cli.on('success', function(e) {
    swal("Copied!","Bla bla bla!","success");
    ///// unrelated stuff
  });
}
```

With this sometime working, sometime isn't. If it isn't, I got error: `Uncaught SyntaxError: Failed to execute 'webkitMatchesSelector' on 'Element': '.approve.4WNfGokpZAeBgwZDp' is not a valid selector.`

The element is correct and valid as I inspect on browser.

Just need some clue with this error. And I'll get back to you if I found something interesting for improvement

**Comment by zenorocha** [comment]
This line can be found in one of our dependencies.

https://github.com/ForbesLindesay/matches-selector/blob/master/index.js

I have no idea how to solve this since I don't use Meteor.
