### ISSUE TITLE
The tagline lied to me

### ISSUE THREAD

**Issue by robertmassaioli** [zenorocha/clipboard.js#210]
Your tagline: "No Flash. No dependencies. **Just 2kb gzipped**"

Actually:

![screen shot 2016-03-17 at 3 48 52 pm](https://cloud.githubusercontent.com/assets/149178/13836668/cc66d40e-ec57-11e5-9362-4c5d37438574.png)

So it's about five times bigger than advertised. Even gzipped it's too big:

    $ wc -c clipboard.min.js.gz 
    3257 clipboard.min.js.gz

**Comment by FagnerMartinsBrack** [comment]
If this project stops using OO the code size can be shrinked tremendously.

**Comment by zenorocha** [comment]
@robertmassaioli Take it easy boy. The code grew and we forgot to update the tagline. As you said, it's 3kb gzipped and I'll update the tagline now.

<img width="400" alt="screen shot 2016-03-17 at 9 07 02 am" src="https://cloud.githubusercontent.com/assets/398893/13852572/ecfae21a-ec1f-11e5-9de3-59b4a042239f.png">

**Comment by zenorocha** [comment]
@FagnerMartinsBrack I'm completely aware about that but I still prefer this approach. If you believe 3kb gzipped is too much, feel free to use another library.
