### ISSUE TITLE
in IE 11 document scroll jumps to the bottom, when clicking the copy button

### ISSUE THREAD

**Issue by DarthVanger** [zenorocha/clipboard.js#215]
### Expected behaviour

When I click on a DOM element with clipboard initialized, document scroll remains on the same position.

### Actual behaviour

When I click on a DOM element with clipboard intialized, document scroll jumps to the very bottom of the page.

### Steps to reproduce

1. Go this JSBin [http://jsbin.com/lenajuvixe/1/edit?html,js,output](http://jsbin.com/lenajuvixe/1/edit?html,js,output)
2. Make sure that the "Output" tab has scroll (its content should be longer than the tab height). 
3. Click on "ANCHOR copy button" or "DIV copy button".
4. The scroll will jump to the bottom of the tab.

### Browsers affected

In chrome it works fine, in IE 11 the scroll jumps.
(my version of IE is 11.0.9600.18231, Update Versions: 11.0.29 (KB3139929) )
I use Windows 8, 64bit.

### My guess of what is wrong
While debugging, I've found out that scroll stops jumping if I comment out this line in `select(element)` function
```
element.setSelectionRange(0, element.value.length);
```
And it also stops jumping, if I comment out this line in `ClipboardAction.prototype.removeFake()` function
```
document.body.removeChild(this.fakeElem);
```
So maybe IE pulls down the scroll, when an element with active selection is removed from the DOM?
### Attachments
I've attached a gif image with video of how the scroll is jumping in the JSBin I posted here.
![clipboard-js-ie-11-scroll-jumps-bug](https://cloud.githubusercontent.com/assets/6686679/14183527/6fed0e5a-f779-11e5-9a77-4826d283f5d8.gif)

**Comment by DarthVanger** [comment]
The problem was that I didn't close the <a> tag :)
JSBin with proper HTML works OK :) http://jsbin.com/padizewefa/1/edit?html,js,output

**Comment by zenorocha** [comment]
Yay!
