### ISSUE TITLE
Auto clipboard after jQuery Ajax

### ISSUE THREAD

**Issue by rmff** [zenorocha/clipboard.js#217]
Hello!

I've a situation where I need to clipboard a text received via an jQuery Ajax, request fired when user click on some button.

When the user first click on button, I cache the received data as "data-clipboard-text" attribute on some "no-display" div.

After, I emulate a click on this div to copy data-clipboard-text.

The strange behavior occurs only on first click (Ajax Request), Clipboard fails, on next clicks (no Ajax request, cached data) on same button, data are copied... there is some security problem on use Clipboard with jQuery Ajax success function? 

PS: I can pre-load all requests, because they need to be request on demand. 

I've this behavior on Chrome and Firefox.

**Comment by zenorocha** [comment]
> Due to security restrictions imposed by browser vendors, user interaction is required in order copy/cut to work. Which means that the first argument in the constructor is required and must refer to a valid element in the page. A simulated click event using JavaScript does not work as this would enable clipboard poisoning.

https://github.com/zenorocha/clipboard.js/wiki/Known-Limitations
