### ISSUE TITLE
Emit event when nothing is copied due to lack of text source

### ISSUE THREAD

**Issue by Nothing4You** [zenorocha/clipboard.js#219]
Hi there,

as followup on #154 I noticed that the fix 7a5a910bcd83aa44718dc30caea503d9da37d4b9 introduced a new, different problem.

When I have `clipboardText` as `undefined` it now emits no event at all, after thinking about this I thought it might be a good idea to change the behavior not to ignore errors completely on that part but rather use `else { this.handleResult(false); }` in https://github.com/zenorocha/clipboard.js/blob/7a5a910bcd83aa44718dc30caea503d9da37d4b9/src/clipboard-action.js#L40 as result of that.

I'm not sure whether `error` is the best solution here since the copy itself didn't fail as it was just skipped, especially since it's intended to allow fallback options.

Maybe add another event type?

The use case is auto copying a fields value when clicking a button, assuming the text is not empty.
After copying it opens a popup where you can see the value and also edit it if you want.
When the value is empty I still want to allow setting the value in the popup, however, right now there is just no event at all when the button is pressed and the text / target are undefined.

**Comment by zenorocha** [comment]
I thought about emitting an error event but as you said that is made for fallback purposes.

Have you tried using the imperative API?

```js
new Clipboard('.btn', {
    text: function(trigger) {
        var sometext = trigger.getAttribute('data-clipboard-text');
        if (sometext) {
             return sometext;
        } else {
            alert('do something else');
        }
    }
});
```

**Comment by budwig** [comment]
that snippet worked perfectly for my purposes. thanks.
