### ISSUE TITLE
ios 9.3.1 safari opens keybord on click to clipboard button

### ISSUE THREAD

**Issue by stepancar** [zenorocha/clipboard.js#220]
To reproduce.

Open [main](https://clipboardjs.com/)  on ipad/iphone

then try to click on any clipboard button.

keyboard appears.

As i understand, because we focus on fake elem withou blur

**Comment by zenorocha** [comment]
That's the expected behavior. The demo page only calls `clearSelection` when it succeeds (https://github.com/zenorocha/clipboard.js/blob/gh-pages/assets/scripts/demos.js#L4).

**Comment by zenorocha** [comment]
If text is not selected (which triggers the keyboard), then you wouldn't be able to click on the selection and click copy.

![ios](https://cloud.githubusercontent.com/assets/398893/14328501/d1567656-fbeb-11e5-838e-172e99cfad28.gif)

**Comment by stepancar** [comment]
@zenorocha, but if you have only fake textarea?

**Comment by stepancar** [comment]
@whats program u use for do this test?

**Comment by zenorocha** [comment]
clipboard.js is not supported on Safari (Mobile or Desktop)

**Comment by zenorocha** [comment]
used browserstack to test that
