### ISSUE TITLE
Does not work with tinymce

### ISSUE THREAD

**Issue by steveyblam** [zenorocha/clipboard.js#222]
### Expected behaviour

Setting a textarea target that is being controlled by tinymce should allow copying

### Actual behaviour

There are no errors but the text is not copied. Paste is empty.

### Steps to reproduce

1. include tinymce
2. set target
3. attempt to copy and paste

**Comment by kafeltz** [comment]
I think tinymce has a specific plugin for copy and paste. It has some tricky to copy because there are a textarea hidden.

**Comment by zenorocha** [comment]
clipboard.js works with selectable HTML elements such as inputs and textareas. From my understanding tinymce doesnt use that, but you can still make clipboard.js work with it by using the imperative API: https://github.com/zenorocha/clipboard.js#advanced-options

All you have to do is, grab the string from your WYSIWYG editor and return it on the clipboard.js text function. Here is a full example: https://github.com/zenorocha/clipboard.js/blob/master/demo/function-text.html
