### ISSUE TITLE
Unable to copy a hidden element

### ISSUE THREAD

**Issue by JonHaywood** [zenorocha/clipboard.js#223]
### Expected behaviour

I thought that by having a hidden element (using css display none) and using it as the target of clipboard.js then it would copy the contents to the clipboard.

### Actual behaviour

Instead of the contents of the element, nothing seemed to be copied to the clip board

### Steps to reproduce

1. Go this JSFiddle: https://jsfiddle.net/8gkvnucr/
2. Click on 'Copy to Clipboard - Does Work'. That will copy just fine.
3. Click on 'Copy to Clipboard - Doesn't Work'. That will not copy because the target element is hidden.

### Browsers affected

I've only tested on Chrome.

Awesome library by the way!

**Comment by zenorocha** [comment]
Thats why this https://github.com/zenorocha/clipboard.js#copy-text-from-attribute and this https://github.com/zenorocha/clipboard.js#advanced-options exists. See more demos at: https://github.com/zenorocha/clipboard.js/blob/master/demo/constructor-selector.html and https://github.com/zenorocha/clipboard.js/blob/master/demo/function-text.html

**Comment by rgfx** [comment]
Here is little css hackery to get it done. https://jsfiddle.net/uyqqz3d9/

I am not sure if @zenorocha is saying it possible or impossible.  My solution  works for what I need it for.

**Comment by kafeltz** [comment]
i see no css in this jsfiddle

**Comment by rgfx** [comment]
@kafeltz its inline, look at the html.

**Comment by zenorocha** [comment]
You don't need an element, you just need to use `data-clipboard-text`.
