### ISSUE TITLE
stopPropagation with enter action on row in jQuery dataTable

### ISSUE THREAD

**Issue by selcet** [zenorocha/clipboard.js#225]
#### Situation
.1 I have _jQuery dataTable_ with link to another page when click on an entire row;
.2 In last _tr_ I have two spans, and if click on first of them, it will copy content from second.

#### Problem
When click on span to copy content - it is copied, but after a transition began automatically.
Can you help me, how can I stopPropagation using clipboard.js ?

**Comment by zenorocha** [comment]
Please share a JSFiddle

**Comment by selcet** [comment]
You can check it here - https://results-keeper.herokuapp.com/revisions?project_id=42
Please, login with next temp credentials:
login: ivankozakov0@gmail.com
pass: q1w2e3r4

**Comment by zenorocha** [comment]
Yes, JSFiddle would be way better. If event delegation is not working for you, try passing a nodelist: https://github.com/zenorocha/clipboard.js/blob/master/demo/constructor-nodelist.html
