### ISSUE TITLE
it always fail when i copy an long json string which length is 384006

### ISSUE THREAD

**Issue by anihc628** [zenorocha/clipboard.js#227]
### Expected behaviour
i use below code to copy an long json str (length= 384006 ),
it's should be quick done and success

` var clipboard = {
        copy: function (str) {
            console.log(str.length);
            var def = $.Deferred()
            //clean
                .always(function (e) {
                    dom.remove();
                    instance.destroy();
                    console.log(this.state());
                });
            var dom = $('<span>').appendTo('body').css('display','none');
            var instance = new Clipboard(dom.get(0), {
                text: function () {
                    return str;
                }
            });
            instance.on('success', function (e) {
                def.resolve();
            });
            instance.on('error', function (e) {
                def.reject();
            });
            dom.click();
            return def.promise();
        }
    };`

### Actual behaviour

Instead of 'success', what I saw was that ‘browser get stuck  a few seconds,then fail' happened instead.

### Steps to reproduce

1. Go this http://plnkr.co/edit/AX4E56OUpRhX9378yIwT?p=preview
2. Click on 'Save'
3. Console will show length ,and then show result(reject:fail,resolve,success)

### Browsers affected

I tested on chrome 49.0.2623.112 m (64-bit).

**Comment by zenorocha** [comment]
This has nothing to do with the size of what is being copied. You added a click event listener but clipboard.js already adds one for you.

Try these demos or read the docs to understand the API better: https://github.com/zenorocha/clipboard.js/tree/master/demo
