### ISSUE TITLE
Simpler API

### ISSUE THREAD

**Issue by JustinDrake** [zenorocha/clipboard.js#230]
I want single function (e.g. `copyToClipboard`) which takes a single string argument and copies that string to the clipboard. Do I really need a 3bK library for this? How much fat can I remove from clipboard.js to get to this essential `copyToClipboard` function?

**Comment by zenorocha** [comment]
If 3kb is too much for you feel free to fork the project and adapt to your own needs. We don't have plans to change the API in the near future.

**Comment by kafeltz** [comment]
I did this same feature with a single function and it must have few bytes. You could do the same.

**Comment by zenorocha** [comment]
You can make it in 1 line if you want. Clipboard.js is a third-party library, nobody is forced to use it ;)
