### ISSUE TITLE
Changing clipboard text from a callback

### ISSUE THREAD

**Issue by prionkor** [zenorocha/clipboard.js#231]
Example 
-----------

There is a copy button on a table cell, when clicked some contents from `<td>` elements (child of a particular `<tr>` element) will be copied to clipboard (not all of them). 

Is it possible? I have looked into documentation and didn't find anything related. I didn't see any types of custom event listener for this plugin. Perhaps I missed something?

**Comment by jamesryanbell** [comment]
I'm in this exact situation too! Does anyone know if this is possible?

Thanks,
James

**Comment by zenorocha** [comment]
Please share a JSFiddle so we can debug this.

**Comment by prionkor** [comment]
Hello, 

Please find the js fiddle link below. The main goal is to able to catch and modify the content just before plugin sends it to clipboard. This is a very simplistic example. 

https://jsfiddle.net/sisir/0a2w6av3/2/

On my app I am trying to copy on a `dblclick` event. But I guess that is for another question.

**Comment by carlosjdelgado** [comment]
Maybe could be good to have the ability to concatenate in the clipboard the content of all targets matching certain class.
testing the fiddle i see that actually this is not possible.

https://jsfiddle.net/kganafuj/1/

**Comment by prionkor** [comment]
Another idea that can be considered is a copy method that takes string and sends to clipboard. This will have a vast implementation use cases. 

```
var clipboard = new Clipboard(); // no element passed
clipboard.copy('my text');

This will help implementing the plugin with keyboard shortcut library like [Mousetrap](https://craig.is/killing/mice)


```

**Comment by prionkor** [comment]
@carlosjdelgado This may be confusing to the plugin because it will not know which element it should be copy from. Considering if there are multiple element available using same class.

**Comment by zenorocha** [comment]
There are a number of errors on these JSFiddles.

1. You're loading the GitHub raw path, which doesn't include the proper MIME type and therefore cannot be executed.
2. You haven't read the [documentation](https://github.com/zenorocha/clipboard.js#advanced-options) or [checked the demo folder](https://github.com/zenorocha/clipboard.js/blob/master/demo/function-text.html) properly. It explains exactly how to use the imperative API.

Here's the end result @prionkor is looking for https://jsfiddle.net/zenorocha/d48hxmzy

**Comment by zenorocha** [comment]
Hey guys, I added a proposal for this feature. Can you check #518?

Thanks!
