### ISSUE TITLE
alert repeatedly in chrome and opera

### ISSUE THREAD

**Issue by brunce2** [zenorocha/clipboard.js#232]
### Expected behaviour

I thought that it can show a tooltip saying 'Copy success!' in clipboard.on() method. 

### Actual behaviour

According to the following way. in chrome or opera,if i clicked to copy button one time,alert the 'Copied!' message one time. if i clicked two times,alert two times. And so on,it can alert a lot of times message if you clicked a lot of times

### Steps to reproduce

1,by onClick method to invoke clipboard.
2,in clipboard.on('success') function to alert message.

html:
`<button class="btn" onClick="copy();" data-clipboard-action="copy" data-clipboard-target="#foo">Copy</button>`   

js:
`
function copy(){
    var clipboard = new Clipboard(".btn");
   
    clipboard.on('success', function(e) {
        console.log(e);
        alert(' copy success');
        clipboard.destory();
    });

    clipboard.on('error', function(e) {
        console.log(e);
        alert('copy fail');
    });
`
please help analyze it. thanks

**Comment by zenorocha** [comment]
Clipboard.js already adds a click listener for you, you don't need to add another one. Please see the [demos](https://github.com/zenorocha/clipboard.js/tree/master/demo) to better understand how the API works.
