### ISSUE TITLE
Issue with iPad

### ISSUE THREAD

**Issue by seldimi** [zenorocha/clipboard.js#233]
### Expected behaviour

I was expecting to copy in iPad Chrome.

### Actual behaviour

Instead of copying, it doesn't trigger any event

### Steps to reproduce

Just used new Clipboard('.copyme'); and class refers to a button that works on desktops.

**Comment by zenorocha** [comment]
It doesn't work in all the iOS devices because in iOS every browser runs a Safari webview. Hopefully this will change in the near feature: https://webkit.org/blog/6017/introducing-safari-technology-preview/
