### ISSUE TITLE
Problem with YUICompressor

### ISSUE THREAD

**Issue by MeMyselfI** [zenorocha/clipboard.js#236]
Hi.

Thanks for this great library.

Compressing the library with YUICompressor fails because "default" is a reserved word for that lib. So for instance changing 

_goodListener2.default

to 

_goodListener2['default']

fixes that problem.

I know that YUICompressor is quite old but it's still widely used I think.

Cheers,
Jörn

**Comment by zenorocha** [comment]
Hey @MeMyselfI, thanks for reporting but this should be fixed in YUICompressor, not here.
