### ISSUE TITLE
Should not throw errors in IE8

### ISSUE THREAD

**Issue by cnsgithub** [zenorocha/clipboard.js#238]
While I understand IE8 is not supported - and it is fine, it should not causing JS errors, instead just print out a warning in console that it's not supported.

Thanks

**Comment by zenorocha** [comment]
Could send a screenshot of these errors?

**Comment by cnsgithub** [comment]
Hi, sorry i have not been able to provide screenshots yet, however the issue still persists, as soon as clipboard.js is added, the site throws js errors and does not continue. Now ive made the screenshot, please see

 https://abload.de/img/clipboardjsbug3rqib.png

Note: it is the real IE8. In emulation mode it maybe not reproducible

**Comment by zenorocha** [comment]
Thanks for providing a screenshot @cnsgithub. Unfortunately I have no plans to support IE8 or add if statements to prevent console errors on IE8. Feel free to use another library or `execCommand` directly.

**Comment by cnsgithub** [comment]
OK I understand, but this virtually means that it is not possible to include the library if there's a chance that users visit a site with IE8 and in business-environments it still can and will happen. If those errors happen the site's other scripts below that error don't execute anymore.

I'm using the execCommand directly wrapped in try catch as you suggested now. Thanks

**Comment by zenorocha** [comment]
Thanks for your feedback

**Comment by black-snow** [comment]
Seeing this, too.

> Expected identifier
> clipboard.min.js Line: 7
> Code: 0 Char: 5691

**Comment by anrananran** [comment]
@cnsgithub hi! can you share your solution, I tried to add try catch like this:
try{
    !function(e){if("object"==typeof exports&........emitter":6}]},{},[8])(8)}); //clipboard.js
}catch(e){}
,but nothing helped, in IE8 scripts still throw errors ,then other scripts can't execute

**Comment by cnsgithub** [comment]
I suggest to not use clipboard.js if you want to run it in IE8
```
function copyToClipboard(e, trget) {

    // find target element
    var   t = e.target,
      c = trget,
      inp = (c ? document.querySelector(c) : null);

    // is element selectable?
    if (inp && inp.select) {

      // select text
      inp.select();

      try {
        // copy text
        document.execCommand('copy');
        inp.blur();
      }
      catch (err) {
        alert('please press Ctrl/Cmd+C to copy');
      }

    }

  }
```

**Comment by anrananran** [comment]
@cnsgithub  thanks,I will try it!
