### ISSUE TITLE
IE 11 bug

### ISSUE THREAD

**Issue by emolchanov** [zenorocha/clipboard.js#240]
Steps for reproduce:
1) Open https://clipboardjs.com/ in IE11 on Windows 8/8.1/10
2) Click on **copy-button** and see blocking popup with two action - **Apply** or **Deny** permissions to get/put into clipboard.
3) Click **Deny**
4) Let`s click on **copy-button** again and get **success** message!

**Comment by zenorocha** [comment]
Hey @emolchanov, thanks for sending this out.

Unfortunately there's nothing we can do about it, this is a known issue originally reported on #77.

https://github.com/zenorocha/clipboard.js/wiki/Known-Issues

**Comment by emolchanov** [comment]
Thanks :(
