### ISSUE TITLE
Works in Safari above version 9.1.1

### ISSUE THREAD

**Issue by leo** [zenorocha/clipboard.js#241]
Just wanted to let you guys know that the code now works since Safari 9.1.1. While this version is a so-called "[Technology Preview](https://developer.apple.com/safari/technology-preview/)", I still think it's a good idea to add it to the site.

I mean, currently, the site implies that it doesn't work at all on Safari and that isn't correct... :blush:

**Comment by zenorocha** [comment]
I'm aware about this but I decided not to change that since Safari Technology Preview still have a very low adoption and it's not available on mobile. As soon as the stable version is out, I'll make sure to update the site ;)

Thanks @leo!
