### ISSUE TITLE
Question - Pure imperative use to copy text to clipboard

### ISSUE THREAD

**Issue by dsl101** [zenorocha/clipboard.js#242]
clipboard.js has been great where the user interaction with a page element initiates the need to copy something to the clipboard.

My current development is on node/electron, and I just hit a point where I've created a context menu within the app, and want the selection of a menu item to cause something to be copied. I'm not sure this is easy with clipboard.js, and was looking at [node-copy-paste](https://github.com/xavi-/node-copy-paste) instead. But before I take clipboard.js out and replace all its current uses, is there an easy way to simply call a function, pass it the text and job done, without having to bind to a DOM element? I'm guessing it would mean exposing `selectFake()` in some way, but I'm presuming that isn't trivial...

Tx.

**Comment by kafeltz** [comment]
Do you mean this? https://github.com/zenorocha/clipboard.js#advanced-options

**Comment by zenorocha** [comment]
Due to security restrictions imposed by browser vendors, user interaction is required in order for copy/cut to work. For example, a simulated click event using JavaScript would not work as this would enable clipboard poisoning.

I'm afraid clipboard.js will not be able to help you on this one.
