### ISSUE TITLE
Initializing clipboard.js using a DOM selector should degrade gracefully in Safari

### ISSUE THREAD

**Issue by Omer** [zenorocha/clipboard.js#247]
### Minimal example

[JSFiddle](https://jsfiddle.net/ytyd5k77/)

### Expected behaviour

Initializing clipboard.js using a DOM selector should degrade gracefully in Safari.

### Actual behaviour

Unlike other major browsers, initializing clipboard.js using a DOM selector prevents Safari from copying text (using ⌘-C of course 😄)

### Browsers affected

I tested Chrome/Firefox/Safari and only Safari (9.1.1) does not work.

**Comment by zenorocha** [comment]
Hey @Omer, thanks for reporting!

Unfortunately there's no way to gracefully degrade on Safari when using `data-clipboard-text`. See how we handle this scenario on the "Copy text from attribute" demo at https://clipboardjs.com.

Hopefully this will change in the near future: https://webkit.org/blog/6017/introducing-safari-technology-preview/

**Comment by Omer** [comment]
I'm a bit confused.

Isn't it that Safari does not support the execCommand and as such we must fallback to the Selection API instead?

Note that, simply changing the way I am initializing the library (selector string as opposed to a DOM node) "fixes" the issue (that is allowing me to use ⌘-C to copy the data in `data-clipboard-text`).

**Comment by zenorocha** [comment]
I see... so that's probably a bug on https://github.com/zenorocha/select.
