### ISSUE TITLE
IE8 'default' keyword issue

### ISSUE THREAD

**Issue by Jinkwon** [zenorocha/clipboard.js#249]
### Expected behaviour
'default' is reserved keyword in ie 8, so it broke entire scripts.

### Actual behaviour
https://phabricator.babeljs.io/T2817
I think build with new babel version can fix this issue.

### Browsers affected
I tested on only IE 8 does not work.

**Comment by Jinkwon** [comment]
I found this same issue(#238), and it can be solution with new babel version.

Here is release note.
https://github.com/babel/babel/releases/tag/v6.7.4

**Comment by zenorocha** [comment]
Thanks for reporting @Jinkwon but clipboard.js does not support IE8.

**Comment by Jinkwon** [comment]
clipboard.js does not support IE8, so I made ie8 support build in here.

If someone had same issue, use this.
https://github.com/Jinkwon/clipboard.js

Also can using bower this command.
```
bower install clipboard-ie8
```

**Comment by kafeltz** [comment]
I'm interesting to know if is it working on IE8. I thought it was impossible without some flash plugins.

**Comment by Jinkwon** [comment]
Hi, @kafeltz 
If I access to page included clipboard.js in IE8, it makes broken because of default keywords.
So I made it to support ES3 specs with some babel option. (Especially ES3 plugin)
I think we can make a spec for safari. (When you click the button, it shows copy & paste UI. That's all)
I know that clipboard.js does not support IE8, but in my business area still so many user using IE8.
I had to modify even it's not working similar with modern browsers.

**Comment by kafeltz** [comment]
@Jinkwon Ha I understand know, you made a workaround to prevent error. I thought you made it work on IE8, would be a miracle!

**Comment by Jinkwon** [comment]
@kafeltz 
I understood. Wait for me few days. :) I'll trying to make this.

**Comment by anrananran** [comment]
@Jinkwon  sorry, your fork's mini version still throw Errors in IE8
