### ISSUE TITLE
Idea: pass in the elements

### ISSUE THREAD

**Issue by kmalakoff** [zenorocha/clipboard.js#25]
With single page apps, you may want to manage the lifecycle of the DOM more precisely. 

What I would like would be for a way to provide a single element or list of elements that are used instead of having the library use the selector to find elements on the document. Otherwise, it feels like jQuery spaghetti by adding extra classes to HTML (FYI: I'm using React refs to find elements).

**Comment by hasansoydabas** [comment]
+1. I made a pull request #42

**Comment by zenorocha** [comment]
That's a valid use case, thanks for suggesting @kmalakoff.

**Comment by kmalakoff** [comment]
Awesome...that was quick!

**Comment by codeclown** [comment]
Came here looking for this. Using Mithril on a project. Great to see it's on the way!

**Comment by zenorocha** [comment]
Great. We're looking into that @codeclown ;)
