### ISSUE TITLE
clipboard  is not used in android 4.2.2.

### ISSUE THREAD

**Issue by chenEdgar** [zenorocha/clipboard.js#254]
### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/96goysy3/) and reproduce your issue.

I used clipboard.js in my mobile project. It works well in the operating system of android 4.4.4, but it fail in android 4.2.2.

the difference of android 4.2.2 is that when I clicked the btn, I saw the target object's background change to blue and then the blue disappeared. When I wanted to pasted it, I failed.

**Comment by FagnerMartinsBrack** [comment]
Please, provide the browser version too.

**Comment by chenEdgar** [comment]
I got a user-agent from the browser:
User-Agent: Mozilla/5.0 (Linux; U; Android 4.2.2; en-us; HUAWEI G750-T01 Build/HuaweiG750-T01) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

**Comment by zenorocha** [comment]
Sorry, I wasn't able to reproduce this problem. But feel free to send a pull request. Thanks for reporting @chenEdgar!
