### ISSUE TITLE
Can not copy empty string (vue.js)

### ISSUE THREAD

**Issue by misog** [zenorocha/clipboard.js#255]
When data-clipboard-text has empty string (''), nothing is copied to the clipboard and the previous clipboard value is not removed.

**Comment by zenorocha** [comment]
What was the expected behavior and where can I see a minimal working example?

> Closing since it didn't follow the issue template.

**Comment by misog** [comment]
updated the original post

**Comment by zenorocha** [comment]
If you pass nothing, nothing will be copied, and what was previously on the clipboard will remain the same.

You can save an empty space on the clipboard but I don't recommend doing that because there's absolutely no value in overriding user's clipboard with an empty space.

https://jsfiddle.net/zenorocha/8p07fs5d/

**Comment by misog** [comment]
With empty space no, but of course there is value in saving empty string / removal - if you have a button to copy hidden password or secret API key and the target it is empty (bug or purpose) you really do not want to keep in clipboard previous copied after click. Current behaviour (or lack of the possibility to clear clipboard) can have bad consequences for user.

**Comment by zenorocha** [comment]
I still disagree that it's a good idea to replace a user's clipboard with empty information but that doesn't really matter. Feel free to save an empty space using Clipboard.js or use `execCommand` directly to achieve the behavior you're looking for.

**Comment by misog** [comment]
In general, every action should support undo to default state.
And after all, empty string is just ordinary string, why the special behavior? clipboard.js is universal tool, not final implementation of specific use case.

**Comment by zenorocha** [comment]
I totally agree that every action should support undo to previous state. If you find an API that will fetch what is the current clipboard content, then you have the right value to pass to clipboard.js.

**Comment by misog** [comment]
For clarification: with the "undo to default state" I mean *change* to default state - default state is known state by programmer. Now I can set default state to whatever except '' with clipboard.js.

Obviously I can not find such API, but it does not matter - I do not want to implement "undo to the very previous value".

From w3.org specification:
> Note that empty attribute syntax is exactly equivalent to specifying the empty string as the value for the attribute, as in the following example. [w3.org](https://www.w3.org/TR/html-markup/syntax.html#syntax-attr-empty)

```
<input disabled="">
```

If attribute is absent, then it is undefined. But undefined is not empty string.

You said:
> If you pass nothing, nothing will be copied,

This is not what I did - I passed empty string. Nothing should be copied (ignored) when I pass no attribute.

Such wrong design prevents many use cases. There are many use cases with clipboard clear:

1. Tor browser clears the clipboard before close (privacy/security)
2. Adobe Illustrator clears the clipboard before close, after confirmation (performance)

Another important thing:
> I still disagree that it's a good idea to replace a user's clipboard with empty information but that doesn't really matter.

It matters - the facts that you do not think it is a good idea and that the implementation ignores empty string imply that clipboard.js is has business logic baked-in. But it should just copy stuff to OS clipboard, no business logic should be included.

**Comment by zenorocha** [comment]
When I said "it doesn't really matter" I was talking about my opinion on this subject that doesn't really matter. Clipboard.js uses execCommand and if you pass an empty string to this API it will not work. It has nothing to do with Clipboard.js or what I think about this.

Anyways, enough with this discussion that is going nowhere. Feel free to fork this project, send a pull request, or use execCommand directly to achieve the behavior you're looking for.

**Comment by dhjw** [comment]
Clearing the clipboard completely appears to be impossible, at least on Chrome, because `document.execCommand('copy');` requires an active selection. The best you can apparently achieve is a single space which can be done with both clipboard.js and execCommand.
