### ISSUE TITLE
app.bundle.00917b9….js:13773 Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.

### ISSUE THREAD

**Issue by MikaelDev** [zenorocha/clipboard.js#257]
app.bundle.00917b9….js:13773 Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.

	        ClipboardAction.prototype.removeFake = function removeFake() {
	            if (this.fakeHandler) {
	                **document.body.removeEventListener('click');**
	                this.fakeHandler = null;
	            }

	            if (this.fakeElem) {
	                document.body.removeChild(this.fakeElem);
	                this.fakeElem = null;
	            }
	        };

**Comment by zenorocha** [comment]
Fixed by #256
