### ISSUE TITLE
Is there a way to use this programmatically?

### ISSUE THREAD

**Issue by cmeans** [zenorocha/clipboard.js#258]
I'd like to be able to construct your object without a selector.

`var worker = new Clipboard();`

and to then call the `copy` function as necessary...

`worker.copy("text");`

This doesn't seem possible right now (based on the documentation), or did I miss something?

Thanks.

**Comment by kafeltz** [comment]
#203

**Comment by zenorocha** [comment]
https://github.com/zenorocha/clipboard.js#advanced-options

**Comment by cmeans** [comment]
So, there is no way to create the Clipboard object without a node/selector.

I've found a work-around, but it breaks the model I'm using.  Being able to use this without a selector/node would be a useful option.

**Comment by zenorocha** [comment]
Clipboard.js doesn't work that way due to security restrictions imposed by browser vendors. User interaction is always required in order copy/cut to work.

**Comment by cmeans** [comment]
OK.  That makes sense.  Thank-you.

**Comment by zenorocha** [comment]
Hey guys, I added a proposal for this feature. Can you check #518?

Thanks!
