### ISSUE TITLE
Copy after drag-and-drop?

### ISSUE THREAD

**Issue by LusciousPear** [zenorocha/clipboard.js#259]
Heyas,

Thanks so much for writing this. I'm trying to make an easy file upload workflow. Drag+drop -> upload -> URL copied to clipboard.

I know that you can only copy after a user action -- but does that action have to be a button click? Can it be after a drag-and-drop, then some kind of pause, then on the upload response, you fire off the copy? 

Here's the code: https://gist.github.com/LusciousPear/3190e66c8bfc1751a84a464017046e3e

**Comment by zenorocha** [comment]
Unfortunately clipboard.js can't help you with that since it includes a click event listener but you can try using [execCommand('copy')](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) directly. Try it out and let me know, I would love to hear if it works or not ;)

**Comment by LusciousPear** [comment]
FYI - it's totally possible. You can select and copy after a 'mouse drop'
event using execCommand. Had to do some lib hacking with Dropzone, but
we'll get there. Thanks!

On Sat, Jun 11, 2016 at 8:12 AM, Zeno Rocha <notifications@github.com>
wrote:

> Closed #259 <https://github.com/zenorocha/clipboard.js/issues/259>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zenorocha/clipboard.js/issues/259#event-689433136>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAKzlsn4ffbpKYs2cqOz8ReNQR8c-Mh8ks5qKtBLgaJpZM4IzetS>
> .
>



-- 
Bradford Stephens
Freelance CTO & Startup Exec
22acacia.com
(530) 763-DATA

**Comment by zenorocha** [comment]
Awesome! That's good to know, thanks for getting back @LusciousPear ;)
