### ISSUE TITLE
meteor package v1.5.12 not available for mac

### ISSUE THREAD

**Issue by welelay** [zenorocha/clipboard.js#262]
`meteor update` shows and error. It's also true for a brand new application (see minimal example).

### Minimal example

```
meteor create testV1512
cd testV1512
meteor add zenorocha:clipboard
```

### Expected behaviour

meteor adds the package to my application

### Actual behaviour

```
 => Errors while adding packages:

While checking for zenorocha:clipboard@1.5.12:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

### Browsers affected

N/A

**Comment by zenorocha** [comment]
I'm not a Meteor user so I'm not sure how to fix this. I ran `meteor publish --update` and now everything seems to be working fine on https://atmospherejs.com/zenorocha/clipboard. Could you test please?

Thanks for reporting @welelay!

**Comment by welelay** [comment]
@zenorocha it doesn't work any better.

Did you run this from mac ?
What version of meteor did you use ?
I guess that with the move to npm packages in meteor, the `meteor publish` command is using the package.json file, and if it finds dependencies it decides that your package is platform dependent.
Could you try to temporarily remove the package.json and rerun meteor publish ?

Thanks,

**Comment by welelay** [comment]
@zenorocha I've tried on a 64-bit linux, but get the same error.

**Comment by zenorocha** [comment]
Yes, I'm using a Mac. I tried what you suggested but it doesn't seem to work:

<img width="353" alt="screen shot 2016-06-15 at 8 54 23 am" src="https://cloud.githubusercontent.com/assets/398893/16087178/f7a156c4-32d6-11e6-9638-e331dd7a00e2.png">

**Comment by welelay** [comment]
maybe `meteor publish --update` then?

**Comment by welelay** [comment]
I've opened a topic on the meteor forums: https://forums.meteor.com/t/zenorocha-clipboard-1-5-12-unusable-even-in-fresh-app/24933

**Comment by zenorocha** [comment]
<img width="561" alt="screen shot 2016-06-15 at 11 34 42 am" src="https://cloud.githubusercontent.com/assets/398893/16092551/35a4335e-32ed-11e6-948e-ac0d0b36d9f9.png">

**Comment by elelay** [comment]
no change :-(

**Comment by zenorocha** [comment]
From @humberaquino on #263

> Thanks @zenorocha ! The following commands let me complete the meteor update.

```
meteor remove zenorocha:clipboard 
meteor update
meteor npm install clipboard --save
```

> Ref: http://guide.meteor.com/atmosphere-vs-npm.html

> Well check how clipboard works with this install method for my app and come back to you 👍

**Comment by welelay** [comment]
Thanks @zenorocha 

It works, I just had to add this to my client code to access the `Clipboard` object.

    import Clipboard from 'clipboard';

**Comment by zenorocha** [comment]
Awesome ;)
