### ISSUE TITLE
No compatible binary build for package zenorocha:clipboard when trying to upgrade to Meteor 1.3.3 

### ISSUE THREAD

**Issue by humberaquino** [zenorocha/clipboard.js#263]
Hey there :)

Just wanted to share that after trying to update a Meteor project to version 1.3.3 (was Meteor 1.3.2.4) by using:
```
meteor update
```
the command fails and shows to the following error:
```
=> Errors while upgrading packages:           
                                              
While checking for zenorocha:clipboard@1.5.12:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

Also tried with a fresh meteor project and got the same error.

I'm on OSX 10.11.5 (El Capitan) using Node 0.10.45.

Not sure if this is the best place to post this so I apologize if that's the case.

Thanks for the help and awesome work with clipboard.js!

**Comment by zenorocha** [comment]
Hey @humberaquino, I'm not a Meteor user and have no idea on how to fix this. Any ideas?

> Closing since it's duplicated from #262

**Comment by humberaquino** [comment]
Thanks @zenorocha ! The following commands let me complete the meteor update.

```
meteor remove zenorocha:clipboard 
meteor update
meteor npm install clipboard --save
```

Ref: http://guide.meteor.com/atmosphere-vs-npm.html

Well check how clipboard works with this install method for my app and come back to you 👍

**Comment by ktian** [comment]
Are there any updates? I still get the same error "error: No compatible binary build found for this package." for both Meteor 1.3.2 and 1.3.4

**Comment by zenorocha** [comment]
@ktian have you seen the comment above?

**Comment by ktian** [comment]
@zenorocha 

so I have to do this? meteor npm install clipboard --save
Still prefer the default meteor package way to add this...

**Comment by zenorocha** [comment]
This is issue not related to Clipboard.js: https://guide.meteor.com/atmosphere-vs-npm.html

**Comment by ktian** [comment]
Any way you can provide atmosphere support?

**Comment by zenorocha** [comment]
I don't use Meteor, so feel free to send a pull request.
