### ISSUE TITLE
Not working inside of a Slick.js carousel

### ISSUE THREAD

**Issue by paolo-g** [zenorocha/clipboard.js#264]
Hi, I'm trying to add a click-to-copy button inside of a Slick.js carousel slide and am not able to get Clipboard.js to work. I've tried using both the data-clipboard-text and dynamic text function approaches but neither worked. I also tried to instantiate the clipboard object when the slide is shown (in an afterChange event) in case it had to do with the trigger button being hidden, but that didn't work either.

I know that the object is being created because I can console.log it after var clipboard = new Clipboard(<selector>). Maybe there are some functions that I could run on the object to confirm the trigger object and/or it's text value?

I've tried on both Chrome 49 and Firefox 47

**Comment by zenorocha** [comment]
> Closing since it didn't follow the issue template and didn't provide a minimal JSFiddle.
