### ISSUE TITLE
Input focus/click does not copy to clipboard in Firefox.

### ISSUE THREAD

**Issue by zackgilbert** [zenorocha/clipboard.js#265]
### Minimal example

https://jsfiddle.net/1u3xwnLh/

### Expected behaviour

In most browsers, clicking (focusing into) the input field will successfully copy the input value to the clipboard.

### Actual behaviour

Instead of copying input value to clipboard, despite hitting the success callback, the clipboard does not actually contain the input value.

### Browsers affected

Firefox (45) does not work, but does in most other modern browsers like Chrome.

**Comment by zenorocha** [comment]
Hey @zackgilbert, the JSFiddle you shared is incomplete. Can you provide one that reproduces the error you're describing?

**Comment by zenorocha** [comment]
I made a small update to your example and everything seems to be working fine: https://jsfiddle.net/1u3xwnLh/1/

**Comment by zenorocha** [comment]
I also noticed you also loaded the file from GitHub Raw which doesn't contain the proper MIME types. Try using one of our CDN providers: https://github.com/zenorocha/clipboard.js/wiki/CDN-Providers

**Comment by zackgilbert** [comment]
Your update (adding the button to click), while totally fixing the issue
(and what I've had to do to fix the issue in my project), defeats the
issue. I'll try to get the jsfiddle working (had it working from a standard
html file).

**Comment by zenorocha** [comment]
Ok, I'll wait for the updated jsfiddle but I don't think it's possible to copy the input value to the clipboard when focusing on the input field.

**Comment by zackgilbert** [comment]
Man. Well, got the fiddles to work as intended (https://jsfiddle.net/1u3xwnLh/4/), but of course now I can't reproduce the error in Firefox. Not sure why its not working in my app but not in the example. Computers are fun.

I'll just close this for now until I can more accurately reproduce the issue.

**Comment by zenorocha** [comment]
Cool! Are you using the script from GitHub Raw locally? Maybe that was the problem.

**Comment by zackgilbert** [comment]
Nope. I have a locally saved filed for that. Probably just conflicts with other js code.
