### ISSUE TITLE
meteor package breaking on install for 1.5.12 release

### ISSUE THREAD

**Issue by ellisonleao** [zenorocha/clipboard.js#269]
Hey Zeno,

i just updated my meteor app to the latest version (1.3.4) and the clipboard package is getting an error on update:

```
=> Errors prevented startup:

   While checking for zenorocha:clipboard@1.5.12:
   error: No compatible binary build found for this package. Contact
   the package author and ask them to publish it for your platform.
```

Is that  version published ( i can see the tag on atmospherejs page) ?

**Comment by zenorocha** [comment]
> Duplicated from #263
