### ISSUE TITLE
Clipboard icon as React component

### ISSUE THREAD

**Issue by fibo** [zenorocha/clipboard.js#272]
Hi,

I am writing just to inform about this npm package [react-clipboard-icon](https://www.npmjs.com/package/react-clipboard-icon) which contains **clippy.svg** as a React stateless component.

I hope this can be useful to other people, maybe you can consider to link it to the wiki or somewhere.

**Comment by zenorocha** [comment]
Nice! Just added to the wiki page https://github.com/zenorocha/clipboard.js/wiki ;)
