### ISSUE TITLE
server side tests

### ISSUE THREAD

**Issue by fibo** [zenorocha/clipboard.js#274]
### Intro

I am opening this issue to keep track of this pull request https://github.com/ForbesLindesay/matches-selector/pull/1 which should solve it.

### Minimal example

I am testing a *Root* React component which contains a component that do a `new Clipbloard`.

The test is something like

```javascript
import React from 'react'
import reactDom from 'react-dom/server'
import dom from 'cheerio'
import Root from 'components/Root'

const render = reactDom.renderToStaticMarkup

import test from 'tape'

const noop = () => {}

const props = {
  goal: { list: [] },
  isEditing: {
    goal: false,
    postback: false
  },
  onChange: {
    goal: {}
  },
  onClick: {
    goal: {}
  },
  onClickGoal: noop,
  onClickNew: noop,
  onMount: noop
}

test('Root component', (t) => {
  const el = (
    <Root
      {...props}
    />
  )

  const $ = dom.load(render(el))
  const $h1 = $('h1')

  t.equal($h1.html(), 'My app')

  t.end()
})
```

### Expected behaviour

Run tests server side with no error.

### Actual behaviour

When I run tests server side, since Clipboard uses [ForbesLindesay/matches-selector](https://github.com/ForbesLindesay/matches-selector), I get this error

```
var proto = Element.prototype;
            ^

ReferenceError: Element is not defined
```

### Browsers affected

None

**Comment by thebarada** [comment]
+ with angular universal

**Comment by zenorocha** [comment]
I think this is finally fixed in `v1.5.14`, could you please test it @fibo and @thebarada?

**Comment by fibo** [comment]
ok, thanks!

 I opened an issue on a component using Clipboard.js (maybe you do not see it cause it is private), so it is in my todo list.

**Comment by zenorocha** [comment]
Awesome! I basically got rid of the dependency that caused that problem and rewrite that piece of code. Now I have control to change anything if needed.

**Comment by fibo** [comment]
here it the issue on the private repo

<img width="771" alt="screen shot 2016-10-24 at 10 42 55" src="https://cloud.githubusercontent.com/assets/176730/19638998/adef053c-99d6-11e6-9850-6d56fa5b7882.png">
