### ISSUE TITLE
Data is not copied to Clipboard.

### ISSUE THREAD

**Issue by Balakumar90** [zenorocha/clipboard.js#275]
I am using Clipboard.min.js . The control flow goes inside  `clipboard.on('success', function (e)` successfully but data is not copied to clipboard. I am using IE 11. **This functionality working in Google chrome but not in IE and firefox.**

HTML :  `<button` id="btn" class="btn btn-primary btn-success" data-clipboard-text="testing" `data-bind="click:$parent.addList">`

I wrote the below code in addList. 

JS : 
```
 var btn = document.getElementById('btn');
            var clipboard = new Clipboard(btn);

            clipboard.on('success', function (e) {
                console.log(e);
            });

            clipboard.on('error', function (e) {
                console.log(e);
            });
```

Please help

**Comment by zenorocha** [comment]
Everything seems to be working here.

Check our [demos](https://github.com/zenorocha/clipboard.js/tree/master/demo) and if things still don't work feel free to share a JSFiddle that reproduces the actual error.
