### ISSUE TITLE
Support for disabled inputs

### ISSUE THREAD

**Issue by cezarlz** [zenorocha/clipboard.js#276]
### Minimal example

Example: https://jsfiddle.net/zp0o56ns/1/

### Expected behaviour

Copy as the same way.

### Actual behaviour

Don't copy with disabled inputs.

### Browsers affected

Chrome, Firefox and Opera on macOS.

**Comment by cezarlz** [comment]
Tested with `readonly` attr and works fine!

**Comment by zenorocha** [comment]
Yes, `readonly` is the attribute you should use instead :)
