### ISSUE TITLE
Only Works on IE!

### ISSUE THREAD

**Issue by mehmetalidumlu** [zenorocha/clipboard.js#278]
Hi all,
It works on IE11 but not works other browsers on Windows.
I want copy hidden div text to clipboard on mouse right click. 
There is main javascript class

****************
`init(){
var clipboard;
map().addEventListener('contextmenu', function (e) {
        e.preventDefault();
        var newCoordinate = $('#hiddenCoordinates').text().trim();

        clipboard = new Clipboard('#hiddenCopyButton', {
            text: function (trigger) {
                return newCoordinate;
            }
        });

        $("#hiddenCopyButton").trigger("click");
        clipboard.destroy();

    });

    clipboard = new Clipboard('#hiddenCopyButton');

    clipboard.on('success', function (e) {
        e.clearSelection();
        showProccessInformation(1, 'Saved !');
    });

    clipboard.on('error', function (e) {
        showProccessInformation(2, 'Error !');        
    });
}`
*******************************

Can you help me about this?

**Comment by zenorocha** [comment]
Clipboard.js don't have support to mouse right click events, it comes with a predefined click event listener. I recommend using `execCommand` directly to achieve what you're looking for.
