### ISSUE TITLE
Support for paste

### ISSUE THREAD

**Issue by josdejong** [zenorocha/clipboard.js#28]
Thanks for writing clipboard.js, really awesome!

Besides support for `copy` and `cut`, it would be great be able to `paste` text too.

**Comment by realityking** [comment]
As far as I know, browsers don't allow read access to the clipboard because of the privacy implications.

**Comment by josdejong** [comment]
I'm afraid you're right. Because of security issues browsers don't allow programmatically getting data from the system clipboard. I was hoping for a way to add cut/copy/paste buttons on top of web based editors.

It is possible though to "intercept" a paste event triggered by a user (via context menu or Ctrl+V), and do something with the pasted content, see for example [this stackoverflow answer](http://stackoverflow.com/questions/2176861/javascript-get-clipboard-data-on-paste-event-cross-browser/6804718#6804718).

**Comment by GomesNayagam** [comment]
i tried a lot for execCommand('paste') security issue, so for no luck. Love to see it here.

**Comment by zenorocha** [comment]
Exactly, there are lot of privacy implications involved.

**Comment by GomesNayagam** [comment]
also i have another quick quesiton, we do have the https://w3c.github.io/clipboard-apis for clipboard api and here is the current implementation status of it http://caniuse.com/#feat=clipboard, so which one is preferred to use

**Comment by zenorocha** [comment]
"[5] Does not support the ClipboardEvent constructor"
