### ISSUE TITLE
Require.js compatibility issue

### ISSUE THREAD

**Issue by jkauffman503** [zenorocha/clipboard.js#280]
I'm using MadCap Flare to create help docs, which uses require.js to serve up a bunch of scripts required for the docs to work. I tried using clipboard.js and I'm getting a "Mismatched anonymous define() module: " error. Is there any way to make the clipboard.min.js script work without the define() function? I'm not super familiar with javascript, so any explanation would be helpful! Thanks.

**Comment by zenorocha** [comment]
Hey @jkauffman503, everything seems to be working fine with require.js over here: https://jsfiddle.net/zenorocha/0yup6bof/. Please share a JSFiddle so we can reproduce the error.

**Comment by jkauffman503** [comment]
I figured out it's the program I'm using, nothing wrong with clipboard.js. Thanks!

**Comment by zenorocha** [comment]
Cool, thanks for letting us know :)

**Comment by spolisano** [comment]
Hey @jkauffman503 how did you make it in Flare? I have the same issue and I can't Figure it out. Cheers!

**Comment by jkauffman503** [comment]
@spolisano I wish I remembered, sorry! I'm no longer with the company and don't have access to the project to even see what I did. Good luck!

**Comment by sfwaer** [comment]
Hey @spolisano did you find the solution ? I have the same issue and I'm still trying.
Thanks.

**Comment by spolisano** [comment]
Hey @sfwaer , I just called it from a local repo and it worked. Hope it might help
