### ISSUE TITLE
Copying text in Angularjs

### ISSUE THREAD

**Issue by deejay220989** [zenorocha/clipboard.js#281]
Hi,

Is it possible to perform a copy of text to the clipboard in AngularJS instead of doing it in the HTML? For example, ngClipboard.toClipboard('textToBeCopied') will add the text "textToBeCopied" to my clipboard.

Thanks!

**Comment by zenorocha** [comment]
Feel free to use https://github.com/sachinchoolur/ngclipboard or https://github.com/maxisam/angular2-clipboard :)
