### ISSUE TITLE
Problem with safari fallback

### ISSUE THREAD

**Issue by Pudge601** [zenorocha/clipboard.js#285]
The fallback behaviour in safari doesn't work for copying text from the 'fake' textarea element when providing a DOM element as the trigger (as opposed to using a selector).

Open this fiddle in safari to see the issue: https://jsfiddle.net/Ltas2obg/

This seems to be because the textarea gets removed during the same click event as the one which tries to perform the copy, because the listener for removing the 'fake' gets added to the body, and the click event is able to propagate up to the body after the click on the element has been handled.

This isn't an issue when using a selector, because it listens to click events on the body itself, and so the newly added listener to remove the fake will not be called during the same click event.

**Comment by chrisminett** [comment]
Perhaps could add `e.stopPropagation()` within the Clipboard.js click handler?

**Comment by kafeltz** [comment]
Looks like a job for setTimeout(fn, 0)!

**Comment by philip** [comment]
Is there a simple workaround for this?

**Comment by zacharytamas** [comment]
This one has wrecked me for the past hour. I should have checked here sooner.

In my case, I'm using this inside an Angular component which will exist multiple times on the page so I can't count on a single ID always. It's handy to just pass exactly the element I want to listen to but then I run into this problem.

Will report back any solutions I find. :)

**Comment by Pudge601** [comment]
As @chrisminett alluded to, you can stop the propagation of the click event so that it doesn't reach up to the body element where the listener is attached for removing the fake textarea.

Since you have a reference to the exact DOM element in question, at the point that you register it with Clipboard.js, you can then also attach a click listener to the same DOM element which simply stops the propagation.

This fiddle demonstrates the workaround: https://jsfiddle.net/Ltas2obg/2/

This may have some side effects if you have other click handling listeners higher up the DOM tree, but this has proved safe for me for a temporary workaround.

If that isn't a viable option, however, you could always provide a function as the `target` config to Clipboard.js which would return a hidden textarea for you to then clean up manually - effectively re-implementing the 'fake' text area which Clipboard.js creates by default.

**Comment by zacharytamas** [comment]
@Pudge601 Yeah I got it to work by stopping the propagation which is definitely One Weird Trick™️  but it will work for us, I think. It's not listened for anywhere above our element. Thanks all for the tips!

**Comment by zenorocha** [comment]
Thanks for reporting and sharing your solutions, if you have any suggestion please feel free to send a pull request.
