### ISSUE TITLE
Unable to copy in any config

### ISSUE THREAD

**Issue by jpearson24** [zenorocha/clipboard.js#287]
I have reproduced a snippet of my code in [JSFiddle](https://jsfiddle.net/ag38qt1k/). My complete page is under my "screenshots" repo in "test3.php", if you need more detail.

I have tried the `<input>` (with a `type="hidden"`) and `data-clipboard-text` (on the submit button) and I can't seem to get it to work. I even added the code you gave to someone else who was using `type="hidden"` (issue #59) however it's still not working.

Knowing me, it's something simple, or something I've done elsewhere that's causing the issue, but if there's something I'm not doing right with your code at least that you can point out, I'd be extremely grateful.

Cheers.

**Comment by zenorocha** [comment]
Hey @jpearson24,

1. You haven't included the clipboard.js script on that JSFiddle. 
2. You're using both `target` and `text` API. Remove the `data-clipboard-target` attribute.

https://jsfiddle.net/zenorocha/msg9tr7f/2/

For more working demos check: https://github.com/zenorocha/clipboard.js/tree/master/demo

**Comment by jpearson24** [comment]
Hmmmm. I've done some more digging, and it would appear it's a bug with Chrome on OSX, where it's not firing `execCommand('copy')` correctly. According to the WebKit bug tracker it has been patched, but Chrome doesn't seem to have the patching implemented. Even using your fiddle it still wouldn't copy, nor would the demos I copied straight across.

**Comment by zenorocha** [comment]
Interesting, tons of people use this library everyday and nobody reported a bug on Chrome yet. Let me know if there's something related to clipboard.js that I can help with.

**Comment by jpearson24** [comment]
Ok, so issue resolved. I'm not sure why or how, but when I put the `<script>` link to the .js file down the bottom, it suddenly miraculously worked.

**Comment by kafeltz** [comment]
Try to search some OnReady events from javascript and init your stuff inside it. It seems to be that issue.

**Comment by zenorocha** [comment]
Do you mean `document.addEventListener("DOMContentLoaded", ...)`? This shouldn't be required, see how all the examples from `demo` folder work without them.
