### ISSUE TITLE
setSelectionRange triggers clipboard event

### ISSUE THREAD

**Issue by devnull791101** [zenorocha/clipboard.js#289]
### Minimal example

im unable to get a jsfiddle working

### Expected behaviour

triggering a jquery event on an anchor to copy text from a "pre" element to the clipboard. 

### Actual behaviour

when there is a large amount of text  (353kb in my example) line 260 : 

element.setSelectionRange(0, element.value.length);

causes the text to be copied to the clipboard. when line 499:

succeeded = document.execCommand(this.action);

is executed a blank entry is added to the clipboard 

### Browsers affected

Chrome Version 52.0.2743.116 (64-bit) / linux

<a id='action_copy' href="#"><i class="icon-docs"></i><span>Copy</span></a>

jQuery(document).ready(function() 
	{ 
		new Clipboard("#action_copy", {
			text : function (e) {
				var t = $("div").filter(".tab-pane").filter(".active").attr("id");
				if (t.length > 0)
				{
					if ($("#" + t + " pre").length)
					{
						return $("#" + t + " pre").text();
					}
					else
					{
						return "";
					}
				}
				else
				{
					return "";
				}
			},
		});
}

**Comment by zenorocha** [comment]
Hey @devnull791101, unfortunately I wasn't able to reproduce this bug. Please share a JSFiddle or something like that so we can see it happening. Thanks for sharing!
