### ISSUE TITLE
Copy Text of Selected <select> element

### ISSUE THREAD

**Issue by engemasa** [zenorocha/clipboard.js#290]
### Example

https://jsfiddle.net/engemasa/uqrLtegc/1/

### Expected behaviour

I would expect the text of a select element's selected item would be copied to the clipboard

### Actual behaviour

An empty string was copied to the clipboard. (On FireFox a blank space was copied: " ")

### Browsers affected

Tested on Chrome, FireFox, and IE11. Only IE11 threw an error: 
```
SCRIPT16389: Unspecified error.
clipboard.min.js (7,3097)
```
### Suggested Resolution

document.getElementById('foo').options[document.getElementById('foo').selectedIndex].text

**Comment by engemasa** [comment]
In the mean time, I found an angular approach that works for this:

```
<select ng-model="ctrl.selectedCustomer"
     ng-options="item.name for item in ctrl.customerList track by id"></select>

<button class="btn btn-primary copy-to-clipboard" ng-disabled="!ctrl.selectedCustomer"
     data-clipboard-text="{{ ctrl.customerList[ctrl.selectedCustomer.id].name }}">
     Copy to Clipboard <i class="fa fa-clipboard fa-fw"></i>
</button>

```

**Comment by zenorocha** [comment]
Hey @engemasa, thanks for reporting!

I'd love to have this feature as well. I played a little bit with it but it seems like it won't be possible to make this work with `data-clipboard-target`. You'll need to use `data-clipboard-text` (like you already did) or use the imperative API.

```js
new Clipboard('.btn', {
    text: function(trigger) {
        return document.querySelector('select').value;
    }
});
```
