### ISSUE TITLE
Code not working on iOS (browser and app version)

### ISSUE THREAD

**Issue by michaelwalgraeve** [zenorocha/clipboard.js#293]
### Minimal example

https://jsfiddle.net/mwalgraeve/b0tzbf39/

### Expected behaviour

Copy function is not working in Safari on iOS and in iOS App.

### Actual behaviour

I get an error message in the console but it is not clear to me what is wrong. Any help? 

### Browsers affected

Safari

**Comment by PandaWood** [comment]
You're expectation seems to be wrong, the documentation for this project clearly states that Safari is not supported.

> The execCommand aren't supported on Safari yet (including mobile)

**Comment by BubbaJoe** [comment]
Can this be reopened? Not working for me on the iPhone XR (Safari/Chrome) or the Chrome Devtool (iPhone 6/7/8/X)
