### ISSUE TITLE
Use setAttribute("style") instead of el.style

### ISSUE THREAD

**Issue by chrisbenseler** [zenorocha/clipboard.js#294]
Zeno, couldn't this piece of code in clipboard-action.js:

```
this.fakeElem.style.fontSize = '12pt';
this.fakeElem.style.border = '0';
this.fakeElem.style.padding = '0';
this.fakeElem.style.margin = '0';
//etc...
```

be rewritten with the following syntax:
```
this.fakeElem.setAttribute("style","fontSize: 12pt, border: 0, padding: 0, margin: 0");
```

? I think there are no side effects with this implementation.

so it wouldn't be necessary to repeat this.fakeElement.style for each css attribute.

**Comment by zenorocha** [comment]
That's a personal preference but thanks for sharing your thoughts @chrisbenseler :)
