### ISSUE TITLE
Prueba LAB

### ISSUE THREAD

**Issue by yaninavaleria** [zenorocha/clipboard.js#295]
### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

### Expected behaviour

I thought that by going to the page '...' and pressing the button '...' then '...' would happen.

### Actual behaviour

Instead of '...', what I saw was that '...' happened instead.

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

**Comment by yaninavaleria** [comment]
![j0405026](https://cloud.githubusercontent.com/assets/20710452/18016555/f900ddee-6b9a-11e6-8df6-7a997b530cf4.jpg)
![j0401924](https://cloud.githubusercontent.com/assets/20710452/18016570/06687ae6-6b9b-11e6-8341-3d0ada2b40be.jpg)

**Comment by yaninavaleria** [comment]
Buscando plugin

**Comment by zenorocha** [comment]
![](https://media.giphy.com/media/XrHc1gDORei1q/giphy.gif)
