### ISSUE TITLE
Clipboard not defined

### ISSUE THREAD

**Issue by lausianne** [zenorocha/clipboard.js#296]
This is my code, nothing else:

```
<script src="https://cdn.jsdelivr.net/clipboard.js/1.5.12/clipboard.min.js"></script>
<script>
    new Clipboard('.cbcopy');
</script>
```

Result: Uncaught ReferenceError: Clipboard is not defined

EDIT: Meanwhile I found the hidden complete example:
https://github.com/zenorocha/clipboard.js/blob/master/demo/constructor-selector.html#L18
Result is the same: Clipboard is not defined

EDIT 2: Now I found that the error only occurs when the code is loaded via AJAX. If called directly, it works. So maybe it's no bug at all and just a matter of correct code placement. Sorry if it's just my fault.

**Comment by diogoca** [comment]
Hi Lausianne,

Here the same... loading via
`<script src="//cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.12/clipboard.min.js" async></script>`

**Comment by zenorocha** [comment]
Everything seems to be working fine over here, please share a JSFiddle with a reproducible bug.

**Comment by lausianne** [comment]
Have you tried via AJAX? I wouldn't know how to test that with JSFiddle.

**Comment by zenorocha** [comment]
I haven't because a reproducible scenario has not been provided. If someone else has the same issue and has the ability to reproduce it, please share with us so we can evaluate this problem.

**Comment by lauff** [comment]
I am having the same problem. 
The issue is closed, but I can't find the solution...
Thanks Markus

**Comment by zenorocha** [comment]
Can you provide a JSFiddle that reproduces your problem @lauff?

**Comment by lausianne** [comment]
I assume that my original error was because of AJAX: code does not run in browser, but on server, so JS is not executed.

**Comment by budwig** [comment]
lausianna, have you tried to load clipboard.min.js at the end of your page, after the ajax call is made?

**Comment by lausianne** [comment]
Yes, exactly. Otherwise `new Clipboard('.cbcopy');` will find nothing. (I'd need to check the code to find out for sure.) 
But two conditions are for sure: 
1. JS does not run on server (unless, perhaps, with node.js)
2. The object to be clicked for Clipboard must exist before the script is called

**Comment by budwig** [comment]
lausianna, I use AJAX a lot, and I do encounter this recurrent problem of JS not being "seen" by the html code returned by the AJAX call. The solution is to run the JS when the DOM is ready. So try this:

`<script>
$(document).ready(function () {
    new Clipboard('.cbcopy');
});

// or shorthand
$(function () {
    new Clipboard('.cbcopy');
});
</script>`

**Comment by lauff** [comment]
> Can you provide a JSFiddle that reproduces your problem @lauff?
let's see, I have a bigger dynamically created page - I will try

**Comment by gatetothestars** [comment]
Howdy folks. 
My app was working in development but not in production.
My **solution** was to link  
 `<script src="https://cdn.jsdelivr.net/npm/clipboard@1/dist/clipboard.min.js"></script>`
instead of linking to my local folders copy in node_modules/dist etc. 
Seemed to do the trick.:relieved:  
Good luck!

**Comment by ottz0** [comment]
Same isssue, can only run using the CDN and not from node_modules folder

**Comment by moth** [comment]
Same for me. Can only run using the CDN and not from node_modules folder.

**Comment by rswhite7** [comment]
Surprised this still isn't fixed.  I couldn't get version 2.0.0 to work loaded via AJAX, then instantiating Clipboard after AJAX finished.  My solution was to revert back to version 1.7.1 and now it works.  I'm using loadjs to call the node_modules file, then on success I instantiate Clipboard and it works great.

**Comment by albabsaifi** [comment]
In case if anyone's still struggling to make it work with requirejs, here's how it's done:

**1) Your requirejs config file should look like this:**

```
"use strict";
require.config({
    baseUrl: '',
    paths: {
        'jquery': 'vendor/jquery/jquery.min',
        'plugins/clipboard': 'vendor/clipboard/clipboard.min',
        'modules/clipboard': 'js/modules/clipboard',
    },
    shim : {
        'jquery': {
            exports: '$'
        },
        'pluggins/clipboard': {
            exports: 'ClipboardJS',
            deps: ['jquery']
        },
    },
    priority : ['jquery']
});
```

**2) In the module file:**

```
define([
    'jquery',
    'clipboard'
], function ($,ClipboardJS){ **//Notice the parameters**
    new ClipboardJS('.btn);
});
```

**Comment by waterfan312** [comment]
Hello, old chap, you needn't exports use ClipboardJS, just use it as parameters called ClipboardJS

**Comment by asfarley** [comment]
Hi, 

I seem to be running into this issue (ReferenceError: Clipboard is not defined) using the latest CDN releases:
<script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>
or
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js"></script>

However, if I go back to this version then I don't get the error:
<script src="https://cdn.jsdelivr.net/clipboard.js/1.5.3/clipboard.min.js"></script>

As mentioned by @rswhite7, I tried using the JQuery run-after-loaded recommendation, but it did not work for me; I still got 'ReferenceError: Clipboard is not defined'.
