### ISSUE TITLE
Copy without style information

### ISSUE THREAD

**Issue by moddish** [zenorocha/clipboard.js#299]
When you set to copy the contents of a div, I want to copy the content and any html that is in it like bold, italic etc but dont want the styles that are being inherited from other divs. EG if no styles are set, the font is auto new times romand, and when pasted into a mail editor etc the styles from the page it was copied from are being carried over, I want to copy without any style information. Is that possible?

**Comment by kjgarza** [comment]
I actually think copy without any style (plain text) should be the default.

**Comment by zenorocha** [comment]
Hey @moddish, try using this https://github.com/zenorocha/clipboard.js#copy-text-from-attribute or https://github.com/zenorocha/clipboard.js#advanced-options.
