### ISSUE TITLE
Submit clipboard.js to jsDelivr

### ISSUE THREAD

**Issue by gjmveloso** [zenorocha/clipboard.js#30]
Hi Zeno,

I was thinking if we could add this amazing library to JSDelivr and help more developers to incorporate your llbrary using a CDN - even the library is pretty small ;)
[Seems to be something really straightforward](https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md) and if you want my help on this just let me know.

Thanks again for your great job!

**Comment by zenorocha** [comment]
Hey @gjmveloso, that's a good idea. Could you do that?

**Comment by gjmveloso** [comment]
I'lll work on it. I'll let you know when it's done and integrated with jdDelivr.

Thanks,
Gustavo

**Comment by gjmveloso** [comment]
Olá @zenorocha,

Just sent [the pull request](https://github.com/jsdelivr/jsdelivr/pull/7223). Hopefully I got the contributing guide right and we can see clipboard.js on jsDelivr soon.

Thanks,
Gustavo

**Comment by gjmveloso** [comment]
It's done and working. [Website UI still needs to be refreshed](http://www.jsdelivr.com/?query=clipboard.js) but we can access the latest version from https://cdn.jsdelivr.net/clipboard.js/latest/clipboard.min.js

**Comment by jimaek** [comment]
Our API is a bit slow right now. It will be fixed soon, normally updates are made available through the site immediately. The files are still uploaded instantly.

P.S. I dont recommend using /latest/ in production. Only for testing/debugging/demos
