### ISSUE TITLE
Whether support Safari ?

### ISSUE THREAD

**Issue by lebornjose** [zenorocha/clipboard.js#302]
### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

### Browsers affected
Safari is supported

**Comment by kafeltz** [comment]
It does not work here.

**Comment by zenorocha** [comment]
https://github.com/zenorocha/clipboard.js#browser-support

**Comment by evanjmg** [comment]
Still does not work for function text copying

**Comment by zenorocha** [comment]
@evanjmg please share a JSFiddle with a reproducible example.

**Comment by evanjmg** [comment]
https://jsfiddle.net/evanjmg/on1wrxry/ - works in chrome, but doesn't work in safari. I have to use window.prompt as a fallback. I need to programmatically copy text in all browsers for a project I'm working on .

**Comment by zenorocha** [comment]
Everything seems to be working fine over here.

![bug](https://cloud.githubusercontent.com/assets/398893/19839257/ae674dde-9e9b-11e6-850e-63f57c215ef8.gif)

**Comment by evanjmg** [comment]
ah checked my browser and it's safari 9.2

**Comment by zenorocha** [comment]
No worries :)
