### ISSUE TITLE
how to copy from the window prompt

### ISSUE THREAD

**Issue by kunkaiHuang** [zenorocha/clipboard.js#303]
I can not copy from the window prompt,can you show me the way to copy from window prompt,thank you very much

**Comment by zenorocha** [comment]
Please share a JSFiddle with the expected behavior.

**Comment by kunkaiHuang** [comment]
https://jsfiddle.net/hkkk/omtwc654/1/  , when i click the button,it will have a window prompt,if i choose yes,i can copy "hkkk".if i choose no,i can not copy "hkkk".I do not how to achieve it if i use clipboard.js.Can you show me some method,thank you very much!
