### ISSUE TITLE
The event is wrong on IE 11 when I don't allow the website to access my clipboard

### ISSUE THREAD

**Issue by Dragon-Rider** [zenorocha/clipboard.js#304]
Hi, there :)

I found the "events" of clipborde.js don‘t work well on IE 11,  when I didn't allow the website to access to my clipboard.

### Minimal example

> https://jsfiddle.net/EragonJiang/6zuguyjx/3/

### Expected behaviour
![image](https://cloud.githubusercontent.com/assets/8859216/18377797/c39c8070-769b-11e6-801e-b3ae8e71373d.png)

If  you choose "Don't allow" on IE 11(Windows 7),  and then click the "copy" button, you can't copy anything from the input box, and the event should be ‘error’.

### Actual behaviour
Instead of 'error', what I saw was that 'success' happened instead and my clipboard is empty. 

### Browsers affected

I tested on all major browsers and IE 11 and 10 does not work.

**Comment by Dragon-Rider** [comment]
I read your source code and found that you use the parameter 'succeeded' to check the "document.execCommand(this.action)". And I test it on IE. If I choose “don't allow the website access to the clipboard”, then I execute this command（“document.execCommand(copy)”）. It still return 'true'，but my clipboard is empty.

![image](https://cloud.githubusercontent.com/assets/8859216/18378136/b241524a-769d-11e6-8695-bd3967c84b36.png)

**Comment by zenorocha** [comment]
Hey @Dragon-Rider, this is a known issue https://github.com/zenorocha/clipboard.js/issues/77 https://github.com/zenorocha/clipboard.js/wiki/Known-Issues. At this moment, there are no solutions for this problem. If you have an idea, please feel free to send a pull request.
