### ISSUE TITLE
Firefox vs Chrome

### ISSUE THREAD

**Issue by radar1975** [zenorocha/clipboard.js#305]
### Minimal example

https://jsfiddle.net/5kk0eysw/2/

### Expected behaviour

When i ctrl-v it is suppose to return the text value

### Actual behaviour

In chrome it work just find but not in FF

**Comment by zenorocha** [comment]
It is working over here, just tested on Firefox 47 and Firefox Aurora 50.

**Comment by radar1975** [comment]
Thanks for your time but FF 48 it's not .... i will see what i can do

**Comment by zenorocha** [comment]
Just upgraded to Firefox 48 and everything still works.

**Comment by radar1975** [comment]
Sorry about that ... certainly, a issue on my side
Thanks for your time
