### ISSUE TITLE
Display Message

### ISSUE THREAD

**Issue by jt4000** [zenorocha/clipboard.js#306]
If you have a picture or text and when you press it by using the left click mouse button a message "Copied!" should display. Today, there is a function for it but it is only for <button>. Please take a look at the attached picture.

Is it possibly to do it?

Thank you!

![asdf](https://cloud.githubusercontent.com/assets/14993569/18542400/fcd5c12e-7b2a-11e6-9132-7005fea81e5e.png)

**Comment by stamster** [comment]
I just do `alert()` message, users are one eye blind at times and you need to explicitly inform them about some event.

**Comment by zenorocha** [comment]
clipboard.js is not opinionated about tooltip implementations. It only does what it needs to do and you can handle that kind of user feedback on the `success` callback. If you need some inspiration check out the `gh-pages` from this project which contains the website.
