### ISSUE TITLE
react-bootstrap modal also failing in Firefox

### ISSUE THREAD

**Issue by ansonkao** [zenorocha/clipboard.js#308]
The following does not work in Firefox: https://jsfiddle.net/jr0wn11w/1/

It is using `react-bootstrap` for the modal. This library has it's own implementation (it does not use the jQuery plugin that comes with bootstrap). 

I read the other issues talking about similar problems with modals but am unsure as to how to debug the problem. Any ideas?

**Comment by ansonkao** [comment]
Resolved by turning off the `enforceFocus` option in `react-bootstrap.Modal`.

[Documentation](https://react-bootstrap.github.io/components.html#modals)

**Comment by kafeltz** [comment]
https://github.com/zenorocha/clipboard.js/issues/155

**Comment by zenorocha** [comment]
Check the new `container` option introduced by #368 on `v1.7.0`
