### ISSUE TITLE
Run clipboard trigger programmatically

### ISSUE THREAD

**Issue by danilychen** [zenorocha/clipboard.js#310]
There is an requirement to make ajax request on button click and then run clipboard trigger with custom data. It will be great to run clipboard trigger programmatically - not only on click event.

**Comment by cnrudd** [comment]
I don't think that the browser security models built around execCommand allow for a copy to clipboard that was not directly triggered by a user event.  The click that triggers your async ajax request does not carry through to the callback triggered by the request's success.

You can make it work if you set ajax to sync = true, but that will freeze your browser till the request completes.

I worked around this by opening a modal that says 'preparing your [whatever]...' and when the ajax request completes, enable a 'copy' button on the modal.

If you have other ideas, I'd be glad to hear them.

**Comment by zenorocha** [comment]
@cnrudd is right, that's a browser security thing.

**Comment by xuyongchaos** [comment]
`
setTimeout(function(){
   $('copy_btn').trigger('click')
}, 100)
`

this is not working too
