### ISSUE TITLE
ClearSelection does not work with text in textarea in IE

### ISSUE THREAD

**Issue by gtrubach** [zenorocha/clipboard.js#312]
Textarea text selection does not cleared in IE. I found that blur() doesn't work as in Chrome or Firefox. Maybe I'm wrong?

**Comment by zenorocha** [comment]
Hey @gtrubach, please inform the exact version of IE and share a JSFiddle that reproduces this problem.

**Comment by gtrubach** [comment]
[JSFiddle](https://jsfiddle.net/gtrubach/7amepaby/) 
IE version 11.

**Comment by JohnArcher** [comment]
Why is that issue closed? That bug still exists. Problem is, that `e` does not have the function `clearSelection()` attached in IE.
