### ISSUE TITLE
Demo page (and simple use in my build) not working in Safari 9.1.1 (OSX 10.11.5)

### ISSUE THREAD

**Issue by blakerutledge** [zenorocha/clipboard.js#314]
It results in an error on click. 

Chrome works as expected! I thought it was something I was doing wrong but checked on the demo page and that's not working for me in Safari.

Can anyone recreate this?

**Comment by zenorocha** [comment]
Hey @blakerutledge,

Check the browser support table: https://github.com/zenorocha/clipboard.js#browser-support
Fallback ideas are provided there was well.

**Comment by blakerutledge** [comment]
oh awesome. i saw the safari icon and misread the 10. my bad there. sorry about that!

**Comment by zenorocha** [comment]
No worries :)
