### ISSUE TITLE
[clipboardjs] Copy multiple target elements.

### ISSUE THREAD

**Issue by lovebdsobuj** [zenorocha/clipboard.js#319]
Is't possible coping multiple target elements?
Like, **`data-clipboard-target="#data-*"`**

**Comment by kafeltz** [comment]
Make a test!

**Comment by lovebdsobuj** [comment]
Simply it's not working. 
Need a sample demo.

**Comment by zenorocha** [comment]
You can't copy multiple target elements at once. But you can [use the imperative API](https://github.com/zenorocha/clipboard.js#advanced-options) for that, for example:

```js
new Clipboard('.btn', {
    text: function(trigger) {
        var a = document.querySelector('#a').value;
        var b = document.querySelector('#b').value;
        return a + b;
    }
});
```

**Comment by dayanneramos** [comment]
I modified what he did, in order to use in multiple places...
pasting here if somebody need:

new Clipboard('.btn-copy-mutiple', {
        text: function (trigger) {
            var targets = $(trigger).data('clipboard-targets');
            targets = targets.split(',');
            var copyString = '';
            var qtd = targets.length;
            for (var i = 0; i < qtd; i++) {
                copyString += ' ' + $(targets[i]).text();
            }
            return copyString;
        }
    });


button:
<a class="btn-copy-mutiple btn" data-clipboard-targets="#chamado-id27558,#chamado-titulo27558"><i class="fa fa-copy"></i></a>


ps:
.text() or val(), depending on what you're going to copy

**Comment by craigtommola** [comment]
I have generated a list of user emails (based on role) from WordPress. I'm trying to get a button on the page that will "copy all" emails. Thoughts on this?
