### ISSUE TITLE
Can I copy actual HTML tags and css?

### ISSUE THREAD

**Issue by rgfx** [zenorocha/clipboard.js#321]
I read all the issues, it seems some people were able to copy HTML but maybe am missing something.

They seems like they wanted to just copy text, I want copy everything,  tags and css inside a specified element. 

I used the code found #72 still just copying text without tags. 

Please advise.

**Comment by rgfx** [comment]
Was hoping and clipboard.js could support this, never heard got a response. I had to find another solution. I manage to remove the need for clipboard.js all together with a few lines of JS. 

Good support for cut and paste using Document.execCommand()

copy/cut : Chrome < 42,	 Firefox  < 41 (41),	IE < 9, Opera < 29,  Safari <10

Here is working code with no dependencies. http://codepen.io/rgfx/pen/GjOmOL

Jquery with pop notification. http://codepen.io/rgfx/pen/yaPWGg

Hope this helps someone.

**Comment by zenorocha** [comment]
@rgfx clipboard.js supports copying any kind of string you pass to it.

```js
new Clipboard('.btn', {
    text: function() {
        var htmlBlock = document.querySelector('.yourSelector');
        return htmlBlock.innerHTML;
    }
});
```

But I'm glad you were able to leverage your own copy to clipboard solution :)

**Comment by rgfx** [comment]
@zenorocha thanks for the response, even it was tad bit late. Learned some more js so it wasn't all that bad.

**Comment by zenorocha** [comment]
🎉 🎉 🎉

**Comment by ottz0** [comment]
What if you have multiple code blocks on one page? Do you need to instantiate a new clipboard for each block ('.yourSelector'), ('.yourSelector1')?

```
new Clipboard('.btn', {
    text: function() {
        var htmlBlock = document.querySelector('.yourSelector');
        return htmlBlock.innerHTML;
    }
});
```

**Comment by skunkwerk** [comment]
This just copies the HTML as text, but when you paste it in Chrome it's not formatted as HTML... it's just text.  Is there any way to avoid this?

**Comment by Johennes** [comment]
Maybe the advanced option documentation changed since 2018 but this doesn't seem to answer the question. All the examples seem to copy plain text (not `text/html`) from what I see.

**Comment by Dan-Do** [comment]
> Maybe the advanced option documentation changed since 2018 but this doesn't seem to answer the question. All the examples seem to copy plain text (not `text/html`) from what I see.

Hello @Johennes, did you solve this? I also want to copy the html code of an element as rich text, so that I can paste to Gmail web client (in browser).

**Comment by Johennes** [comment]
@Dan-Do I ended up doing something else in the project where I needed this ([mailto:me browser extension](https://github.com/Johennes/mailto-me)). I merely needed a nice reader-like view of the content, so I opted for extracting that with [Readability](https://github.com/Johennes/mailto-me/blob/master/content.js#L38) and then copied the resulting HTML to the clipboard like [this](https://github.com/Johennes/mailto-me/blob/master/content.js#L78).
