### ISSUE TITLE
Copy text on keypress

### ISSUE THREAD

**Issue by itsnwa** [zenorocha/clipboard.js#322]
How can I copy the text within this span element: `<span class="git-repo">https://github.com/...</span>` on keypress `C`?

**Comment by zenorocha** [comment]
Hey @itsnwa, thanks for asking! clipboard.js does not support `keypress` events, I recommend you to leverage your own implementation using `document.execCommand('copy')`.

**Comment by itsnwa** [comment]
Okey, I see - thank you :)
