### ISSUE TITLE
[Question] Can not begin to use issue

### ISSUE THREAD

**Issue by Kristinita** [zenorocha/clipboard.js#323]
### Summary

I can not to make simple `copy` button.

### Expected behavior

![Simple `copy` button](http://i.imgur.com/qHFT3nG.png)

### Actual behavior

Not `copy` button.

### Steps to reproduce

My not working code: <http://cssdeck.com/labs/reaxdmj8>. I can not to make simple `copy` button and successful reproduce your examples.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.4.0/clipboard.js"></script>
    <script>
        var new Clipboard('.Sasha');
    
        clipboard.on('success', function(e) {
        console.log(e);
    });
    clipboard.on('error', function(e) {
        console.log(e);
    });
    </script>
</head>
<body>
  <pre><code class="Sasha">Sasha Goddess
Sasha Miracle</code></pre>
    
  <br>

    <textarea id="bar">Test</textarea>

    <!-- Trigger -->
    <button class="btn" data-clipboard-action="cut" data-clipboard-target="#bar">
        Cut to clipboard
    </button>
</body>
</html>
```

### Environment

**Operating system and version:**
Windows 10.0.14393
**Browser:**
Firefox 49.0.1

Thanks.

**Comment by chriskellet** [comment]
Your code has many errors in it.  
Have a look at this modified version of you example http://cssdeck.com/labs/pwahbkej

**Comment by zenorocha** [comment]
Exactly, thanks @chriskellet :)

**Comment by Kristinita** [comment]
@zenorocha, @chriskellet, see expected behavior. I don't need to copy button for `textarea` element.

![No Textarea](http://i.imgur.com/s73O8yF.png)

I need `Copy` button for my code as in [title page clipboard.js](https://clipboardjs.com/) site:

![Expected behavior](http://i.imgur.com/nVXzySA.png)

### Steps to reproduce

I run command prompt in node_modules folder of my project → I install Clipboard.js — `npm install clipboard --save`. 
My code: <https://github.com/Kristinita/Kristinita.github.io/blob/1ffe4530e30a0b055a7fb51687d9a45d9ac75191/Sublime-Text/Test.html>
GitHub Pages: <http://kristinita.ru/Sublime-Text/Test>

```html
<!doctype html>
<html lang="en">

<head>
    <title> </title>
    <style type="text/css">
    body {
        background: sienna;
        color: pink;
        margin: 0;
    }

    code {
        font-size: 19px;
    }
    </style>
    <script src="../node_modules/clipboard/dist/clipboard.min.js"></script>
    <script src="../bower-components/rainbow/dist/rainbow.min.js"></script>
    <script>
    new Clipboard('.SashaButton');
    </script>
    <link rel="stylesheet" type="text/css" href="../bower-components/rainbow/themes/css/espresso-libre.css">
</head>

<body>
    <main>
        <p>Test</p>
        <pre class="SashaClipboard"><code>17uctxtsWG3gpyAy6iJ8AVd5rdSjkJH2</code>&nbsp;<button class="SashaButton" data-clipboard-target=".SashaClipboard"><img src="https://clipboardjs.com/assets/images/clippy.svg" alt="Copy to clipboard" width="13"></button></pre>
        <p>Example</p>
        <p>Another example code:</p>
        <pre><code data-language="json">
        &quot;target&quot;: &quot;ansi_color_build&quot;,
        &quot;syntax&quot;: &quot;Packages/ANSIescape/ANSI.tmLanguage&quot;
        </code></pre></main>
</body>

</html>

```

If I press `Copy` button, code not copy for me, I see error in Firebug:

    TypeError: t is null
    
    ...){var a=i.apply(this,arguments);return t.addEventListener(n,a,r),{destroy:functi...
    
    clipboard.min.js (line 7, col 1005)

![Firebug Error](http://i.imgur.com/PWeVEoo.png)

Thanks.
