### ISSUE TITLE
firefox 49.0 vertion not working

### ISSUE THREAD

**Issue by woolf07** [zenorocha/clipboard.js#324]
**===== HTML**
`<button class="btn-copy" data-clipboard-text="text to copy" id="value-url">
   <span class="share-icon"></span>
   <em class="cb-msg">Share</em>
</button>`

**===== JS**
`var clipboard = new Clipboard('.btn-copy');

clipboard.on('success', function(e) {
    console.log('Copied Success' + e);
    $(e.trigger).html('<span class="share-icon"></span> <em class="share-msg">Share</em>').addClass('share-cb');

});

clipboard.on('error', function(e) {
    console.log('Copied Failed' + e);
});`

**====**
Here is console detail:

document.execCommand(‘cut’/‘copy’) was denied because it was not called from inside a short running user-generated event handler.

**Comment by zenorocha** [comment]
Just tested [clipboardjs.com](https://clipboardjs.com/) and [all demos](https://github.com/zenorocha/clipboard.js/tree/master/demo) on Firefox 49 and everything is working fine. Please share a working example on JSFiddle or something like that so we can better debug it.

**Comment by lizadaly** [comment]
I'm seeing this with Firefox 49.0.2 Mac on clipboardjs.com (plus my own code, v 1.5.15).

Screenshot:

![image](https://cloud.githubusercontent.com/assets/19571/19783904/c13a4e48-9c61-11e6-901f-cd71d8025199.png)

**Comment by zenorocha** [comment]
Everything seems to be working fine over here.

![ff](https://cloud.githubusercontent.com/assets/398893/19785582/ccaee652-9c4e-11e6-9c95-e0ca473d2aa2.gif)

**Comment by lizadaly** [comment]
Huh, also works fine on another machine, same FF version, same OS. I reset FF completely and it does work on my machine too. That's puzzling because I had no extensions installed. Thanks for verifying!
