### ISSUE TITLE
Whenever trying to copy link on IOS the screen zoomed in

### ISSUE THREAD

**Issue by YanivPlaybuzz** [zenorocha/clipboard.js#325]
when i click the button the screen is zoomed in + the text is shown as selected (marked in blue)

thats the code i used :
input id="foo" value="https://github.com/zenorocha/clipboard.js.git">
button class="btn" data-clipboard-target="#foo">
    img src="assets/clippy.svg" alt="Copy to clipboard">
/button>

**Comment by zenorocha** [comment]
Hello, thanks for reporting. Unfortunately I couldn't reproduce this problem. Have you tried including `<meta name="viewport" content="width=device-width, initial-scale=1">`?
