### ISSUE TITLE
Chrome: clipboard.js reports success despite failing to change clipboard when target element is hidden via display: none

### ISSUE THREAD

**Issue by jdpopkin** [zenorocha/clipboard.js#326]
### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.
http://jsfiddle.net/tnLd7zc3/

### Expected behaviour

I thought that when I clicked "Copy" in this JSFiddle one of two things would happen. Either "hello" would replace the contents of my clipboard, or clipboard.js would report a failure (thus avoiding an `alert` in this fiddle).

### Actual behaviour

Instead of "hello" being copied to my clipboard, my clipboard remained unchanged. Instead of seeing no alert, I saw an alert saying "Reporting success, though clipboard wasn't modified".

### Browsers affected

I tested on Chrome 53.

**Comment by zenorocha** [comment]
That is a security limitation imposed by browser vendors. If you need to copy content from a hidden element feel free to use the [imperative API](https://github.com/zenorocha/clipboard.js#advanced-options).

**Comment by jdpopkin** [comment]
Is it possible/worthwhile to fire an error event rather than a success event when the relevant element is hidden? I'm less concerned about the copy failing than I am about Clipboard.js reporting success when this happens.

That said, right now the error event is fired when the _browser_ is the problem. And trying to copy text from a hidden element is a programmer error. So maybe it makes sense to leave this as-is.
