### ISSUE TITLE
Suggested fallback doesn’t work if trigger is specified as an element

### ISSUE THREAD

**Issue by strogonoff** [zenorocha/clipboard.js#330]
This concerns some or all browsers without direct clipboard support, confirmed under Safari 9.1.3.
### Minimal example

[Fiddle](https://jsfiddle.net/jkawfcpo/3/) demonstrating [suggested fallback](https://clipboardjs.com/#browser-support) option twice using different ways of specifying trigger element: first using DOM element, second using selector as a string.
### Expected behaviour

Relevant text is copied after you click either button and press Ctrl+C.
### Actual behaviour

❤️ Text does get copied in the right example, where trigger is specified as a selector.
💔 Text does not get copied in the left example, where trigger is specified as a DOM element.
### Suspected cause

I suspect that in DOM element trigger mode [`fakeHandlerCallback`](https://github.com/zenorocha/clipboard.js/blob/v1.5.15/src/clipboard-action.js#L53) executes on the initial click, destructing the fake textarea and resetting selection before user can press Ctrl+C, while in selector delegation mode the `fakeElem` removal handler gets attached just a bit later and gets triggered on the _next_ click event.
### Browsers affected
- Confirmed under Safari 9.1.3
- All browsers that require fallback, probably

**Comment by HugoCrd** [comment]
This happen because there's a `click` callback on `document.body` which is instantly fired when `selectFake` is fired by a click on the element.
 
https://github.com/zenorocha/clipboard.js/blob/7b5b34913904cb34e6753e19ec1f019b73c620d8/dist/clipboard.js#L439

Removing it, or putting it into a setTimeout "resolves" this issue, but I'm pretty sure it's here for a good reason ;)

**Comment by HugoCrd** [comment]
Does someone had time to look into it?

**Comment by strogonoff** [comment]
At that time I worked around the problem by going with the selector option, although it resulted in a bit clunkier solution.

I’m sure simply being able to read about this quirk will already save troubleshooting time if anyone else gets stuck with this. Might not even be worth complicating the docs with a note about this, since if someone has this trouble searching would probably lead them here.

**Comment by zenorocha** [comment]
Hey guys, I'm on vacations right now, feel free to send a pull request if you find a solution.

**Comment by HugoCrd** [comment]
I'll try to find some time to dig into this.
Enjoy your vacations!

**Comment by zenorocha** [comment]
Hey @strogonoff, in this case I would recommend using `Clipboard.isSupported()`, which is a new method we introduced in `v1.6.0`. That way you can hide the copy buttons from the UI if the users doesn't have support. 

Thanks a lot for reporting this issue!
