### ISSUE TITLE
iphone 上的chrome 浏览器使用呼出部分输入键盘

### ISSUE THREAD

**Issue by herrdu** [zenorocha/clipboard.js#331]
When  I test ‘Copy text from attribute’ feature on  Chrome in iphone  6p (ios10), it will show part of input keyborad of Iphone. 
当我在iphone 6p （ios10 ） 上使用的时候，他会呼出部分键盘

**Comment by zenorocha** [comment]
Yes, unfortunately there's no way to prevent that, but feel free to send a pull request if you have any suggestions.
