### ISSUE TITLE
Strange blank space problem for data-clipboard-text= parameters

### ISSUE THREAD

**Issue by pendave** [zenorocha/clipboard.js#333]
```
var keyword = "Starboy%20The%20Weeknd";
var title_part = keyword+ '%20%5B%E5%B8%A6%2F%E6%97%A0%E5%92%8C%E5%A3%B0%5D%5B320Kbps%5D%E4%BC%B4%E5%A5%8F';
```

When I use the code
`<button class="mybtn"  data-clipboard-text=' + decodeURIComponent(title_part) + '>Copy</button>`

Error:

![qq 20161028120335](https://cloud.githubusercontent.com/assets/1331881/19794663/95834584-9d06-11e6-9e67-789ce71a0397.png)

What can I do?

**Comment by zenorocha** [comment]
Sorry but I couldn't understand, please share a JSFiddle with a reproducible scenario.

**Comment by pendave** [comment]
Ok, I want dynamic writing strings with blank spaces into attribute "data-clipboard-text" but failed, as you see the content for "data-clipboard-text" is ripped off and only the first word is included in quotes.

But I check this tutorial and get the method from floor 3 answer.
http://stackoverflow.com/questions/34191780/javascript-copy-string-to-clipboard-as-text-html

His way http://jsfiddle.net/Loilo/ohy30s6c/2/

Now I only wonder if the "data-clipboard-text" is easier?

**Comment by zenorocha** [comment]
Here it is: https://jsfiddle.net/5kk0eysw/9/

**Comment by zenorocha** [comment]
Or https://jsfiddle.net/5kk0eysw/10/
