### ISSUE TITLE
UC Browser

### ISSUE THREAD

**Issue by ibmua** [zenorocha/clipboard.js#334]
In UC Browser (4% of Android market share) it says that it copied text, but it doesn't. 

Good test case would be https://clipboardjs.com/ itself.

**Comment by zenorocha** [comment]
Hey @ibmua, thanks for sharing. Unfortunately I have no idea how to fix for this browser since I didn't even know it existed. But feel free to send a pull request!

**Comment by ibmua** [comment]
Their PC/Windows browser version copies things fine, so I think I'll just report this issue to the browser devs instead.

**Comment by ibmua** [comment]
FYI, UC Browser has around 3x higher market share than all of IE<11.

**Comment by zenorocha** [comment]
I'm not saying that UC is not popular, I just don't have an idea how to fix that problem and would need a pull request to fix it.

**Comment by shivarajnaidu** [comment]
I think uc mobile browser lags some of the things needed by clipboard Js... it's not like other browsers...

**Comment by ihsansatriawan** [comment]
please somebody fix this issue

**Comment by EasonWang01** [comment]
hi,any update on this?

**Comment by lemonW** [comment]
@EasonWang01 , you to try `execCommand` directly .

**Comment by reedseu** [comment]
Hello, we found in UC browser (https://play.google.com/store/apps/details?id=com.UCMobile.intl&hl=en_US) (one of Alibaba Inc's product) document.execCommand will return undefined so the code will have problem in copyText function.
### succeeded = document.execCommand(this.action);
succeeded  will become undefined
We adjust our code like this
this.clipboard.on('error', (e) => {
  if (Clipboard.isSupported()) {
    successCallBack()
    return;
  }
  errorCallback();
});
But we think It's better you determine whether the browser support the API in copyText function
