### ISSUE TITLE
Doesn't copy to clipboard in realtime, but does when stepping through in Developer Tools

### ISSUE THREAD

**Issue by CouchFrancois** [zenorocha/clipboard.js#335]
First off going in I understand the likelihood of someone having a solution is pretty minimal with a lack of an example, but I'm hoping that maybe someone else has run into this issue.

I have a couple of internal web apps where a bootstrap modal is called and then by clicking on a button the user gets a sql query that they can use to query a database.  Same code, same naming conventions.  Works fine in one, here's what's happening in the other.

In real-time everything on the surface seems to work.  The success event fires and I can see the text within the success event handler.  Whether or not I put the text in the data-clipboard-text attribute or I use the imperative API, the success handler shows everything ran fine and I see the text element.  But the actual clipboard is blank.

Here's where it gets a bit odd.  If I walk through the function calls in developer tools, it works completely.  The text is saved to the clipboard.  To me that seems to point to some odd javascript timing issue, but I don't really know what could be causing it.

Any ideas?  I'm seeing this behavior on Chrome, IE and Firefox

**Comment by CouchFrancois** [comment]
Nevermind, looks like it's a known issue.  Although I'm still not sure why it works in one area and not another, both use a bootstrap modal

**Comment by haqpah** [comment]
I'm seeing this same issue with jQuery 2.2.4 and jQuery UI 1.11 dialogs. I can step through with Dev Tools and it works flawlessly, and normal operation appears to be working but in reality the clipboard is empty. I'm seeing similar behavior with Chrome and Firefox. I attempted doing some focus disabling for the jQuery dialog but could not get it working.

**Comment by zenorocha** [comment]
Check the new `container` option introduced by #368 on `v1.7.0`
