### ISSUE TITLE
Should the library have a beforeAction handler?

### ISSUE THREAD

**Issue by rafaelverger** [zenorocha/clipboard.js#336]
### What it should do?
The lib should be able to execute a function that would allow it (or not) to proceed with the predefined action;

### Why it is useful?
If the copy button is used as a premium feature of an application, this handler would allow developers to prevent users that doesnt have permission to do that action;

### How users should use it?
```js
//client.js
const handler = () => {
  // loading state?
  return fetch(`/user/has-feature/${featureName}`)
};
new Clipboard(selector, { beforeAction: handler });

// ----------------------------
// clipboard.js#L44
{
// ...
  onClick(e) {
    // ...
    this.beforeAction().then(() => {
      this.clipboardAction = new ClipboardAction({
        action  : this.action(trigger),
        target  : this.target(trigger),
        text    : this.text(trigger),
        trigger : trigger,
        emitter : this
      });
    })
  }
}
```

**Comment by zenorocha** [comment]
This is a very important use case, specially for users who want to execute async tasks before copying. Next year I'll start playing with the idea of having a promise-based API, so let's keep this on hold for now.

**Comment by guillaumevincent** [comment]
Why not `new Clipboard(selector, { beforeCopy: asyncMethod });` insted of `new Clipboard(selector, { beforeAction: asyncMethod });`?

**Comment by pedroramon** [comment]
@guillaumevincent, I agree that it reveals intention but, and the cut action? Do you think that we have to do two or three handlers? Like beforeCopy, beforeCut and beforeWhatever (I can't think in a cool name for the last).

**Comment by guillaumevincent** [comment]
@pedroramon you are right, 2/3 handlers is not a good idea, so beforeAction is better because more generic.

**Comment by scottcorgan** [comment]
This is huge for me as I need to copy the window.location.href after the hash has changed. (on button click of course)

**Comment by nuxsmin** [comment]
@zenorocha that "promise" use is that I was looking for. Just an Ajax request before setting text :)

Thanks for kicking out Flash!

**Comment by zenorocha** [comment]
Looks like this will not be possible because `document.execCommand('copy')` doesn't work asynchronously in some browsers as pointed out by @guillaumevincent on #338. See http://hansifer.com/clipboardCopyTest.html
