### ISSUE TITLE
Add API to check if copy action is supported

### ISSUE THREAD

**Issue by theghostbel** [zenorocha/clipboard.js#337]
Code examples

* all commands are checked for support - http://codepen.io/netsi1964/pen/QbLLGW
* "copy" command is checked for support - http://jsfiddle.net/the_ghost/679drp3r/  (`!!document.queryCommandSupported && !!document.queryCommandSupported('copy')`)

I think it could be some static boolean flag or method:
`var flag = Clipboard.copySupported;` or 
`var flag = Clipboard.isCopySupported();`

Real use-case is to hide "Copy" action if we know for sure that copy won't work.

**Comment by zenorocha** [comment]
I like `Clipboard.isSupported()`, we could test support for `copy` and `cut` inside that method.

**Comment by theghostbel** [comment]
I'd separate "cut" and "copy" support checks (if they can exist separately). At least in my project we don't need "cut" functionality and don't care about support.

For example, `Clipboard.isSupported('copy')`? Where string is optional argument. Without it plugin will check all used methods

**Comment by zenorocha** [comment]
Nice! Can you send a pull request?

**Comment by zenorocha** [comment]
Merged and released on `v1.6.0`
