### ISSUE TITLE
Content should be copied whether visible or not

### ISSUE THREAD

**Issue by NoiseEee** [zenorocha/clipboard.js#340]
### Expected behaviour
I had thought that specifying an element with the source would be enough to copy the content of the souce

### Actual behaviour
Nothing gets copied to the clipboard if the source DOM element is not visible

### Browsers affected
All

I'm a bit surprised that specifying any DOM element, visible or not, is not enough to be the 'source' copied from.  The element has to be visible.  It would be nice to be able to hide things in the document to get copied to clipboard (ie: with different markup/formatting).

**Comment by budwig** [comment]
try data-clipboard-text instead of data-clipboard-target

<button class="btn" data-clipboard-text="some text to copy">
    Copy to clipboard
</button>

**Comment by NoiseEee** [comment]
Indeed that will probably suffice for now.

**Comment by budwig** [comment]
I think you can close it, because I had the exact same problem what that solved it. I guess I should have read the original website more carefully, because the solution was in front of my eyes lol

[https://clipboardjs.com/]

**Comment by zenorocha** [comment]
:D
