### ISSUE TITLE
Why does this HAVE to be attached to a control

### ISSUE THREAD

**Issue by edgework** [zenorocha/clipboard.js#341]
It would be awesome if you could decouple this from having to be bound to an HTML element.  The way it is now works for simple uses but anything else is a huge pain.  What if I don't want to put content that's in the DOM into the clipboard?

...also  WHY does it have to select the text and leave it selected?

**Comment by aberel** [comment]
To quit selection, just do...
.on('success', function(e) {
	e.clearSelection();
})

**Comment by zenorocha** [comment]
Unfortunately there's no way to decouple because of how `execCommand` works. But feel free to roll your own implementation or use other library if this one doesn't work for you :)
