### ISSUE TITLE
Question!!!! (Setup and usage)

### ISSUE THREAD

**Issue by jdc20181** [zenorocha/clipboard.js#342]
I am wanting to be able to allow users to copy test results and paste them to social media - Manually for now and then eventually using the api's 

The test is a Bandwidth test to see how fast your internet speed. I want the results as well as a 

"Test your's By going here: https://jdc20181.github.io/SpeedTest" 

I Am using one of the examples, but it just has the button data copying - what my goal is to copy the text from the element h1 with a id of "Progress"

Any help is appreciated 

Thanks!!

**Comment by zenorocha** [comment]
Hey @jdc20181, please share a minimal reproducible example on JSFiddle or check our list of working [demos](https://github.com/zenorocha/clipboard.js/tree/master/demo).
