### ISSUE TITLE
How-To Question : How to include both a element and a url 

### ISSUE THREAD

**Issue by jdc20181** [zenorocha/clipboard.js#346]
Right now I just have the ability to copy a element value - but I also want to copy a url so when a user copies and shares - the url is shared too so they can see thier results?

**Comment by budwig** [comment]
You mean something like this?
```
    <a target="_blank" href="http://www.gmail.com" class="clipboardBtn" data-clipboard-text="http://www.gmail.com">TEST</a>

    <script src="js/clipboard.min.js"></script>
    <script>
      var clipboard = new Clipboard('.clipboardBtn', {
        text: function (e) {
          var sometext = e.getAttribute('data-clipboard-text');
          if (sometext) {
            console.info('Text:', 'Copied');
            return sometext;
          } else {
            console.info('Text:', 'Nothing to copy');
          }
        }
      });
    </script>
```

**Comment by jdc20181** [comment]
No. That is not what I mean - BTW I found the error in my code becaue of what I want to do. 

NOTE: I didn't want to have to make another css class so I am using a "Link" button,  it works fine. 


What  I want to do is where it says `Data-Clipboard-Target="#progress"` I want to include a url, not visible to the user until you paste it - So the user copies both a url, and the results. 

The idea is to make users able to share results and also have at the end "See your results by going to https://jdc20181.github.io/SpeedTest/


`<a class="button btn" href="#" data-clipboard-action="copy" data-clipboard-target="#progress">
Copy Results
</a>
<script>
     var clipboard = new Clipboard('.btn');
    clipboard.on('success', function(e) {
        console.log(e);
    });
    clipboard.on('error', function(e) {
        console.log(e);
    });
      </script>`

**Comment by zenorocha** [comment]
See the [imperative API](https://github.com/zenorocha/clipboard.js#advanced-options) in order to manipulate content before copying it.
