### ISSUE TITLE
Ability in error handler to re-trigger the selection after showing a popup

### ISSUE THREAD

**Issue by mzealey** [zenorocha/clipboard.js#349]
As suggested I'm attaching to .on('error') to show a popup telling the user to hit Ctrl+C if execCommand fails for some reason. However the library that I'm using appears to do something which clears the selection when I show the popup. In other words, if i do a `console.log` within the error I can hit ctrl-c and get the text copied correctly, however if I show a html-popup it looses the selection and so Ctrl-C doesn't copy anything (I'm using the `text:` api to specify custom text)

I would suggest a workaround would be to extend the event object that is passed in to have a new bound function (like `clearSelection`) which is something like `redoSelection()` so I can trigger the popup to show and then redo the selection after the event (without it attempting a second copy and then success/error trigger).

**Comment by zenorocha** [comment]
Hey @mzealey, this is a very specific use case, I would suggest you implement your own clipboard implementation, but thanks for your suggestion :)
