### ISSUE TITLE
data-clipboard-target should be data-clipboard-source

### ISSUE THREAD

**Issue by MarcusJT** [zenorocha/clipboard.js#35]
"data-clipboard-target" is confusingly misnamed as it indicates the source, the clipboard is the target.

I had to read the example twice to make sure that I wasn't going mad - therefore please rename it "data-clipboard-source" to preserve everyone's sanity!

**Comment by zenorocha** [comment]
Hey @MarcusJT,

Thanks for your suggestion. You see `data-clipboard-` is just a prefix. Target indicates what element should have its text copied.

<img width="512" alt="screen shot 2015-09-30 at 8 03 45 am" src="https://cloud.githubusercontent.com/assets/398893/10196932/2cadfcea-674a-11e5-8668-c06c12990ec9.png">

I'm closing this issue for now, but we can revisit it later if more people start to complain too.

**Comment by MarcusJT** [comment]
The problem is not the prefix, the problem is the suffix which your code interprets in a specific way but humans interpret differently because you've used the opposite word, which is why it's very confusing and should be changed as I suggest.
