### ISSUE TITLE
Ability to stopPropagation on click event of attached DOM element

### ISSUE THREAD

**Issue by campbeln** [zenorocha/clipboard.js#350]
Searching the prior issues, "stopPropagation" has been mentioned before and a solution is alluded to but I have been unable to figure out how to have a hooked DOM element `stopPropagation`. Can this be added as a feature? Or, if it is a feature, can you document how to use it?

**Comment by zenorocha** [comment]
Hey @campbeln, I'm on vacations right now, but feel free to send a pull request if you find a solution to your problem.

**Comment by zenorocha** [comment]
Closing this issue since no solution has been proposed so far. But feel free to open a pull request when possible.
