### ISSUE TITLE
Only copying on the second time it is clicked

### ISSUE THREAD

**Issue by matt-paul** [zenorocha/clipboard.js#351]
### My code

`                 

                      <button id="copy-to-clipboard"
                        class="copy-to-clipboard"
                        data-clipboard-text="https://etc">Copy Invitation Link
                      </button>

                      document.addEventListener('click', function(e) {
                        if (e.target && e.target.classList.contains('copy-to-clipboard')) {
                        new Clipboard('.copy-to-clipboard');
                        }
                     })
`
### Actual behaviour

It is only copying to the clipboard on the second click.  I have tried using both a cdn and webpack script-loader.

### Browsers affected
Chrome 54

Any help would be appreciated, thank you.

**Comment by matt-paul** [comment]
Just to note that i am not using a text or input element in addition to the above code.  I wonder if this could be the cause?

**Comment by zenorocha** [comment]
Clipboard.js already comes with a built-in click event listener, you only need this part:

```js
new Clipboard('.copy-to-clipboard');
```

**Comment by matt-paul** [comment]
Thanks @zenorocha - if you have a moment, could you explain what is actually happening then that causes it so not work on first click when i have added an additional event listener? Thank you

**Comment by zenorocha** [comment]
When you write `new Clipboard('.something')` we already do a `document.addEventListener('click')` behind the scenes, so you don't need to do another one.

**Comment by matt-paul** [comment]
Thanks @zenorocha, if i am not testing your patience too much, what is the underlying problem that is caused by the duplicate event listeners that stop it from working?

**Comment by fahmilatib** [comment]
@matt-paul 

Actually it's a logic error.

```
document.addEventListener('click', function(e) {
    if (e.target && e.target.classList.contains('copy-to-clipboard')) {
```

Whenever you click on an `.copy-to-clipboard` element **for the first time**,

```
        new Clipboard('.copy-to-clipboard');
```

only then a new `Clipboard` instance gets created and **that clicked** `.copy-to-clipboard` element will be its trigger. The **next time** you click on that specific trigger, it will do the copying thing.

This makes sense because whenever you click on an `.copy-to-clipboard` element for the first time, it hasn't become a trigger yet.

**Comment by zenorocha** [comment]
Thanks @fahmilatib

**Comment by rojantandukar** [comment]
@zenorocha would be great if you help!!

<html>
<head>
<body>
<script src="https://cdn.jsdelivr.net/clipboard.js/1.6.0/clipboard.min.js"></script>	
<script type="text/javascript">
function clicked(){
 var Bookurl = "https://www.google.com";
 ClipCopy(Bookurl);
}
function ClipCopy(Bookurl){
 console.log("ValReqd: " +Bookurl);
 var bttn = top.doc1.doc2.document.getElementById('bCopyClip');
 console.log(bttn);
 var clipb = new Clipboard(bttn,{
    text: function(trigger){
	return Bookurl;
	}
 });
 console.log("clipb value: ");
 console.log(clipb);
 clipb.on('success', function(e) {
  console.info('Action:', e.action);
  console.info('Text:', e.text);
  console.info('Trigger:', e.trigger);
  e.clearSelection();
});
}
</script>
<button onclick="clicked()" id="bCopyClip" type="button" class="btnclass" title="Copy Link" style="background: rgb(240, 240, 240);">
Document</button>
</head>
</body>
</html>



If i run this individually, it works on second click, but if I merge this in my project code, it fails. Where did i went wrong??

**Comment by rojantandukar** [comment]
@zenorocha 
![png](https://cloud.githubusercontent.com/assets/15669233/23608774/fa3f4da2-0290-11e7-80e4-0de9d129c842.png)
Log:
ValReqd: https://www.google.com
<button onclick="clicked()" id="bCopyClip" type="button" class="btnclass" title="Copy Link to Document" style="background: rgb(240, 240, 240);"
Document</button>
clipb value:
t {listener: Object}

If i run this code individually, it will run in second click, but if i merge this code with my project source, it doesn't work.. would be great if you'd help..

**Comment by ghost** [comment]
Hello, everyone! Here is my template:

```
<div class="album-form to-be-hidden">                
  <div class="form-group">                           
    <input id="copy-box"                             
           class="form-control"                      
           type="text"                               
           name="copy-box"                           
           value="<% picture.url %>">                
  </div>                                             
  <div class="form-group">                           
    <button id="copy-button"                         
            type="button"                            
            data-clipboard-target="#copy-box"        
            class="btn btn-sm btn-primary btn-block">
      Скопировать в буфер обмена                     
    </button>                                        
  </div>                                             
</div>                                               

```

And my script:

```
function copyThis(event) {                             
  $(this).blur();                                      
  let clipboard = new ClipboardJS('#' + $(this)[0].id);
  clipboard.on('success', function(e) {                
    $(event.data.cls).slideUp('slow');                 
  });                                                  
$(function() {
  $('body').on('click', '#copy-button', {cls: '.album-form'}, copyThis);    
  $('body').on('click', '#copy-button-b', {cls: '.album-form-b'}, copyThis);
});
```

I do not know why but, unfortunately, it works only after second click. And I am not quite sure this is the bug of this library, probably this is my falt. Any suggestion how to debug it would be wonderful.
