### ISSUE TITLE
"Cannot read property '_bound' of undefined" when element is clicked

### ISSUE THREAD

**Issue by krtrice** [zenorocha/clipboard.js#352]
Following the docs, I instantiate Clipboard and set the text.

```
const linkUrl = "http://google.com";
new Clipboard(".js-copyLink"), {
   text: function() {
      return linkUrl;
   }
});
```

When the element is clicked, I get a couple of errors in the browser console (I'm using the latest version of Chrome on a Mac) and no content is copied to clipboard.

```
Error: Cannot read property '_bound' of undefined
TypeError: Cannot read property '_bound' of undefined
    at ClipboardAction.selectFake (utils.js:24)
    at ClipboardAction.initSelection (utils.js:24)
    at new ClipboardAction (utils.js:24)
    at Clipboard.onClick (utils.js:24)
    at HTMLDivElement.<anonymous> (utils.js:24)
reporters.js?1481501964485:67 Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ClipboardAction.removeFake (utils.js:24)
    at HTMLBodyElement.fakeHandlerCallback (utils.js:24)
```

Any ideas?

**Comment by zenorocha** [comment]
Hey @krtrice, you have a syntax error.

Instead of

```js
new Clipboard(".js-copyLink"), {
```

You must type 

```js
new Clipboard(".js-copyLink", {
```

https://jsfiddle.net/zenorocha/r9LonqvL/

**Comment by krtrice** [comment]
@zenorocha ah yes, sorry about that but thanks for catching the typo in my sample code. This is not the issue I am encountering though (my actual code doesn't have a typo), and the error would be different in that case as well.

I am using the Meteor framework. Do you know if that could be related?

**Comment by zenorocha** [comment]
No idea, as you can see on the JSFiddle https://jsfiddle.net/zenorocha/r9LonqvL/ it's working well.
