### ISSUE TITLE
Copying text from hidden elements is not working

### ISSUE THREAD

**Issue by amureki** [zenorocha/clipboard.js#353]
### Minimal example

https://jsfiddle.net/amureki/3fst62yf/

### Expected behaviour

I thought that by clicking copy button with `data-clipboard-target` attribute applied to a hidden element text will be copied to clipboard.

### Actual behaviour

Instead of copying text in a hidden element, what I saw was that nothing happened instead.

### Browsers affected

I tested on all major browsers except IE and it does not work anywhere.

**Comment by zenorocha** [comment]
This is a browser security limitation. I suggest you use `data-clipboard-text` or the [imperative API](https://github.com/zenorocha/clipboard.js#advanced-options).

**Comment by amureki** [comment]
@zenorocha okay, thank you.

**Comment by JamoCA** [comment]
This worked for me using Clipboard.js.

Make the element (ie, textarea field) really small (cols=2 rows=1) and then use absolute positioning to move it off the visible page.

    <div style="position:absolute; top:0; left:-500px;">
        <textarea id="ordertext" type="text" rows="1" cols="2">#trim(TheOrderText)#</textarea>
    </div>
