### ISSUE TITLE
Is it possible to copy from data attribute instead for value?

### ISSUE THREAD

**Issue by lavezzi1** [zenorocha/clipboard.js#356]
Hello! 

I need to copy string from data attribute instead of input's value, because initially inputs value is truncated. So I want to copy full string from input. Thanks.

**Comment by zenorocha** [comment]
@lavezzi1 try something like this:

```js
new Clipboard('.btn', {
    text: function(trigger) {
        return trigger.getAttribute('data-example');
    }
});
```

See https://github.com/zenorocha/clipboard.js#advanced-options for more info.
