### ISSUE TITLE
Compability with shadydom polyfill

### ISSUE THREAD

**Issue by tobilen** [zenorocha/clipboard.js#358]
see https://github.com/zenorocha/good-listener/issues/7

```
class MyElement extends Polymer.Element {
  connectedCallback () {
    super.connectedCallback ();
    this.clipboard = new Clipboard(this.$.clipboardButton);
  }
}
customElements.define("my-element", MyElement );
```
errors out if webcomponents v1 polyfill is used, the reason being that polyfilled dom elements arent using the HTMLElement constructor, and good-listener checks for that to determine whether or not a node was passed.

not actually an issue with clipboard.js, but until it is adressed, i provided a version which uses my fork of good-listener: https://github.com/zenorocha/clipboard.js/pull/359

**Comment by zenorocha** [comment]
Moving discussion to `good-listener`...
