### ISSUE TITLE
You may wanna upgrade your Chrome

### ISSUE THREAD

**Issue by sdegutis** [zenorocha/clipboard.js#36]
Looks like it's got an update waiting...

**Comment by zenorocha** [comment]
What?

**Comment by sdegutis** [comment]
That's what the green indicator means in [this screenshot](https://cloud.githubusercontent.com/assets/398893/9983535/5ab0a950-5fb4-11e5-9602-e73c0b661883.jpg) on your readme.

**Comment by zenorocha** [comment]
![](http://media.giphy.com/media/2dJ5Iait4QrW8/giphy.gif)
