### ISSUE TITLE
Bug: Not Working on IOS  - Not copying

### ISSUE THREAD

**Issue by jdc20181** [zenorocha/clipboard.js#362]
Location: http://jdc20181.github.io/SpeedTest/speedtest.html

*Important* It only occurs on the MOBILE site, which is redirected automatically on mobile devices.
Additionally, To repoduce you **MUST** use a IOS device, works fine on Android devices, as well as Windows. 

You will automatically be redirected to the mobile site. 

The code is IDENTICAL to the desktop version. Only differences are in progress and will be visual. 

What the code *Should* do:

Copy the text from the following: `<h1 id='progress'></h1>`

It should give a snackbar notification of success - if successful. 

And don't say it!!

I did that! I tried pasting to see if copied maybe the Snackbar didn't work. 

So Far the browsers I have tested: Safari, Chrome.  All are up to date to the latest version. I am running IOS 10.2 (whatever is the latest) on a Iphone 7 + 

Any solutions would be great. 

Thanks!

**Comment by jcfariadias** [comment]
+1

**Comment by ridakk** [comment]
+1

**Comment by zenorocha** [comment]
Just tested this URL you sent on iPhone and iPad both on iOS 10.2, both work normally.

**Comment by zenorocha** [comment]
Also check `v1.6.0` for new iOS fixes.

**Comment by jdc20181** [comment]
You shouldn't have closed it until I checked but it finally worked - just a
FYI idk what I did. Anyways the code didn't change any it must have been a
connection issue with the server and CDN but others +1 the issue so be sure
to keep a open eye.

**Comment by zenorocha** [comment]
I'll, thanks!

**Comment by yijiaqingilm** [comment]
+1

**Comment by Ruffio** [comment]
@yijiaqingilm this issue is closed and the url that the originator used is no longer accessable. 
I have just tested the demo site using an iPad and it is working perfectly. If you have issues, then you have to create a JSBin so we can see your code that demonstrates your issue.
