### ISSUE TITLE
How can I use this to copy img tag

### ISSUE THREAD

**Issue by han8435762** [zenorocha/clipboard.js#363]
I use it like this
but I got the src not the image

`
    
    <img src="http://img3.imgtn.bdimg.com/it/u=3355811632,1718080977&fm=23&gp=0.jpg" />
    <button class="btn" data-clipboard-action="copy" data-clipboard-target="img">Copy</button>

    
    <script src="../dist/clipboard.min.js"></script>

    
    <script>
    var clipboard = new Clipboard('.btn');

    clipboard.on('success', function(e) {
        console.log(e);
    });

    clipboard.on('error', function(e) {
        console.log(e);
    });
    </script>`

**Comment by jdc20181** [comment]
I use when setting up a CDN, `  <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.13/clipboard.min.js"></script>
`
And I don't understand what you mean? You want to copy a image? or save the image? Not sure if it's possible. 

But   -doesn't mean you can't try:

You apparently are new - so you are missing a vital step which is a button - I use link buttons (easier to style xD ) 

but you need to set the following:
`data-clipboard-action="copy" data-clipboard-target="img"`

You need the Js you have as well to make it work. 

I made a fiddle but I don't think you can copy a image. Too many issues with doing such. 
https://jsfiddle.net/zm3L7gcr/

**Comment by sboesch** [comment]
This works at least in Safari/Chrome:
```
<div>
    <img src="https://placeholdit.imgix.net/~text?txtsize=33&txt=350×150&w=350&h=150" alt="">
</div>
<button data-clipboard-action="copy" data-clipboard-target="div">Copy</button>

<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.13/clipboard.min.js"></script>
<script>new Clipboard('button');</script>
```

**Comment by zenorocha** [comment]
Clipboard.js is only intended for copying text.
