### ISSUE TITLE
Unable to copy dynamic link in React

### ISSUE THREAD

**Issue by divyanshupathak** [zenorocha/clipboard.js#364]
Hello,
I am in trouble while copying dynamic text. Actually I want to copy the link which is generated dynamically, but got no success.
I have created minimal reproduction on github as well. Here is the github link -
[https://github.com/deepupathak/test](https://github.com/deepupathak/test)

Please check and advice.
Thanks.

**Comment by zenorocha** [comment]
I can't help since you're not actually using clipboard.js here.
