### ISSUE TITLE
Cannot filter html before it reaches clipboard

### ISSUE THREAD

**Issue by bernd-wechner** [zenorocha/clipboard.js#365]
Perhaps not an intended feature, but certainly one I'd like and will have to find a workaround for. But I'd like send an HTML element to the clipboard with filtered code.

The doc provides a clue:

```
new Clipboard('.btn', {
    text: function(trigger) {
        return trigger.getAttribute('aria-label');
    }
});
```
but fails to explain how this works for starters just provides a rather odd example, and trying it out, we can see that setting "text" like this just sends text to the clipboard.

For example try this:

```
new Clipboard('.btn', {
    text: function(trigger) {
        return document.getElementById("MyTable").outerHTML;
    }
});
```

Paste the result into say an email editor and you can see it's only the text renditon of the table, all the HTML is lost.

I'd like essentially to strip a pile of tags (notably "a" tags) from the elemtn of my choice. This works a dream:

```
<button type="button" id='btnCopy' data-clipboard-target="#MyTable">Copy</button>
<script>
	var clipboard = new Clipboard(document.getElementById("btnCopy"));
</script>
```
I can click btnCopy and paste a table into an email editor and it's great. But it has a pile of links I'd like to filter out first.

I'll look for a workaround of course combining with other Javascript events but I table it here as what I expect is not an uncommon use case. The desire to copy the filtered version of an HTML element.

**Comment by zenorocha** [comment]
Hey @bernd-wechner,

My suggestion to you is to use the `target` function instead of `text`. That way you can manipulate the HTML in any way you want. For example:

```js
new Clipboard('.btn', {
    target: function(trigger) {
        return trigger.nextElementSibling;
    }
});
```

Thanks for reaching out!
