### ISSUE TITLE
"Copied!" magic!

### ISSUE THREAD

**Issue by caifagithub** [zenorocha/clipboard.js#366]
Could someone help me to understand how I can make the magic with message shows "Copied!". It comes from aria-label attribute, but how I can set it? And then show it to user.

**Comment by guillaumevincent** [comment]
@caifagithub I use [hint.css](https://kushagragour.in/lab/hint/) and a some javascript:

    clipboard.on('success', event => {
        if (event.text) {
            showTooltip(event.trigger, 'copied!');
        }
    });

```
showTooltip(elem, msg) {
    var classNames = elem.className;
    elem.setAttribute('class', classNames + ' hint--right');
    elem.setAttribute('aria-label', msg);
    setTimeout(function () {
        elem.setAttribute('class', classNames);
    }, 2000);
}
```

**Comment by zenorocha** [comment]
Thakns for helping out @guillaumevincent!

**Comment by oshihirii** [comment]
And if it helps future viewers, here is solution that worked for me using [Tooltipster](http://iamceege.github.io/tooltipster):

**HTML**
```
<i class="my_clipboard clipboard_tooltip" title="copied!" data-clipboard-target="#my_target_div"></i>
```

**JS**
```
$('.clipboard_tooltip').tooltipster({
theme: 'tooltipster-noir',
animation: 'fade',
animationDuration: 100,
delay: 0,
trigger: 'custom',
distance: 6,
interactive: true
});


function setTooltip(btn) {
$(btn).tooltipster('open');
}

function hideTooltip(btn) {
setTimeout(function() {
$(btn).tooltipster('close');
}, 1000);
}

var clipboard = new Clipboard('.my_clipboard');

clipboard.on('success', function(e) {
setTooltip(e.trigger);
hideTooltip(e.trigger);
console.info('Text:', e.text);
e.clearSelection();
});
```

The following [answer](http://stackoverflow.com/a/37395225) helped me figure it out.

**Comment by produktive** [comment]
@guillaumevincent I added your method to my page and I can't get it to work? I included the css at the top but when I add the JS, even the copying functionality breaks. The console shows nothing. How is this possible?

**Comment by produktive** [comment]
@guillaumevincent thank you for that code. I had to modify it a bit to get it to work. Is there a way to preserve the disappearing animation that exists with the hint.css normal functionality instead of the timeout just making it disappear?
