### ISSUE TITLE
Allow to alter the copied text before putting it into the clipboard

### ISSUE THREAD

**Issue by gunnarmorling** [zenorocha/clipboard.js#367]
I'd like to modify the copied text before it's put into the clipboard in order to perform some sanitization (trimming etc.).

Is this possible somehow? If not, could the API be extended so I could pass in a function for doing so? Thanks for your consideration.

**Comment by zenorocha** [comment]
https://github.com/zenorocha/clipboard.js#advanced-options

**Comment by gunnarmorling** [comment]
I saw the text function, but how can I get hold of the selected text in there? I don't want to return a static text but rather modify the selection. Is there an example for doing so somewhere?

**Comment by zenorocha** [comment]
Try this: http://jsfiddle.net/zenorocha/2jph1vuf/

**Comment by gunnarmorling** [comment]
Ok, so I have to look for the source element itself. I had hoped to avoid this, given the fact that clipboard.js already has done this and could simply pass the text to me in a callback. I still think that'd be a valuable addition, but I'll go for the approach you suggest. Thanks.

**Comment by zenorocha** [comment]
Can you explain in a JSFiddle how you wanted things to work?

**Comment by gunnarmorling** [comment]
What I'd like to have is the option pass in a function that modifies the selected text:

    new Clipboard('.btn', {
        textModifier: function(text) {
            return text + '123';
        }
    });

It'd also suffice to pass the selected text to the existing text function alongside the trigger:

    new Clipboard('.btn', {
        text: function(trigger, text) {
            return ...;
        }
    });

Then one can either return a new text from scratch as of today, or amend the text already selected by the library.
