### ISSUE TITLE
API

### ISSUE THREAD

**Issue by cironunes** [zenorocha/clipboard.js#37]
As per conversation w/ @zenorocha on Hangouts, I'm creating this issue for the record.

I'm suggesting some breaking changes to the public API so we can remove all the logic from the constructors of `clipboard` and `clipboard-action`.

The resulting API would be:

```
var clipboard = new Clipboard('.btn'); // config options

clipboard.setup(); // initializing logic (event delegation, construction of clipboard-action, etc.) this could maybe return a promise that either resolves or fails if the setup succeed or not.

clipboard.on('[event]', callbackFn);

clipboard.destroy(); // unbind all the events and maybe kill the elements in the DOM
```

The main reason of those changes are to avoid side effects on the constructors to make it easier to test and more flexible for the users.

**Comment by yogibea** [comment]
I hope ur not talking to my wife

**Comment by zenorocha** [comment]
I acknowledge that having initialization logic on constructors makes it harder to test, but this proposal breaks the API and would require a major release. I don't think we're in a good moment to do that.

Let's wait and see if there are more people interested in such change.

P.S.: We thought about using promises but its polyfill was huge.
