### ISSUE TITLE
Clipboard.js only works on click events

### ISSUE THREAD

**Issue by ddivecs** [zenorocha/clipboard.js#370]
I understand that the clipboard api has security in place that requires user interaction and have read #127 and #189, but would it be possible to expand clipboard.js to work with other events besides `.click` (preferably, any arbitrary user event).

Specifically, it is useful in my app to respond to the keydown and context menu events, but currently clipboard only lets us respond to clicks. Also in these cases I would like to unbind from the click event in clipboardjs. Essentially, our click events handle selection in a grid, but should not necessarily trigger copy. Other interactions in our application cause copy.

**Comment by zenorocha** [comment]
Hey @ddivecs, this is a very nice feature suggestion but unfortunately the browser has some limitations in what is considered a user interaction. My advice to you is to use `execCommand` directly and see if it works for your particular case.

Thanks again for your input!

**Comment by lcw0622** [comment]
@zenorocha Hello, I'm very confused of this `security restrictions` because I had met many scenario that my program can only worked in click envent. Would you have something like document or key words can help me to get definitly description of it?
Thank you.

**Comment by raineorshine** [comment]
This works for me in Chrome:

```js
/** Copies a string directly to the clipboard with a simulated button click. */
const copy = s => {
  const dummyButton = document.createElement('button')
  const clipboard = new ClipboardJS(dummyButton, { text: () => s })
  dummyButton.click()
}

// copy on keydown
window.addEventListener('keydown', e => {
  copy('Hello universe')
})
```

> A simulated click event using JavaScript does not work as this would enable clipboard poisoning.

https://github.com/zenorocha/clipboard.js/wiki/Known-Limitations

Seems to not be a problem for `keydown` in Chrome.
