### ISSUE TITLE
Is it possible to copy an image by using the clipboard

### ISSUE THREAD

**Issue by yuyouwen** [zenorocha/clipboard.js#373]
I have try to find a way copy image in js, so I want know why clipboard.js did not support copy image.

**Comment by shivarajnaidu** [comment]
I think it's not possible with clipboardjs (atleast for now)

**Comment by shivarajnaidu** [comment]
I think it's not possible with clipboardjs (atleast for now)

**Comment by zenorocha** [comment]
Clipboard.js only supports string copying. Thanks for @yuyouwen for asking and @shivarajnaidu for answering!
