### ISSUE TITLE
Clipboard.js firing multiple on success events

### ISSUE THREAD

**Issue by JamesTheHacker** [zenorocha/clipboard.js#374]
I'm using [Clipboard.js](https://github.com/zenorocha/clipboard.js) in a project to allow the user to copy text to their clipboard when a button is pressed.

It works fine, except when I refresh the list of buttons in the list using jQuery it fires multiple on success events. Here's some example code that will reproduce the error:

    $(function() {
    	var data = [
      	'Button One',
        'Button Two',
        'Button Three'
    ];
      
    var refreshButton = $('#refresh').on('click', function(e) {
      	var list = $('#buttonList');
        list.empty();
        
      	for(i=0; i < data.length; i++) {
      		list.append('<li><button class="btn"  data-clipboard-text="Copy Me">' + data[i] + '</button></li>')
      	}
        
        var clipboard = new Clipboard('.btn');
      	clipboard.on('success', function(e) {
      		var n = $('body').noty({
            text: 'Link copied to clipboard',
            timeout: 1000,
            type: 'success',
            theme: 'metroui'
        	});
    		});
      });
    });

I have created a jsFiddle to reproduce the issue: https://jsfiddle.net/jdfj52or/

1. First press the "load list" button
2. Press one of the loaded buttons and you will see a notification
3. Press "load list" again
4. Press one of the loaded buttons and you will 2 notifications

Repeat step 4, and it will continue to repeat more notifications.

Is this an issue with my code or Clipboard.js?

**Comment by zenorocha** [comment]
Replied on StackOverflow: http://stackoverflow.com/questions/42227496/clipboard-js-firing-multiple-on-success-events/42234323#42234323
