### ISSUE TITLE
How to destroy clipboard if it exists?  

### ISSUE THREAD

**Issue by oshihirii** [zenorocha/clipboard.js#376]
Hello,

I saw [this code example on the home page](https://clipboardjs.com/) for destroying instance in one page app's:

```
var clipboard = new Clipboard('.btn');
clipboard.destroy();
```

How can I do a check to see *if* clipboard exists, and if so delete it?

I am doing this (less than ideal solution):

```
// instantiate in order to destroy
var clipboard = new Clipboard('.fa-clipboard');

// destroy
clipboard.destroy();

// instantiate
var clipboard = new Clipboard('.fa-clipboard');

clipboard.on('success', function(e) {
console.log('text copied: ' + e.text);
e.clearSelection();
});
```

But it prints out the text twice (which infers that there are two instances running).  

Thank You.

**Comment by zenorocha** [comment]
Try this:

```js
var clipboard; 

if (clipboard) {
    clipboard.destroy();
}

clipboard = new Clipboard('.fa-clipboard');
```

**Comment by oshihirii** [comment]
Hello,

Thank you for the suggestion, unfortunately it didn't work.

The same behaviour occurs as when doing the following (ie text is printed out twice):
```
// instantiate in order to destroy
var clipboard = new Clipboard('.fa-clipboard');

// destroy
clipboard.destroy();

// instantiate
var clipboard = new Clipboard('.fa-clipboard');

clipboard.on('success', function(e) {
console.log('text copied: ' + e.text);
e.clearSelection();
});
```

**Comment by zenorocha** [comment]
Could you please share a JSFiddle?

**Comment by oshihirii** [comment]
Will make one asap and post back, thanks.

**Comment by davidtaubmann** [comment]
I have the same trouble... We are sending an alert upon success and then destroying the clipboard, but whenever anothe rclipboard is triggered, the alert fires twice... not the console messages (which fire onces) but the alert messages do fire twice.

**Comment by oshihirii** [comment]
For reference, I don't have access to the code that is causing the issue at the moment, but created [jsFiddle](https://jsfiddle.net/rwone/kar9pbaL) to try and replicate the error - unfortunately it doesn't, so I will have to update it when I have access to the code again, but thought someone else could use the fiddle as a base to try and replicate error.
