### ISSUE TITLE
Does not work with Android 4.4

### ISSUE THREAD

**Issue by jonashaag** [zenorocha/clipboard.js#379]
I just tried the demo [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) with Android 4.4.2 and it doesn't work. The problem is that `execCommand` returns `false` with "copy" as argument, i.e. it doesn't support the "copy" command.

However caniuse.com says Android 4.4 supports the "copy" command, but:

> Only fires copy event on a valid selection and only cut and paste in focused editable fields.

**Comment by icesman** [comment]
I have tried it on Android 6.0.1, it works.
But in caniuse.com says Android 6.0.1 doesn't support 

> document.execCommand()
It makes me confused. And I tried it on other Android device 7.0 with Chrome, it works. But no UC Browser.
So I doubt that some browsers have changed some configuration which make the lib doesn't work.😂

**Comment by jonashaag** [comment]
That's interesting. It still doesn't work for Android 4.x

**Comment by icesman** [comment]
it also depends on the browser, I think. Perhaps u can try another browser.
Some browser acts so weirdly that the events of the lib works but anyway it can't write the data into the clipboard.

**Comment by zenorocha** [comment]
Hey @jonashaag, unfortunately I don't have control over those browsers, my suggestion is for you to try `execCommand` directly and see what happens.

**Comment by perany** [comment]
it doesn't work in own browser on android mobile, you just can copy by hand operation but not by calling javascript function.

**Comment by perany** [comment]
waiting solution！！！
