### ISSUE TITLE
Text is copied to clipboard with a trailing space in Firefox (OS X)

### ISSUE THREAD

**Issue by ignacioHermosilla** [zenorocha/clipboard.js#382]
I tested on Chrome and Safari without problems. Only Firefox does not work. The setup and Usage is the Basic explained in the clipboard documentation ("Copy text from another element"). 

### Browsers affected

Firefox 51.0.1 (OS X)

**Comment by fhightower** [comment]
Interesting... I just tested it out and can not duplicate the issue. Am I correct that your html looks something like:

```
<!-- Target -->
<input id="foo" value="https://github.com/zenorocha/clipboard.js.git">

<!-- Trigger -->
<button class="btn" data-clipboard-target="#foo">
    <img src="assets/clippy.svg" alt="Copy to clipboard">
</button>
```

**Comment by zenorocha** [comment]
I can't reproduce that problem either. Even on a newer version of Firefox.

![ff](https://cloud.githubusercontent.com/assets/398893/23532182/05bd9966-ff5f-11e6-8abb-e4312df10131.gif)

**Comment by ignacioHermosilla** [comment]
Maybe i'm doing it wrong. I created a snippet with the code:
[jsfiddle snippet]( https://jsfiddle.net/n4j3x21w/4/)

**Comment by wodow** [comment]
Having the same problem.

I can reproduce this on both Firefox 53 (Developer Edition) and Firefox 54 (Nightly).

**Comment by fhightower** [comment]
Ok, I can reproduce it from the [jsfiddle snippet](https://jsfiddle.net/n4j3x21w/4/) you provided.

Here is a working fork of your example: https://jsfiddle.net/w7b5csc7/ .

**Comment by ignacioHermosilla** [comment]
Thank you. I'm going to adapt the html then.

**Comment by zenorocha** [comment]
Thanks @fhightower for providing a solution!

**Comment by fhightower** [comment]
My pleasure.

**Comment by Woody93** [comment]
That isn't really a fix for this issue, I would have hoped that the structure of the DOM was irrelevant.
I have the same problem as ignacioHermosilla but I don't want to move my trigger element.

However, this is probably a Firefox issue as much as it is a clipboard.js issue and as such, I appreciate that a fix may be hard to come by.

**Comment by edhgoose** [comment]
@fhightower is it possible to elaborate on the difference between the two solutions in https://github.com/zenorocha/clipboard.js/issues/382#issuecomment-283933208? I'm not familiar enough with Clipboard.js, but from what I can tell the same data is copied - and yet different content is pasted.

What is it about those two examples that means one works and the other doesn't? Is it worth raising a bug with Firefox? I'd be happy to do this if I can elaborate more on the difference.

**Comment by fhightower** [comment]
Absolutely; I should have clarified this earlier. The difference (I think) is the location of the text you are trying to copy from relative to the copy button.

The simplest example I can come up with that exhibits this bug is: https://jsfiddle.net/n4j3x21w/9/ . The html code is:

```html
<div>
  <a id="text_to_copy">text</a>
</div>
<div>
  <button data-clipboard-target="#text_to_copy" id="clipboard">Copy to clipboard</button>
</div>
```

A couple observations that may help identify the underlying bug:

- The bug only occurs when the element with id `text_to_copy` is an`<a>` or `<span>` (and possibly others). The bug does not occur if the element with id `text_to_copy` is something like `<div>` or `<p>` .
- If you move the element with id `text_to_copy` into the same div as the button with id `clipboard`, the bug does not occur.

**Comment by manueljacob** [comment]
Is there a chance that the bug will be fixed?

**Comment by DigiDank** [comment]
I was able to recreate this with the following html. The key focus is in the `card-body`.
``` html
<button class="btn btn-default btn-sm pull-right copy " data-clipboard-action="copy" data-clipboard-target="#abc"><i class="fa fa-copy" aria-hidden="true"></i> Copy</button>

<div class="card ">
   <div class="card-header bg-dark text-white">
         Card Title  
         <button class="btn btn-default btn-sm pull-right copy " data-clipboard-action="copy" data-clipboard-target="#abc"><i class="fa fa-copy" aria-hidden="true"></i> Copy</button>
     </div>
     <div class="card-body">
          <div id="abc">My Text To Copy</div>
      </div>
</div>
```

To resolve the extra space issue I changed the `card-body` section of code to this. You can see that I removed the nested div. This resolved the issue for me. Hope this helps someone else.
```html
<div class="card-body" id="abc">My Text To Copy</div>
```

**Comment by kelvinatorr** [comment]
I didn't see this issue so I posted the solution I found in another (older) issue:

https://github.com/zenorocha/clipboard.js/issues/147#issuecomment-613161030

Anyway, I think the fix for Firefox is to not have new lines or indentation in your HTML code.
