### ISSUE TITLE
Clipboardjs not taking first argument even though you send HTMLelements or node or nodelist

### ISSUE THREAD

**Issue by rojantandukar** [zenorocha/clipboard.js#384]
![png](https://cloud.githubusercontent.com/assets/15669233/23649399/52d099ea-0344-11e7-8b82-98e71b196b0c.png)
Log:
ValReqd: https://www.google.com
<button onclick="clicked()" id="bCopyClip" type="button" class="btnclass" title="Copy Link to Document" style="background: rgb(240, 240, 240);"
Document
clipb value:
t {listener: Object}

If i run this code individually, it will run in second click, but if i merge this code with my project source, it doesn't even work.. would be great if you'd help..

**Comment by zenorocha** [comment]
Clipboard.js already comes with a built-in click event listener. You don't need another one.

**Comment by zenorocha** [comment]
Check the documentation or see the `demo` folder for more examples.

**Comment by rojantandukar** [comment]
@zenorocha 

First of all, thanks..okay.. if I remove the onclick function and just declare the constructor as well, I got an error.
var url = "https://www.google.com";
var bttn = top.doc1.doc2.document.getElementById('bCopyClip');
var clip = new Clipboard(bttn,{
   text: function(trigger){ 
   return url;
  }
});
Error:
Uncaught Typeerror: First argument must be a String, HTMLElement, HTMLCollection, or NodeList

Am I doing anything wrong here??Can you please help me on this..

**Comment by zenorocha** [comment]
Please share a JSFiddle, otherwise I can't really debug it.

**Comment by rojantandukar** [comment]
While doing for demo purpose, in a separate file, it is working absolutely fine. But in my project source, it is creating problem.. I can share the working of it.

In a webpage, Ill right click and in context menu, i click on a button, which in back-end, will generate a link. That link has to be copied in the clipboard. This event is required as to generate a link..
