### ISSUE TITLE
Support to custom key combination(like ctrl+alt+c) or adding data to clipboard with custom menu link

### ISSUE THREAD

**Issue by piu** [zenorocha/clipboard.js#387]
Hi,

I have question that does this module support in React JS Application and does the custom key combination work for copying to clipboard(like Ctrl+Alt+C)? Also if there is any support to custom menu implementation like in any react function I want to copy some custom data to clipboard dynamically and later paste it on some other menu item click.

Is there any example for it? I couldn't find anything of this sought

**Comment by zenorocha** [comment]
Yes, this module supports React and any other JavaScript library. But currently, clipboard.js only supports `click` event listeners. No custom key combination or anything like that.
