### ISSUE TITLE
copy to clipboard only via JavaScript and no DOM Element need?

### ISSUE THREAD

**Issue by godoffrags** [zenorocha/clipboard.js#389]
Hi,

is it possible to copy text to clipboard only use Javascript?
There is no DOM element for use!

Example:
`<script>
  Clipboard.toClipboard('my Text');
</script>`
or something?

**Comment by MadLittleMods** [comment]
Related to https://github.com/zenorocha/clipboard.js/issues/218

**Comment by MadLittleMods** [comment]
You could use [`clipboard-action`](https://github.com/zenorocha/clipboard.js/blob/f59d4e6b4db55b0f462eeb96fb74db3469e0765d/src/clipboard-action.js) directly

```js
import ClipboardAction from 'clipboard/lib/clipboard-action';

const elementToCopy = document.querySelector('.some-element');
elementToCopy.addEventListener('click', (e) => {
  const clipboardAction = new ClipboardAction({
    action: 'copy',
    target: elementToCopy ,
    text: elementToCopy.textContent,
    trigger: e,
    emitter: { emit: () => {} },
  });

  clipboardAction.destroy();
});
```

**Comment by pietrovismara** [comment]
@godoffrags Or you can do like this: 
```
    function clipboard(text, event) {
        const cb = new Clipboard('.null', {
            text: () => text
        });

        cb.on('success', function(e) {
            console.log(e);
            cb.off('error');
            cb.off('success');
        });

        cb.on('error', function(e) {
            console.log(e);
            cb.off('error');
            cb.off('success');
        });

        cb.onClick(event);
    }
```

In this way, you don't need to bind clipboard with any DOM element. This is useful if you want to keep clipboard separated from your code logic / markup. You can even use it with angularjs / ng-click.

**Comment by zenorocha** [comment]
Hey guys, I added a proposal for this feature. Can you check #518?

Thanks!
