### ISSUE TITLE
custom domain "clipboard.js.org" for free

### ISSUE THREAD

**Issue by indus** [zenorocha/clipboard.js#39]
If you are interested in a sleek URL for your gh-pages branch check out [dns.js.org](https://dns.js.org).
The current URL would still work, so no broken links.

**Comment by zenorocha** [comment]
I'm trying to get `clipboardjs.com`, if that doesn't work then I'll definitely use this. Thanks for your tip!

**Comment by indus** [comment]
Sure. :+1: Nice project, by the way.

**Comment by lipis** [comment]
@zenorocha I really think that you don't need a special URL for it.. even after a few days.. just by searching [`clipboard`](https://www.google.com/#q=clipboard) you are number 5 and second when searching for [`clipboard js`](https://www.google.com/#q=clipboard+js). In a few days I think you will even beat the ZeroClipboard.

<img width="766" alt="screen shot 2015-10-01 at 00 21 52" src="https://cloud.githubusercontent.com/assets/125676/10208359/1ffbae46-67d3-11e5-81e2-7d1dcd8c1162.png">


Also another reason not having your own domain (besides the fact that you have to mainain, bla, bla) try googling for ZeroClipboard and see what comes first.. :)

So in my opinion it's simply not worth it.. plus this is for developers.. you are not trying to attract marketing and new customers :)

**Comment by lipis** [comment]
P.S. I also shamelessly stole the idea of using emojis in project descriptions.. :suspect:

**Comment by zenorocha** [comment]
Good argument @lipis but I think a custom domain gives more credibility.

I'll close this one for now since it's not really a code issue ;)

P.S. hey, that's trademark! :P
