### ISSUE TITLE
Closest check on SVG breaks in IE11 and Edge

### ISSUE THREAD

**Issue by nateperry** [zenorocha/clipboard.js#390]
This is seems to be a similar issue to #159 but since this we are now on v1.6.1, the error is a bit different. If I need to move this report into the Delegate repo, I am happy to do so. Figured I would post here first in case other people are searching with a similar issue due to Clipboard specifically.

JSFiddle: https://jsfiddle.net/nateperry/rxw2j2de/4/

### Expected behaviour

As you can see in the fiddle, I am using an `a` element as the target to click, with an `<svg><use></svg>` as a child. In Internet Explorer 11 and Microsoft Edge, I would expect that the text "Hello!" is copied to my clipboard. This works in every other browser I have tested (Chrome 56, Firefox 52). I included a second `<a>` as proof that everything works without the SVG.

### Actual behaviour

Instead, I get a JS error "Object doesn't support property or method 'matches'". From the best I can tell, an SVG is not considered an Element, so even though there is a polyfill for `matches`, it is does not affect SVG's.

### Browsers affected

Internet Explorer 11 and Microsoft Edge 38

**Comment by zenorocha** [comment]
Hey @nateperry, yeah this is an issue with `delegate`, can you close it here and open there. Also, if you have an idea how to solve it, please send a pull request :)

**Comment by nateperry** [comment]
Sure thing! Thanks for the quick reply!
