### ISSUE TITLE
why can't use trigger('click') ? (为什么无法手动触发拷贝事件？)

### ISSUE THREAD

**Issue by gaoqiang19514** [zenorocha/clipboard.js#393]
`
button class="btn" data-clipboard-text="123456"
        click to copy
button

new Clipboard('.btn');  
$('.btn').trigger('click');
// nothing to happen
`

**Comment by Froguard** [comment]
@gaoqiang19514 应该是浏览器的安全限制，要有一个event才执行剪切板的相关操作，这里的event需要注意，用js代码创建的event 和 用户交互式（即用户正常鼠标点击）产生的event有一定的区别的。比如，
```js
domXxx.click();// domXxx.onClick();
$('.xx').click();//$('.xx').trigger('click');
```
等，都是不会让copy效果生效的，clipboard.js 会抛error

**Comment by Froguard** [comment]
@gaoqiang19514  issues里有一种曲线救国的方式，你看一下
[issues/389](https://github.com/zenorocha/clipboard.js/issues/389#issuecomment-301916808)
```js
function clipboard(text, event) {
        const cb = new Clipboard('.null', {
            text: () => text
        });
        cb.on('success', function(e) {
            console.log(e);
            cb.off('error');
            cb.off('success');
        });
        cb.on('error', function(e) {
            console.log(e);
            cb.off('error');
            cb.off('success');
        });
        cb.onClick(event);
    }
```

**Comment by gaoqiang19514** [comment]
谢谢老哥！

**Comment by designbyadrian** [comment]
Can somebody please translate the rest of the comments to English so the rest of us who might have the same issue might learn something?

**Comment by Froguard** [comment]
@designbyadrian done! 😃

**Comment by ieliwb** [comment]
@Froguard 大哥，这个怎么使用啊

**Comment by pecopeco** [comment]
@RosApr @ieliwb 
$('#copyBtn').on('touchstart', (e) => {
     clipboard('text', e);
 });

**Comment by wlxscn** [comment]
> @Froguard 大哥，这个怎么使用啊
> function clipboard(text, event) {
> const cb = new Clipboard('.null', {
> text: () => text
> });
> cb.on('success', function(e) {
> console.log(e);
> cb.off('error');
> cb.off('success');
> });
> cb.on('error', function(e) {
> console.log(e);
> cb.off('error');
> cb.off('success');
> });
> cb.onClick(event);
> }
> 我直接clipboard("xxoo",null);报错

你解决了吗，我直接用这个也报错

**Comment by gaoqiang19514** [comment]
是可以用的，我当时弄通了的，自己多摸索下，几年前的了，我都忘记了

在 2019-08-08 18:35:46，"山丘" <notifications@github.com> 写道：


@Froguard 大哥，这个怎么使用啊
function clipboard(text, event) {
const cb = new Clipboard('.null', {
text: () => text
});
cb.on('success', function(e) {
console.log(e);
cb.off('error');
cb.off('success');
});
cb.on('error', function(e) {
console.log(e);
cb.off('error');
cb.off('success');
});
cb.onClick(event);
}
我直接clipboard("xxoo",null);报错

你解决了吗，我直接用这个也报错

**Comment by wlxscn** [comment]
> 是可以用的，我当时弄通了的，自己多摸索下，几年前的了，我都忘记了 在 2019-08-08 18:35:46，"山丘" <notifications@github.com> 写道： @Froguard 大哥，这个怎么使用啊 function clipboard(text, event) { const cb = new Clipboard('.null', { text: () => text }); cb.on('success', function(e) { console.log(e); cb.off('error'); cb.off('success'); }); cb.on('error', function(e) { console.log(e); cb.off('error'); cb.off('success'); }); cb.onClick(event); } 我直接clipboard("xxoo",null);报错 你解决了吗，我直接用这个也报错 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
想想呗，我这边报错，不知道跟版本有没有关系

**Comment by gaoqiang19514** [comment]
@wlxscn 你的报错信息发来看看

**Comment by wlxscn** [comment]
> @wlxscn 你的报错信息发来看看

已经解决了，谢谢

**Comment by gaoqiang19514** [comment]
@wlxscn 啥忙都没帮上，拒绝你的谢谢！
