### ISSUE TITLE
Auto scroll to focused element when copy

### ISSUE THREAD

**Issue by thanhdnh** [zenorocha/clipboard.js#395]
I have The same problem in this https://github.com/zenorocha/clipboard.js/issues/250
iOS10+, clipboard js 1.6. The process on iOS:
+ Focus on clipboard-data-target
+ Select text
+ Copy
But for the first step, iOS scrolls automatically to the clipboard-data-target, so it's very badddd!!!!

**Comment by zenorocha** [comment]
Please share a minimal demo that reproduces this problem or feel free to send a pull request.

**Comment by zenorocha** [comment]
Also, why are you showing the select text to the user? iOS10+ already supports copy to clipboard. Try using this:

```js
clipboard.on('success', function(e) {
    e.clearSelection();
});
```

**Comment by thanhdnh** [comment]
Dear zenorocha,
You Just open your site clipboardjs.com on iPhone 6 and above, scroll down to example that relates to input or textarea, continue scrolling until to hide the input (or textarea), just enough to see button copy/cut. Click on it, you will see browser auto scroll to the input (or textarea). In my site http://emojiselector.com , this problem is still there :(
Please fix this. I try many methods, but useless.
Thank you!

**Comment by zenorocha** [comment]
Just tested on iPhone 6 and everything seems to be working fine over here.
