### ISSUE TITLE
Clipboard.isSupported() not working

### ISSUE THREAD

**Issue by artrayd** [zenorocha/clipboard.js#396]
I am not pro at javascript, maybe I am doing something wrong. But when I try to run Clipboard.isSupported() function, receiving following error:

Uncaught ReferenceError: Clipboard is not defined

https://jsfiddle.net/artrayd/Lhmeh6bg/

Rest of plugin works as magic, thank you!

**Comment by zenorocha** [comment]
The only thing you missed was including the JS file: https://jsfiddle.net/2vqwfLzu/
