### ISSUE TITLE
Tooltip not shown in anchor tag.

### ISSUE THREAD

**Issue by muhghazaliakbar** [zenorocha/clipboard.js#398]
I tried to create anchor tag with clipboard.js but the tooltip not shown after success copy to clipboard
```
<a href="javascript:void(0);" id="copyUrl" data-clipboard-text="http://example.com">
    <i class="fa fa-link"></i>
    <span>Copy</span>
</a>
```

**Comment by zenorocha** [comment]
Hey @muhghazaliakbar, the tooltip is not included on clipboard.js.
