### ISSUE TITLE
False advertising!

### ISSUE THREAD

**Issue by AlecTaylor** [zenorocha/clipboard.js#399]
:1st_place_medal: 

10.4KB? - https://github.com/zenorocha/clipboard.js/blob/f59d4e6b4db55b0f462eeb96fb74db3469e0765d/dist/clipboard.min.js

:P

**Comment by zenorocha** [comment]
<img width="444" alt="screen shot 2017-04-04 at 8 21 28 am" src="https://cloud.githubusercontent.com/assets/398893/24664538/c746fa9a-190f-11e7-860b-e58b00fa0339.png">
<img width="446" alt="screen shot 2017-04-04 at 8 21 40 am" src="https://cloud.githubusercontent.com/assets/398893/24664540/c751d366-190f-11e7-817f-01596076003e.png">
<img width="562" alt="screen shot 2017-04-04 at 8 21 51 am" src="https://cloud.githubusercontent.com/assets/398893/24664539/c74ebdb6-190f-11e7-8717-d01369c162ae.png">
