### ISSUE TITLE
Why it don't supports copy Image but I copy Image with it?

### ISSUE THREAD

**Issue by chang0022** [zenorocha/clipboard.js#402]
You said clipboard.js don't supports copy Image。 But I used it in my [Website](http://www.51huotao.com/portal/portalGoodsList)

![image](https://cloud.githubusercontent.com/assets/6067222/25161167/0bd433e2-24ed-11e7-9e6d-3c6102444bdd.png)

It copy the image and word in Word or Wechat.

### Actual behaviour

You can see gif in  this url 
https://imgchr.com/i/ilrAH
or
http://i4.buimg.com/4851/878a9bbd1173adc5.gif

### Browsers affected

Chrome 57

So I don't know it is mean  supports copy Image?  

Thanks

**Comment by zenorocha** [comment]
I can confirm it works on certain browsers like Chrome and Firefox. But not on all of them like Safari.
