### ISSUE TITLE
How to add something after the copy of the text ?

### ISSUE THREAD

**Issue by SouSuoKe** [zenorocha/clipboard.js#404]
### Expected behaviour

How to add something after the copy of the text, such as to copy the text is Hello, paste show Hello from xxx, how to do this effect?
Hello --(paste)--> Hello from xxx
Thanks!

**Comment by zenorocha** [comment]
You can listen to the `success` event and get the `text` property from that fired event.

```js
clipboard.on('success', function(e) {
    console.info('Text:', e.text);
});
```

**Comment by SouSuoKe** [comment]
Can I ask you to write an example for me? I tried many times, but did not succeed, I was just an amateur, just started learning, and did not learn a lot.

**Comment by zenorocha** [comment]
There are lots of examples on the [demo](https://github.com/zenorocha/clipboard.js/tree/master/demo) folder. I'm pretty sure one of them will help you ;)
