### ISSUE TITLE
Firefox fails to copy bigger amount of data

### ISSUE THREAD

**Issue by BikingGlobetrotter** [zenorocha/clipboard.js#407]
### Error description
I would like to copy a bigger amount of data (~3MB of text) via clipboard JS. Unfortunately, this does not work in firefox. In the browser.console you can see the following error message:

> document.execCommand(‘cut’/‘copy’) was denied because it was not called from inside a short running user-generated event handler.

Looks like a firefox security policy denied the copying of the data. Copying the data to the hidden form takes some time in Firefox. Do you think it is possible to fix / workaround this policy?

You can find a minimal example here:
https://jsfiddle.net/m951utk7/2/

### Browsers affected
Chrome 58 (works fine)
Firefox 53 (does not work)
Opera 44 (works fine)
Internet Explorer (Windows 7) (works fine)

**Comment by zenorocha** [comment]
Unfortunately there's nothing we can do about this. I recommend you open an issue on https://bugzilla.mozilla.org.

**Comment by BikingGlobetrotter** [comment]
Thank you for your answer. I did so: https://bugzilla.mozilla.org/show_bug.cgi?id=1360441

**Comment by BikingGlobetrotter** [comment]
Hi @zenorocha,
I don't know how to reopen the case, but the firefox guys created a solution how the workaround this issue and make clipboard.js extremly fast. I think that is interesting for you.

Since Safari and IE allow copying text to the clipboard only if data is selected, but don't care, whether the selected text and the text text copied to the clipboard are actually the same, they select a dummy text in the dummy textarea and set the clipboard data manually in the event handler.

`
// This is implemented by directly copying the text into the DataTransfer.
function selectDataTransfer() {
  // Register a copy handler which will directly add the text to the DataTransfer object.
  function copyHandler(event) {
    if (event.clipboardData) {
      event.clipboardData.setData("text/plain", text);
    } else {
      // Internet Explorer is special, and needs to be given both a different
      // MIME type, and have the method called on a different object.
      clipboardData.setData("Text", text);
    }
    console.log("Added text");
    event.preventDefault();
  }
  document.addEventListener("copy", copyHandler);

  // Create a dummy text area and select it, as Safari and Edge require the
  // text area to be selected to trigger an execCommand("copy")
  var fakeElem = makeTextArea();
  fakeElem.value = "a";
  document.body.appendChild(fakeElem);
  fakeElem.select();
  fakeElem.setSelectionRange(0, fakeElem.value.length);

  // Trigger the copy command, and then remove the event listener
  console.log("execCommand =", document.execCommand("copy"));
  document.removeEventListener("copy", copyHandler);
}
`

Detailed description:
https://bugzilla.mozilla.org/show_bug.cgi?id=1360441
Sample code (Click: "Select Data Transfer")
https://mystor.github.io/copy-reflow/

**Comment by eythort** [comment]
I tested this as a potential workaround for when Chrome is not able to copy a large text blob. Version 1.6.1 threw an error after 2 seconds, but this patch copied all the text successfully instantly.
This patch warrants a new immediate clipboard.js release, in my opinion.

**Comment by alecazam** [comment]
This is closed, but have you tried this with larger amounts of data?  In my test cases, you need to be able to async/setTimeout run the execCommand but then Firefox requires clipboardWrite permission.  Formatting larger amounts of data in the textArea (36s in Chrome to format 6.2MB of ascii text) runs over the time limit, and then Chrome/Firefox will often fail the execCommand('copy') operation.  Chrome at least lets the execCommand be run from a setTimeout call that isn't user-generated.

**Comment by eythort** [comment]
I basically added the solution (or hack, if you will) that mystor provided in #412 , but wasn't accepted, exactly because large amounts of data ("large" being a few MBs), and clipboard.js then works in an instant instead of timing out or taking several seconds. Such a pity that it wasn't accepted, being a hack or not
