### ISSUE TITLE
click button one time, but new Clipboard multiple times bug.

### ISSUE THREAD

**Issue by kookob** [zenorocha/clipboard.js#410]
### My Code

HTML:
`<button class="testBtn" type="button" onclick="test();" data-clipboard-text="">Test</button>`

JS:
```
function test() {
    var clipboard = new Clipboard('.testBtn', {
        text: function(trigger) {
            alert("testBtn");
            return "testCopy";
        }
    });
    clipboard.on('success', function(e) {
        console.log("ok");
    });
    clipboard.on('error', function(e) {
        console.log("error");
    });
}
```

### Actual behaviour

At the first click Test Button, the behaviour is normal.
and at the second click the Test Button, the code 
```
var clipboard = new Clipboard('.testBtn', {
        text: function(trigger) {
            alert("testBtn");
            return "testCopy";
        }
    });
```
will execute twice, and 'testBtn' alert twice.

click again, the code will execute one more time, always accumulate.

use `var clipboard = new Clipboard('.copyBtn');`
the behaviour is normal.
Is this dynamically set a text has a bug?
or where my code is error?

### Browsers affected

IE 11 and Chrome  57.0.2987.133 does not work good.

**Comment by zenorocha** [comment]
clipboard.js already comes with a built-in click event listener when you create a new instance, so there's no need to add another one.

**Comment by delia-curiel** [comment]
hi, I have the same problem as @kookob , and I don't understand the answer @zenorocha  have given ...

**Comment by Surajit229** [comment]
Sir, How to solve the above problem ?
: I've just shown notification message in success method, and it come more than one times.

Because of, I already to used [on : success ] event for Notification.
Please sir way out this problem.
