### ISSUE TITLE
IE continuously ask for clipboard permission

### ISSUE THREAD

**Issue by tiasmc** [zenorocha/clipboard.js#411]
### Minimal example

> https://clipboardjs.com/

### Expected behaviour

When allowing access to use the clipboard in IE, the permission is valid for the whole site.

### Actual behaviour

IE asks for permission on all pages, the access is only valid for the current page.

I have found that by adding the website to trusted sites and always allow clipboard access for trusted sites this is fixed, but i would like a solution where my customers won't have to edit internet options security.

### Browsers affected

IE only.

**Comment by zenorocha** [comment]
Yes, on IE9-11 there's a prompt that asks if the user wants to allow access to his/her clipboard.

<img width="373" alt="screen shot 2015-10-14 at 8 49 20 pm" src="https://cloud.githubusercontent.com/assets/398893/10504423/33c8fa90-72b5-11e5-8ca9-1a1b0a342e9f.png">

Unfortunately, that's a browser limitation and there's nothing we can do about it. 

Thanks for reporting @tiasmc!
