### ISSUE TITLE
Is there an event for "start"?

### ISSUE THREAD

**Issue by UweKeim** [zenorocha/clipboard.js#413]
I'm using the `success` and `error` event handlers successfully:

    clipboard.on('success',
        function (e) {
            // ...
        }
    }

I'm now looking for a way to also register an event handler right after the user clicks the copy button.

**My question:**

Is there such an event?

Or any workaround to get some notifications right after the start, before the `success` or `error` events?

**Comment by UweKeim** [comment]
My workaround is to directly register my own `click` handler:

    $('#btnclipboard').on('click',
         function() {
            // ...
    });

This seems to work on Google Chrome.

Is this a good workaround?

**Comment by zenorocha** [comment]
Hey @UweKeim, from what I understood you want to show something to the user before the click, so the only thing I can think is to use the `mouseover` event.
