### ISSUE TITLE
Pasting as plain text but still with breakings

### ISSUE THREAD

**Issue by purgeru** [zenorocha/clipboard.js#414]
### Minimal example

https://jsfiddle.net/purgeru/nq62vwzc/4/

### Expected behaviour

I want to copy and paste text without browser style and links, but still with breakings.
As pasting CTRL+SHIFT+V. Need this for copying text into Lotus notes for predefined answers.

### Actual behaviour

Now it pastes all the styles.

**Comment by zenorocha** [comment]
Hey @purgeru, you have two options, you can try the `data-clipboard-text` or the [imperative API](https://github.com/zenorocha/clipboard.js#advanced-options), that way you can have more control over what you're copying and modify it to your needs.
