### ISSUE TITLE
Tooltip functionality doesn't seem to be packaged with base install

### ISSUE THREAD

**Issue by kureus** [zenorocha/clipboard.js#415]
Hey @zenorocha. Looking through clipboardjs.com every time I take an action using your library I get some fantastic UI feedback in the form of a tooltip saying "Copied!" etc. However dropping the lib into a site I don't get this ootb. On clipboardjs.com you load three extra javascript files, demo.js, snippets.js and tooltips.js with the first two containing `showTooltip(e.trigger,'Copied!')` which seems to enable this functionality on top. Is it a deliberate design decision to not have this in the base lib or am I missing a way to enable it?

Thanks

**Comment by zenorocha** [comment]
Hey @kureus, yes this is a deliberate decision. Clipboard.js is not opinionated in terms of UI and UX, each site has different needs and designs so they know better than anybody else how the user feedback should look like.

If you're looking for that same tooltip, you can check the [gh-pages branch](https://github.com/zenorocha/clipboard.js/tree/gh-pages), all I do is use [primer-css](https://github.com/primer/primer-tooltips).

**Comment by kureus** [comment]
Thought this might be the case. Maybe worth making this explicit somewhere to address the difference between the demo an ootb functionality? Appreciate the prompt response and great lib 😄
