### ISSUE TITLE
Problem when using clipboard.js in Jupyter Notebook

### ISSUE THREAD

**Issue by AndreWin** [zenorocha/clipboard.js#416]
Hello!

I used clipboard.js for Jupyter Notebook (JN). On first run JN create `.jupyter` folder. We can create folder named `custom` in it and place `custom.js` there. I have following code in this file:

```
console.log("load clipboard.js");
requirejs.config({
    paths: {
        'clipboard': ['notebook/js/clipboard.min']
    },
    shim: {
        clipboard: {
            deps: [],
            export: "clipboard"
        }
    }
});
```

Before last update this code worked fine, but now it doesn't work and I have no idea how to fix it.

I noticed that there is file `clipboard.js` in `path_to_python_virtual_environment/Lib/site_packages/notebook/static/notebook/js` folder. I use `clipboard.min.js`, but it seems to me a conflict steel can be a conflict still...

I'm ready to create a portable distribution of JN for Windows or Linux, so you will need only download and run it. Also I can give you full and easy instruction how to install and run JN and how custom.js can be used.

Best regards,
Andrey.

**Comment by zenorocha** [comment]
Hey @AndreWin, thanks for reporting. I'm afraid I can't help you with that, please refer to the people that implemented clipboard.js inside Jupyter Notebook. This repository is for discussions on the core library.
