### ISSUE TITLE
Improve Documentation for Imperative API

### ISSUE THREAD

**Issue by ryantheleach** [zenorocha/clipboard.js#422]
I really love JQuery's API documentation when it comes to imperative code.

At the moment the story driven examples in the readme help, but they feel really informal.

Could a section listing the events, public functions, and expected types be added?

**Comment by zenorocha** [comment]
Hey @ryantheleach, thanks a lot for your suggestion. In my perspective, there's no need to add a complicated documentation for this. In fact, I believe this is one of the reasons why clipboard.js is so successful. 

But feel free to send a pull request if you have a more objective proposal ;)
