### ISSUE TITLE
document missing tooltip

### ISSUE THREAD

**Issue by MartinMuzatko** [zenorocha/clipboard.js#423]
Hello!
As discussed in issue #62, #94, #195, #306, #366, #398 and #415, you **SHOULD** really document that the tooltip is **NOT** part of the base install! All these issues are closed, but there is still **no** documentation.

It is really a time-waster to see, that everything is included correctly, but the **demonstrated functionality is missing**. Even worse: not documented. 

The user has to
1. first scan the website
2. look for "Copied!"
3. find the missleading phrase
> The good news is that clipboard.js gracefully degrades if you need to support older browsers. All you have to do is show a tooltip saying Copied!

And my thoughts are just: _clipboard.js is doing this for me ... right?_
4. then search the issues
5. then be linked to the assets
6. include the [tooltips.js](https://github.com/zenorocha/clipboard.js/blob/gh-pages/assets/scripts/tooltips.js), get an error for `Uncaught ReferenceError: hljs is not defined`
6. then find out that the style is coming from primer.css.
7. piece together the tooltips.js and the style 

It doesn't have to be included in the base package, I'm all for a tiny filesize. But some pointers to the advertised functionality, would be great and would save a lot of time.

Best,
Martin

**Comment by produktive** [comment]
@MartinMuzatko How do I use the damn tooltip? I still can't figure it out. I included the tooltips.js code, what do I do after: "Uncaught ReferenceError: hljs is not defined"?

**Comment by zenorocha** [comment]
Could you send a pull request @MartinMuzatko?

**Comment by zenorocha** [comment]
Done, thanks @MartinMuzatko!

**Comment by JacobBumgarner** [comment]
For anyone searching how to do this like I was, see this example solution:

```javascript
// Tooltip
$('button').tooltip({
  trigger: 'click',
  placement: 'bottom'
});

function setTooltip(btn_id, message) {
  $(btn_id).tooltip('hide')
    .attr('data-original-title', message)
    .tooltip('show');
}

function hideTooltip(btn_id) {
  setTimeout(function() {
    $(btn_id).tooltip('hide');
  }, 1000);
}

// Clipboard
var clipboard = new ClipboardJS('.btn');

clipboard.on('success', function(e) {
  var btn_id = "#" + e.trigger.id;
  setTooltip(btn_id, 'Copied!');
  hideTooltip(btn_id);
 
});

clipboard.on('error', function(e) {
  setTooltip('Failed!');
  hideTooltip();
  
});
```

I generalized this solution from this codepen example that I found:
https://codepen.io/OasesOng/pen/WBWpVK
