### ISSUE TITLE
FireFox is broken again for the 'execCommand' issue.  I'm at 53.0.3

### ISSUE THREAD

**Issue by robertkjr3d** [zenorocha/clipboard.js#424]
### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

### Expected behaviour

Expected behavior is to copy and be able to paste with the FireFox browser.

### Actual behaviour

It does highlight, which is more than I can say than most software.  But the actual Clipboard is not filled for Firefox version 53.0.3 on 6/6/2017

### Browsers affected

Only Firefox 53.0.3

**Comment by zenorocha** [comment]
Can you share a JSFiddle? Everything seems to be working fine over here.

**Comment by robertkjr3d** [comment]
https://jsfiddle.net/5t9t5ymm/ Here is the fork that produces the:
document.execCommand('cut/'copy') was denied error...

**Comment by zenorocha** [comment]
It's working fine here on Firefox 53.

![a](https://user-images.githubusercontent.com/398893/26843698-fb535a46-4aa5-11e7-8a53-b988404d3300.gif)

**Comment by robertkjr3d** [comment]
Indeed...? my laptop that was not upgraded:
went from 43.0.1 works
then 47.0.2 works
then 53.0.3 works

The only thing different, is that my desktop says it's a 'funnelcake' build.  But firefox claims these are supposed to be no different.

**Comment by robertkjr3d** [comment]
https://support.mozilla.org/en-US/questions/1163139 -- It was the funnelcake version.
