### ISSUE TITLE
1.7.1 not available on jsDelivr/CDN wiki page doesn't reflect 1.7.1 release

### ISSUE THREAD

**Issue by karlr42** [zenorocha/clipboard.js#425]
I was going to submit a PR to update your [CDN](https://github.com/zenorocha/clipboard.js/wiki/CDN-Providers) page to 1.7.1, but I noticed that that version isn't available on [jsDelivr](https://www.jsdelivr.com/projects/clipboard.js) yet.

**Comment by MartinKolarik** [comment]
@karlr42 it *is* on jsDelivr, but under a new link: https://cdn.jsdelivr.net/npm/clipboard@1.7.1/dist/clipboard.min.js

You can [check the new jsDelivr docs for more info](https://github.com/jsdelivr/jsdelivr#note-our-backend-changed-learn-how-to-use-the-new-jsdelivr).

**Comment by karlr42** [comment]
Ah, cool. I updated the wiki [page](https://github.com/zenorocha/clipboard.js/wiki/CDN-Providers) anyway, and for jsDelivr just let it use the latest version, that seems to make the most sense. Thanks!

**Comment by MartinKolarik** [comment]
I suggest using at least https://cdn.jsdelivr.net/npm/clipboard@1/dist/clipboard.min.js
Links without version are dangerous because you can be updated to a new major version with breaking changes without knowing.

**Comment by karlr42** [comment]
Good point, changed, thanks.
