### ISSUE TITLE
API extension to handle copying fully imperatively

### ISSUE THREAD

**Issue by tambeta** [zenorocha/clipboard.js#426]
I'd like to propose extending the API so that the following use case would be possible.

In some scenarios, clicking the copy trigger element may have unwanted consequences, e.g. a `<button>` or `<a>` in a Bootstrap dropdown which causes the dropdown to close if event propagation is not stopped. I would like to stop propagation of the click event beyond the button and handle clipboard actions immediately. Right now this does not seem to be possible, but I could not locate thorough API documentation which would confirm this (an issue raised in #422).

[JSFiddle example](https://jsfiddle.net/addsesgm/).

**Comment by tambeta** [comment]
I managed to resolve my particular issue by examining the code. [src/clipboard.js](https://github.com/zenorocha/clipboard.js/blob/f42b57067d461f5a8c71deec9818670f0c71d818/src/clipboard.js#L38) calls [listen](https://github.com/zenorocha/good-listener/blob/master/src/listen.js#L13) from `good-listener`, which has different behavior depending on whether a selector or a DOM node is passed. In the former case, an event handler is attached to `<body>`, in the latter to the passed node itself. Passing a node allows stopping event propagation early on. This should certainly be documented.

**Comment by zenorocha** [comment]
Thanks for reporting @tambeta, feel free to send a pull request with your suggestions.
