### ISSUE TITLE
Need for copy inputs

### ISSUE THREAD

**Issue by ppKrauss** [zenorocha/clipboard.js#428]
### Minimal example

HTML ```<select><option>1<option>2</select>```.

### Expected behaviour

To copy the the *selected value*.

### Actual behaviour

Copy nothing (empty).

### Browsers affected

All.

------

Clue for solution: see #427.

**Comment by zenorocha** [comment]
Hey @ppKrauss, thanks for reporting. Feel free to send a pull request or use the imperative API.

```html
<select id="foo">
  <option>1<option>
  <option selected>2<option>
  <option>3<option>
</select>

<button class="btn">Copy</button>
```

```js
var clipboard = new Clipboard('.btn', {
  text: function() {
    return document.querySelector('#foo').value;
  }
});
```

See: https://jsfiddle.net/5kk0eysw/29/

**Comment by visioncode** [comment]
Is it also possible to copy by the change event, not any btn?

**Comment by ppKrauss** [comment]
Hi @zenorocha,  your code **is not a solution**, it is a "only one value copy", ignoring all other contents (!). My `#foo` is a whole table, and your code is coping only a cell of the table.

**Comment by ppKrauss** [comment]
A workaround is perhaps a kind of "OR logic". 
Copy as *clipboard.js* default **OR** as additional specification when it exists. 

This configurable "OR logic" avoid the need of a trigger (as #427 by #338 can't implemented in Firefox)... Is a solution for you @visioncode?
