### ISSUE TITLE
Compatibility between jQuery and Bootstrap

### ISSUE THREAD

**Issue by produktive** [zenorocha/clipboard.js#429]
I realize this may not be the right place to post this. I finally got Clipboard + Tooltip to work on my custom profile page for Wordpress users. One of the features on the Wordpress profile page is a password generator/strength indicator, I believe this comes standard on Wordpress and relies on jQuery. I cannot get both Clipboard+Tooltip to work at the same time as the password button, one of them breaks. How can I make them work together?

**Comment by zenorocha** [comment]
Please share a minimal reproducible code on JSFiddle, otherwise it's completely impossible for me to debug such case.
