### ISSUE TITLE
Comparison with ZeroClipboard

### ISSUE THREAD

**Issue by dandv** [zenorocha/clipboard.js#43]
Since ZeroCliboard is so popular, it might be worth listing the [browser/OS configurations which clipboard.js doesn't support, but ZeroClipboard does](https://github.com/zeroclipboard/zeroclipboard/issues/171#issuecomment-144117095).

**Comment by zenorocha** [comment]
I disagree, the whole point of this project is to not encourage Flash usage.

**Comment by dandv** [comment]
I might have been misunderstood. You [said](https://github.com/zeroclipboard/zeroclipboard/issues/171#issuecomment-144579551) yourself that

> ZeroClipboard [...] has better browser support

I also much abhor Flash usage (we use ZC in production, and have had our share of issues with Flash).

All I was looking for was a *comparison* with ZC.

**Comment by zenorocha** [comment]
Developers should do their homework when comparing different tools. Both projects list what browsers they support, so it's just a matter of comparing that to what your Analytics tell you.
