### ISSUE TITLE
How do I put this in a function?

### ISSUE THREAD

**Issue by spencerthayer** [zenorocha/clipboard.js#432]
How would I wrap `var clipboard = new Clipboard("#inputID");` into a function? Or bind it to another click function?

**Comment by spencerthayer** [comment]
I need to do this...

```javascript
//CLIPBOARD AND PASS REVEAL
var clipboard = new Clipboard("#domainPassword");
clipboard.on("success", function(e) {
    Materialize.toast("Password copied!", 1500);
});
function revealPass() {
    $("#domainPassword").attr("type", "text");
}
function hidePass() {
    $("#domainPassword").attr("type", "password");
}
$("#domainPassword").click(revealPass).mousedown(revealPass).mouseup(hidePass);
```

```html
                    <input type="password" class="domainPassword" id="domainPassword" name="domainPassword" placeholder="Domain Password:" readonly="true" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" style="" data-clipboard-target="#hiddenPassword" />
                    <input type="hidden" id="hiddenPassword" data-clipboard-text="" />
```

**Comment by spencerthayer** [comment]
This is for a password generator not for login so there are no issues of security.

**Comment by spencerthayer** [comment]
From what I am getting from the documentation this usecase is out of the scope of clipboard.js. But before I abandon clipboard.js I would like to know if I am wrong.

**Comment by spencerthayer** [comment]
This works for just a single password type input but I the hold function cannot work with it so this isn't a desirable solution.

```javascript
var clipboard = new Clipboard("#domainPassword", {
    target: function() {
        if ($("#domainPassword").attr("type") == "password") {
            revealPass();
        } else {
            hidePass();
        }
        return document.querySelector("#domainPassword");
    }
});
clipboard.on("success", function(e) {
    Materialize.toast("Password copied!", 1500);
    setTimeout(function() {
        hidePass();
    }, 1500);
});
```

**Comment by spencerthayer** [comment]
``javascript
//CLIPBOARD AND PASS REVEAL
function copyToClipboard() {
    $("#domainPassword").attr("type", "text");
    document.querySelector("#domainPassword").select();
    document.execCommand("copy"); //cut, copy or paste
    //clear selection
    if ( document.selection ) {
            document.selection.empty();
        } else if ( window.getSelection ) {
            window.getSelection().removeAllRanges();
        }
    Materialize.toast("Password copied!", 1500);
}
function revealPass() {
    $("#domainPassword").attr("type", "text");
}
function hidePass() {
    $("#domainPassword").attr("type", "password");
}
$("#domainPassword").mousedown(copyToClipboard).mouseup(hidePass);
```

I'm just going with a solution out of the scope of clipboard.js. You may want to consider expanding the functionality of the app. It's a pretty good idea but kind of limited.

**Comment by jayant-lumino** [comment]
> ```js
> //CLIPBOARD AND PASS REVEAL
> function revealPass() {
>     $("#domainPassword").attr("type", "text");
> }
> function hidePass() {
>     $("#domainPassword").attr("type", "password");
> }
> function copyToClipboard() {
>     revealPass();
>     document.querySelector("#domainPassword").select();
>     document.execCommand("copy"); //cut, copy or paste
>     //clear selection
>     if ( document.selection ) {
>             document.selection.empty();
>         } else if ( window.getSelection ) {
>             window.getSelection().removeAllRanges();
>         }
>     Materialize.toast("Password copied!", 1500);
> }
> $("#domainPassword").mousedown(copyToClipboard).mouseup(hidePass);
> ```
> 
> I'm just going with a solution out of the scope of clipboard.js. You may want to consider expanding the functionality of the app. It's a pretty good idea but kind of limited.

Your answer is the solution, I was looking for. But you can go with only 1 instead of 1500 in setTimeout. It''ll not let users see the text box and work the same as you mentioned.
