### ISSUE TITLE
How Can I do?

### ISSUE THREAD

**Issue by Wahitler** [zenorocha/clipboard.js#434]
### I write my code is:

![image](https://user-images.githubusercontent.com/12858618/27223299-5c0d9882-52c2-11e7-9b10-751c3ec0d151.png)

### How can i fix it?

**Comment by oPorks** [comment]
I notice, u don`t need to create a new object every click, and you are doing it.

**Comment by Wahitler** [comment]
thank you for your reply,my need is
![image](https://user-images.githubusercontent.com/12858618/27513809-79fb5cb2-59a7-11e7-982a-25b00bf94789.png)
how can i not new object ? i am new for js.
here is my code:
`    <input type="text" id="foo" value="hehe">
    <button data-clipboard-target="#foo" id="btnFoo" data-clipboard-action="copy"  onclick="copyUrl('btnFoo')">Copy</button>

    <input type="text" id="gfd" value="gfd">
    <button data-clipboard-target="#gfd" id="btnGfd" data-clipboard-action="copy"  onclick="copyUrl('btnGfd')">copyMe</button>

    
    <script src="lib/clipboard.js"></script>
    <script>
        var clipboard;
        function copyUrl(urlText) {
            clipboard= new Clipboard('#' + urlText + '');
            clipboard.on('success', function (e) {
                alert('success!');
                e.clearSelection();
            });
            clipboard.on('error', function (e) {
                alert('error');
            });

        }
    </script>`

> object

**Comment by higornevesmarques** [comment]
@Wahitler Try it:

```
<input type="text" id="gfd" value="gfd">
<button data-clipboard-target="#gfd" id="btnGfd" data-clipboard-action="copy">copyMe</button>


<script src="lib/clipboard.js"></script>
<script>
    new Clipboard("#btnGfd");

    clipboard.on('success', function (e) {
        alert('success!');
        e.clearSelection();
    });
    clipboard.on('error', function (e) {
        alert('error');
    });
</script>
```
You need to create a new instance only one time, with the element which you have passed as parameter will receive all actions you need

**Comment by zenorocha** [comment]
Thanks @higornevesmarques!
