### ISSUE TITLE
Trying To Copy an empty string doesn't trigger success or failure

### ISSUE THREAD

**Issue by pavlism** [zenorocha/clipboard.js#436]
Awesome project!!
I just spent some time debugging your code because the success trigger, not the error trigger was firing when the text property return an empty string.  I didn't realise the problem was the empty string (duh), but letting the success or failure trigger fire in this case might be nice to help users debug their code.

**Comment by zenorocha** [comment]
Thanks for reporting @pavlism! Feel free to send a pull request ;)
