### ISSUE TITLE
Carriage return added in the copied string

### ISSUE THREAD

**Issue by dlicois** [zenorocha/clipboard.js#439]
### clipboard.js adds carriage return when copying string

see:
https://jsfiddle.net/dlicois/yvx5n5fb/

### Expected behaviour

Saved string should be :

> http://www.google.com

### Actual behaviour

But when pasting, carriage returns are added :

>{carriage return here}
>http://www.google.com {carriage return here}
> 

### Browsers affected

Tested on firefox 54 and a few versions earlier. This seem to be caused by the action element not being at the same dom level as the target element.

**Comment by zenorocha** [comment]
This seems like a bug on Firefox only. Unfortunately, I cannot add a `trim` function into the library because people might not want this behavior, but you can run this by yourself:

```js
var clipboard = new Clipboard('[data-clipboard-target]', {
    text: function(trigger) {
        return document.querySelector('#link').innerText.trim();
    }
});
```

See: https://jsfiddle.net/yvx5n5fb/6/
