### ISSUE TITLE
Copying text doesn't work if using text method and a very (very!) long text

### ISSUE THREAD

**Issue by orangecoding** [zenorocha/clipboard.js#442]
### Minimal example

http://jsbin.com/hocakiliru/edit?html,css,js,output

### Expected behaviour

Both methods, either target or text should work.

### Actual behaviour

copying with text attribute doesn't work while target works

### Browsers affected

Chrome, FF, Safari... Doesn't have IE but it's most certainly be broken too.

**Comment by Ruffio** [comment]
Howmany chars are there? I think the limitation is in the browsers, so it can't be fixed/changes. What is the usecase for such long a text to copyright?

**Comment by yobusayo** [comment]
I got this issue either.
When copying a long table (about 3000 rows), it failed.

**Comment by zenorocha** [comment]
Closing since like @Ruffio said this is a limitation in the browsers.
