### ISSUE TITLE
Use in ElementUI popover

### ISSUE THREAD

**Issue by JarRySW** [zenorocha/clipboard.js#443]
### Minimal example

[JSFiddle] https://jsfiddle.net/5kk0eysw/38/

### Expected behaviour

copy text in popover

### Actual behaviour

nothing happened. neither success nor error.

### Browsers affected

can not copy

**Comment by zenorocha** [comment]
Clipboard.js comes with a built-in click event listener, success or error events will only be triggered after a click is made. Check the `demo` folder to understand how the API works in practice.

**Comment by JarRySW** [comment]
Of course, it must click the copy button.
