### ISSUE TITLE
Calling Element's Click Event Only Works In Certain Situations

### ISSUE THREAD

**Issue by ypinskiy** [zenorocha/clipboard.js#445]
### Minimal example
Setup for both:

```
var clipboard = new Clipboard( '.copy-div', {
			text: function ( trigger ) {
				return trigger.dataset.clipboard;
			}
		} );
```

This works fine:

```
notification.onclick = function ( event ) {
	event.preventDefault();
	var div = document.getElementById( somedata.id );
	div.click();
}
```

but if I call

```
var div = document.getElementById( somedata.id );
div.click();
```

in a seperate function, it does not work, calls the onError callback of clipboardjs

### Expected behaviour

The text should be copied.

### Actual behaviour

Throws an error if using onError callback, nothing otherwise

### Browsers affected

Chrome 59 and Firefox Dev Edition 55

**Comment by zenorocha** [comment]
Due to security restrictions imposed by browser vendors, user interaction is required in order copy/cut to work. A simulated click event using JavaScript does not work as this would enable clipboard poisoning.
