### ISSUE TITLE
it is  a good plugin but I wonder why I have to bind to a specific DOM rather than provide API only for freely use

### ISSUE THREAD

**Issue by codewhensleep** [zenorocha/clipboard.js#446]
### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

### Expected behaviour

I thought that by going to the page '...' and pressing the button '...' then '...' would happen.

### Actual behaviour

Instead of '...', what I saw was that '...' happened instead.

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

**Comment by cesarpachon** [comment]
Agree on this. I am working on HTML5 games that only have a root canvas element. I need to fire the clipboard behaviour from a custom callback (that, following the framework chain, by sure will start eventually at some canvas.onClick handler). it would be great if I can fire clipboard.copy(mytext) directly.

**Comment by gengshenghong** [comment]
Agree with @cesarpachon Hope it will be possible to use clipboard.copy freely!!! It is sometimes difficult to create a button (DOM) bind to the clipboard directly....

**Comment by djmattyg007** [comment]
This was asked previously and the request was denied: https://github.com/zenorocha/clipboard.js/issues/329

**Comment by darylteo** [comment]
This library is great for handling the cross browser concerns when it comes to copying. However there are modern situations where a blanket "dom" selector isn't necessary.

 - If you're using a component based front end (i.e. angular, react etc.), you'll be instantiating new Clipboard() for every component each time to attach a dom click event to a button.
 - the component framework you're using will have established patterns for handling user interactions in built. There is no need to throw in another Dom level event listener.
 - even when using a global selector, relying on the presence of a global level event delegator would violate encapsulation of components.

Anyway, just my opinion. We're just ended up writing a function that simply spawns a new ClipboardAction with dummy elements and a noop emitter on a click event, which is still within the bounds of the execCommand security restrictions.

**Comment by zenorocha** [comment]
That's a very important argument @darylteo, thanks for sharing. I created an issue for us to track this new functionality #518.

Let me know what you guys think about it.
