### ISSUE TITLE
Safari Compatibility

### ISSUE THREAD

**Issue by Clebiez** [zenorocha/clipboard.js#448]
Hi, 
your plugin does not work on Safari under 10.
Do you know why and do you know any way to make it work ? For example with a polyfill ?

Good plugin anyway =)

Regards,

**Comment by zenorocha** [comment]
The only fallback is to use Flash. There is a way for you to offer a different behavior on browsers that don't support `document.execCommand('copy')`, we described over here: https://github.com/zenorocha/clipboard.js#browser-support
