### ISSUE TITLE
How to return from two var? 

### ISSUE THREAD

**Issue by agusesetiyono** [zenorocha/clipboard.js#45]
new Clipboard('.btn-copy', {
				    target: function(trigger) {
				    	var a = document.querySelector(".data-order");
				    	var b = document.querySelector("#t");
				        return (a,b);
				    }
				});

I wanna make somehing like above, but return wrong result, can u help?

**Comment by zenorocha** [comment]
Hey @agusesetiyono,

You can't set two targets, it needs to be only one Node. Please share an isolated code on JSFiddle that includes some isolated markup so I can help you better.

**Comment by TimPetricola** [comment]
Looks dirty, but using `text` instead could work:

```js
new Clipboard('.btn-copy', {
  text: function() {
    var v1 = document.querySelector('.data-order').value;
    var v2 = document.querySelector('#t').value;
    return '' + v1 + v2;
  }
});
```

**Comment by zenorocha** [comment]
Yep, that's an alternative. Thanks for sharing @TimPetricola :)

**Comment by agusesetiyono** [comment]
thanks all :)
