### ISSUE TITLE
when the content contains '\n' or '\r' ,how to write the string?

### ISSUE THREAD

**Issue by jerryniepan** [zenorocha/clipboard.js#450]
### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

### Expected behaviour

I thought that by going to the page '...' and pressing the button '...' then '...' would happen.

### Actual behaviour

Instead of '...', what I saw was that '...' happened instead.

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

**Comment by Smile4ever** [comment]
Use a textarea?
<textarea id="foo" type="text" value="hello"></textarea>

**Comment by Ruffio** [comment]
@jerryniepan what is the issue? Can you supply a code sample demonstrating the issue?

**Comment by zenorocha** [comment]
Closing since no information has been provided on how to reproduce it.
