### ISSUE TITLE
Can I skip a column from a row?

### ISSUE THREAD

**Issue by raphaeldiasrj** [zenorocha/clipboard.js#453]
I'm copying a tr element, but I want to skip a td. Is there any "skip" attribute?

**Comment by rsuk** [comment]
I too would like to do this. I'm thinking that I might need to implement a custom version of the standard action that would hide the element before, and show it again after the operation but would appreciate any steer on how to best (i.e. in terms of fitting with the api design) do this kind of customization.

**Comment by Ruffio** [comment]
This is not an issue with the code/project but a question about implementation. Such questions should be asked at stackoverflow. This issue should be closed.

**Comment by flexbox** [comment]
Hello @raphaeldiasrj 
Can you provide an example on https://jsfiddle.net/ ?
OR if your problem is solved please close this issue 😉

**Comment by zenorocha** [comment]
Thanks for helping with the issues @Ruffio and @flexbox!

Closing since it's not part of the scope of the project.
