### ISSUE TITLE
Pass DOM element directly

### ISSUE THREAD

**Issue by GProst** [zenorocha/clipboard.js#454]
Is it possible to pass DOM element to `Clipboard` directly?

In case of ReactJS it would be very handy. For example:

    componentDidMount () {
      this.copyBtn = new Clipboard(this.ref) // where this.ref is a reference to button DOM element
      this.copyBtn.on('success', ...)
      this.copyBtn.on('error', ...)
    }

    componentWillUnmount () {
      this.copyBtn.destroy();
    }

**Comment by mmclau14** [comment]
this is probably an implementation bug. clipboard does support this feature

**Comment by GProst** [comment]
@mmclau14 my apology, it really works. I guess I made something wrong when I first time tried.

But maybe this should be placed in usages example?

**Comment by zenorocha** [comment]
Thanks @mmclau14!

@GProst we already document that you can pass a DOM element and the destroy function. What exactly do you want to be placed in usages?

**Comment by GProst** [comment]
And sorry again, I was reading README superficially, mostly looking on examples. Didn't notice the line when it says that I can use a DOM selector, HTML element, or list of HTML elements.

**Comment by zenorocha** [comment]
No problem at all ;)
