### ISSUE TITLE
Problem to copy an invisible input value

### ISSUE THREAD

**Issue by alexandrebfaust** [zenorocha/clipboard.js#456]
I've been trying to copy an input value, but I am not being able to. Did somebody try it
before and it was successful?
Here are the models that I attempted on, I used boostrap's class on some of them to hide the input value. 

https://jsfiddle.net/phksjxz3/3/
https://jsfiddle.net/zenorocha/msg9tr7f/

-----------

Estou tentando de diversas formas copiar o valor de um input, porém não estou conseguindo
alguém já tentou anteriormente e conseguiu?
Segue modelos que tentei... alguns utilizei class do bootstrap para esconder a input

https://jsfiddle.net/phksjxz3/3/
https://jsfiddle.net/zenorocha/msg9tr7f/

**Comment by alexandrebfaust** [comment]
Encontrei uma solução.
Usando style="z-index: -9999;", para mover a input para trás do painel
----------------
I found a solution.
Using style = "z-index: -9999;", to move the input to the back of the panel

**Comment by Ruffio** [comment]
@alexandrebfaust if the issue has been resolved, then please close it. Thanks.
