### ISSUE TITLE
Can you include the 'clipboard-rails' Rails gem for clipboard.js

### ISSUE THREAD

**Issue by sadiqmmm** [zenorocha/clipboard.js#46]
Can you include the 'clipboard-rails' Rails gem for clipboard.js in README.md

https://github.com/sadiqmmm/clipboard-rails

https://rubygems.org/gems/clipboard-rails

**Comment by zenorocha** [comment]
That's awesome! :tada: 

I've just included in the [wiki page](https://github.com/zenorocha/clipboard.js/wiki)

**Comment by zenorocha** [comment]
Here's a crazy idea @sadiqmmm, I noticed that the rubygems site itself uses zeroclipboard.

<img width="359" alt="screen shot 2015-10-01 at 7 35 52 am" src="https://cloud.githubusercontent.com/assets/398893/10223680/1e79401a-680f-11e5-81d4-09b6e536f18e.png">

What do you think of sending them a PR to use clipboard.js instead?

https://github.com/rubygems/rubygems.org
