### ISSUE TITLE
1.7.1 Clipboard.js is not working in firefox 38.6.0, but working fine in Chrome

### ISSUE THREAD

**Issue by raghala** [zenorocha/clipboard.js#461]
We are using clipboard.js 1.7.1 version. but it is not working in firefox browser.

**Comment by raghala** [comment]
@zenorocha Please

**Comment by joshuaptfan** [comment]
clipboard.js [only lists support for Firefox 41+](https://github.com/zenorocha/clipboard.js#browser-support), While document.execCommand is widely supported, [copy/cut was not enabled by default until that version of Firefox.](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#Browser_compatibility)

You can catch the error and prompt the user to manually copy.

Do you expect a significant portion of your users to be using such an old version of Firefox?

**Comment by Ruffio** [comment]
Is current version 55? If so version 41 seams ancient and we must expect users to be using a newer version than that. IMHO this issue should be closed.
