### ISSUE TITLE
Unfortunately v1.7.1 doesn't work on iphone / ipad safari

### ISSUE THREAD

**Issue by redjersey** [zenorocha/clipboard.js#462]
I used my iphone to browse clipboardjs.com and played with the demos, unfortunately it doesn't work. Nothing is copied / cut.

**Comment by aviatix** [comment]
Experiences the same thing with iOS on iPad. Any plans, that this will be included in this library?

**Comment by Ruffio** [comment]
Personally I have no issues with this in iOS 10.3.3 Safari browser. Could it be your implementation?
