### ISSUE TITLE
clipboard did not run for the first click . It only runs with double click in the first times

### ISSUE THREAD

**Issue by toolaugh** [zenorocha/clipboard.js#463]
### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

### Expected behaviour

I thought that by going to the page '...' and pressing the button '...' then '...' would happen.

### Actual behaviour

Instead of '...', what I saw was that '...' happened instead.

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

**Comment by tprupsys** [comment]
same here

**Comment by Ruffio** [comment]
What is the issue? I can't reproduce your issue with your JSFiddler provided...

**Comment by flexbox** [comment]
Hello @toolaugh 
Any update on this?
If the problem is solved you can close the issue 😉

**Comment by springxiege** [comment]
I have the same problem , have you resolved it ?

**Comment by Ruffio** [comment]
@toolaugh what is th issue here? Can you provide an example in JSBin or similar? Else please close this issue.

**Comment by zenorocha** [comment]
Closing since an example has not been provided.
