### ISSUE TITLE
clipboardjs with reactjs 

### ISSUE THREAD

**Issue by toolaugh** [zenorocha/clipboard.js#465]
I use advance usages of clipboardjs.
 `const clipboard = new ClipBoard('.btnCopy', {
            text: () => this.props.value,
              });
        clipboard.on('success', (e) => {
            if (this.targetCopyBtn) {
                this.setState({
                    isCopied: true,
                });
            }
            console.info('text', e.text);
            e.clearSelection();
        });`
when i Click button 'btnCopy' it run clipboard.success with 'text' value . But when I paste value to some where it is null

**Comment by designbyadrian** [comment]
In which component are you creating the clipboard instance?

What do you get if you log `e` to console on success?

**Comment by toolaugh** [comment]
thank @designbyadrian  
- I create clipboard instance in ditmount
- the result  of conslog is the value the text value which is copied 
- this.props.value is which I pass from other component.
===> But the problem is I using clipboboard with modal of bootstrap . I missed use 'container params' when creating instance of clipboard.
