### ISSUE TITLE
javascript copy to clipboard readonly

### ISSUE THREAD

**Issue by barbiot** [zenorocha/clipboard.js#469]
I need copy to clipboard after press <button onClick="quotes()">Click Here</button>, how can I
copy value inside textbox on this code below?

<script language="javascript">
function quotes(){

var aquote = new Array;
aquote[0] = "rQzKyUaeRpHGnjTDi5HgRLaWXZ"
aquote[1] = "ABJbbEsoSUAtURFRg8rEwLyj7y"
aquote[2] = "ucGZZLcf8S52vV4jyee1zE46B8"
aquote[3] = "AuvmCrxZpxcHBFHXzc5gYywNCR"
aquote[4] = "BgjgAb221SgP85Gr2SNyP2uiss"
aquote[5] = "Ac4xNgaTkLXLdWDea2kAZt2xma"

rdmQuote = Math.floor(Math.random()*aquote.length);
document.getElementById("txtbox") .value=aquote[rdmQuote];
}

</script>
<textarea id="txtbox" style="width:600px;" readonly></textarea>
<script>
var copyCodeBtn = document.querySelector('#js-emailcopybtn');

copyCodeBtn.addEventListener('click', function(event)
{
    // Select the email link anchor text  
    var emailLink = document.querySelector('#code-to-copy');
    var range = document.createRange();
    range.selectNode(emailLink);
    window.getSelection().addRange(range);
    
    try
    {
        // Now that we've selected the anchor text, execute the copy command
        var successful = document.execCommand('copy');
        var msg = successful ? 'successful' : 'unsuccessful';
        console.log('Copy email command was ' + msg);
    } 
    catch (err)
    {
        console.log('Oops, unable to copy');
    }

    // Remove the selections - NOTE: Should use
    // removeRange(range) when it is supported
    window.getSelection().removeAllRanges();
});

</script>
<button class="copyBtn" data-clipboard-target="#myTextArea">Copy</button>
<button onClick="quotes()">Click Here</button>

<script language="JavaScript">document.addEventListener("contextmenu", function(e){
    e.preventDefault();
}, false);</script>

**Comment by Ruffio** [comment]
As this is not an issue but a question about implementation, this should be closed. Implementation questions should be asked at stackoverflow or simular site...

**Comment by zenorocha** [comment]
Thanks @Ruffio!
