### ISSUE TITLE
Anyone get Clipboard.js working with Slick.js?

### ISSUE THREAD

**Issue by EKerrigan** [zenorocha/clipboard.js#477]
I've got Clipboard (with Prism) working beautifully- unless I drop it into a Slick.js slider. It still reads as a 'success', it logs trigger.previousElementSibling correctly, there are no errors-  but it doesn't actually copy.  I'm guessing  this is maybe a focus/container issue, but the log tells me that body is the active element on load, so maybe not.  Has anyone else hit this issue? If I pull the element out of the slider (in the same project) it works like a charm.

**Comment by zenorocha** [comment]
Hey @EKerrigan,

I never used Slick.js but I suspect this is related to the focus as well. 

The good news is that you can change the focus you'll want to set the focused element as the container value.

```
new Clipboard('.btn', {
    container: document.getElementById('modal')
});
```
