### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by 1der1** [zenorocha/clipboard.js#480]
### Minimal example

var clipboard = new Clipboard('.btn');

### Expected behaviour

This line from the docs is supposed to create a Clipboard object.

### Actual behaviour

causes Uncaught SyntaxError: Unexpected identifier

### Browsers affected

Chrome

**Comment by j-snow** [comment]
Same in firefox, tried:
`var clipboard = new Clipboard('.snippet-button');`
and the first advanced example
```
var clipboard = new Clipboard('.snippet-button', {
    target: function(trigger) {
        return trigger.nextElementSibling;
    }
});
```
Get:
>  TypeError: element is null

**Comment by zenorocha** [comment]
Everything works fine, check this list of demos for working examples: https://github.com/zenorocha/clipboard.js/tree/master/demo
