### ISSUE TITLE
basic functionality missing

### ISSUE THREAD

**Issue by 1der1** [zenorocha/clipboard.js#481]
It looks like clipboard,js works with element binding only.
I am missing a basic string to clipboard functionality.

I know that there has to be an event involved:

1) User clicks button
2) Program gets the string from an element
3) Program processes string
4) The string is copied to clipboard. <--- There is no function for this

This would all be in the event context.

**Comment by zenorocha** [comment]
Due to security restrictions imposed by browser vendors, user interaction is required in order copy/cut to work. That's why it's not possible to have a basic function to copy.
