### ISSUE TITLE
Copying does not work when used in Angularjs

### ISSUE THREAD

**Issue by jdkleo** [zenorocha/clipboard.js#483]
chrome 61 
firefox 56
--------------
when i use debug in 
text: function(trigger) {
       debug: return "...";
    }
and wait for 10+ sec then
debug in 
clipboard.on('success', function(e) {
 debug:   console.info('Action:', e.action);
    console.info('Text:', e.text);
    console.info('Trigger:', e.trigger);

    e.clearSelection();
});

it's ok.
when remove debug tag,it's not ok,but console output e.text is right!

**Comment by zenorocha** [comment]
There's nothing that prevents this library to work with Angular. Please review your implementation or consider clipboard.js wrappers like https://github.com/maxisam/ngx-clipboard. Thanks!
