### ISSUE TITLE
Fail to include clipboard as module when using requirejs's optimizer namespace rename

### ISSUE THREAD

**Issue by kontur** [zenorocha/clipboard.js#485]
The requirejs optimizer has an option to [namespace any require method calls](http://requirejs.org/docs/faq-advanced.html#rename) (require, module, define) to protect against scenarios where you cannot control the possible presence of a second requirejs, which would collide.

What the `namespace` option does is essentially prefix all `require` and `define` calls. Although it does go through all included module's code to replace those, somehow the dist code of clipboard fails to pass through and clipboard ends up undefined.

Now, my guess is this has to do with how clipboard is transpiled, but to be perfectly honest this goes somewhat above my head. Of about 20 or so included libraries in my project this is the only that fails when the requirejs optimizer namespaces those calls. Any ideas where to look or what could cause it?

**Comment by zenorocha** [comment]
Hey @kontur, I've never seen this problem before as well, but I'm open for pull requests if needed. Thanks!
