### ISSUE TITLE
How to copy a text directly?

### ISSUE THREAD

**Issue by KuoKongQingYun** [zenorocha/clipboard.js#489]
I want to copy a text directly,which is generated in javascript.
so how to do that?

**Comment by nyuszika7h** [comment]
It's not possible to change the contents of the clipboard without a user-initiated action, if that's what you mean.

**Comment by JounQin** [comment]
[clipboard-polyfill](https://github.com/lgarron/clipboard-polyfill) works.

**Comment by KuoKongQingYun** [comment]
@JounQin thank you for your suggestion!

**Comment by zenorocha** [comment]
Hey guys, I added a proposal for this feature. Can you check #518?

Thanks!

**Comment by KuoKongQingYun** [comment]
@zenorocha thank you!
