### ISSUE TITLE
Please update npm package

### ISSUE THREAD

**Issue by vsn4ik** [zenorocha/clipboard.js#49]

**Comment by JoshSpears3** [comment]
Fixed this issue. See pull request https://github.com/zenorocha/clipboard.js/pull/50.

**Comment by vsn4ik** [comment]
Dont fixed. See: https://www.npmjs.com/package/clipboard.

**Comment by JoshSpears3** [comment]
@vsn4ik Oh. I misunderstood your request. I thought you were having problems updating the npm packages FOR clipboard.js. Not the actual package itself.

**Comment by zenorocha** [comment]
Thanks for reporting @vsn4ik! Published!

**Comment by vsn4ik** [comment]
Thanks!
