### ISSUE TITLE
Copy clip not working for large data

### ISSUE THREAD

**Issue by jaichaturvedi88** [zenorocha/clipboard.js#490]
Hi!  I am getting strange issue. When I try to copy data to clipboard

`<button id="dummy" class="btn123" data-clipboard-text="asdf">Copy</button>`

`<script>
	$(document).ready(function(){
		var textToSet = ""
		for(var i=1; i<= 20000; i++)
		{
			textToSet +="some dummy text" + "\n";
		}
		
		$( "#dummy" ).attr("data-clipboard-text", textToSet);
		
		try{
			
			var clipboard = new Clipboard(".btn123", {
				text: function() {
					console.log("text copying");
					//alert("sdf");
					
					return textToSet;
				}
			});
		}
		catch(e){
			console.log(e.message);
		}
	});
    
    </script>`

[CopyClip.zip](https://github.com/zenorocha/clipboard.js/files/1407489/CopyClip.zip)

If we uncomment the alert it will work or else it is not working. I am not getting the reason why it is happening like this.
I have attached the files also.

**Comment by aPinix** [comment]
I want to copy a **base64 converted code from an image**, the string is indeed large and **clipboard.js** doesn't work with **large strings**.

**Comment by deniqwe** [comment]
Do anybody have a solution? A lot of clipboard plugins don't copy large text.

**Comment by shay-dw** [comment]
Same here :(

**Comment by Ruffio** [comment]
It could be limitations in the different browsers that are hit by this issue. I would be nice if someone could test the major browsers, so we could get a list of limitations in the readme file...

**Comment by ivu4e** [comment]
I want to copy a part of large data, but split data use time too long.
Can register an error handler, but can't know why.
```
	clipboard.on('error', function(e) {
	    //console.error('Action:', e.action);
	    //console.error('Trigger:', e.trigger);
	});
```

**Comment by zenorocha** [comment]
Unfortunately this is a browser security limitation and there's nothing we can do about it.

**Comment by milrak** [comment]
@zenorocha i'm using linux tls 18.04 it works. more windows not working.
Was it really a browser limitation?

Example
https://jsfiddle.net/milrak/sb3tr1nh/6/
