### ISSUE TITLE
Adding Promise support to text option?

### ISSUE THREAD

**Issue by ClementParis016** [zenorocha/clipboard.js#492]
Considering a reasonable amount of people want to perform asynchronous operations before a clipboard action, I think adding Promise support to the `text` option would be nice.

For example, you may want to call an API when clicking a button and use its response data as the value to be copied.

As far as I could explore the code, it doesn't seem to be such a big change to allow both a function or a promise to be passed as an argument.

What do you think @zenorocha ? I could start working on a PR if that feels right.

**Comment by zenorocha** [comment]
Hey @ClementParis016,

I'm open to this change. Here's a proposal for it #516 #517. Let me know what you think and if you're able to help.

Thanks for the suggestion!
