### ISSUE TITLE
Copy clip not working first click for async load clipboard.js

### ISSUE THREAD

**Issue by lolipop99** [zenorocha/clipboard.js#493]
### Minimal example

```javascript
$.getScript('https://github.com/zenorocha/clipboard.js', function(){
  let clipboard = new Clipboard('.btn', {
    text: function () {
             return 'asdfasdf';
    }
  });
                    
  clipboard.on('success', function(){

  });          
})
```
### Describe
Copy clip not working first time for async load clipboard.js

### Browsers affected

I tested on all major browsers and all does not work.

**Comment by NinjaJin** [comment]
I have this problem too, on mobile browser. Have you solved it?

**Comment by JSosaRDZ** [comment]
@lolipop99 Are you sing this as part of a webcomponent? Is there HTML associated with this function? If so, could you include the rest of the HTML code?

**Comment by homura** [comment]
Since browser security, document.execCommand('copy') must be triggered by user
I recommend you do it in this way
https://codepen.io/anon/pen/pdaqaK
