### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by jt4000** [zenorocha/clipboard.js#495]
"Tooltips

Each application has different design needs, that's why clipboard.js does not include any CSS or built-in tooltip solution.

The tooltips you see on this demo site were built using GitHub's Primer. You may want to check that out if you're looking for a similar look and feel."

The link doesn't work, is there another approach to use a tooltip when you have pressed the button?

Thank you!

**Comment by zenorocha** [comment]
Fixed on #479. Thanks @jt4000!

**Comment by suxiaogang** [comment]
not working with bootstrap 3.3.7 
https://stackoverflow.com/questions/37381640/tooltips-highlight-animation-with-clipboard-js-click/37395225
