### ISSUE TITLE
Not working on this page https://y.qq.com/portal/player.html but worked before.

### ISSUE THREAD

**Issue by pendave** [zenorocha/clipboard.js#496]
Hi, I write a Greasymonkey userscript with clipboard.js for click copy the text content I need on this page
https://y.qq.com/portal/player.html but now it's not working as before.

I wondering why, is it due to the site's js priority？

**Comment by zenorocha** [comment]
Hey @pendave, unfortunately there's absolutely no way for me to debug this. I would recommend checking with Greasymonkey.
