### ISSUE TITLE
IE continuously ask for clipboard permission

### ISSUE THREAD

**Issue by mu-yu** [zenorocha/clipboard.js#499]
### Minimal example

https://clipboardjs.com/

### Expected behaviour
Emit error event after disallowed access to use clipboard in IE.

### Actual behaviour

After disallowing access to use the clipboard in IE, the success will be emitted, but the copy *FAILED* with nothing copyed

### Browsers affected

IE

**Comment by renanlecaro** [comment]
Same here with IE10 : i get a succes callback when the copy failed, and a failure when the copy succeeded . Works fine on chrome, firefox and safari

**Comment by zenorocha** [comment]
Yes, that's a known issue: https://github.com/zenorocha/clipboard.js/wiki/Known-Issues

Unfortunately there's nothing we can do about it. It's a problem on IE10 and not clipboard.js.
