### ISSUE TITLE
Consider rename the data attributes actions

### ISSUE THREAD

**Issue by mauriciosoares** [zenorocha/clipboard.js#5]
Hello Zeno, nice project :)

This issue is for you to consider renaming the configuration data-attributes for something like `data-clipboard-action` instead of `data-action`.

The reason,

In my project (for example) I already use a lot the attribute `data-action`, this is too generic and most likely to be used by other developers as well, this may conflict with your library.

What you think?

**Comment by zenorocha** [comment]
Hey @mauriciosoares,

That's a good point, could you send a PR?

**Comment by mauriciosoares** [comment]
PR created, and tests passing.

You may need to update the GH pages, (or should I update it as well?)

:)

**Comment by zenorocha** [comment]
You can send a PR to gh-pages as well, thanks @mauriciosoares!

**Comment by mauriciosoares** [comment]
there you go

https://github.com/zenorocha/clipboard.js/pull/8

**Comment by mauriciosoares** [comment]
Closing this issue as branches are already merged.

Thanks @zenorocha

**Comment by zenorocha** [comment]
Thanks @mauriciosoares! I released a minor version with that. Although it breaks semver it's better to break now for 5 people than 100 next week

**Comment by mauriciosoares** [comment]
Agreed.

**Comment by paulirish** [comment]
makes the html5 spec happy too.

![image](https://cloud.githubusercontent.com/assets/39191/10150451/619a40d2-65f4-11e5-923b-38a28066157a.png)

**Comment by mauriciosoares** [comment]
😬

**Comment by zenorocha** [comment]
:+1:
