### ISSUE TITLE
Suggest using Subresource Integrity for 3rd CDN to wiki

### ISSUE THREAD

**Issue by Thunder33345** [zenorocha/clipboard.js#509]
It has been slight talked at #53 but never brought up again
Info about [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)
it's parthly supported according to [caniuse.com](https://caniuse.com/#feat=subresource-integrity)
I dont see what issues it could cause by adding that, the SRI "integrity" tag can be generated and added by maintainer, or ask user to generate it themself using websites like https://www.srihash.org/

**Comment by zenorocha** [comment]
Hey @Thunder33345,

Unfortunately this is something I don't have time to work on right now. Thanks for sharing your ideas though!
