### ISSUE TITLE
The content is selected on clicking a copy button.

### ISSUE THREAD

**Issue by HemanthGowda** [zenorocha/clipboard.js#512]
> Refer [JSFiddle](https://jsfiddle.net/qrjgb1Lv/) to reproduce issue.

### Expected behaviour

On clicking a copy button should just copy instead of selecting a content.

### Actual behaviour

On clicking a copy button the content is copied and also selected. (observe content)

### Browsers affected

I tested on Chrome 63. MacOS High sierra.

**Comment by zenorocha** [comment]
Hey @HemanthGowda, thanks for reporting.

I wasn't able to reproduce this problem, see GIF below:

![non](https://user-images.githubusercontent.com/398893/35291028-e72ed87a-0020-11e8-9531-1965be1db95a.gif)

**Comment by JeremyTCD** [comment]
Clipboard has to select the text to copy it. To deselect after copying (so the text isn't highlighted), just call `clearSelection()` in the success callback.

```           
let clipboard = new Clipboard(buttonElement);
clipboard.on('success', (event: Clipboard.Event) => {
    event.clearSelection();
});
```
