### ISSUE TITLE
How auto copy?

### ISSUE THREAD

**Issue by websterguo** [zenorocha/clipboard.js#513]
### Minimal example
var clipboard = new Clipboard('body', {
        text: function() {
            return 'copy data';
        }
    });
var e = document.createEvent("MouseEvents");
e.initEvent("click", false, true);
document.body.dispatchEvent(e);
> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

### Expected behaviour

I thought that by going to the page '...' and pressing the button '...' then '...' would happen.

### Actual behaviour

Instead of '...', what I saw was that '...' happened instead.

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

**Comment by zenorocha** [comment]
Due to security restrictions imposed by browser vendors, user interaction is required in order copy/cut to work. A simulated click event using JavaScript does not work as this would enable clipboard poisoning.

**Comment by JamoCA** [comment]
I was hoping to do it solely using this plugin too, but I figured out how to do with using vanilla javascript.  The following code sample will copy text from the `#myTextAreaToCopy` textarea element, attempt to write it to  hidden `#myTextAreaToCopy` div and then output whether it was successful or not to the console.log.  (This works for me using Microsoft Edge Dev v105.)

```html
<script>
function autoCopyToClipboard(){
	console.log("init autoCopyToClipboard", new Date);
	document.execCommand("copy");
	var text = document.getElementById("myTextAreaToCopy").value;
	var output = document.getElementById("AHiddenDivToTestCopy");
	navigator.clipboard.writeText(text).then(function(){
		console.log('Copied to clipboard!', new Date);
	}, function(){
		console.log('Unable to copied to clipboard!', new Date);
	});
}
window.addEventListener("DOMContentLoaded", autoCopyToClipboard, false);
</script>

<button type="button" onclick="autoCopyToClipboard()">Manual Copy</button>
<textarea id="myTextAreaToCopy">This is a test text.</textarea>

<div id="AHiddenDivToTestCopy" style="display:none;"></div>
```
