### ISSUE TITLE
Clipboard triggers success event but cant paste content

### ISSUE THREAD

**Issue by cbenitez101** [zenorocha/clipboard.js#514]
Hi guys,
I have the next code on my website

https://jsfiddle.net/49kmqwxm/

When clicking on the button I want to copy to the clipboard some Mikrotik configuration code.

It seems to trigger the success event, but whem I try to paste the content, I realize that there is no new content copied.

What am I doing wrong?
 Thanks in advance!!

EDIT:
Sorry, I forgot to say that I tried doing it in different ways, using the data-clipboard-target="#SomeID" and data-clipboard-text="SomeText" with the same result.
Thanks again!
  
EDIT2:
Forgot to mention that if I copy the same code to another project for example using xampp it works. I think the problem is in my server but cant get to it. Itworked for a time but suddenly stopped copying.

**Comment by cbenitez101** [comment]
Sorry, I forgot to say that I tried doing it in different ways, using de data-clipboard-target="#SomeID" and  data-clipboard-text="SomeText" with the same result.
Thanks again!

**Comment by MrDarkest** [comment]
I had the same problem with a div loaded with AJAX (with no AJAX load no problem). I was able to fix this with a little change in the library code.
I added "this.fakeElem.focus()" in selectFake() right before "this.copyText()" according with this stackoverflow post: https://stackoverflow.com/questions/43380921/document-execcommand-copy-not-working-with-ajax

**Comment by cbenitez101** [comment]
Thank you so much. I was loosing my head with this issue. It worked perfectly!
I'd invite you a beer, but you only have to come to Gran Canaria jeje.
Thanks again.

**Comment by MrDarkest** [comment]
@zenorocha can you add this fix in master project? I'd like to include in my site the minified version again instead the actual modified (and not minified) version of your library.
Thanks.

**Comment by baris22** [comment]
When I add this.fakeElem.focus(); it looses the indentation of the codes when I paste it. I have the same problem as MrDarkest. I display the page using AJAX.

**Comment by baris22** [comment]
Passing the bootstrap modal id solved my problem.
var clipboard = new Clipboard('.copy-button', {
	container: document.getElementById('rep')
});

**Comment by Ruffio** [comment]
Has this been resolved?

**Comment by RPSPandora** [comment]
> Passing the bootstrap modal id solved my problem.
var clipboard = new Clipboard('.copy-button', {
container: document.getElementById('rep')
});

this works. thanks!!

**Comment by SmileLxy** [comment]
Thank you so much. @MrDarkest

**Comment by Ruffio** [comment]
@cb Has this been resolved?

**Comment by cbenitez101** [comment]
Yep, in my case this has been resolved, so I close the thread.
Thank's a lot for the responses!

**Comment by phuong17889** [comment]
> Passing the bootstrap modal id solved my problem.
> var clipboard = new Clipboard('.copy-button', {
> container: document.getElementById('rep')
> });

work like charm
