### ISSUE TITLE
TypeError: Illegal constructor Error on Chrome version greater that 62

### ISSUE THREAD

**Issue by rishabhfitkids** [zenorocha/clipboard.js#515]
Calling new Clipboard(".selector") throws this error.

Chrome added native Clipboard api which conflicts with the library.

**Comment by rishabhfitkids** [comment]
<img width="1429" alt="screen shot 2018-01-23 at 5 47 25 pm" src="https://user-images.githubusercontent.com/22075327/35275368-829543fa-0065-11e8-8af4-97a392ef028f.png">

**Comment by zenorocha** [comment]
Thanks for reporting @rishabhfitkids.

Closing since it's duplicated from #468
