### ISSUE TITLE
Clipboard.js 3.0

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/clipboard.js#516]
Hello everybody!

I'm starting to think about Clipboard.js 3.0, here's what I'm envisioning:

* Promise-based (which will drop support for IE) #517
* DOM-independent (which will be more Angular/React/Vue friendly) #518

What do you think?

**Comment by josefanostylus** [comment]
What's the status on the "DOM-independent copy/cut API" ?

**Comment by stjava** [comment]
I want to ask the same question.

**Comment by stjava** [comment]
I want to ask the same question.

**Comment by spieglio** [comment]
I like the two proposed ideas. Especially the DOOM-Independent functionality would make the library more useful in even more cases and chainable to other user interaction.

My example: click button => change text in textarea => copy to clipboard. This would be possible all in one go (does not seem to be possible at the moment).

Looking forward to v3.0!

**Comment by foreverpinetree** [comment]
I am just wonding what's the difference between the native [clicpboard API](https://developer.mozilla.org/en-US/docs/Web/Events/copy) and this plugin?

**Comment by stof** [comment]
this v3 looks like a polyfill for the native API :smile:

**Comment by JanOonk** [comment]
Please support rich text copy text/html besides text/plain.
