### ISSUE TITLE
Add DOM-independent copy/cut API

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/clipboard.js#518]
> Part II of a new major release proposal #516

*Current state*

```js
new Clipboard('.btn', {
    text: function(trigger) {
        return 'blah blah';
    }
});
```

*Proposal*

```js
button.addEventListener('click', () => {
    clipboard.copy('blah blah')
})
```

*Benefits*

Today a click event listener is created inside the library in order to facilitate usage. The problem is that attaching an event to the DOM might not be a good idea when using Angular, React, Vue, etc

The benefits of this approach is that users can call a copy/cut function independently inside their own event listeners.

*Drawbacks*

Users will need to know that an event listener is necessary, otherwise it will not work.

*Related*

#203 #218 #231 #258 #329 #389 #446 #466 #489 #498 #474

**Comment by deejay-baddog** [comment]
got it. thank you very much.

**Comment by hoangmngo** [comment]
I think the drawback is not a big problem since we can mention this in the documentation. The huge DOM-independent advantage outweighs this.

**Comment by zenorocha** [comment]
@hoangmngo error handling is being mentioned here #517

**Comment by danielravina** [comment]
> Users will need to know that an event listener is necessary, otherwise it will not work.

That's why we have a Readme 😃

**Comment by yuri-wisestamp** [comment]
So there's no way to do it at the moment?

**Comment by zenorocha** [comment]
There is a way, but browser support is very limited.

https://caniuse.com/#search=clipboard

I'm tracking the status of the implementation as soon as it lands on other major browsers, I'll update the library to address this use case.

**Comment by TheGr8Nik** [comment]
It seems that all the major browsers allow triggering copy events inside a event handler, but not paste events.

https://jsbin.com/huhekiqope/1/edit?html,js,console,output

Click on `Copy` button will correctly copy the data in clipboard, while click on `Paste` will not trigger paste event. Using `Ctrl+v` will trigger the event correctly.

**Comment by RobertAKARobin** [comment]
Can't you just expose `ClipboardAction` for importing and let users do it themselves?
