### ISSUE TITLE
Uncaught TypeError: First argument must be a String, HTMLElement, HTMLCollection, or NodeList

### ISSUE THREAD

**Issue by OtoNoOto** [zenorocha/clipboard.js#519]
Receiving the following error:

clipboard.min.js:7 Uncaught TypeError: First argument must be a String, HTMLElement, HTMLCollection, or NodeList
    at o (VM96 clipboard.min.js:7)
    at e.t (VM96 clipboard.min.js:7)
    at new e (VM96 clipboard.min.js:7)
    at window.onload ((index):47)

See jsFiddle to reproduce issue:

https://jsfiddle.net/cz5oLjmy/

**Comment by Ruffio** [comment]
Your btn is null because of wrong ID in getElementById. Remove # ...

**Comment by Ruffio** [comment]
This issue can be closed. jQuery syntax used in vanilla js...

No response from originator in a month.

**Comment by zenorocha** [comment]
Thanks @Ruffio <3

**Comment by tenadolanter** [comment]
if you click on svg , add style to svg like this : `pointer-events: none;` then the error gone !
