### ISSUE TITLE
Plug-in elements to prevent bubbling failure, I hope the author can fix this problem, thank you.

### ISSUE THREAD

**Issue by lvleihere** [zenorocha/clipboard.js#520]
### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

### Expected behaviour

I thought that by going to the page '...' and pressing the button '...' then '...' would happen.

### Actual behaviour

Instead of '...', what I saw was that '...' happened instead.

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

**Comment by lvleihere** [comment]
Plug-in elements to prevent bubbling failure, I hope the author can fix this problem, thank you.

**Comment by Ruffio** [comment]
What is the issue? Please provide a simple sample.

**Comment by zenorocha** [comment]
Closing since no information has been provided on how to reproduce it.
