### ISSUE TITLE
Question: Trigger copy from JavaScript

### ISSUE THREAD

**Issue by woodyrew** [zenorocha/clipboard.js#521]
Is there an API to trigger Clipboard.js to copy?
### Minimal example

> See this [JSFiddle](https://jsfiddle.net/y0sd8407/2/) to reproduce.

### Expected behaviour

When 'k' is pressed and `$('#foo').click()` is called, expected Clipboard.js to copy href, this happens correctly when clicking the link with the mouse.

### Actual behaviour

Instead of the `success` or `error` handlers, nothing gets triggered.

### Browsers affected

I tested on chrome but it's not a browser issue.

Thanks in advance.

**Comment by fatbattk** [comment]
Nope. See, https://github.com/zenorocha/clipboard.js/issues/270#issuecomment-228770685
