### ISSUE TITLE
maybe not compatible

### ISSUE THREAD

**Issue by tuhongwei** [zenorocha/clipboard.js#524]
When I copy in mobile qq(Chinese communicate software), the copy can't success. but 'success' event can trigger. Then I try to open "https://clipboardjs.com/" in my mobile qq, the "copy button" makes no effect, but the "copy button" with icon can work. It makes me confused vary much.Why?

**Comment by zenorocha** [comment]
Please provide a JSFiddle that reproduces this problem, otherwise it's impossible for me to debug. Thanks!
