### ISSUE TITLE
clipboard.js not working in php scripts (except index.php)

### ISSUE THREAD

**Issue by ademcan** [zenorocha/clipboard.js#525]
### Expected behaviour

I am using the "standard" protocol to copy some text to the clipboard on a php script as follow:
<button style="background-color:transparent; border-color:transparent;" class="btn" id="btn" data-clipboard-text="'.$code.'"><img src="images/copy.png" style="height:25px;" alt="Copy to clipboard"></button>
This works work well on the index.php page. However, the exact same code does not work when I redirect to another php file, although clipboard.js is correctly loaded.

### Actual behaviour

The code above does not work, nothing is copied to the clipboard in other php scripts (except index.php)

### Browsers affected

I tested on Firefox 59 and Safari 10.1.2 and could reproduce the same issue!

**Comment by ademcan** [comment]
I know, I just wanted to point out that the error occurs on my php project.

**Comment by zenorocha** [comment]
As @greedying pointed out, this is a client-side library and the server-side language you use shouldn't affect how it works. Please check your code base. Thanks!
