### ISSUE TITLE
Can't copy from Vue

### ISSUE THREAD

**Issue by carlosgomez2** [zenorocha/clipboard.js#527]
### Minimal example

> https://codepen.io/rasalghul/pen/OQOVor

### Expected behaviour

When input has text, show 'p' tag with the text from the input 'Author'. then you should able to copy the text from inside 'p' tag to clipboard with the button.

### Actual behaviour

 If I click on copy button, nothing is copied

### Browsers affected

Not working on: Firefox 508.0.1, Chrome 64.0.3282.140

**Comment by Ruffio** [comment]
Do you actually load the clipboard.js? I can't see where you load it...

**Comment by frodopwns** [comment]
ClipboardJS does not work in current release of Chrome for me. It only works in Safari in my experience.

**Comment by frodopwns** [comment]
I think this is actually just the VueJS implementation that is floating around the internet. I got this to work fine in Chrome in a JSFiddle.

**Comment by zenorocha** [comment]
Thanks for the info @frodopwns, in that case, I'm closing this issue.
