### ISSUE TITLE
Add to CDN for easy deployment on production environments

### ISSUE THREAD

**Issue by holtkamp** [zenorocha/clipboard.js#53]
First of all, compliments for the library!

To deploy it on a production environment, hosting on a CDN would be nice. 
For the time being [RawGit](www.rawgit.com) suits fine, this converts a github URL to a CDN like approach:
https://cdn.rawgit.com/zenorocha/clipboard.js/v1.3.1/dist/clipboard.min.js

But maybe you can consider registering it at something like www.cdnjs.com?

**Comment by zenorocha** [comment]
Hey @holtkamp,

Thanks for the suggestion. Could you register it on cdnjs.com?

Related to #30

**Comment by holtkamp** [comment]
Apparently @AuspeXeu already submitted such request: https://github.com/cdnjs/cdnjs/issues/5800, a Pull Request will be processed faster, but also requires some effort, the part about auto-updating is new for me...

**Comment by zenorocha** [comment]
Cool, I need to work on other clipboard.js issues right now so can you send that PR?

**Comment by holtkamp** [comment]
Will give it a shot coming week :+1:

**Comment by gjmveloso** [comment]
It's done and working. [Website UI still needs to be refreshed](http://www.jsdelivr.com/?query=clipboard.js) but we can access the latest version from https://cdn.jsdelivr.net/clipboard.js/latest/clipboard.min.js

**Comment by holtkamp** [comment]
Seems to be added to [cdnjs.com](https://cdnjs.com/libraries/clipboard.js) as well, kudos to @PeterDaveHello

https://github.com/cdnjs/cdnjs/commit/7a610ca5dbaf176aab590e90c0ac1d9ef5a42d02

@zenorocha, you might want to update the [documentation part that suggests using a CDN](https://github.com/zenorocha/clipboard.js/blame/master/readme.md#L39-L44) since [RawGit does not provide any uptime guarantee](https://rawgit.com/faq#no-uptime-guarantee) . [CDNJS](https://cdnjs.com/about) has some serious sponsors backing them.

**Comment by PeterDaveHello** [comment]
And we will support the SRI feature soon for more secure service.

**Comment by holtkamp** [comment]
For the no-knows: SRI: 

- http://www.w3.org/TR/SRI/
- https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/
