### ISSUE TITLE
Migrate to Webpack 4

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/clipboard.js#530]

**Comment by zooks** [comment]
I'm using Webpack and after upgrade got these errors:
`TypeError: Cannot read property 'compilation' of undefined`

In Firefox:
`Clipboard is not defined`
for Clipboard 2.0. Clipboard 1.7.1 works fine.

**Comment by zenorocha** [comment]
@zooks we changed our global variable from `Clipboard` to `ClipboardJS`. More information on: https://github.com/zenorocha/clipboard.js/releases/tag/v2.0.0

This problem is related to upgrading to Clipboard.js 2.0 and not related to us migrating to Webpack 4.
