### ISSUE TITLE
Could image be copied to clipboard as Blob then save to local folder with Clipboard.js?

### ISSUE THREAD

**Issue by pendave** [zenorocha/clipboard.js#533]
I want to write user script of Greasemonkey to implement a click on a picture in a web page or add a button next to the picture. 
To save the corresponding picture to the local specified path on my computer.

How is it done?

![z80 74ub 78ucho4 fx](https://user-images.githubusercontent.com/1331881/37255150-4f96be0a-2583-11e8-91fc-fbcacc863909.png)

Some refer I get:

Copy Image to Clipboard via Javascript by Owais Afaq
https://github.com/owaisafaq/copier-js
demo：
http://owaisafaq.com/blog/demos/copier/

How to retrieve images from the clipboard with JavaScript in the Browser
https://ourcodeworld.com/articles/read/491/how-to-retrieve-images-from-the-clipboard-with-javascript-in-the-browser
demo：
https://jsfiddle.net/ourcodeworld/hzvfq82b/?utm_source=website&utm_medium=embed&utm_campaign=hzvfq82b

Not "Save as" function anyway. As save as will get the image downloading from http://www.xxx.com/sample.jpg wasting time. I prefer to directly copy the image already rendered in the web page.

How about Clipboard.js to achieve that goal? Thanks.

**Comment by zenorocha** [comment]
Hey @pendave, Clipboard.js was built only to copy strings.

Thanks for the suggestion!

**Comment by PhatDang** [comment]
Thanks for the suggestion!
