### ISSUE TITLE
Clicking icon or child element of disabled button performs copy.

### ISSUE THREAD

**Issue by rally25rs** [zenorocha/clipboard.js#540]
### Minimal example

https://jsfiddle.net/4w4jqonz/7/

### Expected behaviour

Should not copy when clicking `disabled` buttons

### Actual behaviour

Clicking the plain text of a `disabled` `<button>` element correctly ignores the click event, however when a button has child nodes (for example an icon) you can click on the child element and the copy will happen.

In the above example, click on the left and right text parts of the single button element. Clicking the left half still copies the text because it is in a `<span>`, but the same would be true of an `<img>` tag.

For example if you had:

```
<button disabled="disabled"><img src="copy.jpg"/> Copy</button>
```

then clicking the word "Copy" would do nothing, but clicking the `<img>` icon _would_ copy.

(This is probably actually a problem with `good-listener`)

### Browsers affected

Tested in Chrome, not sure of others.

**Comment by kayandrae07** [comment]
@rally25rs I somehow glanced over it. I see what you mean now

**Comment by paulprins** [comment]
You could always adapt your selector to something like `new Clipboard('.btn:not(:disabled)')`. So not sure that this is an issue with the library. I would not expect the library to address specific use cases like this where user expectations are different (a disabled input element could be used).

**Comment by Ruffio** [comment]
@rally25rs Have you found a solution and this issue can be closed?
