### ISSUE TITLE
cross-origin blocked

### ISSUE THREAD

**Issue by Wqrld** [zenorocha/clipboard.js#545]
### Minimal example

to reproduce go to https://feroxmc.ga/ and click "FeroxMc" on the background image and then open the console.
this might happen because i am hiding the button as text but that would be weird to me. This might also be a issue with me using cloudflare.
### Expected behaviour

I clicked my button and it should have copied the text that was in the text as a attribute

### Actual behaviour

instead of the text getting copied chrome gives me a 

```
DOMException: Blocked a frame with origin "https://feroxmc.ga" from accessing a cross-origin frame.
    at MutationObserver.<anonymous> (https://feroxmc.ga/:509:51)
```
### Browsers affected

Only tested chrome but that is my biggest userbase

**Comment by Wqrld** [comment]
i wanted to have a "click-to-copy" on that text and i've seen other sites do it but how?

**Comment by pedroabreu** [comment]
Works for me on Chrome 66. What version are you on ?

**Comment by zenorocha** [comment]
Hey @Wqrld, in order to evaluate if there's a real problem happening we need a minimal example on JSFiddle. By sharing your wholesite, it makes it impossible for us to determine if the problem is on Clipboard.js or some other part of your application.

**Comment by Wqrld** [comment]
please reopen

fiddle: https://jsfiddle.net/4m731rh8/
(click the red text)
