### ISSUE TITLE
Bracket character [ is encoded in the pasted string if a colon ":" precedes it

### ISSUE THREAD

**Issue by Bubka** [zenorocha/clipboard.js#546]
Hi,

I discovered whats seems to be a bug, but i can't say if it belongs to clipboard.js or Safari.
The <kbd>[</kbd> character is pasted as an encoded string (`%5B`) if a <kbd>:</kbd> precedes the bracket in the copied string.

### Minimal example

Here is an example using CodePen (i can't use jsfiddle at work) :
https://codepen.io/anon/pen/ELbmOx?editors=1111

First click the Copy button, then, using the iOS Paste feature (long press + Paste), paste in the empty field below.

FYI: the bug can be reproduced using the **Usage** example of the [Clipboard.js](https://clipboardjs.com/) homepage.

### Expected behavior

The pasted string should be the same as the copied string

### Actual behavior

Instead of `A:[` Safari paste the string `A:%5B`
If you remove the <kbd>:</kbd> and test again the bracket is pasted as expected.

### Browsers affected

Safari on iOS 11.3

#### Tested browsers not affected
Firefox 56, Windows 7 64b
Firefox 57, Kubuntu 16.04 64b

**Comment by Ruffio** [comment]
@Bubka has this issue been resolved?

The 'conversion' from [ to %5B is urlencoding. However, nowhere in the code are urlencoding used. The fact that it doesn't appear in other browsers suggest that it is a Safari issue.

**Comment by Bubka** [comment]
> has this issue been resolved?

no.

I agree with you, Safari is at fault. I just tested on Firefox for iOS and the bug is fired (given that FF for iOS use Safari's engine).

**Comment by zenorocha** [comment]
Closing since this is an issue on Safari and not Clipboard.js.
