### ISSUE TITLE
What's the license of clippy.svg?

### ISSUE THREAD

**Issue by akimd** [zenorocha/clipboard.js#550]
This is more a question than a real issue, but the examples are using https://clipboardjs.com/assets/images/clippy.svg as a Github-like icon.  I would like to use it in a product so...

What's the license of this file?  Can it be made clear somewhere?

Thanks in advance!

**Comment by Bubka** [comment]
Hi

[Iconfinder](https://www.iconfinder.com/search/?q=clipboard&type=vector) has tons of svg free|premium Clipboard icons. Did you search for these icon? Maybe you could find an alternative.

**Comment by zenorocha** [comment]
The icon is from [Octicons](https://github.com/primer/octicons) which has [MIT license](https://github.com/primer/octicons/blob/master/LICENSE).
