### ISSUE TITLE
Clicking First results in error and when focus is on input

### ISSUE THREAD

**Issue by cdwebdev** [zenorocha/clipboard.js#551]
### Issue

> When focus is on the form, and you click on copy, an error results. Clicking the second time removes the error.

Sample Code:

export default class {
  constructor(el){
    $(config).attr('tabindex', '-1');
    this.myclipboard = new ClipboardJS(config, {
      text: function(trigger) {
        let my-target = $(trigger).data('my-clipboard-target');
        console.log ('my target is' + target);
        return $(my-target).val();
      }
    });
    
    this.myclipboard.on('success', function(e) {
      console.info('Action:', e.action);
    });
    
    this.clipboard.on('error', function(e) {
      console.log (e);
    });
  }
}

**Comment by zenorocha** [comment]
Closing since it didn't follow the recommendations on the issue template. We need an example running on JSFiddle in order to debug the problem.
