### ISSUE TITLE
Use getElementById as fallback for querySelector

### ISSUE THREAD

**Issue by JohnArcher** [zenorocha/clipboard.js#553]
Sometimes in my DOM I have (generated) DOM ids which starts with a digit. According to e.g. https://stackoverflow.com/a/37271406/887930 this is allowed in HTML5 documents, but not within CSS3 and with the querySelector method. I would like to have/implement a way that works with both ways.

### Minimal example

https://jsfiddle.net/JohnArcher/w64fxr65/3/

### Expected behaviour

Copy the content of a text box no matter whether the DOM id starts with a digit or not.

### Actual behaviour

An exception is thrown (and not handled): 
```
DOMException: Failed to execute 'querySelector' on 'Document': '#5841ce72-e8c6-4f9b-aa2c-1906aa556ffa' is not a valid selector.
    at Clipboard.defaultTarget
```
### Browsers affected

Does not work on any browser.

### Solution (draft)

I would create a pull request which would look like this:

```javascript
    defaultTarget(trigger) {
        const selector = getAttributeValue('target', trigger);

        if (selector) {
            try {
                return document.querySelector(selector);
            } catch (ex) {
                
                // delete # of the selector if exists        
                if (selector.startsWith('#')) {
                     selector = selector.slice(1);
                }

                return document.getElementById(selector);
            }
        }
    }
```

Is that something you can live with?

**Comment by Ruffio** [comment]
@zenorocha what do you say about a PR with the above? Mayby just switch to .getElementById only?

**Comment by Ruffio** [comment]
@JohnArcher I understand your view but isn't a workaround just to generate ids starting with a letter? I know digits are 'legal', but it looks like that is not fully implemented in the different JS libraries.

Take Bootstrap for example, they have switched to .querySelector from version 4.1.3:
![image](https://user-images.githubusercontent.com/1877612/45214478-d69b2680-b29a-11e8-8bfc-37dd01d4a4ad.png)

IMHO we should leave the current selector as it is. 
@zenorocha What you say?

**Comment by chasers** [comment]
Would be useful for me also.  Maybe a way to pass in which way to target the id.

**Comment by Ruffio** [comment]
Using IDs starting with a digit is the way to trouble: https://benfrain.com/when-and-where-you-can-use-numbers-in-id-and-class-names/

As written above Bootstrap doesn't support Them. That says it All IMHO. Stay with current selector.
