### ISSUE TITLE
clipboard.js can't work in ios9

### ISSUE THREAD

**Issue by eherry** [zenorocha/clipboard.js#556]
### Minimal example

> Fork this [link](https://daily-xieshangpeng.retailing.cccwei.com/?#/share?id=51) 

### Expected behaviour

I thought that clipboard.js can copy the text  in moblie clipborad.

### Actual behaviour

clipborad.js throw an error on this page under ios9.

### Devices affected

I tested on all major devices like huawei honor v10、samsung s6、iphone x with ios11、iphone 6, only iphone 6 with ios9 does not work.

**Comment by Ruffio** [comment]
There is no sample in this issue that demonstrates the issue. Please try the demo page at: https://clipboardjs.com

This issue should be closed...

**Comment by bosspan** [comment]
The same problem for me. Have you solved it ?

**Comment by Ruffio** [comment]
iOS9? Take a look at the readme. This project supports Safari 10+ due to limitations in previous versions...

**Comment by meibin08** [comment]
I have the same problem，IOS9+, Have you solved it ?

**Comment by eherry** [comment]
emmm..as @Ruffio says, the project supports Sarfari 10+. It has limitations in previous versions.
so,  i pop up a popup window to remind users to manually copy by themselves.
