### ISSUE TITLE
Not work for example

### ISSUE THREAD

**Issue by vhly** [zenorocha/clipboard.js#564]
Bad code.

When i write empty html code, and include the demo content, 

can't work with docs example, please write document right!!!
.

````
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AliPay</title>
</head>
<body>

<!-- Trigger -->
<button class="btn" data-clipboard-action="copy" data-clipboard-text="Just because you can doesn't mean you should — clipboard.js">
    Copy to clipboard
</button>

<script src="js/clipboard.min.js"></script>
<script>
    new ClipboardJS(".btn");
</script>

</body>
</html>
````

**Comment by vhly** [comment]
YES

**Comment by vhly** [comment]
DEMO page in mobile browser work right, but my page not work.

**Comment by pedroabreu** [comment]
Your example works if using the CDN, so it's most likely an issue with the loading of the scripts on your page

https://jsbin.com/woqefavuli/edit?html,output 

So this is not an issue with documentation but a debug issue and an issue with your code. A little less demanding attitude would've helped you a lot more.
