### ISSUE TITLE
binding body bug

### ISSUE THREAD

**Issue by etjson** [zenorocha/clipboard.js#567]
var clipboard = new ClipboardJS('body',{
				text:function(){
					return 'test';
				}
			});
body The input and textarea inside can not be used properly. You must click two times.

**Comment by Ruffio** [comment]
![image](https://user-images.githubusercontent.com/1877612/45213929-47414380-b299-11e8-9a89-7067383d4c58.png)

I think you have to have the 'trigger' inside the function. Try with the above sample.
