### ISSUE TITLE
can I copy img

### ISSUE THREAD

**Issue by XZZsr** [zenorocha/clipboard.js#569]
can I copy image  and paste image  in word ? is  image  ! not img url?

**Comment by XZZsr** [comment]
new ClipboardJS('.btn', {
        html: function(trigger) {
            return trigger.getAttribute('aria-label');
        }
    });

change into html can resolve this question!
but doc not intro!

**Comment by zhe-he** [comment]
base64 is ok?

**Comment by zenorocha** [comment]
Base64 is ok since it's just a string.

**Comment by milrak** [comment]
> base64 is ok?

In linux it works!

https://jsfiddle.net/milrak/sb3tr1nh/8/
