### ISSUE TITLE
Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by godforger** [zenorocha/clipboard.js#570]
### Minimal example

I have problem  after webpack build with production mode

clipboard.js 2.0.1
webpack 4.24.0

Super expression must either be null or a function, not undefined

**Comment by burt202** [comment]
I have just stumbled into this as well. Same re-production steps.

**Comment by lsg-richard** [comment]
Having this issue as well.

Webpack 4.16.5, clipboard 2.0.1

Is it possible this is related to the previous issue around needing to import from `clipboard/dist/clipboard.min`?

Weirdly I noticed that this error goes away when I disable uglify-js on the production build. Not sure if that's a meaningful lead yet though. Going to try and find a better workaround.

**Comment by lsg-richard** [comment]
Yep, if I import from `clipboard/dist/clipboard.min` instead of `clipboard` this problem goes away.

I'm using TypeScript, so also added the following type definition to keep the TypeScript compiler happy:

```
declare module 'clipboard/dist/clipboard.min' {
  import ClipboardJS from 'clipboard'
  export default ClipboardJS
}
```
