### ISSUE TITLE
how to copy with background-image style

### ISSUE THREAD

**Issue by ZhengXiaowei** [zenorocha/clipboard.js#571]
I want to copy dom like this:
```html
<div id="container">
  <div class="demo" style="background-image('1.png');height:100px"></div>
</div>
```

but while I paste it, it show me empty?

how to do?

**Comment by Sheroa** [comment]
I guess it shows empty, because you don’t have a picture in the same folder named 1.png. 1.png is a relative address. You can replace it with an absolute address of a picture or put a picture named 1.png in the same folder

**Comment by ZhengXiaowei** [comment]
@Sheroa it's jsut a demo in the code. actually, the picture address was in the nets.

**Comment by Sheroa** [comment]
Yes. So if you just copy the code, it can’t find the picture. 1.png means the picture is named 1.png and it is in the same folder as the code. If not, your code can’t find the picture.
