### ISSUE TITLE
Copy cannot work in UC brower

### ISSUE THREAD

**Issue by rachelichen** [zenorocha/clipboard.js#576]
### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

### Expected behaviour

I thought that by going to the page '...' and pressing the button '...' then '...' would happen.

### Actual behaviour

Instead of '...', what I saw was that '...' happened instead.

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

**Comment by reedseu** [comment]
Hello, we found in UC browser (https://play.google.com/store/apps/details?id=com.UCMobile.intl&hl=en_US) (one of Alibaba Inc's product) document.execCommand will return undefined so the code will have problem in copyText function.
### succeeded = document.execCommand(this.action);
succeeded  will become undefined
We adjust our code like this
this.clipboard.on('error', (e) => {
  if (Clipboard.isSupported()) {
    successCallBack()
    return;
  }
  errorCallback();
});
But we think It's better you determine whether the browser support the API in copyText function

**Comment by zenorocha** [comment]
UC Browser must support the `execCommand` API for this library to work.
