### ISSUE TITLE
[feature request] Please upload the src directory to npm.

### ISSUE THREAD

**Issue by LeuisKen** [zenorocha/clipboard.js#579]
Since I want to build the source files by myself and for some reason I want to use `ClipboardAction` directly.

Thank your~   :)

**Comment by jsnavarroc** [comment]
I want to help how can I do it?

**Comment by LeuisKen** [comment]
To me, just add `files` field in `package.json` like this:

```
"files": [
  "src",
  "dist"
]
```

**Comment by jsnavarroc** [comment]
and I do not do anything else? OK.

**Comment by jsnavarroc** [comment]
Think that already ... how can you see? thanks to you!! :+1:

**Comment by LeuisKen** [comment]
😄Since only the maintainers can publish this package and both of us are not, I think it's time for you to create a new pull request.

**Comment by zenorocha** [comment]
Closed by https://github.com/zenorocha/clipboard.js/commit/f1d99de5d3fe4ee82ba4e0abd04128c3dde32715
