### ISSUE TITLE
Using bootstrap tooltips vs primercss

### ISSUE THREAD

**Issue by avongluck-r1soft** [zenorocha/clipboard.js#58]
bootstrap is present in a lot more projects, any way you could pick - and - choose?

**Comment by avongluck-r1soft** [comment]
primercss also seems to carry a lot of dependencies making the 2KB of clipboard.js a lot less relevant.

http://getbootstrap.com/javascript/#tooltips

**Comment by zenorocha** [comment]
Hey @avongluck-r1soft, clipboard.js is not opinionated on what tooltip implementation you should use. We only use primer css on the documentation because it already has GitHub's styling for demos.

**Comment by zenorocha** [comment]
Regardless of what we use, I think a tutorial about how to use clipboard.js with Bootstrap's tooltip is a very good idea.

**Comment by zenorocha** [comment]
I just wrote a working example using Bootstrap's Tooltip, feel free to check it out if needed: http://stackoverflow.com/questions/37381640/tooltips-highlight-animation-with-clipboard-js-click/37395225
