### ISSUE TITLE
Confused by IOS(Safari) copy issue

### ISSUE THREAD

**Issue by Candy374** [zenorocha/clipboard.js#587]
first, your project is awesome~! its totally worked on IOS,
but I really want to know, how it works.
I'm using Safari Version 12.0 (13606.2.11) ,
and I can see your core code is `select` the target, and run `document.execCommand('copy')`, 
and I tried document.execCommand('copy') directly in Safari, it returns `false`,
but after the select function, it will return true. 

![image](https://user-images.githubusercontent.com/5716683/47476065-2173fc00-d851-11e8-849a-60a131b28aa1.png)
![image](https://user-images.githubusercontent.com/5716683/47476092-48cac900-d851-11e8-8b27-a1d31c723d23.png)
![image](https://user-images.githubusercontent.com/5716683/47476099-4d8f7d00-d851-11e8-9b33-da13e8babec9.png)

as @zenorocha said, 1.6.0 fixed the IOS issue, but I checked the commits, cant find any clue.

Its killing me not knowing the cause,
@zenorocha could you please explain this?
Thanks very much!

**Comment by zenorocha** [comment]
Closing since everything seems to be working fine on iOS.
