### ISSUE TITLE
Can not support server side 

### ISSUE THREAD

**Issue by HsuTing** [zenorocha/clipboard.js#597]
### Minimal example

You can see [here](https://npm.runkit.com/clipboard). I just import `clipboard` in the server side, but this will throw `ReferenceError: window is not defined`.

```js
// Just import, not use in the server side
import clipboard from 'clipboard';

class Example extends React.PureComponent {
  ...
}
```

### Expected behaviour

I think this can import in the server side.

### Actual behaviour

This break, now.

### Browsers affected

`clipboard` work in the Browsers.

**Comment by zenorocha** [comment]
Fixed at 2.0.4, thanks for reporting!
