### ISSUE TITLE
React wrapper?

### ISSUE THREAD

**Issue by goldensunliu** [zenorocha/clipboard.js#60]
would love to see a react wrapper for this nugget.

**Comment by zenorocha** [comment]
I don't see a problem with that, would you like to start it?

**Comment by JoseRoman** [comment]
@goldensunliu I have created a [repo](https://github.com/JoseRoman/react-clipboardjs) for a react wrapper. Let me know if you would be interested in contributing. :+1:

**Comment by lipis** [comment]
@JoseRoman Good one :) Contributing to what? To the README file?

**Comment by marclundgren** [comment]
@goldensunliu actually, a `react-native`-compatible wrapper would be great ^_^

**Comment by nihey** [comment]
Well, I've actually started something [here](https://github.com/nihey/react-clipboard).

I think it'll be done (in worst case scenario) by the end of this weekend - as I'm a little busy these days.

**Comment by zenorocha** [comment]
Added to https://github.com/zenorocha/clipboard.js/wiki#have-you-built-a-clipboardjs-wrapper
