### ISSUE TITLE
Uc browser has some problem

### ISSUE THREAD

**Issue by reedseu** [zenorocha/clipboard.js#603]
Hello, we found in UC browser (https://play.google.com/store/apps/details?id=com.UCMobile.intl&hl=en_US) (one of Alibaba Inc's product) document.execCommand will return undefined so the code will have problem in copyText function.
### succeeded = document.execCommand(this.action);
succeeded  will become undefined
We adjust our code like this
this.clipboard.on('error', (e) => {
  if (Clipboard.isSupported()) {
    successCallBack()
    return;
  }
  errorCallback();
});
But we think It's better you determine whether the browser support the API in copyText function

**Comment by zenorocha** [comment]
It appears that UC browser does not support `execCommand`.
