### ISSUE TITLE
Can I translate README ?

### ISSUE THREAD

**Issue by h2ck4u** [zenorocha/clipboard.js#605]
Hello, i'm Web Developer from South Korea.

I am using `clipboard.js` very useful.

and i interested in translating README file to korean.

can i do it?

**Comment by zenorocha** [comment]
Although I love the idea of translating, I also know how hard it is to maintain translations. It's very easy to get things outdated as the project evolves, so for that reason, I would rather we not invest time on this issue. But thank you so much for willing to do that.
