### ISSUE TITLE
Appear form icon on iPhone

### ISSUE THREAD

**Issue by SkipTyler** [zenorocha/clipboard.js#606]
Hello!
When copying on the iPhone, a form icon appears.
An example is [here](http://img.netpeaksoftware.com/goodman/H561FH.png).

Is it possible to fix this?
If so, how?
Thank!

**Comment by zenorocha** [comment]
I'm not sure how to fix this and apparently no contributor has, therefore I'm going to close this issue for now. Thanks for understanding.
