### ISSUE TITLE
Is there a limit on how much can be copied?

### ISSUE THREAD

**Issue by suhasdeshpande** [zenorocha/clipboard.js#607]
### Minimal example

>https://jsbin.com/jejijuk/1/edit?js,console,output

### Expected behaviour

Anything I pass to clipboard object should be copied? 

### Actual behaviour

It always throws errors and there is no clear error message on why this failed which makes really hard to debug where the problem lies. i.e if this is related to how I have implemented text method or if there is inherent limitation on how much can be copied.

**Comment by zenorocha** [comment]
This is a browser limitation and unfortunately, there's no way we can get around it.
