### ISSUE TITLE
hidden

### ISSUE THREAD

**Issue by Theolodewijk** [zenorocha/clipboard.js#608]
kopie hidden element not work, how to bypass?

<span class="input-group-button"><button class="btn clipboard_button" type="button" data-clipboard-target="#image-' . $i . '"><i class="fas fa-clipboard-list"></i></button>&nbsp;</span>
						<input type="hidden" class="form-control" data-placement="bottom" id="image-' . $i . '" value="' . $url . '">

**Comment by bernd-wechner** [comment]
Duplicate of https://github.com/zenorocha/clipboard.js/issues/560
Suggest closing this.

**Comment by zenorocha** [comment]
Thanks @bernd-wechner!
