### ISSUE TITLE
Fake element direction issue(Can be important)

### ISSUE THREAD

**Issue by aslanahmet** [zenorocha/clipboard.js#613]
### Minimal example
Some Website's direction is coming from css for example 
![image](https://user-images.githubusercontent.com/15240292/52419315-de3c5100-2b00-11e9-9e92-dc4ec9afc3af.png)

Your code does not work in this situations. Why you are using left or right? You can use top property I think just like this 
![image](https://user-images.githubusercontent.com/15240292/52419413-13e13a00-2b01-11e9-86f9-238a0c65258a.png)

I fixed that problem for my site. If you want I can open Pull request.

Or we can remove that fake element after copy why that element stay in the screen I do not understand

**Comment by zenorocha** [comment]
Thanks for pointing it out the `rtl` attribute.

That invisible element is required to facilitate the copying of content, without that one of our features won't work. You can look at the source code for more information.
