### ISSUE TITLE
Not work on Chrome 71.0.3578.98

### ISSUE THREAD

**Issue by 3l0w** [zenorocha/clipboard.js#615]
When i use Clipboard.js on Chrome 71.0.3578.98 When i click on ```copy``` nothing work.
I dont know if is my chrome or other web browser.
my code :
 index.html :
```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>titre</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js"></script>

</head>

<body>
    <!-- Target -->
    <input id="foo" value="https://github.com/zenorocha/clipboard.js.git">

    <!-- Trigger -->
    <button class="btn" data-clipboard-target="#foo">
        copy
    </button>

    <script src="index.js"></script>
</body>

</html>
```
index.js : 
```js
new ClipboardJS('#btn');
```

**Comment by SimplyCrazy** [comment]
Can confirm. Doesn't work on 72.0.3626.96 as well. "Cut text from another element" example on clipboardjs.com doesn't work, but other do.

Also, in this case error is returned when trigger element is <button>, but works OK with <input>
`var clipboard = new ClipboardJS('.btn', {text: function(trigger) {return trigger.value;}});`

**Comment by 3l0w** [comment]
Thanks I add the bug tag

**Comment by 3l0w** [comment]
I thinks its a bug
