### ISSUE TITLE
cut example does not work with Chrome

### ISSUE THREAD

**Issue by mb73** [zenorocha/clipboard.js#616]
### Minimal example

Using Chrome, clicking **Cut to clipboard** on [clipboardjs.com](https://clipboardjs.com/) does not seem to have any effect.

### Expected behaviour

Should cut the content of #bar into the clipboard.

### Actual behaviour

Popup says **Copied!** but nothing else happens (text is still in #bar and clipboard stays the same).

### Browsers affected

Problem noticed on Chrome (Version 72.0.3626.109 64-Bit). No problem on Firefox, Edge, IE11.

**Comment by futianshu** [comment]
The same problem. Chrome (69.0.3497.100 64-bit)

**Comment by zenorocha** [comment]
Closing since everything seems to be working fine here:

![Screen Recording 2020-02-29 at 11 45 AM](https://user-images.githubusercontent.com/398893/75614041-30c02500-5ae9-11ea-984c-209ad9f2a155.gif)
