### ISSUE TITLE
Dynamically generated text issue.

### ISSUE THREAD

**Issue by drew309** [zenorocha/clipboard.js#618]
howdy,

i've tried several approaches to copy the text that is generated in a field by typing into a box.
here is the code on the page that generates the text and a link to the page.

>     
        <pre class="prettyprint"><code id="code"></code></pre>

[http://68.188.156.191/sql-wizard](url)

is this possible?

thank you

**Comment by zenorocha** [comment]
Yes, this is possible, please check the documentation or the `demo` folder for more details.
