### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by Unknwon** [zenorocha/clipboard.js#62]
Hi, thanks for the awesome project!

From the docs: 

> That means you can show a tooltip saying Copied! when success event is called and Press Ctrl+C to copy when error event is called because the text is already selected.

I'm not pro on JS and just wonder is there any API for me change the text so I can achieve the localization?

Thanks!

**Comment by zenorocha** [comment]
Hey @Unknwon, you can put any text you want, the tooltip is not included on this library. See https://github.com/zenorocha/clipboard.js/tree/gh-pages/assets/scripts to understand how we use it on the documentation.

**Comment by Unknwon** [comment]
Thanks again!
