### ISSUE TITLE
The first copy, you need to click twice to copy successfully.Tested Google, firefox, 360 security three browsers are the same。

### ISSUE THREAD

**Issue by kongabc** [zenorocha/clipboard.js#620]

**Comment by Ruffio** [comment]
You must have an issue with your implementation.
The demosite works without any issues: https://clipboardjs.com/ (just verified it in Chrome)

**Comment by inputherf** [comment]
When the data is obtained asynchronously, the first copy needs to be clicked twice.How to solve?

**Comment by inputherf** [comment]
I can't take the DOM element with $nextTick in vue's mouted, so I can't pre-initialize it.

**Comment by inputherf** [comment]
The problem was resolved because I didn't get the DOM elements right.

**Comment by Ruffio** [comment]
@inputherf then please close Thisted issue

**Comment by zsirfs** [comment]
look：

![image](https://user-images.githubusercontent.com/22249411/57211175-ecbbdb00-7011-11e9-8b1f-25b548c061a3.png)

I met the same problem

**Comment by MontageD** [comment]
> The problem was resolved because I didn't get the DOM elements right.

Thank you for your answer .The problem is really with the DOM binding
