### ISSUE TITLE
Uncaught TypeError: Illegal constructor

### ISSUE THREAD

**Issue by WillGoldstein** [zenorocha/clipboard.js#622]
I am seeing this error again on Chrome/FireFox when instantiating `new Clipboard('.copyText');`

**Comment by praVishal2910** [comment]
TypeError: Illegal constructor. Getting this error too. Tested on both Chrome and Firefox.

**Comment by praVishal2910** [comment]
Using the ClipboardJS constructor helps:
`var clipboard = new ClipboardJS('.btn');`

**Comment by zenorocha** [comment]
Thanks @praVishal2910!
