### ISSUE TITLE
Not working on popup window - Not copying

### ISSUE THREAD

**Issue by cristal2431** [zenorocha/clipboard.js#623]
on console.log(e);

it returns: {action: "copy", text: "hello", trigger: button.btn, clearSelection: ƒ}

its not copying in popup window. Fuction works as expected otherwise

**Comment by CrashyBang** [comment]
Same issue here, I have also tried passing the popup through as `options.container` like so:

```js
const popup = window.open("", "Popup");
const input = popup.document.querySelector(`[data-target="copy-button"]`);
const target = popup.document.querySelector(`[data-target="copy-input"]`);
new ClipboardJS(input, {
    target: () => target
    container: popup.document
});
```
