### ISSUE TITLE
doesn't work on iOS 12.2

### ISSUE THREAD

**Issue by lsc949982212** [zenorocha/clipboard.js#625]
it can works on versions before iOS12.2 , but doesn't work on iOS12.2

**Comment by keepchen** [comment]
> it can works on versions before iOS12.2 , but doesn't work on iOS12.2

+1

**Comment by wangcheng007** [comment]
Did you use fastclick？

**Comment by keepchen** [comment]
> Did you use fastclick？

Yes, I used it.
I found that the trigger for each `trigger` is `fastClickScrollParent`

**Comment by wangcheng007** [comment]
> > Did you use fastclick？
> 
> Yes, I used it.
> I found that the trigger for each `trigger` is `fastClickScrollParent`

你可能需要改一下 fastclick 里面的方法 这篇[文章](https://www.cnblogs.com/vajoy/p/5522114.html) 上面有说，就是 ckipboard 和 fastclick 两个冲突了。

**Comment by keepchen** [comment]
> > > Did you use fastclick？
> > 
> > 
> > Yes, I used it.
> > I found that the trigger for each `trigger` is `fastClickScrollParent`
> 
> 你可能需要改一下 fastclick 里面的方法 这篇[文章](https://www.cnblogs.com/vajoy/p/5522114.html) 上面有说，就是 ckipboard 和 fastclick 两个冲突了。

谢谢

**Comment by Burongtang** [comment]
请问一下 ，如何改写

**Comment by adolt** [comment]
> 请问一下 ，如何改写

可以单独 [禁用fastclick](https://github.com/ftlabs/fastclick#ignore-certain-elements-with-needsclick)

**Comment by Burongtang** [comment]
> > 请问一下，如何改写
> 
> 单独可以[禁用fastclick](https://github.com/ftlabs/fastclick#ignore-certain-elements-with-needsclick)
不怎么明白 - -。

**Comment by sunshanguang** [comment]
> 它可以在iOS12.2之前的版本上运行，但在iOS12.2上不起作用

解决了嘛 兄弟

**Comment by zenorocha** [comment]
Closing since this is a behavior caused by fastclick and not this library.
