### ISSUE TITLE
The mobile side will not be able to replicate

### ISSUE THREAD

**Issue by xiaohaook** [zenorocha/clipboard.js#627]
If you remove the 300ms delay of the mobile terminal and use fastclick.js or onclick to change the ontouchend event, the mobile terminal will not be able to be copied

**Comment by Ruffio** [comment]
Can you provide a JSBin or similar that demonstrates the issue? It it probably fastclick that 'removes' the focus or similar before clipboard kicks in.

**Comment by Ruffio** [comment]
@xiaohaook have you read the readme and tried this:

![image](https://user-images.githubusercontent.com/1877612/56946310-0d73c480-6b2a-11e9-95d0-62faea3e994c.png)

**Comment by xiaohaook** [comment]
<img width="626" alt="屏幕快照 2019-04-30 下午3 24 40" src="https://user-images.githubusercontent.com/19567662/56946531-e682b600-6b5c-11e9-9043-746c6e67c1cb.png">
<img width="325" alt="屏幕快照 2019-04-30 下午3 25 58" src="https://user-images.githubusercontent.com/19567662/56946536-e7b3e300-6b5c-11e9-96c0-21c73068d7c5.png">
<img width="345" alt="屏幕快照 2019-04-30 下午3 26 30" src="https://user-images.githubusercontent.com/19567662/56946538-e84c7980-6b5c-11e9-80a0-8a1ddd43e91f.png">
<img width="359" alt="屏幕快照 2019-04-30 下午3 26 43" src="https://user-images.githubusercontent.com/19567662/56946540-e8e51000-6b5c-11e9-9d0f-d2060dfcd409.png">
This code is an example of what I use in vue. If I use the click event mobile, I can copy it successfully. If I use the touchend event mobile, it will fail

**Comment by DAHU123** [comment]
在iPhone6s上不起作用，出现了一个兼容性问题

**Comment by zenorocha** [comment]
Closing since this is a behavior caused by fastclick and not this library.
