### ISSUE TITLE
would be helpful if the license was stored in a LICENSE file 

### ISSUE THREAD

**Issue by marcstreeter** [zenorocha/clipboard.js#635]
While doing my review of all the Open Source software we're using (for an Open Source Licensing disclosure) what has made it easier is having a `LICENSE` file at the very root of the project.  I notice that the license here is displayed in plain text on the ReadMe but it would be helpful to have it in a `LICENSE` file at the root of this project so that I can automate the process.

**Comment by MerlinMason** [comment]
I'm also running into the same issue, happy to open a PR to resolve if that's ok?

**Comment by zenorocha** [comment]
Done! Sorry for the delay.

https://github.com/zenorocha/clipboard.js/pull/638
