### ISSUE TITLE
Should `main` be `dist/clipboard.js` in bower.json?

### ISSUE THREAD

**Issue by arve0** [zenorocha/clipboard.js#64]
I use [wiredep](https://github.com/taptapship/wiredep) for injecting my bower dependencies. Wiredep uses the `main` property in bower.json, which points to `src/clipboard.js` right now.

Should not main point to `dist/clipboard.js` like it does in package.json?

**Comment by zenorocha** [comment]
Thanks @arve0!

**Comment by arve0** [comment]
Thanks yourself, great library!

**Comment by zenorocha** [comment]
lol :tada:
