### ISSUE TITLE
After the successful copy in the UC browser, the successful callback is not taken, and the failure callback is taken

### ISSUE THREAD

**Issue by XieXiRong** [zenorocha/clipboard.js#642]
I  test in UC browser, it is copy success, but the successful callback is not taken, and the failure callback is taken, what is wrong with it
and the code:

var clipboardJs=new ClipboardJS('#all', {
   text: function() {
  return getUrlParam("a");
  }
 });
  
 var fn=function(){
     clipboardJs.destroy();
     if (browser.versions.iPhone \|\| browser.versions.iPad \|\| browser.versions.ios) {
     window.location.href='/instructions.php?a=' + getUrlParam("a");
   } else if (browser.versions.android) {
  window.location.href='';
   }else{
   var isok = confirm("isComputer?");
  if(isok){
  window.open('');
  } else{
     return;
   }
   }
  };
   
  clipboardJs.on('success',function(){
       fn();
   });
   clipboardJs.on('error',function(){
       fn();
   });

**Comment by wowolyzh** [comment]
UC browser is not support “document.execCommand” function([caniuse](https://caniuse.com/#search=document.execCommand))

In addition, perhaps this article can help you.  [research-of-the-browser-clipboard](https://yi-jy.com/2017/11/15/research-of-the-browser-clipboard/)

**Comment by amhoho** [comment]
英文对话的两个国人啊.

**Comment by wowolyzh** [comment]
> 英文对话的两个国人啊.

haha，毕竟项目的作者是英文的，感觉还是用英文比较合适的~
