### ISSUE TITLE
Rich data not copying accurately on Microsoft Edge

### ISSUE THREAD

**Issue by asriznet** [zenorocha/clipboard.js#643]
### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

my full code is on: http://asri.pro/e-sig

Below fiddle is a stripped down portion of the <div> element that needs to be copied.

https://jsfiddle.net/kcLzpex2/1/

### Expected behaviour

Expected to copy <div> element with full style for supported browsers.
When pasted in Microsoft Word, the fonts should be in "Avenir Std 45 Book" and the red bars below and top of image should be in 2px.

### Actual behaviour

Copied data is missing font information(showing &quot instead of "Avenir Std 45 Book") and the red bar are thinner than expected.

### Browsers affected

I tested on all major browsers and only Microsoft EdgeHTML 17.17134 does not work.

![clipboardjs](https://user-images.githubusercontent.com/11292398/61765359-537db300-ae0f-11e9-9a93-fdb4c094b449.png)

**Comment by carpii** [comment]
> When pasted in Microsoft Word, the fonts should be in "Avenir Std 45 Book" and the red bars below and top of image should be in 2px.

I don't think this library claims to offer a rich text clipboard. Its for plaintext only

**Comment by zenorocha** [comment]
That's correct @carpii, unfortunately this behavior isn't covered by `execCommand` which is the browser API we use.
