### ISSUE TITLE
clipbord not working

### ISSUE THREAD

**Issue by wangzhijun-github** [zenorocha/clipboard.js#646]
### version: 2.0.4
Error info: clipboard.on is not a function
### code： 
![image](https://user-images.githubusercontent.com/24643503/63679185-50694e80-c823-11e9-965e-b14c3da001e8.png)
### Error:
![image](https://user-images.githubusercontent.com/24643503/63679224-6a0a9600-c823-11e9-8211-3f29205f0bab.png)

**Comment by martifenosa** [comment]
Did you initiated it?

`var clipboard = new ClipboardJS('.copy-clipboard');`
