### ISSUE TITLE
table contents are not copied to clipboard

### ISSUE THREAD

**Issue by aamirghanchi** [zenorocha/clipboard.js#647]
The contents of an html table are not being copied to clipboard. I have tried it in all major browsers to no effect.

### Minimal example
https://jsfiddle.net/aamirghanchi/oq58r0kL/5/

### Actual behaviour
In the JSFiddle example, after clicking the button, the table contents are not available when paste is applied.

### Browsers affected
Edge, Chrome, Firefox

**Comment by carpii** [comment]
In your example, jquery is being blocked because jsfiddle is https, but you are trying to load jquery form an http source

I'm not sure this lib even claims it supports copying of HTML tables?
