### ISSUE TITLE
Cannot copy from trigger attribute when in BS Modal

### ISSUE THREAD

**Issue by aussiechief** [zenorocha/clipboard.js#648]
### Minimal example

Example: https://jsfiddle.net/adzbyt3q/5/

### Expected behaviour

Text should be copied from the trigger element's attribute (`data-clipboard-text="text"`) even when the trigger is in a Bootstrap modal.

### Actual behaviour

Text cannot be copied from the trigger element's attribute (`data-clipboard-text="text"`) when that trigger element happens to be within a Bootstrap modal.

### Browsers affected

Issue occurs in latest versions of Chrome, Firefox, and Internet Explorer.

### Notes

I am rather new to Clipboard.JS, so I hope I am not overlooking something. The console records a successful copy (and no error), but nothing appears on the actual clipboard.

In the Fiddle, you'll see that copying from the trigger's own attribute works fine, until you place that trigger in a modal. Also in the Fiddle, this issue does not occur when the trigger is targeting a different element, even when that different element is also within the modal.

**Comment by marco97pa** [comment]
I experienced the same bug, but your workaround saved me

**Comment by jamesbanogon** [comment]
Set the container value to the modal's ID:

```
var clipboard = new ClipboardJS('.btn', {
    container: document.getElementById('exampleModal')
}); 
```

**Comment by zenorocha** [comment]
Thanks @jamesbanogon!

**Comment by programcsharp** [comment]
The problem with the container fix is that it only works with a specific modal, not any modal.

The root cause is that the Bootstrap modal keeps the fakeElem from getting selected normally.

To fix that, add a `focus()` call in clipboard.js selectFake -- right after selecting, but before copying:

```
        this.selectedText = _select2['default'](this.fakeElem);
        this.fakeElem.focus(); // <------
        this.copyText();
```

**Comment by ryantheleach** [comment]
If you end up messing with focus, please restore it after copy.
