### ISSUE TITLE
Dependencies are misleading

### ISSUE THREAD

**Issue by stof** [zenorocha/clipboard.js#650]
The package.json lists good-listener, select and tiny-emitter as dependencies, meaning they will get installed when requiring clipboard.
But these are misleading. The main file points to the `dist` folder, where these dependencies are bundled inside the generated file. These dependencies should either be defined as dev dependencies (if you keep bundling them) or be marked as externals in the webpack config.

**Comment by Dieldore** [comment]
nobody is involved in the project, don't give a shit

**Comment by zenorocha** [comment]
Thanks @stof. I'm not sure if I understand your point exactly.

According to [npm docs](https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file):

> "dependencies": Packages required by your application in production.
> "devDependencies": Packages that are only needed for local development and testing.

What would be your suggestion here? Can you send a PR to clarify?

**Comment by ogonkov** [comment]
Dependencies are okay, if you want to use `src/clipboard.js` instead of prebundled file from `dist`

**Comment by stof** [comment]
@zenorocha currently, your entrypoint (`dist/clipboard.js` does not require good-listener, select and tiny-emitter in production. They are required by your webpack build process generating the `dist` file.

**Comment by ogonkov** [comment]
@stof i make a PR with using `src/clipboard.js` as entry oint for environments that support ES modules (eg webpack)

**Comment by stof** [comment]
if #668 is merged, this issue should indeed be closed if `dist/clipboard.js` wants to keep bundling dependencies.

**Comment by ogonkov** [comment]
This merge will not change anything in `dist` file bundling

**Comment by stof** [comment]
@ogonkov I know. This merge will make it needed to keep the dependencies as is though for `modules`. but then, there is the question whether the file for `main` should be updated too, or whether this issue should be closed without changing anything.

**Comment by stof** [comment]
Note that for my own projects, #668 will be enough though (I'm using webpack)
