### ISSUE TITLE
Distributed bundles should use prod optimizations

### ISSUE THREAD

**Issue by stof** [zenorocha/clipboard.js#651]
The main file point to `dist/clipboard.js`. This means that any webpack (or rollup) project importing clipboard will use this file.

This file is not only skipping minification, compared to `dist/clipboard.min.js`. It is built with webpack in dev mode, which disables other optimizations like the module concatenation, which are helping minification a lot, and cannot be recovered when importing layer (as these apply only on ES modules in webpack, and your dist file is an UMD module).

Due to the limited number of source modules, this is not as impactful as in other libraries where I found this issue, but it would still be great to fix it.

**Comment by stof** [comment]
@zenorocha this is still relevant IMO, and has not been reviewed AFAICT.

**Comment by zenorocha** [comment]
Can you confirm that this is fixed by https://github.com/zenorocha/clipboard.js/pull/596?

If not, can you submit a pull request?

**Comment by stof** [comment]
Well, #596 means that webpack users won't be affected anymore. Buy `dist/clipboard.js` is still bigger than necessary for people using a different way to bundle their file.

**Comment by stof** [comment]
#668 might be fixing this for webpack users (and rollup users)

**Comment by stof** [comment]
Actually, #596 indeed fixes it (there is still `tiny-emitter` and `good-listener` not being concatenated, because they don't ship an ES module version themselves).
