### ISSUE TITLE
When copying the picture, there will be write picture copy is not in

### ISSUE THREAD

**Issue by xwyjh-qd** [zenorocha/clipboard.js#658]
The second picture cannot be copied. Is there any requirement for the picture address?
< div id="copyDiv1" data-clipboard-target="#copyDiv1" @click="clickCopy('#copyDiv1')" ref="copyDiv1">
        < img src="https://www.baidu.com/img/bd_logo1.png" />123
        < img src="http://img.api.yunzhinang.net/Fkb2Qt0sy3hrzCTJTuKq0VmqNAoS.png" />
        < img src="http://www.mikeblog.cn/content/demo/copyimage/images/1.jpg" />
</div>

**Comment by zenorocha** [comment]
This error should be fixed by providing the appropriate DOM selector. Closing since it didn't provide a JSFiddle.
