### ISSUE TITLE
IE8 Support

### ISSUE THREAD

**Issue by sameoldmadness** [zenorocha/clipboard.js#67]
`ClipboardAction` uses `addEventListener` and `removeEventListener` methods, which are not supported in IE8.

clipboard.js already contains `component-events` module that can be used to resolve this issue.

**Comment by lipis** [comment]
Microsoft is officially going to stop supporting IE8 on Jan 12, 2016
http://blogs.msdn.com/b/ie/archive/2014/08/07/stay-up-to-date-with-internet-explorer.aspx and the last stable release was 4 years ago.. :) I really don't see any point on supporting IE8 especially when it comes to new stuff..

**Comment by sameoldmadness** [comment]
My point is that it comes with no additional price: a native method call could be replaced with library method call, and the library is already there.

Also, it is not nice to leave 2% of users behind just because IE8 is not cool anymore.

**Comment by gurde** [comment]
Why support something that will be unsupported in a couple of months?

**Comment by vvo** [comment]
You can include https://cdn.polyfill.io/v2/docs/ if you want to easily support IE8

**Comment by XrXr** [comment]
`addEventListener` is not the core issue. IE8 can't be supported easily because it doesn't have support for [`execCommand`](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand), which clipboard.js needs to function properly. 

You should look into flash based alternatives if you really need to support IE8

**Comment by sameoldmadness** [comment]
MDN is wrong, `execCommand` is supported in IE8.

Event if it wasn't it is okay, since it is wrapped in `try/catch` block, so I could provide the fallback..

**Comment by sameoldmadness** [comment]
> Why support something that will be unsupported in a couple of months?

As a web developer I could not care less whether it is supported or not. The question that matters to me is "Will it still be used by a significant number of people in a couple of months?"

Extrapolating stats for last three years: sure as hell it will be.

**Comment by XrXr** [comment]
`execCommand` is how the writing to clipboard is done. You can try catch it all you want, but in IE8 land there is no `copy` command.

**Comment by XrXr** [comment]
So I fired up an IE8 VM and tested `execCommand` with the copy command, and it indeed worked. (with a pop up asking me about clipboard permission first)

With enough will someone could probably get it to work. If you really want it, you could pick up that task and send a pull request.

**Comment by Daniel15** [comment]
I think the bigger issue will be that getters and setters don't work in IE8, so [this code](https://github.com/zenorocha/clipboard.js/blob/master/src/clipboard-action.js#L159) will need to be refactored slightly (to use `setAction` and `getAction` methods, rather than a property).

**Comment by sameoldmadness** [comment]
@zenorocha If you don't mind, I'll make a PR.

**Comment by vvo** [comment]
Refactoring code to support a dying browser is something we should avoid.

**Comment by maxigimenez** [comment]
![](http://i966.photobucket.com/albums/ae145/ockoala/K-dramas/Dr%20Stranger/Dr%20Stranger001/kfsl.jpg)

**Comment by zenorocha** [comment]
Hey guys, 

If only adding `component-events` would resolve this issue, then I'd be more than happy to go for it. But refactoring code to support that is the first step into a wrong path. Also Babel only supports IE9+.

Anyways, thanks @sameoldmadness for starting this conversation.
