### ISSUE TITLE
Please Help, How to use ClipBoard.js with Delegate, Not Found any Example ?

### ISSUE THREAD

**Issue by AnkushChharri** [zenorocha/clipboard.js#673]
Hi, I am Student and Learn Coding but I am Work on Clipboard.js for Copying Table Rows without add Classes and ID on Table Rows. Then I Found, You'r Delegate that Can help me to Do that. But I am Crowled EveryWhere but Not Found any Example of How to integrate Clipboard.js with Delegate.

So, I am Requested to You, For Give me the Small Example of How to integrate Clipboard.js with Delegate. Below is my Working Code. I want to Copy Each below List one by one Text on Click on it.

`<ul>
        <li>Item 1</li>
        <li>Item 2</li>
    </ul>`

`delegate(document.body, 'ul', 'click', function(e){var clipboard = new ClipboardJS(e.target); });`

I am Try Everything but How to Copy that List Row. I am New and Learn Coding. I Do not Know, What Next, I need to Do after that `var clipboard = new ClipboardJS(e.target);` I think this Wrong because it is not Work.

Please Help Me to integrate.

### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

### Expected behaviour

I thought that by going to the page '...' and pressing the button '...' then '...' would happen.

### Actual behaviour

Instead of '...', what I saw was that '...' happened instead.

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

**Comment by AnkushChharri** [comment]
Please Help me, Sir.
I am Waiting for You'r Reply from 10Hours. Please Give me Small Example.

**Comment by AnkushChharri** [comment]
Please Reply. I am waiting ...

**Comment by zenorocha** [comment]
Clipboard.js already comes with an event delegation built-in. Please see one of the examples shown on https://clipboardjs.com or download the repository try the [examples folder](https://github.com/zenorocha/clipboard.js/tree/master/demo) yourself.
