### ISSUE TITLE
Only values from originally loaded DOM are being copied - dynamically updated values not being copied

### ISSUE THREAD

**Issue by howiecamp** [zenorocha/clipboard.js#675]
I have some basic html as follows:
```
<input id="PersonalEmailAddress" value="whatever" disabled>
<input type="image" src="....png" class="myclass" data-clipboard-text="PersonalEmailAddress" />
```
When I load the page and click on the image input, I appropriately get "whatever" in my clipboard.

But when I dynamically update that input element after page load, e.g. via:

`document.getElementById('PersonalEmailAddress').value = response;`

and then click the image input again, I get the *original* value that existed when the page was loaded.  The new values aren't being copied.  The clipboard code is simply:

```
var clipboard = new Clipboard('.myclass');

    clipboard.on('success', function (e) {
        setTooltip(e.trigger, 'Link copied');
        console.log(e);
    });
```

**Comment by ties-s** [comment]
I think you need `data-clipboard-target`
