### ISSUE TITLE
Making clipboard action keyboard accessible when used on non-native controls

### ISSUE THREAD

**Issue by lightman76** [zenorocha/clipboard.js#676]
### Minimal example
For projects that are using div or other non-native elements instead of native button/link elements, the "click" event isn't triggered by space or enter keypress like they are on HTML button elements which would be required for users who can only use keyboard navigation

This example shows a custom button, link button, and native button
https://jsfiddle.net/wex3jnL4/5/

### Expected behaviour

In the example, focus the input area and then tab to the custom button and press the enter or space key.  When using keyboard navigation, users with accessibility needs need to be able to activate the copy action by using either the space or enter keys.

### Actual behaviour

Nothing happens on space or enter keypresses

### Browsers affected

I've tested this in Chrome and Firefox (latest stable), but would expect it affects all browsers because the implementation only has a click event handler.

### Pull request

I have a forked branch at https://github.com/lightman76/clipboard.js/tree/accessibility with a workaround for this that I needed immediately for my project.  Is this something you would want in the mainline implementation?  If so, I can create a pull request.

For compatibility,  I have made using the key listener opt-in through the options.  Since making custom elements accessible would already take other actions by developers such as adding tabindex and role to the element, I think requiring a flag to enable this is ok and would avoid breaking implementations for existing users.

**Comment by torgeadelin** [comment]
I'm facing the same problem actually.
The fork looks like it should fix the problem.
Is there any plan to fix this in the near future?
