### ISSUE TITLE
In actual use, only the second click can effectively copy the URL

### ISSUE THREAD

**Issue by zhangchenglin** [zenorocha/clipboard.js#678]
### Minimal example

`https://codepen.io/zhangchenglin/pen/gOaVpEO
`

---

```

1. https://github.com/jzeg-net/tools/blob/bd31b6be20c24322d3e51d0694f43f5b06038f90/tools_static_src/js/tools.js#L496
2. https://github.com/jzeg-net/tools/blob/bd31b6be20c24322d3e51d0694f43f5b06038f90/tools_static_src/js/tools.js#L534-L550
3. https://test.jzeg.net/phone_number/

Footer QR code icon, modal box inside
```

### Expected behaviour

It should be true and effective copy to the URL when you click for the first time.

### Actual behaviour

In the code example, the URL was successfully copied on the first click, and the URL was successfully copied.
However, in actual use, the URL can only be copied when the image is clicked for the second time.

### Browsers affected

 83.0.4103.61

**Comment by zhangchenglin** [comment]
jsfiddle is good, but I ca n’t open it, so I can only use codepen

**Comment by virajsoni06** [comment]
@zhangchenglin I am facing the same issue as well
