### ISSUE TITLE
ClipboardJS not copying href from anchor

### ISSUE THREAD

**Issue by kapooramit** [zenorocha/clipboard.js#679]
I believed that ClipboardJS would copy from any HTML element when the element is clicked upon if the attributes are set right. What I have found in my code is that it does not work if the clicked element is anchor and not a button. I don't know why this is because anchors/links are clickable. I am using AnchorJS to add deep anchors to headings etc. and ClipBoardJS for copying the href value of the anchor but it doesn't work. However, if I change the AnchorJS code to create button element and not a (anchor) element, ClipboardJS starts working though now, href is only the anchor value and I need to add baseurl to it. I don't want to edit AnchorJS code. So how can I use both without compromising their original code?

Here is an example:

This one doesn't work. 

```javascript
<script>
        anchors.add();
       
       // add deep anchor link href value to data-clipboard-text attribute for ClipboardJS
        for (var r=0; r < document.getElementsByClassName("anchorjs-link").length; r++) {
          var danchors = document.getElementsByClassName("anchorjs-link");
          var danchorshref = danchors[r].href;
          danchors[r].setAttribute('data-clipboard-text',danchorshref);
        }

        // run this after running AnchorJS
        let anchorjsLinks = document.querySelectorAll(".anchorjs-link");

        anchorjsLinks.forEach(el => {
          el.addEventListener("click", event => {
            event.preventDefault();
            // add custom "copy to clipboard" code
            new ClipboardJS('.anchorjs-link');       
          });
        });
</script>
```

The HTML:

```
<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="#Overview-DesignAssumptions" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;" data-clipboard-text="https://BaseURL#Overview-DesignAssumptions">
</a>
```

If I change the AnchorJS to create button instead of anchor element, the above code works. 

I have posted the same question on stackoverflow too. Sorry for duplicacy...
[https://stackoverflow.com/questions/62198313/clipboardjs-not-copying-href-from-anchor](url)

**Comment by y377** [comment]
Here you are, I tracked you all the way from anchorjs to here lol
