### ISSUE TITLE
clipboardJS relies on execCommand which is now obsolete and could be removed. Any plans for alternatives?

### ISSUE THREAD

**Issue by Danscap** [zenorocha/clipboard.js#683]
As per the title, mozilla has made execCommand obsolete. The alternative is the clipboard API. Any plans to move clipboardJS to use that instead?

**Comment by jamieburchell** [comment]
I think it should be "as well as" not "instead" because of browser compatibility (it doesn't work at all in IE). So, perhaps check for the existence of `Navigator.clipboard`, falling back to `document.execCommand`?
