### ISSUE TITLE
Is this (still) 2kb?

### ISSUE THREAD

**Issue by IonicaBizau** [zenorocha/clipboard.js#69]
> Modern copy to clipboard. No Flash. Just 2kb 

But the file stats say:

 - [`dist/clipboard.js`](https://github.com/zenorocha/clipboard.js/blob/019b021624da18cc738f9c94c2057b53cc4ae203/dist/clipboard.js)–17.6 KB
 - [`dist/clipboard.min.js`](https://github.com/zenorocha/clipboard.js/blob/019b021624da18cc738f9c94c2057b53cc4ae203/dist/clipboard.min.js)–7.5KB
 - [`src/clipboard.js`](https://github.com/zenorocha/clipboard.js/blob/019b021624da18cc738f9c94c2057b53cc4ae203/src/clipboard.js)–3.09 KB
 - [`src/clipboard-action.js`](https://github.com/zenorocha/clipboard.js/blob/019b021624da18cc738f9c94c2057b53cc4ae203/src/clipboard-action.js)–5.32 KB

Of course, this is a great library, but is the description still correct? `src/clipboard.js` seems to be the tiniest file, but [it includes another 5.32KB file](https://github.com/zenorocha/clipboard.js/blob/019b021624da18cc738f9c94c2057b53cc4ae203/src/clipboard.js#L1). :dizzy:

**Comment by addyosmani** [comment]
I wonder if this is 2KB gzipped?

```
$ gz clipboard.min.js
orig size    (bytes):
    7675
gzipped size (bytes):
    2631
```

**Comment by IonicaBizau** [comment]
Hey @addyosmani! :smile:

Yeah, good point, *but*, it looks the previous versions were smaller. Here is [`1.4.0`](https://github.com/zenorocha/clipboard.js/blob/f7d3fb249a53bc45867ac29471816f7911d480f9/dist/clipboard.min.js)–1.28KB. :bar_chart: 

```sh
$ gzipped clipboard.min.js
Original size: 1.31 kB
Compressed size: 695 B
Compression ratio: 53.18%
```

**Comment by zenorocha** [comment]
Yep, it's gzipped. Thanks for answering it @addyosmani.

@IonicaBizau previous versions were smaller because there was no event delegation, event emitter and other things that we added to make the API easier.

**Comment by addyosmani** [comment]
It's probably worth updating the strap-line + project homepage at some point to reflect the latest numbers gzipped.

**Comment by kafeltz** [comment]
"Just" is a little "much" considering que main goal is just copy/cut texts.

**Comment by zenorocha** [comment]
@addyosmani it still 2.something kb gzipped ;)

**Comment by zenorocha** [comment]
@kafeltz it could be way smaller if it wasn't for ES6 transpiling, an event emitter, and many other stuff.

You can do copy/cut text with two lines of code if you want but that's not the point of this project. The point is making something that is extremely easy to use.

**Comment by kafeltz** [comment]
@zenorocha you're right, transpiling boilerplate makes a huge difference.

**Comment by zenorocha** [comment]
?
