### ISSUE TITLE
Import as ES6 "javascript" module not working

### ISSUE THREAD

**Issue by andreinocenti** [zenorocha/clipboard.js#690]
When importing the ClipboardJS as ES6 module like this: 
````
import ClipboardJS from "/mjs/vendors/clipboard.js";
````
I had the following error:

```
Uncaught TypeError: Cannot set property 'ClipboardJS' of undefined
    at webpackUniversalModuleDefinition (clipboard.js:15)
    at clipboard.js:16
```

Or when I tried with this:
````
import * as ClipboardJS from "/mjs/vendors/clipboard.js";
````
I had the following error:
```
clipboard.js:15 Uncaught TypeError: Cannot set property 'ClipboardJS' of undefined
    at webpackUniversalModuleDefinition (clipboard.js:15)
    at clipboard.js:16
````

### Expected behaviour
When using javascript modules and try to import an JS module it should import an exported function/class/property. But the ClipboardJS is not been loading.

Exemple, to export something in EcmaScript 6 Module it must be like this:
```
export default = function foo () {}
```
OR
```
export function foo () {}
```

> More info here: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Statements/export

### Actual behaviour
Loading errors

### Browsers affected
I tested on Chrome and Firefox

**Comment by vespadj** [comment]
I image and try these, but it doesn't work and without any error.
```
import ClipboardJS from "clipboard"
window.ClipboardJS = ClipboardJS
```
