### ISSUE TITLE
Not work in Safari when stopPropagation in capture phase

### ISSUE THREAD

**Issue by nekronhuang** [zenorocha/clipboard.js#692]
### Minimal example

```
var $btn = document.querySelector('.btn');
var btn = new ClipboardJS($btn);

btn.on('success', function() {
  alert('success');
});

$btn.addEventListener('click', function(e) {
  e.stopPropagation();
}, true)
```
See [Codepen](https://codepen.io/nekronhuang/pen/yLOLzdv?editors=1111) .

### Expected behaviour

The success callback will be called in both Safari and Chrome.

### Actual behaviour

It's only called in Chrome, not in Safari.

### Browsers affected

I tested on latest Chrome (84) and latest Safari (13).

**Comment by peoplesing1832** [comment]
I ran into the same problem

**Comment by peoplesing1832** [comment]
老铁，你解决了吗

**Comment by nekronhuang** [comment]
> 老铁，你解决了吗

Nope~

**Comment by peoplesing1832** [comment]
> > 老铁，你解决了吗
> 
> Nope~

https://github.com/zenorocha/clipboard.js/issues/698  我测试了是ok的
