### ISSUE TITLE
Trigger loses focus after copy event

### ISSUE THREAD

**Issue by adamgruber** [zenorocha/clipboard.js#695]
[This line of code](https://github.com/zenorocha/clipboard.js/blob/master/src/clipboard-action.js#L140) was added in v2.0.5 that caused a breaking change. I was unable to find a reason for the addition in the commit logs but the behavior is such that calling `clearSelection` no longer behaves as expected.

#### Behavior in 2.0.4
Calling `clearSelection` returns focus to the trigger

#### Behavior in 2.0.5+
Calling `clearSelection` returns focus to the trigger THEN is subsequently cleared by calling `document.activeElement.blur()`

Can you provide any insight on the reason for this change? It seems like a bug to me.

**Comment by adamgruber** [comment]
Bump

**Comment by ktfth** [comment]
@adamgruber can you provide some case to reproduce this on another enviroment?

**Comment by adamgruber** [comment]
@helderburato Why was this closed without explanation? It's only been 2 days since the request for repro. I plan to add one but even still I feel like the original question was never answered.

**Comment by adamgruber** [comment]
Here's a repo project that illustrates this issue: https://github.com/adamgruber/clipboard-js-issue. I stand by my original statement that this was a breaking change.

**Comment by patrickhlauke** [comment]
Why was this closed? it's an actual issue still...

**Comment by patrickhlauke** [comment]
copying in what I wrote over in https://github.com/twbs/bootstrap/issues/33894

> setting keyboard focus on one of the "Copy" buttons and activating it, focus is then lost/reset to the start of the page. While browsers try to error-correct for this (meaning that a subsequent Tab moves to the next focusable element), the issue becomes evident when using AT (e.g. Chrome/JAWS, activate the button, then use reading keys to carry on reading...focus was moved back right to the start of the page).
>
> Ideally, focus should remain on the "Copy" button, but I'm assuming this was not done in order to "clear" the visual style of the button. Perhaps this needs to dynamically set a class immediately after a copy operation was carried out, which suppresses/changes the styling (maybe suppressing the tooltip, OR adding some indicator like a tick that shows it was indeed copied), and clearing that class again as soon as the button loses focus.

Note that this behaviour now reverts what was fixed originally in https://github.com/zenorocha/clipboard.js/pull/419

**Comment by patrickhlauke** [comment]
@zenorocha could this be reopened please?

**Comment by patrickhlauke** [comment]
Note that this has now been fixed/merged https://github.com/zenorocha/clipboard.js/pull/807
