### ISSUE TITLE
Emit mouse events too

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/clipboard.js#7]
It's quite common for people to show user feedback after a copy to clipboard action. [1] Although we provide a `success` event on which they can show a `Copied!` tooltip, we do not expose mouse events such as `mouseover`, `mouseleave`, so they can show a `Copy to Clipboard` tooltip. Our own site shows that this is a good use reason to implement that. [2]

[1] http://stackoverflow.com/questions/27488279/how-to-show-tooltip-after-copying-using-zero-clipboard
[2] https://github.com/zenorocha/clipboard.js/blob/gh-pages/assets/scripts/main.js#L1-L8

**Comment by heldr** [comment]
:+1:

**Comment by zenorocha** [comment]
I put some thought into this, although this is handy it's not a clipboard library responsibility.
