### ISSUE TITLE
Implicit instantiation of trigger element(s)

### ISSUE THREAD

**Issue by GreenCoder64** [zenorocha/clipboard.js#70]
As from my understanding, a very basic workflow of using clipboard.js would involve importing clipboard.js/clipboard.min.js, and then instantiating the clipboard element(s) using; `new Clipboard("{selector}");`. Perhaps, this workflow can be further simplified through the implicit instantiation of those element(s).

Thus instead of;
```html
<!DOCTYPE html>
<html>
  <head>
    <script src="jquery-1.11.3.js"></script>
    <script src="clipboard.js"></script>
    <script>
      $("document").ready(function(){
        new Clipboard(".btn");
      });
    </script>
    <title>Test Page</title>
  </head>
  <body>
    <input id="foo" value="asdf">
    <button class="btn" data-clipboard-target="#foo">Click me!</button>
  </body>
</html>
```
, we have,
```html
<!DOCTYPE html>
<html>
  <head>
    <script src="clipboard.js"></script>
    <title>Test Page</title>
  </head>
  <body>
    <input id="foo" value="asdf">
    <button class="btn" data-clipboard-target="#foo">Click me!</button>
  </body>
</html>
```
.

**Comment by zenorocha** [comment]
Hey @GreenCoder64,

Although this looks like it simplify things, it can cause some other problems. A developer should have full control of a component's lifecycle from instantiating to destroying it.

**Comment by zenorocha** [comment]
By the way, I was looking at your code and you don't need to include jQuery just for `.ready`, just use the `DOMContentLoaded` event.

**Comment by mjbruni** [comment]
IF you use bootstrap and jQuery, add an additional class (btn-clipboard) to your buttons you want auto-instantiated and leave the buttons you need more control over as is.  Then include the following code to only instantiate the Clipboard construct if the button is clicked.
`+function ($) {
    'use strict';
    
    $(document).on('click.bs.btn-clipboard', '.btn-clipboard', function(e) {
        e.preventDefault();
        
        var $buttonGroup = $(this);
        var $data = $buttonGroup.data();
        
        if (!$data.Clipboard) {
            $buttonGroup.data('Clipboard', new Clipboard($buttonGroup[0]));
        }
    });

}(jQuery);`
