### ISSUE TITLE
点击按钮发送ajax请求，异步回调里，复制请求返回的结果？？

### ISSUE THREAD

**Issue by miuqiang** [zenorocha/clipboard.js#704]
![image](https://user-images.githubusercontent.com/19277011/95647220-3f9b9b00-0b00-11eb-9a79-e44477a0cdd2.png)

**Comment by miuqiang** [comment]
![image](https://user-images.githubusercontent.com/19277011/95647239-6fe33980-0b00-11eb-90eb-42fa7da22ba0.png)

**Comment by miuqiang** [comment]
await shareCardCode(data)
          .then(res => {
            Toast.clear()
            let host = window.location.origin
            let link = (process.env.VUE_APP_ROOT_API || host) + res.data
            _key === 'copylink' ? clipboard(link, temp) : (window.location.href = link)
          })
          .catch((e) => {
            Toast.clear()
          })

**Comment by peoplesing1832** [comment]
安全限制，不能这样做

**Comment by zxzxac110** [comment]
> 安全限制，不能这样做

但是使用 ajax post请求可以达到标题要的效果 代码如下 可直接复制运行查看
`<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
  <style>
    body {
      font-family: "Microsoft YaHei", arial, "PingFang SC";
      max-width: 750px;
      margin: 0 auto;
      font-size: .32rem
    }

    ol,
    ul {
      list-style: none
    }

    li {
      list-style-type: none
    }

    * {
      margin: 0;
      padding: 0;
      -webkit-tap-highlight-color: transparent
    }

    html {
      font-size: 13.33333333vw
    }

    @media screen and (min-width:750px) {
      html {
        font-size: 100px
      }
    }

    li {
      border: 1px solid #f00;
      padding: 20px;
    }
  </style>
</head>

<body>
  <div id="app">
    <ul>
      <li class="btn-copy" v-for="(shoplist, index) in shopArr" :id="'activity' + index"
        v-on:click="tokenBtn(index, shoplist)">
        复制
      </li>
    </ul>
  </div>
  </div>

  <script src="https://cdn.staticfile.org/vue/2.6.10/vue.min.js"></script>
  <script src="https://cdn.staticfile.org/jquery/2.2.4/jquery.min.js"></script>
  <script src="https://cdn.staticfile.org/clipboard.js/2.0.4/clipboard.min.js"></script>

  <script>
    var app = new Vue({
      el: "#app",
      data: {
        shopArr: [{}, {}, {}, {}]
      },

      methods: {
        tokenBtn: function (oIndex) {
          var self = this;
          var url = 'https://v2.api.haodanku.com/ratesurl'
          var url2 = 'http://dev-test-gzhhongbao-m.wl2018888.cn/api/open.php?d=open&m=InvitePresent&c=useConvertGoods'
          var pram = {}
          $.ajax({
            url: url2,
            type: 'post',
            data: pram,
            dataType: 'jsonp',
            async: false,
            success: function (data) {
              var clipboard = new ClipboardJS('#activity' + oIndex, {
                text: function (target) {
                  return (data.Msg || data.msg) + oIndex;
                }
              });
              clipboard.on('success', function (e) {
                alert('成功')
              });

              clipboard.on('error', function (e) {
                alert('成功')
              });
            },
          });
        },
      },
    })
  </script>
</body>

</html>`

**Comment by miuqiang** [comment]
改了交互，按到结果后再去复制

**Comment by vitormalencar** [comment]
Hi @miuqiang 👋🏾 
I do belive that the best way out here is to create a button so once you have the response you can click on copy and then close the modal

something along the lines of what you mention in your comment ( if the translator is right )

**Comment by miuqiang** [comment]
Yes, the current process is to get the results, a pop-up box prompts you to copy

**Comment by vitormalencar** [comment]
nice @miuqiang  can we close the issue then?

**Comment by jzsn2018** [comment]
you can see my solution ~
 ```javascript   
   if (actionType === "COPY_JSON") {
        let data = await this.publishCenterCopyJsonData(id); // request
        let a = document.createElement("a");
        a.addEventListener("click",(event)=>{
          handleClipboard(event, JSON.stringify(data), "复制json成功");
        })
        a.click();
        a.remove();
      }`

**Comment by EmiyaYang** [comment]
> you can see my solution ~
> 
> ```js
>   if (actionType === "COPY_JSON") {
>        let data = await this.publishCenterCopyJsonData(id); // request
>        let a = document.createElement("a");
>        a.addEventListener("click",(event)=>{
>          handleClipboard(event, JSON.stringify(data), "复制json成功");
>        })
>        a.click();
>        a.remove();
>      }`
> ```

It cannot get around the security policy, I've tested it in iPhone 12 with safari.
