### ISSUE TITLE
Clipboard.js potentially incompatible with event delegation changes in React 17

### ISSUE THREAD

**Issue by Leonya** [zenorocha/clipboard.js#708]
React 17 made the following internal change: https://reactjs.org/blog/2020/10/20/react-v17.html#changes-to-event-delegation

On a project I'm working on, upgrading to React 17 broke all clipboard buttons because they were using stopPropagation and indeed the event no longer reached the `document.body` listener created by Clipboard.js

I have forked the library to change the way the listener is created and now all's good again. Please consider adding it as an option to the API.

**Comment by ogonkov** [comment]
What is your integration with react looks like?

**Comment by Leonya** [comment]
I'm initializing Clipboard.js in componentDidMount

**Comment by ogonkov** [comment]
I didn't see any issues with copying text with react@17

I listen for `clipboard.on('success')`, and it works as expected.

**Comment by Leonya** [comment]
Try adding a click handler to the button and calling event.stopPropagation in it.

**Comment by ogonkov** [comment]
I have no idea why you using `stopPropagation`, but it still works for me. I have added both `stopPropagation` and `preventDefault`, because i use link in my case.

**Comment by Leonya** [comment]
I am glad that it does work for you but it didn't work for me and the documentation of React is very clear about the reasons.

**Comment by ogonkov** [comment]
I'm very glad to talk with such a polite person.

I think that you got problem somewhere else. I made a simple codesandbox demo, and it still working smoothly.

https://codesandbox.io/s/small-paper-98bnp

**Comment by Leonya** [comment]
The title of the issue says "potentially", I was never implying that it's broken for everyone.

**Comment by ktfth** [comment]
@Leonya can you provide more information about your implementation to us review more properly?

**Comment by helderburato** [comment]
Hello @Leonya,

Can you provide a replication of the problem with [Codesandbox](https://codesandbox.io/)? It will help us to help you.
