### ISSUE TITLE
与vue 混写时候 第一次无法触发成功！

### ISSUE THREAD

**Issue by Hareis** [zenorocha/clipboard.js#709]
错误的demo放在了下面的地址
https://jsfiddle.net/hareis/gzcf6k4d/8/

![GIF 2020-11-17 17-57-36](https://user-images.githubusercontent.com/11290701/99375324-931eb700-28fe-11eb-9e1c-c6303be46254.gif)

**Comment by Hareis** [comment]
是我用错了

**Comment by roy2651** [comment]
怎么用的，我发现在react下也第一次无法触发，点两次成功

**Comment by jzsn2018** [comment]
> 怎么用的，我发现在react下也第一次无法触发，点两次成功

i have meet same problem. so have you solved this;

**Comment by roy2651** [comment]
> > 怎么用的，我发现在react下也第一次无法触发，点两次成功
> 
> i have meet same problem. so have you solved this;
  可以成功的，在mout的时候注册时间，然后在赋值text
`
```javascript

```javascript
this.setState(
      {
        clipboardJS: new ClipboardJS('#copyBtn'),
      },
      () => {
        this.state.clipboardJS.on('success', () => {
          Toast.success('复制成功', 1);
        });
        this.state.clipboardJS.on('error', err => {
          Toast.fail('复制出错', 1);
        });
      }
    );
```
this.state.clipboardJS.text = () => {
                    return xxxx;
                  };
````
类似这样的

**Comment by roy2651** [comment]
> > 怎么用的，我发现在react下也第一次无法触发，点两次成功
> 
> i have meet same problem. so have you solved this;
  可以成功的，在mout的时候注册时间，然后在赋值text
`

```javascript
this.setState(
      {
        clipboardJS: new ClipboardJS('#copyBtn'),
      },
      () => {
        this.state.clipboardJS.on('success', () => {
          Toast.success('复制成功', 1);
        });
        this.state.clipboardJS.on('error', err => {
          Toast.fail('复制出错', 1);
        });
      }
    );
this.state.clipboardJS.text = () => {
                    return xxxx;
                  };
````



类似这样的
@jzsn2018
