### ISSUE TITLE
可以一打开网页不需要点击动作自动复制内容到剪贴板吗？？

### ISSUE THREAD

**Issue by weixiaoting** [zenorocha/clipboard.js#710]
### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

### Expected behaviour

I thought that by going to the page '...' and pressing the button '...' then '...' would happen.

### Actual behaviour

Instead of '...', what I saw was that '...' happened instead.

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

**Comment by ogonkov** [comment]
No.

**Comment by vitormalencar** [comment]
if the translation is correct, as @ogonkov said is not possible for the button to click itself
due to security reasons
