### ISSUE TITLE
How to prevent code from being escaped in label attributes?

### ISSUE THREAD

**Issue by caicailv** [zenorocha/clipboard.js#714]
Hello, I'd like to ask.
When I add the code that needs to be copied to the 'data clipboard text' attribute of an element, the quotation marks of the code itself will affect the rendering of HTM and also cause the problem of incomplete copying. Is there any solution?

**Comment by vitormalencar** [comment]
Hi 👋 @caicailv, can you describe a little more what you are trying to achieve in this case =)? 
if I understood correctly you want to copy HTML code using the data-attribute, if this is the case I guess that you use Javascript here to help with that,

for example the following:

```html

  <button id="myButton" class="btn"> Copy to clipboard </button>

  <script>
    let button = document.getElementById("myButton");
    button.setAttribute(
      "data-clipboard-text",
      `
      <html>
        <p id="foo">"bar"</p>
        </html>
      `
    );
  </script>

```


should copy this to the clipboard

```html

<html>
 <p id="foo">"bar"</p>
</html>
          
```

let me know if this helps, and if you have a different use cases please share more details and examples =)
