### ISSUE TITLE
Help: I can't get the example to work as described (or at all)

### ISSUE THREAD

**Issue by lucasburlingham** [zenorocha/clipboard.js#716]
### Help needed, not even documented examples will work for me

> I have tried this on multiple sites, including my personal site. I gave up, and am redoing another person's site, and have run into the same problem - no matter what I try, I cannot get the text to be copied to the clipboard per the documentation's instructions (or any way for that matter)

### Expected behavior

> I would expect that the example, listed below, would work if you just added in the third party CDN version of clipboard.js (I tried 2 different CDN's, as well as locally linking it.)

``` 
<button class="btn" data-clipboard-text="Just because you can doesn't mean you should — clipboard.js">
    Copy to clipboard
</button> 
<script src="https://cdn.jsdelivr.net/npm/clipboard@2.0.6/dist/clipboard.min.js"></script>
```

### Actual behavior

> Even when clicked, nothing is logged to console, nothing new is copied to my clipboard.

### Browsers affected

> Tested on latest version of Google Chrome for Ubuntu and Windows, Firefox for Ubuntu and Android.

**Comment by nandinib1999** [comment]
I am also facing this issue

**Comment by lucasburlingham** [comment]
This is the same issue I have. I wonder what is happening.

**Comment by nandinib1999** [comment]
Hey, I made it work with "data-clipboard-text". Not sure if there is some problem in copying text from an input file but if you put the text to be copied in data-clipboard-text, it works perfectly

**Comment by lucasburlingham** [comment]
Hmm. I will give that a try. Thanks.

**Comment by vitormalencar** [comment]
Just a quick question @lucasburlingham, have you instantiate the button in your JS file? 
in order to work you need to create a new instance of the Clipboard and pass your selector

this would be the minimum code required to get the button work 

```html
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/clipboard@2.0.6/dist/clipboard.min.js"></script>
  </head>
  <body>
    <button
      class="btn"
      data-clipboard-text="Just because you can doesn't mean you should — clipboard.js"
    >
      Copy to clipboard
    </button>
  </body>
  <script>
	new ClipboardJS(".btn"); // note that here you need to instanciate the button
  </script>
</html>
```

**Comment by lucasburlingham** [comment]
I think so, met me check...

**Comment by vitormalencar** [comment]
I made this little gif showing the example that you provided working 
I hope is visible =) 

![2021-01-18 22 09 02](https://user-images.githubusercontent.com/7741167/104963172-36ad4600-59da-11eb-8b8f-73032a60a83c.gif)

**Comment by lucasburlingham** [comment]
Hmm. I tried a different framework, and don't know if I had initiated the button when I was still using clipboard.js. I know that I tried the example from the clipboard.js docs, and it had not worked. I will try again.

Thank you.

**Comment by vitormalencar** [comment]
No worries were happy to help =)
@lucasburlingham  and @nandinib1999 do you think we can close this Issue? 
if you have problems again we can re-open

**Comment by lucasburlingham** [comment]
I think we can close the issue, yes.


Thanks a bunch!

**Comment by lucasburlingham** [comment]
@vitormalencar I just realized that I had put the `<script src="https://cdn.jsdelivr.net/npm/clipboard@2.0.6/dist/clipboard.min.js"></script>` at the bottom of my `body` element like one would usually do with scripts, but it works now that I put it in within the `head` tags per your GIF.

**Comment by vitormalencar** [comment]
Hi @lucasburlingham

I also tested putting the script tag in the bottom, and works normally,

it might be another problem or another scrip that was breaking the code that you tested =)
