### ISSUE TITLE
Option to include HTML

### ISSUE THREAD

**Issue by balexandre** [zenorocha/clipboard.js#72]
Would be nice if we could also copy to the clipboard a full HTML block and not just the text that block has.

An example is that I wanted to allow users to copy the email signature code to be pasted in Outlook.

**Comment by zenorocha** [comment]
Hey @balexandre,

Have you tried using the imperative API? You could do something like...

```html
new Clipboard('.btn', {
    text: function() {
        var htmlBlock = document.querySelector('.yourSelector');
        return htmlBlock.innerHTML;
    }
});
```

**Comment by simonmacfadyen** [comment]
The above works, however it pastes the HTML as plain text it would seem. Is there anyway to control that?

**Comment by kafeltz** [comment]
Do you want to strip the html tags?
After you get the content, is up to you to filter/sanitize/etc it.

**Comment by zenorocha** [comment]
Exactly, you can only copy strings to clipboard.

**Comment by simonmacfadyen** [comment]
Well, I ended up using another plugin which as the option I needed to paste as html :).

I see what you're saying though, out of interest how would you filter/sanitize so that it pastes as HTML ? :o

**Comment by kafeltz** [comment]
well, i'm not the author, just random person reading issues =D
I'm curious to know which plugin it is. Just to know if it has the same purpose.

**Comment by Fuzzwah** [comment]
@simonmacfadyen I'm curious which solution you went with?

I'm looking for something which can create [HTML Clipboard Format](https://msdn.microsoft.com/en-us/library/windows/desktop/ms649015(v=vs.85).aspx) entries.

ZeroClipboard does this, but I'm trying to move away from it because of its flash requirement.

**Comment by simonmacfadyen** [comment]
hi @Fuzzwah. 

I stuck it out with this plugin, and used the following:

     var clipboard = new Clipboard('.copy-btn');

     clipboard.on('success', function(e) {
       e.clearSelection();
       alert("Copied!");
     });

     clipboard.on('error', function(e) {
       // error
     });

HTML

     <button class="copy-btn" data-clipboard-target=".myDivToCopy">Click to copy</button

      <div class="myDivToCopy">
           <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
      </div>

The key is the `data-clipboard-target` on the button, which is referencing the div container `myDivToCopy `that contains html.
