### ISSUE TITLE
Bitcoin scam

### ISSUE THREAD

**Issue by iieternal** [zenorocha/clipboard.js#725]
https://elon-bonus.net/btc/index.html
Please read this fully. 
The site mentioned above is a bitcoin scam. While going through their source code i noticed that they also use your clipboard js script directly from your github.io site. So in effect you can change the clipboard.js code to find out who they are, where they are from and literally everthing about them (assuming they check back ones in a while) or could alert users its a scam. I hope you will do justice.

Link on source: https://zenorocha.github.io/clipboard.js

**Comment by carpii** [comment]
They are hosting their own copy of clipboard.js, there is nothing this repo can do
