### ISSUE TITLE
proposing feature: add linter

### ISSUE THREAD

**Issue by r3nanp** [zenorocha/clipboard.js#728]
## 💥 Add Linter

Add a linter like **ESlint**, a linter will make easier to prevent some errors and enforce a code style! Also, ESLint has compatibility with **Prettier** and Typescript.

- [Eslint](https://github.com/eslint/eslint)
- [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier)
- [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier)

**Are you able to assist to bring the feature to reality?**
 yes, I can...

**Comment by vitormalencar** [comment]
I like the idea here, how about creating a PR so we can check the code =) what you say? @r3nanp

**Comment by r3nanp** [comment]
@vitormalencar I would love it.
