### ISSUE TITLE
missing assets folder

### ISSUE THREAD

**Issue by nephilim75** [zenorocha/clipboard.js#734]
Hello

saw in part of the code relation to `assets` folder but cannot find it in the zip file. Am I doing something wrong?

Kind regards
//neph

**Comment by vitormalencar** [comment]
Hi @nephilim75 can you be more specific I'm not sure if I understood your question, also de lib does 
not have any assets folder

**Comment by vitormalencar** [comment]
@nephilim75 I just notice that you might refer to the tooltips on the site examples,
in the website we are using the Github Primer project to do the CSS + icon part there, 

you can check more here https://github.com/zenorocha/clipboard.js#tooltips

**Comment by vitormalencar** [comment]
Closed due to inactivity
