### ISSUE TITLE
ES6 in distribution

### ISSUE THREAD

**Issue by carpiediem** [zenorocha/clipboard.js#737]
### Expected Behaviour

Successful webpack build of our project 

### Actual Behaviour

`SyntaxError: Unexpected token: punc ())`

### To Reproduce

1. Use clipboard.js in a build process that expects ES5 modules
2. Let your project's package.json select version 2.0.7
3. Build fails

**Comment by carpiediem** [comment]
This is easy for me to get around (by specifying v2.0.6), but I thought your team should know about the issue.

**Comment by vitormalencar** [comment]
@carpiediem  Thanks a lot for the bug report, I will have a look into it

**Comment by vitormalencar** [comment]
@carpiediem can you share what Webpack/bundle config are you using?

**Comment by ding-js** [comment]
![image](https://user-images.githubusercontent.com/14885918/110451698-6b4a9d80-80ff-11eb-91c7-fd8b68658a6e.png)

There are arrow functions on the bundle of v2.0.7
