### ISSUE TITLE
After updating to the `2.0.7+` version, an error was reported: `Couldn't find preset "@babel/env"`

### ISSUE THREAD

**Issue by wuwhs** [zenorocha/clipboard.js#745]
My project is normal with the `2.0.6` version, but an error occurs when upgrading to the `2.0.8` version:

```js
**17:15:32**  ERROR in ./node_modules/clipboard/dist/clipboard.js
**17:15:32**  Module build failed (from ./node_modules/babel-loader/lib/index.js):
**17:15:32**  Error: Couldn't find preset "@babel/env" relative to directory "/app/workspace/SIT/node_modules/clipboard"
```
I checked the `2.0.6` version and found that the `preset` used by the `.babelrc` file is `env`, and the `2.0.8` version used `@bable/env`. I guess it is caused by this reason. Apart from rolling back to `2.0.6` and previous versions, is there any solution?

**Comment by vitormalencar** [comment]
@wuwhs, thanks for the report, can you describe what error are you facing? is on the building,
share you env so I can get a better picture of what could be the problem.

**Comment by vitormalencar** [comment]
I did some research and I do believe that this could be an issue related to babel migration, we updated the dependencies and this might be the culprit https://babeljs.io/docs/en/config-files#6x-vs-7x-babelrc-loading

**Comment by wuwhs** [comment]
> @wuwhs, thanks for the report, can you describe what error are you facing? is on the building,
> share you env so I can get a better picture of what could be the problem.

Yes, it was an error that occurred when I was building the project. I pulled out [a simplified project](https://github.com/wuwhs/test-clipboard) to reproduce this problem, if you are interested, you can take a look.

**Comment by wuwhs** [comment]
> I did some research and I do believe that this could be an issue related to babel migration, we updated the dependencies and this might be the culprit https://babeljs.io/docs/en/config-files#6x-vs-7x-babelrc-loading

I doubt too，babel7.x

**Comment by vitormalencar** [comment]
yep I just confirmed, I will create a pr for this and include this fix in the next release at the end of this week, thanks a lot for putting this example in place

**Comment by augustVino** [comment]
I also met. The first installation was the 2.0.6 version of the clipboard. When I upgraded to version 2.0.7, the arrow function was not translated after packaging, which caused the online IE11 to crash. Then it was upgraded to version 2.0.8 urgently, and an error was reported when packaging. babel7.x

**Comment by augustVino** [comment]
> I also met. The first installation was the 2.0.6 version of the clipboard. When I upgraded to version 2.0.7, the arrow function was not translated after packaging, which caused the online IE11 to crash. Then it was upgraded to version 2.0.8 urgently, and an error was reported when packaging. babel7.x

Is it possible to upgrade a major version similar to this upgrade?

**Comment by vitormalencar** [comment]
@augustVino  thanks for the report, sorry that you had this experience, the v2.0.6 is compatible with all the features, the new versions so far just introduced some bug fix for some specific cases so you can downgrade with no problems, tomorrow I will create another release that should fix the babel env problem
