### ISSUE TITLE
Getting copied text in the clipboard on the second time in ReactJS

### ISSUE THREAD

**Issue by AdarshPawar29** [zenorocha/clipboard.js#748]
## 🐛 Bug Report

I was trying to copy text with the help of function like.
```
function copyText(studentId) {
        const text = 'Registration No. : ${studentId}'; 
        const clipboard = new ClipboardJS("a#action-dropdown-menu-option-0 > span", {
          text: () => {
              return text;
          }
        })
        return clipboard;
    }
```
I have a list of student detail rows along with a dropdown component, which takes an options name and an arrow function to call any function outside the return like I'm calling `() => copyText(currentRow.id)` to copy student ID. 
Its all working but after I click twice on the `copy option` inside the dropdown. It's the same for every row, I have to do the same task 2 times to have Student ID on my clipboard.
I wanted to do something like [this](https://github.com/zenorocha/clipboard.js/issues/389#issuecomment-301916808) so that I need not give an id of the tag and got a text when I click the copy option in my dropdown.
Options are not buttons, they are combination on <a> and <span> tags made in saprate components.

**Comment by vitormalencar** [comment]
HI @AdarshPawar29, note sure if I understood, would be better if you create a code sandbox with a reproducible example so I can have a clean view of your env.

**Comment by ShashankGupta28** [comment]
@vitormalencar : may be this can help https://codesandbox.io/s/fast-night-cc5wd?file=/src/Iframe.js

**Comment by vitormalencar** [comment]
not sure if I get the point, 
I got the example to work inside and outside the iframe

```js 
function copyURLB(id) {
    console.log("Iframe Btn clicked with id " + id);
    const clipboard = new ClipboardJS(".btn", {
      text: function () {
        return id;
      }
    });

    console.log(clipboard.text()) // <=== here you can just log the text 
  }
 ```

**Comment by vitormalencar** [comment]
closing due inactivity
