### ISSUE TITLE
Do Not Copy When Target Element Has display:none

### ISSUE THREAD

**Issue by shefik** [zenorocha/clipboard.js#750]
The content does not get copied when the target element has `display:none`.

**Comment by juliorenanp** [comment]
Hey @shefik, there is a workaround for this situation.
You can do something like this:

On HTML:
<div class="test" style="display: none"></div>

On JS:

 new ClipboardJS('.test');
 let clipBoard: HTMLElement = document.querySelector('.test');
 clipBoard.setAttribute('data-clipboard-text', 'the string you want to copy');
 clipBoard.click();

**Comment by netniV** [comment]
As far as I remember, you cannot implement a copy of hidden elements without temporarily showing them first.  Browser-based security blocks this and no coding can get around it (aside from showing said elements).

**Comment by helderburato** [comment]
As @netniV mentioned, it isn’t possible. I’ll close this issue considering it isn’t related to the Clipboard implementation.

**Comment by jorgecolonconsulting** [comment]
A workaround I used was that instead of the target element having `display: none` I moved the element off of the screen with `position: absolute; left: -10000px`

**Comment by netniV** [comment]
Yes, that would work around the issue because it's technically visible from a DOM perspective, it's just not visually available to the end user.
