### ISSUE TITLE
The code does not work if the button is in a Modal window

### ISSUE THREAD

**Issue by S1BIOSE** [zenorocha/clipboard.js#751]
I have a site built with the Bootstrap 5 theme and the code is not working if the button is in a Modal window.

**Comment by alirezagit** [comment]
same issue here.
it doesn't even work on jsfiddle.
I even imported all css and js files.

**Comment by m-e-l-u-h-a-n** [comment]
Hi @S1BIOSE, @alirezagit
I had similar issues, I found
![image](https://user-images.githubusercontent.com/63504956/115404916-5fc4b900-a20b-11eb-9931-55905b9dcf7c.png)

on [documentation](https://clipboardjs.com/) and this solution works too.

**Comment by S1BIOSE** [comment]
hi @m-e-l-u-h-a-n  Thank you your solution works.

**Comment by S1BIOSE** [comment]
On my site at the bottom left, I have a button with 3 dots that opens a "Bootstrap modal" window. There is a button which use "clipboard" to copy its text. I added a "popover" to show "Copied" when I click on the button.

My problem :
The "popover" should still be displayed, but it is displayed for half a second.

How to make the text of "Bootstrap popover" appear ?

https://www.mathieulebert.fr/

Here is the full code :

https://github.com/S1BIOSE/E-business-Card

Here is the button that causes the problem :

`<button role="button" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-trigger="focus" data-bs-content="Copié" class="btn btn-outline-dark btn-clipboard" data-clipboard-text="https://www.mathieulebert.fr">https://www.mathieulebert.fr <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-clipboard" viewBox="0 0 16 16"><path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/><path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/></svg></button>`

Did you manage to display a "popover" when you click on the button to copy the text ? My theme is with Bootstrap 5

**Comment by helderburato** [comment]
Considering the issue already solved I'll close it. Thanks, @m-e-l-u-h-a-n for share your solution.

**Comment by ryantheleach** [comment]
Seems similar to the issue that focustrap received. https://github.com/focus-trap/focus-trap/issues/383
