### ISSUE TITLE
Copying on button click triggered in JavaScript not working on Mobile (Chrome 90+)

### ISSUE THREAD

**Issue by jordib123** [zenorocha/clipboard.js#757]
https://jsfiddle.net/hngukvdt/

I am trying to copy text to clipboard instantly on DOMContentLoaded (see fiddle) without actual interaction. This is working for desktop but not for mobile while my mobile chrome version is 90+. isSupported() function also return true so Chrome version seems to be no problem.

The clipboard error event is fired but does not return any useful information (see image).

![image](https://user-images.githubusercontent.com/31107712/115408015-cee0e400-a1f0-11eb-9f33-14e80f792461.png)

**Comment by obetomuniz** [comment]
Hey @jordib123, thanks for report this issue. Is it still happening? Also, could you please tell us what your device is? I just tested your demo onChrome 90.0.443078 on my iPhone, and it works pretty well.
