### ISSUE TITLE
How do I display a “Copied” popover after copying a link ?

### ISSUE THREAD

**Issue by S1BIOSE** [zenorocha/clipboard.js#758]
I created a small website with the Bootstrap 5 theme and the following library :

https://clipboardjs.com/

I want to use the Bootstrap 5 Popover with this method :

https://getbootstrap.com/docs/5.0/components/popovers/#dismiss-on-next-click

I want when a user clicks the button to copy the website address to see a popover.

My current code works but the popover disappears when the click is released. Normally it should stay displayed, unless I click outside.

I have the impression that the clipboard.min.js library is triggered after the popover and automatically closes the popover.

I want it to copy and then it will display the popover.

How to display the popover after copying the url ?

The files from my site below.

index.html :

```
<!doctype html>
<html lang="fr" class="h-100">

  <head>
    <meta charset="utf-8">
  </head>

  <body>

    <a tabindex="0" role="button" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-trigger="focus" data-bs-content="Copié" class="btn btn-outline-dark btn-clipboard" data-clipboard-text="https://www.mathieulebert.fr">https://www.example.fr</a>

    <script src="bootstrap.bundle.min.js"></script>
    <script src="popover.js"></script>
    <script src="clipboard.min.js"></script>
    <script src="btn-clipboard.js"></script>
    <script src="pwa.js"></script>
    <script src="toasts.js"></script>
    <script src="feed.js"></script>

  </body>

</html>
```

btn-clipboard.js :

```
new ClipboardJS('.btn-clipboard', {
  container: document.getElementById('settingModal')
});
```

popover.js :

```
var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
  return new bootstrap.Popover(popoverTriggerEl)
})
```

Here is my site. You have to go to the button with the 3 dots at the bottom left and click on the button with the address of the site. The problem, when I release the button, the popover disappears. mathieulebert.fr

**Comment by helderburato** [comment]
Hey @S1BIOSE, can you share a codepen or any other platform with an example? It will help us to help you.
