### ISSUE TITLE
Feature Request: Copy image to clipboard to allow pasting it into another app.

### ISSUE THREAD

**Issue by inglesuniversal** [zenorocha/clipboard.js#759]
Can you consider adding this feature to your already awesome script?

Allow the user to copy an image into the clipboard and paste it to desktop apps likes PhotoShop or mobile apps like WhatsApps.

By pasting I mean the actual image copied into the clipboard and not its url or base64 data.

Thanks

**Comment by helderburato** [comment]
Hi @inglesuniversal can you give more details about what you expect? Or maybe share resources with the specifications.

**Comment by helderburato** [comment]
It isn't in the scope of the project, because you can manipulate the image using the text/url copying from the image.

I'll close the issue, because it isn't the scope of Clipboard.js.
