### ISSUE TITLE
How to install clipboard.js with composer

### ISSUE THREAD

**Issue by everhee** [zenorocha/clipboard.js#766]
Could you explain how to install your project with composer.
I tried to install it from zip ou git file source urls to Drupal libraries folder but doesn't succeed.
Tried this in composer.json : 
{
    "type": "package",
    "package": {
        "name": "zenorocha/clipboard.js",
        "version": "2.0.8",
        "type": "drupal-library",
        "dist": {
            "url": "https://github.com/zenorocha/clipboard.js/archive/master.zip",
            "type": "zip"
        }
    }
},
And this : 
{
    "type": "package",
    "package": {
        "name": "zenorocha/clipboard.js",
        "version": "v2.0.8",
        "type": "drupal-library",
        "extra": {
          "installer-name": "clipboard.js"
        },
        "source": {
            "type": "git",
            "url": "https://github.com/zenorocha/clipboard.js",
            "reference": "v2.0.8"
        }
    }
},

Anyone succeed.
Thanks in advance.

**Comment by jeremycaldwell** [comment]
@everhee, I ran into similar issues but was able to resolve it by loading it like so:

```
    "repositories": {
        "zenorocha/clipboard.js": {
            "type": "package",
            "package": {
                "name": "zenorocha/clipboard.js",
                "version": "v2.0.8",
                "type": "drupal-library",
                "dist": {
                    "url": "https://github.com/zenorocha/clipboard.js/archive/refs/heads/master.zip",
                    "type": "zip"
                }
            }
        },

    "require": {
        "zenorocha/clipboard.js": "2.0.8"
```
