### ISSUE TITLE
When the mobile browser forbids the copy function, the copy fails, but the callback is successful

### ISSUE THREAD

**Issue by aYangLi** [zenorocha/clipboard.js#767]
// When the mobile browser forbids the copy function, the copy fails, but the callback is success
clipboard.on('success', (e) => {
      Toast.info('已复制');
      console.info('Action:', e.action);
      console.info('Text:', e.text);
      console.info('Trigger:', e.trigger);
});

**Comment by helderburato** [comment]
Hey @aYangLi, is this still occurring?

**Comment by helderburato** [comment]
Hey @aYangLi, is it still happening?
