### ISSUE TITLE
bower.json still on v2.0.6

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [zenorocha/clipboard.js#768]
## 🐛 Bug Report

When installing from bower it won't install the latest version including the fixes for `=>` leaked to dist folder.

-> i changed to npm now but thought i'll let you know.

### Have you read the [Contributing Guidelines on issues](https://github.com/zenorocha/clipboard.js/blob/master/contributing.md)?

A bit

### Expected Behaviour

Installing through bower (yes, we still use that -.-) results in 2.0.6 for `"^2.0.0"`

### Actual Behaviour

latest version of 2.0.8 

### To Reproduce

`bower install clipboard`

### Operational System

Windows 10

**Comment by helderburato** [comment]
Hey @TheGreatRefrigerator, thanks for the heads up.

Feel free to open a PR, we will really appreciate the engagement of the community.
