### ISSUE TITLE
Copy Working - but not copying

### ISSUE THREAD

**Issue by jorgelina-aydarpaz** [zenorocha/clipboard.js#769]
Hi, I am not sure whether this is a bug, or just an issue I am having.
I am using Oracle APEX - to develop a webpage.
In this page, I initialize the library this way: (I have tried the initalization in several ways but always getting same result)

var cpyClip = new ClipboardJS('#btnCopyClipboardHidden',
                              { container: document.getElementById('contentToCopy')}
                             );

cpyClip.on('success', function(e) {
    console.log('Copied to Clipboard');
    console.info('Action:', e.action);
    console.info('Text:', e.text);
    console.info('Trigger:', e.trigger);

   // e.clearSelection();
});

cpyClip.on('error', function(e) {
    console.log('Error when copying to Clipboard');
    console.error('Action:', e.action);
    console.error('Trigger:', e.trigger);
});

The button btnCopyClipboardHidden is set correctly.
When the user clicks on a specific button, certain contain "Original Content", is cloned into a variable, and some of the Original Content changed, the ID changed to "CopiedContent", and then this added into the body of the page, in a minuscule box of 1px x  1px, with a negative z-index, so the user does not see it under a tool bar is there.
Then I do a $('#btnCopyClipboardHidden').click(), which should copy the content.

I always get a "success", never an "error". The success shows that the e.text is the corresponding content that should be copied, however, this content is not copied.

I always - to check - before clicking on the "specific button" to copy the original content, copy a simple string 'abc', so I can see that changed.
But, it does not, when I paste, I still get the 'abc'.
However, if I press the button several times, it is random, sometimes it is 2 times, others is 5 times... eventually the original content (and copied into the new region) is copied properly, once it does that... it seems to copy it well no matter how many times I click on the buttons (there are actually a couple buttons, all basically do the same, however, each button ads a specific text the others don't; but the main point here is that I can see everytime the right copy there, once it started to copy).
I am not really sure why this is happening, I debugged it lots of times, but never see anything that catches my eye to understand why, it may happen that the button (it all starts once the page is loaded) needs N clicks before it actually starts copying.

Am I missing something here? Perhaps a limitation? Perhaps anyone can hint me to what to look or search for to understand this issue better ? Thanks!

**Comment by helderburato** [comment]
Hi @jorgelina-aydarpaz, can you provide an example in Codepen or Codesandbox? It will help us to analyse if it's really an issue.

**Comment by jorgelina-aydarpaz** [comment]
> Hi @jorgelina-aydarpaz, can you provide an example in Codepen or Codesandbox? It will help us to analyse if it's really an issue.

Hey!!
I have been trying to find a reason behind this, all I could find is the amount of text to be copied. It seems when there is a big/large amount (which is what I was producing) it will not copy properly.
Unfortunately cannot provide a sample, the text that gets copied is a generated HTML from a report, using mustache to set the json-cursor I bring from the DB with the corresponding template, so the html is set and then dynamically set in a region so the user can see the report in the way they want.
After that, this piece of html, is cloned with a different ID, and copied using a trigger on a button with the corresponding region.
When the html is not very big, then it copies it just fine.
But when it is big (and many users like to have a big selection that is then brough with details from the database) it is not copying correctly. 
So it works and it doesn't work, I know , doesn't make a lot of sense.
Not sure how to generate the big amount of html I would be generating with Codepen or Codesandbox, since it is a big chunk of info generated from the database and the, as I said before, mixed up with a template using mustache.
I do wonder, however, if it could be related to execCommand being deprecated as I read on the internet.
Let me know if there is something else I could provide to try to pin point this.
Thanks and regards.

**Comment by helderburato** [comment]
Hi @jorgelina-aydarpaz, thanks for your quickly return.

Can you share a console of this chunk of text with pastebin? It will help us to validate.

Like you said, we are moving to the new browser clipboard API, and somethings with be improved with this approach.

**Comment by jorgelina-aydarpaz** [comment]
Here I am attaching all the html involved (real data obscured).
[GeneratedHTML.txt](https://github.com/zenorocha/clipboard.js/files/6743164/GeneratedHTML.txt)

Content could be even bigger. Usually things with "display: none" are in there, but not copied or at least no pasted on the places they paste text.
Content is copied and user can paste it into a "TXT" or an EMAIL, or (with some processing before copying it - to include ** to highlight data) into WHATSAPP.

**Comment by jorgelina-aydarpaz** [comment]
> Hi @jorgelina-aydarpaz, thanks for your quickly return.
> 
> Can you share a console of this chunk of text with pastebin? It will help us to validate.
> 
> Like you said, we are moving to the new browser clipboard API, and somethings with be improved with this approach.

I am ... thinking that maybe you wanted something different, please explain if so, on what is the console with pastebin iyou want. Thank you!

**Comment by helderburato** [comment]
Sorry, but I didn't catch the issue.

Try to replicate your problem with the Codepen or Codesandbox to share with us.

I think it's the more accurate way to we understand what is expected by you.

If you need any help, feel free to ask.

**Comment by jorgelina-aydarpaz** [comment]
@helderburato Hi, I am trying to set the example in codepen, but I do not know how to add the clipboardJS library into it. Can you help? thank you.

**Comment by helderburato** [comment]
For sure @jorgelina-aydarpaz, I created [this simple example](https://codesandbox.io/s/clipboard-test-052kg) you can fork it and apply your changes.

**Comment by Somiar** [comment]
I also encountered the same problem. It can be used normally on safari, but it does not work on Chrome.

> Hi, I am not sure whether this is a bug, or just an issue I am having.
> I am using Oracle APEX - to develop a webpage.
> In this page, I initialize the library this way: (I have tried the initalization in several ways but always getting same result)
> 
> var cpyClip = new ClipboardJS('#btnCopyClipboardHidden',
> { container: document.getElementById('contentToCopy')}
> );
> 
> cpyClip.on('success', function(e) {
> console.log('Copied to Clipboard');
> console.info('Action:', e.action);
> console.info('Text:', e.text);
> console.info('Trigger:', e.trigger);
> 
> // e.clearSelection();
> });
> 
> cpyClip.on('error', function(e) {
> console.log('Error when copying to Clipboard');
> console.error('Action:', e.action);
> console.error('Trigger:', e.trigger);
> });
> 
> The button btnCopyClipboardHidden is set correctly.
> When the user clicks on a specific button, certain contain "Original Content", is cloned into a variable, and some of the Original Content changed, the ID changed to "CopiedContent", and then this added into the body of the page, in a minuscule box of 1px x 1px, with a negative z-index, so the user does not see it under a tool bar is there.
> Then I do a $('#btnCopyClipboardHidden').click(), which should copy the content.
> 
> I always get a "success", never an "error". The success shows that the e.text is the corresponding content that should be copied, however, this content is not copied.
> 
> I always - to check - before clicking on the "specific button" to copy the original content, copy a simple string 'abc', so I can see that changed.
> But, it does not, when I paste, I still get the 'abc'.
> However, if I press the button several times, it is random, sometimes it is 2 times, others is 5 times... eventually the original content (and copied into the new region) is copied properly, once it does that... it seems to copy it well no matter how many times I click on the buttons (there are actually a couple buttons, all basically do the same, however, each button ads a specific text the others don't; but the main point here is that I can see everytime the right copy there, once it started to copy).
> I am not really sure why this is happening, I debugged it lots of times, but never see anything that catches my eye to understand why, it may happen that the button (it all starts once the page is loaded) needs N clicks before it actually starts copying.
> 
> Am I missing something here? Perhaps a limitation? Perhaps anyone can hint me to what to look or search for to understand this issue better ? Thanks

**Comment by helderburato** [comment]
Can you use [the example](https://codesandbox.io/s/clipboard-test-052kg) to share with us? @Somiar

**Comment by jorgelina-aydarpaz** [comment]
Hi @helderburato, I was not able to replicate the issue in codepen, though I was able to add up the clipboard.js library.
So, there, in codepen, it works and works fine, with Chrome.
I am unsure what is causing this issue, is not like fully consistent, like it "always' happens, though it seems related to the size of the html object that it copies into the clipboard. 

So, let me add a few more things that might be something to think if can be part of the issue.
I - on load - have the script setup against a class that belongs to a button  let's say  HIDDENCOPYBUTTON. The button is associated to a specific ID (let's say COPYTEXT), which is what is going to be copied.

There is a content "ORIGINALTEXT" that is generated via ajax, when rendering the page and whenever the users change some setups in page. Once they like what they see they can click on the "copy" button.
Once they click on that, the ORIGINALTEXT is cloned and "treated" (some things removed, some don't ), and a new object created COPYTEXT set in a specific place, out of the sight of the user, so it can be copied, and a HIDDENCOPYBUTTON.click() executed, so the clipboard copy takes place.

They may want something different, and then redo some of the setups and again click on the COPYBUTTON, and the COPYTEXT gets removed, and a new one generated, and again the HIDDENCOPYBUTTON.click() executed.

At some point between these steps (not always the same step), it stops copying. I am starting to wonder if it could be related to the  re creation of the COPYTEXT object that needs to be copied, or what exactly. It is being removed everytime, to make sure there are no ducplicaates on IDs.

Not sure what else to think, and not easy to set all that up in a codepen.
Thank you.

**Comment by kolessios** [comment]
@helderburato The same thing happens to me but in my case it is when the element is inside a `<dialog>`. 

I managed to [reproduce the problem here](https://codesandbox.io/s/clipboard-test-forked-r5qsh), ClipboardJS indicates that the copying was successful but it is not.

**Comment by jorgelina-aydarpaz** [comment]
Kolession left a message (not seeing anymore), and provided an example with a modal, that is not working. Here the link he provided for the sandbox:
https://codesandbox.io/s/clipboard-test-forked-r5qsh?file=/src/index.js 

Could it be that dynamic objects might be an issue?

**Comment by kolessios** [comment]
@jorgelina-aydarpaz I deleted my message because I realized late that the README mentions using the [`container`](https://github.com/zenorocha/clipboard.js#advanced-options) option for these situations.

**Comment by jorgelina-aydarpaz** [comment]
> @jorgelina-aydarpaz I deleted my message because I realized late that the README mentions using the [`container`](https://github.com/zenorocha/clipboard.js#advanced-options) option for these situations.

Do you mean using it like this:
var cpyClip = new ClipboardJS('#btnCopyClipboardHidden',
{ container: document.getElementById('contentToCopy')}
);
??

**Comment by kolessios** [comment]
I haven't seen how ClipboardJS works exactly but I imagine it needs to create some element in `<body>`, but in my example, when opening the `<dialog>`, `<body>` stops being in focus which causes the created element to stop working.

The solution is to set `container` to the parent element containing the focus, which in this case would be the `<dialog>` itself:

```
const clipboard = new ClipboardJS(".btn", {
  text: () => "Just because you can doesn't mean you should — clipboard.js",
  container: document.querySelector("dialog")
});
```

@jorgelina-aydarpaz  In your specific case I don't know how you have it done, but seeing the name of `contentToCopy` I think that maybe you are confusing `container` with `text`.

**Comment by jorgelina-aydarpaz** [comment]
> I haven't seen how ClipboardJS works exactly but I imagine it needs to create some element in `<body>`, but in my example, when opening the `<dialog>`, `<body>` stops being in focus which causes the created element to stop working.
> 
> The solution is to set `container` to the parent element containing the focus, which in this case would be the `<dialog>` itself:
> 
> ```js
> const clipboard = new ClipboardJS(".btn", {
>   text: () => "Just because you can doesn't mean you should — clipboard.js",
>   container: document.querySelector("dialog")
> });
> ```
> 
> @jorgelina-aydarpaz In your specific case I don't know how you have it done, but seeing the name of `contentToCopy` I think that maybe you are confusing `container` with `text`.

Iván, that actually would be the "div" where the html content that needs to be copied, is.  
Basically a:
```
<div id='contentToCopy'>
   <div>  content to be copied </div>
</div>
```
Thus, why calling it "document.getElementById ('contentToCopy'); "

**Comment by kolessios** [comment]
In that case you should do something like this:

```js
const clipboard = new ClipboardJS(".btn", {
  text: () => {
    return document.getElementById("contentToCopy").textContent.trim();
  }
});
```

[Example](https://codesandbox.io/s/clipboard-test-forked-9iim8)

**Comment by jorgelina-aydarpaz** [comment]
@kolessios  Thank you Iván, I will try that one and see what happens (next Monday)
@helderburato  I have another question, I have noticed that if I have something like this to copy:
<div id="TextToCopy">
   <div id="Main" style="font-weight: 700;">
          <span> This is a title </span>
          <span> Text 1< /span>
          <span style="display: none"> Text 2 </span>
   </div>
</div>

The "Text 2" does not get copied as an object, I checked on your script but I do not see anything (but I cannot be 100% sure of this) that is getting rid of the display: none elements. So my question is what is making rid of the display: none elements? I noticed that if I copy it into a notepad it also does not paste it.
Thank you!

**Comment by jorgelina-aydarpaz** [comment]
> In that case you should do something like this:
> 
> ```js
> const clipboard = new ClipboardJS(".btn", {
>   text: () => {
>     return document.getElementById("contentToCopy").textContent.trim();
>   }
> });
> ```
> 
> [Example](https://codesandbox.io/s/clipboard-test-forked-9iim8)

Sorry , I thought I answered this before, that I would try it on last Monday.
I am wondering, when yous et "text: () " aren't you setting it as plain text rather as an html object ?Because I want the html object to be copied.

**Comment by jorgelina-aydarpaz** [comment]
This is weird, I am pretty sure I sent an answer 2 times, something odd happened.
When you put text: () => { return  ... }  isn't it expecting a text, or can be an html object.

**Comment by obetomuniz** [comment]
@jorgelina-aydarpaz Was it fixed due to the diligence suggested here? I'll close the issue for now, but feel free to reopen if you still did not fix it as expected. Thx again for report the problem you tackle.
