### ISSUE TITLE
Faulty behaviour when browser access is not permitted.

### ISSUE THREAD

**Issue by wpp** [zenorocha/clipboard.js#77]
Hello,

This is a bit of an edge-case and might not have a *proper* solution. But since the project supports IE9+
and I'd qualify this as a ["case where you'd like to show some user feedback"](http://zenorocha.github.io/clipboard.js/).

I thought I'd be worth mentioning here.

Steps to reproduce:

1. Visit http://zenorocha.github.io/clipboard.js/
2. Click one of the triggers in the examples
3. Click on deny access, when prompted for clipboard permissions by the browser. (see screenshot)
4. **UI responds as if the copy to clipboard succeeded.** (see screenshot)

AFAIK the root cause of the problem is that [document.execCommand](https://github.com/zenorocha/clipboard.js/blob/master/src/clipboard-action.js#L113) returns `true` even if it does not have permissions.

- OS: Windows 7 (Home Premium)
- Browser Version: IE 9 (see screenshot)

![permission](https://cloud.githubusercontent.com/assets/942021/10305604/5db96186-6c21-11e5-847c-e4f2f95bade8.png)
![copied](https://cloud.githubusercontent.com/assets/942021/10305633/941b4186-6c21-11e5-968c-929d9f2046d0.png)
![version](https://cloud.githubusercontent.com/assets/942021/10305513/ccc394da-6c20-11e5-8f06-8030d07a0323.png)

Thanks for a great library with superb documentation.
Cheers.

**Comment by zenorocha** [comment]
Thanks a lot for such detailed explanation @wpp. We'll see what options we have to fix this.

**Comment by jylertones** [comment]
Found a possible approach - you can use document.execCommand('paste') on another node and see if it pasted:

	var didItWork = false;
	var checkDiv = document.createElement('textarea');
	checkDiv.position = 'absolute';
	...
	document.body.appendChild(checkDiv);
	checkDiv.select();

	try {
		document.execCommand('paste');
		didItWork = checkDiv.value == "<coped string>";
	} finally {
		document.body.removeChild(checkDiv);
	}

**Comment by jylertones** [comment]
Also worth noting, I believe this problem happens in both IE9 and IE10. IE11 appears to return the correct value from execCommand.

**Comment by zenorocha** [comment]
Hey guys,

I don't think we have a proper solution for this. For now, we'll describe this as a [known bug on the wiki page](https://github.com/zenorocha/clipboard.js/wiki/Known-Issues).


Thanks again for reporting @wpp and @jylertones for trying to help.

**Comment by roseforyou** [comment]
//original code:
`try { e = document.execCommand(this.action) } catch (n) { e = !1 }`

//is OK???
`try { e = window.clipboardData ? window.clipboardData.setData('Text', this.selectedText) : document.execCommand(this.action) } catch (n) { e = !1 }`

**Comment by tmakin** [comment]
The following error trap is working for me on IE11 inside my `success` handler
```
      const clipboardData = window['clipboardData'];
      if (clipboardData && clipboardData.getData) {
        if (!clipboardData.getData('Text')) {
          // display failure message
          return;
        }
      }
```

**Comment by dongyanghe** [comment]
因为之前可能已经有复制内容，会导致误判，所以我加了剪切板的内容对比，这样可能会比较完整：
```javascript
copyeSuccessFun:  function(e) {
        if (!ClipboardJS.isSupported()) {
            //  copyeErrorFun()
           console.log('复制失败');
            return
        }
        const clipboardData = window['clipboardData'];
        if (clipboardData && clipboardData.getData) {
            if (!clipboardData.getData('Text') || e.text != clipboardData.getData('Text')) {
                //  copyeErrorFun()
                console.log('复制失败');
                return;
            }
        }
        console.log('复制成功');
    }
```
