### ISSUE TITLE
Use the Clipboard API instead of execCommand

### ISSUE THREAD

**Issue by max-programming** [zenorocha/clipboard.js#770]
## 💥 Proposal

**Is your feature request related to a problem? Please describe**
Currently, the library uses `document.execCommand` which is a non-standard way nowadays. MDN says:
![image](https://user-images.githubusercontent.com/51731966/123073211-d95b6c00-d433-11eb-9b92-9f2734dc13d2.png)

**Describe the solution you'd like**
Instead of using the current method of copying and other stuff, consider using the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText)

**Describe alternatives you've considered**
The Clipboard API is the modern and safer way to work with. So we should go with that.

**Are you able to assist to bring the feature to reality?**
yes, I can...

**Additional context**
You can simply change the code like this:
```js
// before
textarea.select();
document.execCommand('copy');

// after
// But it returns a Promise so if there is something after this, put it into .then() or await it
navigator.clipboard.writeText(textarea.value); // Promise<void>
```

### Have you read the [Contributing Guidelines on issues](https://github.com/zenorocha/clipboard.js/blob/master/contributing.md)?

Yes

**Comment by ffxsam** [comment]
This would break support for Safari 12. I agree, Clipboard API should be the default, but `Document.execCommand()` should remain as a fallback.

**Comment by helderburato** [comment]
Hey @max-programming, thanks for the proposal.

It's in our roadmap, we just updating some last things, to use this new API, and keep a fallback to ensures the package keep working with the current approach.

**Comment by max-programming** [comment]
Keeping it as a fallback is a nice idea. I agree with that! 👍
