### ISSUE TITLE
Release v2.0.8 is actually v2.0.6

### ISSUE THREAD

**Issue by aurovrata** [zenorocha/clipboard.js#780]
the release [v2.0.8](https://github.com/zenorocha/clipboard.js/releases/tag/v2.0.8) has v2.0.6 in its `dist` folder.

**Comment by vitormalencar** [comment]
Hi @aurovrata we will fix  this issue in the next release thanks for pointing this out

**Comment by a76yyyy** [comment]
> I will try to do later this week =) Probably 28 is the day that I can go back and check this

It seems that there is no new release version now.

**Comment by y377** [comment]
me too !

**Comment by obetomuniz** [comment]
Hey all! Thanks for your patience! First of all, sorry for the delay in answer and fix.

That said, the original issue was fixed after [v2.0.9](https://github.com/zenorocha/clipboard.js/releases/tag/v2.0.9) gets properly released and tagged on GitHub and published on NPM.

I'll close the issue for now, but feel free to re-open if any doubt pops up. Thanks again for your patience.
