### ISSUE TITLE
ClipboardJS.copy is not a function

### ISSUE THREAD

**Issue by Aleksandr2015** [zenorocha/clipboard.js#784]
## 🐛 Bug Report

Hi. I'm use v2.0.8 and try to reproduce this demo https://github.com/zenorocha/clipboard.js/blob/master/demo/text-programmatic-copy.html as result in console this message: "Uncaught TypeError: ClipboardJS.copy is not a function"

jsfiddle as proof:
https://jsfiddle.net/zxg21kvw/4/

Where my mistake or this is bug?

### Browsers Affected
Chrome 95.0.4638.54

### Operational System
Windows 10

**Comment by ComtelJeremy** [comment]
It looks like this is an unreleased feature... I copied the development js files and it worked, but the function is missing in the packages that are released. Is it possible that this could be released soon?

**Comment by vetraz** [comment]
v2.0.8 was released on 10 March 2021
desired [change](https://github.com/zenorocha/clipboard.js/commit/44df750c9fa5b573d1429159d9d63c48523d2e9c) was committed on 18 May 2021
So yeah, it looks like it hasn't been published yet.

**Comment by jingyuLin1999** [comment]
I have the same problem. Has anyone solved it?
```
const textCopied = ClipboardJS.copy('123');
```

**Comment by cheapCoder** [comment]
> I have the same problem. Has anyone solved it?
> 
> ```
> const textCopied = ClipboardJS.copy('123');
> ```

I have the problem too, I solved it like this;

    const fakerBtn = document.createElement('button')
    new ClipboardJS(fakerBtn, {
        text: () => 123412341234,
    })
    fakerBtn.click()

**Comment by jingyuLin1999** [comment]
thanks for you reply. it resolve my problem, thanks.

**Comment by helderburato** [comment]
Hey @obetomuniz, could you check if it's related to our PR #749 ?

**Comment by obetomuniz** [comment]
Hey 👋 It's because the latest version was not released. @helderburato do you have rights to move the latest version forward to NPM? Ty

**Comment by obetomuniz** [comment]
Hey folks, as suggested, the latest code version on GitHub was not deployed properly. Now, the brand new code lives under [@v2.0.9](https://github.com/zenorocha/clipboard.js/releases/tag/v2.0.9) tagged and released on GitHub and published on NPM  🥂 

Thanks, A LOT you all for the report and pairing. 

Also, @Aleksandr2015, the proper API to use the new method `.copy` is declared [here](https://jsfiddle.net/dzpn82kr/5/). TL;DR, once it is a static method, you don't need to instantiate `ClipboardJS`.  Let me know if I can help with anything else. 

I'll close the issue for now, but feel free to re-open it if you need.
