### ISSUE TITLE
Improper versions has been tagged

### ISSUE THREAD

**Issue by zieliq** [zenorocha/clipboard.js#791]
Since v2.0.7 there is a difference between what is placed in github dist and correlated versions on cdnjs.com
Please take a look at https://github.com/zenorocha/clipboard.js/blob/v2.0.8/dist/clipboard.min.js

**Comment by obetomuniz** [comment]
Hey @zieliq , thanks A LOT for the report. You're right. It was fixed on [@v2.0.9](https://github.com/zenorocha/clipboard.js/releases/tag/v2.0.9)
