### ISSUE TITLE
fakeElement.remove()

### ISSUE THREAD

**Issue by john0916** [zenorocha/clipboard.js#818]
```
<a href="javascript:void(0)" class="copy" :data-clipboard-text="inviteUrl" @click="handleCopyClick">

var clipboard = new ClipboardJS('.copy')
    clipboard.on('success', function (e) {
      
      e.clearSelection();
    });

    clipboard.on('error', function (e) {
    
    });
```
ie 9,10,11 
error
对象不支持“remove”属性或方法(methods remove is no support)

**Comment by ohimesamaiti** [comment]
我也遇到同样问题，请问有解决方案吗？

**Comment by goozak** [comment]
I was able to fix this (at least in IE11) with this [element-remove](https://github.com/chenzhenxi/element-remove) polyfill mentioned on MDN's [Element.remove()](https://developer.mozilla.org/docs/Web/API/Element/remove#see_also) page.
