### ISSUE TITLE
Cut and Paste 

### ISSUE THREAD

**Issue by addcms** [zenorocha/clipboard.js#84]
Would it be possible to add "cut" and "paste"  functionality also?

**Comment by zenorocha** [comment]
Hey @addcms, we already provide `cut` command. But paste still not very supported in most browsers.

**Comment by pomeh** [comment]
@zenorocha thanks for building this library, this is awesome. I think you should add in the homepage why the paste functionality is not supported (privacy issues & cross-browser support). This will avoid many issues "how to paste" etc... ;)

**Comment by zenorocha** [comment]
Thanks @pomeh! I'm thinking about creating a FAQ page for this and other questions that always come up ;)
