### ISSUE TITLE
It doesn't work in Safari. 

### ISSUE THREAD

**Issue by LoveTBY** [zenorocha/clipboard.js#87]
why not just use document.execCommand('copy')?   chrome firfox IE edge ....oh, i didn't test opera
just like
          $('.pre-btn-copy').click(function () {
                var execCommandReady = document.execCommand('copy', false, '');
                if (execCommandReady) {
                    var text = document.getElementById('us-detail-c');
                    text.select();
                    document.execCommand('Copy');
                    console.log('ok')
                } else {
                    console.log('doesn\'t work');
                }
            });

**Comment by zenorocha** [comment]
That's exactly the API we use.
