### ISSUE TITLE
Add banner

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/clipboard.js#88]
https://www.npmjs.com/package/bannerify

**Comment by Vekat** [comment]
Looking into it.

**Comment by zenorocha** [comment]
Hey @Vekat,

I just used a patch from your fork and as soon as https://github.com/zemirco/bannerify/pull/4 gets merged we can use the original repo again.

**Comment by zenorocha** [comment]
Thanks for that!

**Comment by Vekat** [comment]
Nice!
