### ISSUE TITLE
clipboard.js (naturally) does not work with stopPropagation() on parents

### ISSUE THREAD

**Issue by Loilo** [zenorocha/clipboard.js#91]
So I tried to get to work clipboard.js with a button inside a modal.
Problem is, there's something like `$( "body" ).one( function () { modal.close(); } );`. Not exactly that code, but take it like that to keep this simple.
Of course the `click` event registered on the modal stops the event propagation to not get closed which means clipboard.js by design won't work inside that modal.

So my question: Is there a way around it?
Could there be a config option provided by the constructor which creates an additional "parent" for event delegation?
Sounds weird, I know, but that's the only kind-of-reasonable solution my mind came up with.

**Comment by zenorocha** [comment]
Hey @Loilo, as soon as I merge #75 you might be able to fix that ;)

**Comment by Loilo** [comment]
Yay :) Thanks!

**Comment by graphographer** [comment]
I'm having a similar problem wherein a Clipboard listener in a Bootstrap modal returns success, and shows the correct text and so on in the console (using your example code in the Readme)... but nothing is actually copied to the clipboard. I'm using v1.5.5 on Firefox with Bootstrap 3. It works as expected when the clicked element is not in a modal.

**Comment by kuba108** [comment]
Hey guys! Are you actually planning to fix this issue and when it'll be ready? I am kind of waiting for it. Thanks

**Comment by Sirence** [comment]
This issue is still present in the latest version, how can I fix this?

**Comment by zenorocha** [comment]
Have you guys tried passing a node or nodelist?

https://github.com/zenorocha/clipboard.js/blob/master/demo/constructor-node.html
https://github.com/zenorocha/clipboard.js/blob/master/demo/constructor-nodelist.html

**Comment by zenorocha** [comment]
@graphographer see #155
