### ISSUE TITLE
Preserving newlines in data-clipboard-text

### ISSUE THREAD

**Issue by dsl101** [zenorocha/clipboard.js#92]
I'm struggling to get newlines across to the clipboard. I don't know if this is related to [this issue](https://github.com/zenorocha/clipboard.js/pull/38). The clipboard is triggered on a `<td>` element, not a button, and all is working OK except newlines. 

The `<td>` looks something like:

    <td class="cpy" data-clipboard-text="Last updated: Mon, 12 Oct 2015 20:16:53 UTC\nLast commit id: xyz">Some text</td>

Note the `\n` in the `data-clipboard-text` attribute after the timestamp. Like this, it becomes a literal '\n' in the copied string. I then read that for data attributes, it's necessary to use `&#xa;` for newlines. Replacing it like this:

    <td class="cpy" data-clipboard-text="Last updated: Mon, 12 Oct 2015 20:16:53 UTC&#xa;Last commit id: xyz">Some text</td>

then works OK in the browser console if I print the text there. But what gets copied to the clipboard (testing in SublimeText3) is this:

    Last updated: Mon, 12 Oct 2015 20:16:53 UTCLast commit id: xyz

Note the newline character has simply vanished, and the text is run together. Is there any way to specify a newline in a `data-clipboard-text` attribute which will be preserved all the way?

**Comment by dsl101** [comment]
Looking closer with this code:

	var clipboard = new Clipboard(".cpy", {
		text: function(trigger) {
			var s = trigger.getAttribute("data-clipboard-text");
			console.log(s);
			for (var i = 0; i< s.length; i++) {
				console.log(i, s[i], s[i].charCodeAt(0));
			}
			return s;
		}
	});

I can see the character `&#xa;` does indeed appear in the string `s` as an ASCII character code 10, so I guess something is eating it later on?

I also tried `&#xd;`, `&#d;&#a;` and `&#xa;&#xd`. All codes are correctly represented in `s` above, but all vanish in what ends up in the clipboard.

**Comment by dsl101** [comment]
Ah ha. This is only happening with the minified version. So, this shows the problem:

    <script src="https://cdn.rawgit.com/zenorocha/clipboard.js/master/dist/clipboard.min.js"></script>

but this does not:

    <script src="https://cdn.rawgit.com/zenorocha/clipboard.js/master/dist/clipboard.js"></script>

Running a diff on the two isn't helping :)...

**Comment by dsl101** [comment]
And I ran my local copy of the standard version through uglifyjs (2.5.0 on Windows), and the minified version works as it should. So, I'll stick with a local copy for now - but obviously would be ideal for the CDN version to work too. I'm not sure if it's possible to write a test for that, since the string in JS looks fine - it's just what ends up in the clipboard which isn't...

**Comment by zenorocha** [comment]
Hey @dsl101,

Thanks for sharing your problem and solution ;)

This sounds like a bug with RawGit. You can try [cdnjs](https://cdnjs.com/libraries/clipboard.js) or [jsdelivr](https://www.jsdelivr.com/projects/clipboard.js).

**Comment by dsl101** [comment]
Thanks - both of those work fine. I didn't spot there were other sources though - might be worth updating the install instructions? I'll see if I can find somewhere to report the issue with rawgit.

Tx.

**Comment by dsl101** [comment]
I reported this to rawgit. Turns out the version being served by rawgit doesn't include [this](https://github.com/zenorocha/clipboard.js/pull/38) update. So the fake element type is still 'input' in the rawgit version, and hence line breaks are not supported.

I put in the rawgit ticket that I wasn't sure who needed to do what about that... If you need it, it's [this](https://github.com/rgrove/rawgit/issues/82) issue.

**Comment by rgrove** [comment]
RawGit's CDN [caches files permanently based on their URL](http://rawgit.com/faq#cdn-ttl), which is why the RawGit website and docs recommend using tags or commit refs in CDN URLs, not branches. In this case, the file was cached based on a branch URL at a point in time prior to the desired update, so that URL will always reflect that version of the file. To refer to a specific version of the file, use a URL containing a commit ref or tag rather than a branch.

**Comment by delia-curiel** [comment]
@zenorocha hi, I know this issue is quite old but I keep on having this problem, the one described by @dsl101 at first...... The newline character is vanished when copied to the clipboard

**Comment by polyamide** [comment]
To support new line, you have to use the `<textarea>` to hold the text.

To do this, you can assign a target which points to a real, visible `<textarea>` on the page.
Or, by using the `text` option or the `data-clipboard-text` attribute, which will internally using a out of viewport `<textarea>` to do the job.

Here's the problem: if the `<textarea>`'s `white-space` property somehow got overwritten with value other then `pre-wrap`.
It will cause browsers to not copying the new line character.

My suggestion is to explicitly add `white-space: pre-wrap` to the internal `<textarea>`, so outside style sheets won't mess up the behavior.
This will make sure, at least, the `text` option and `data-clipboard-text` attribute will work the way it should.

**Comment by richardwm91** [comment]
try change you temp to textarea:

```
 function copyToClipboard(valor) { //my text value
            var $temp = $("<textarea>");
            $("body").append($temp);
            $temp.val(valor).select();
            document.execCommand("copy");
            $temp.remove();
        }
```
