### ISSUE TITLE
"Unspecified error." when trying to copy a table in IE11 (workaround included).

### ISSUE THREAD

**Issue by Poryhack** [zenorocha/clipboard.js#93]
The following example will fail to copy in IE11 and the text `"Unspecified error."` will show up in the console.

```html
    <!-- Trigger -->
    <button class="btn clipboard-button" data-clipboard-target="#foo">Copy!</button>

    <!-- Target -->
    <div>
        <table id="foo">
            <tr>
                <th>First name</th>
                <th>Last name</th>
            </tr>
            <tr>
                <td>John</td>
                <td>Doe</td>
            </tr>
            <tr>
                <td>Jane</td>
                <td>Doe</td>
            </tr>
        </table>
    </div>
```

However if the target element is a `div` wrapping the desired `table`, all works well.

```html
    <!-- Trigger -->
    <button class="btn clipboard-button" data-clipboard-target="#foo">Copy!</button>

    <!-- Target -->
    <div id="foo">
        <table>
            <tr>
                <th>First name</th>
                <th>Last name</th>
            </tr>
            <tr>
                <td>John</td>
                <td>Doe</td>
            </tr>
            <tr>
                <td>Jane</td>
                <td>Doe</td>
            </tr>
        </table>
    </div>
```

Specifics: IE11 version 11.0.9600.18015 running in edge mode on Windows 7.

**Comment by zenorocha** [comment]
Thanks for reporting @Poryhack! I just moved it to the [Know issues](https://github.com/zenorocha/clipboard.js/wiki/Known-Issues) page.

**Comment by ericnkatz** [comment]
Just wanted to add comment for anyone else trying to find this its now on the [Known Limitations](https://github.com/zenorocha/clipboard.js/wiki/Known-Limitations). 

> On IE11 you can't copy a <table> element. A simple workaround is wrapping it with a <div> then all works well.

**Comment by ericnkatz** [comment]
@zenorocha may be worth throwing a specific exception letting users know they are trying to do this and that it is not supported.
