### ISSUE TITLE
Followed instructions; not working.

### ISSUE THREAD

**Issue by F-John** [zenorocha/clipboard.js#94]
Here is my sample page using the instructions found on the Readme.md: http://design-legion.com/test.html

<script src="https://cdn.rawgit.com/zenorocha/clipboard.js/master/dist/clipboard.js"></script>

Then included 3 of the example codes provided. Effect: not working as described.

Copied source code from https://zenorocha.github.io/clipboard.js/ and discovered there are some dependencies in theincluded scripts after the footer. Current test page does not include these per instructions:
Removing this breaks copying action 
      'bower_components/highlightjs/highlight.pack.min.js'

We already know this is required 
     'dist/clipboard.min.js'

Removing this breaks copying action
     'assets/scripts/demos.js'

Removing this effect snippet copying but not needed for my test page 
     'assets/scripts/snippets.js'
    'assets/scripts/tooltips.js'

**Comment by zenorocha** [comment]
Hey @F-John,

It is working as expected. Here's a [minimal example](http://jsfiddle.net/ken5fjb6/1/) so you can start from that.

Noticed that clipboard.js does not include CSS or any Tooltip library. That's up to you to develop. What you've seen in the demo site was built using [GitHub's Primer](http://primercss.io/). You may want to check that if you're looking for a similar look and feel.

**Comment by F-John** [comment]
Thank you, however  that page does not help me see and understand how this is working.

Can you show me this with an inline HTML page example? 

(I don't know how to export the results box from JSFiddle to a simple HTML example.)

**Comment by zenorocha** [comment]
Here it is:

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title></title>
</head>
<body>
	<input id="foo" type="text" value="hello">
	<button class="btn" data-clipboard-action="copy" data-clipboard-target="#foo">Copy</button>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.4.2/clipboard.min.js"></script>
	<script>
	var clipboard = new Clipboard('.btn');

	clipboard.on('success', function(e) {
		console.log(e);
	});

	clipboard.on('error', function(e) {
	    console.log(e);
	});
	</script>
</body>
</html>
```

**Comment by F-John** [comment]
Thank you.

**Comment by edwardm** [comment]
I think this page (https://zenorocha.github.io/clipboard.js/), should mention that GitHub's Primer is used for the tooltip part for user feedback. This whole time I've been wondering why the tooltip was not showing. No biggie, I just simply used the event triggers to show an alert instead of console logging in the mean time.

**Comment by jlukic** [comment]
I think it might be useful to include an example of using a DOM element, instead of a selector to attach copy events. 

I feel like in most controlled DOM environments (angular, react, meteor etc.) it's the most common workflow, but doesnt seem to be addressed by the docs.

**Comment by zenorocha** [comment]
Have you seen https://github.com/zenorocha/clipboard.js/tree/master/demo @jlukic?

Feel free to send a pull request.

**Comment by zenorocha** [comment]
<img width="481" alt="screen shot 2016-04-03 at 9 12 02 pm" src="https://cloud.githubusercontent.com/assets/398893/14238028/c5399540-f9e0-11e5-8bcb-288ab2c610d2.png">
