### ISSUE TITLE
Event "success" fires but not copies to clipbord os

### ISSUE THREAD

**Issue by sdilshod** [zenorocha/clipboard.js#96]
I attempt to integrate it with my app, but i'm little confusion. Even "success" fires and event.text gets result. But not copies to clipboard of my OS

OS - linux(Ubuntu 14.04)

What i'm doing wrong? May be i mess whatever?

here output of console

![screenshot from 2015-10-17 11 57 07](https://cloud.githubusercontent.com/assets/242699/10557432/3fd53ce6-74c6-11e5-9a11-d5b52d41d114.png)

**Comment by zenorocha** [comment]
Hey @sdilshod,

I see you're using Firefox. Is it version 41 or plus?

Here's a more isolated snippet so you can test it: http://jsfiddle.net/zenorocha/tdp2ubn4/

**Comment by sdilshod** [comment]
Yes FireFox and version 41+
![screenshot from 2015-10-18 17 20 38](https://cloud.githubusercontent.com/assets/242699/10564027/a08b8e40-75bc-11e5-933f-befc6dc44c05.png)

**Comment by sdilshod** [comment]
Thank for replay. It was problem with input. I made it hidden. When change to visible text input all works. 
Is there way to copy from invisible input? @zenorocha

**Comment by sdilshod** [comment]
This solved with data-clipboard-text attribute. Thanks again. Question solved

**Comment by zenorocha** [comment]
Cool, thanks for sharing your solution ;)
