### ISSUE TITLE
Error after installing in my Meteor application

### ISSUE THREAD

**Issue by aadamsx** [zenorocha/clipboard.js#97]
I keep getting the following error:

node_modules/clipboard/node_modules/babelify/node_modules/babel-core/node_modules/convert-source-map/test/fixtures/map-file-comment-double-slash.css:
   missing '{' near line 15:1

**Comment by zenorocha** [comment]
@lnmunhoz can you check that?

**Comment by aadamsx** [comment]
I was able to get things working in Meteor by uninstalling the npm your package and just copying over the min.js file.  This works great.

Thanks for this amazing package!

**Comment by lnmunhoz** [comment]
I'm going to check it out @zenorocha

**Comment by lnmunhoz** [comment]
@aadamsx What meteor version are you using?
