### ISSUE TITLE
IE: Declining permission calls success callback

### ISSUE THREAD

**Issue by aarontgrogg** [zenorocha/clipboard.js#98]
In IE (9-11), clicking the copy button the first time per page load asks the user for permission to access the clipboard.  If the user clicks the Don't Allow button, the success callback is still called; I would expect that to call the failure option, or at least pass some other parameter that I can hook another callback onto.

![ie-clipboard-confirmation](https://cloud.githubusercontent.com/assets/366755/10603231/2de29304-771d-11e5-87a0-532aac839e2a.png)

**Comment by ApfelUser** [comment]
Duplicate of #77

**Comment by aarontgrogg** [comment]
Sorry, didn't find that issue when searching, closing this one now.
