### ISSUE TITLE
Irregularities copying FF vs Chrome

### ISSUE THREAD

**Issue by aadamsx** [zenorocha/clipboard.js#99]
I'm using Quill Editor to provide rich text editing into my application.

In mongo when I save off a simple edit session, it looks something like this:

```
<div class="ql-editor ql-content" contenteditable="true">This</div><div class="ql-editor ql-content" contenteditable="true"><br></div><div class="ql-editor ql-content" contenteditable="true">text</div><div class="ql-editor ql-content" contenteditable="true"><br></div><div class="ql-editor ql-content" contenteditable="true">is</div><div class="ql-editor ql-content" contenteditable="true"><br></div><div class="ql-editor ql-content" contenteditable="true"><b>BOLD</b></div><div class="ql-paste-manager" contenteditable="true"><br></div>
```

Using Meteor Blaze and Handlebars my code to target this html looks like this:

```
                      <div class="contents regular">
                        <div id="message-{{messageId}}">
                          {{{message}}}
                        </div>
                      </div>
                      <span id="copy-{{messageId}}" alt="Copy to clipboard" data-clipboard-target="#message-{{messageId}}" data-id="{{messageId}}" class="" style="float: right; margin-right: 15px; cursor: pointer;">
                        <i class="fa fa-clipboard"></i>
                      </span>
```
I also have code to allow me to see what is copied to the clipboard:
```
  var clipboard = new Clipboard('span[id^="copy-"]');
  clipboard.on('success', function (e) {
    console.info('Action:', e.action);
    console.info('Text:', e.text);
    console.info('Trigger:', e.trigger);
  });
```

When I copy the text to the clipboard, all I see in this example is this in the console:
```
Action: copy
messages-detail.js?005609202faf1271a61336d16a44247de0aa130c:30 Text: 
This

text

is

BOLD
```

I don't/can't see the "behind-the-seens" formatting going on in the Text attribute.  So when I copy this text from the clipboard to Word, the word BOLD is bolded, but if I copy this from the clipboard back into Quill editor, all the formatting and any color stays, but I loose the bold in the BOLD text.

Any help see what formatting is going on in the clipboard is appreciated.

**Comment by aadamsx** [comment]
After further research. The bold seems to be working in FF but not in Chrome.  

I have another example...

When I copy from Chrome rich-text (with embedded HTML) to the Quill Editor with clipboar.js, looking at the binary of the clipboard, the bolded text has this for embedded HTML:
```
<b style="box-sizing: border-box; -webkit-font-smoothing: antialiased; font-weight: 700; color: rgb(204, 0,0); font-family: Arial, sans-serif; font-size: 12pt; background-color: inherit;"><br class="Apple-interchange-newline">*** Bold Text ***Â</b>
```

In FF the binary for the text looks like this:
```
<b style="color: rgb(204, 0,0); font-family: Arial, sans-serif; font-size: 12pt;">*** Bold Text ***</b>
```
In Chrome the *** Bold Text *** is not bolded, in FF it is.

This is the mongo field saved from Quill when in Chrome:
```
<div class="ql-editor ql-content" contenteditable="true"><br></div><div class="ql-editor ql-content" contenteditable="true"><span style="color: rgb(204, 0, 0); font-family: Arial, sans-serif; font-size: 12pt;">*****Bold Text*****&nbsp;</span></div><div class="ql-paste-manager" contenteditable="true"><br></div>
```

Here, the ```<b``` has been replace with a ```<span>```

This is the mongo field saved from Quill when in FF:
```
<div class="ql-editor ql-content" contenteditable="true"><b style="color: rgb(204, 0, 0); font-family: Arial,sans-serif; font-size: 12pt;">*****Bold Text*****&nbsp;</b></div><div class="ql-editor ql-content" contenteditable="true"><br></div><div class="ql-paste-manager" contenteditable="true"><br></div>
```

Is this clipboard.js difference between browsers or Quill Editor?

**Comment by zenorocha** [comment]
Hey @aadamsx,

You can copy the HTML content by defining a text function, as described in the documentation.

```
new Clipboard('.btn', {
    text: function() {
        return document.querySelector('body').innerHTML
    }
});
```

There are no irregularities between Firefox and Chrome. You should fill an issue with Quill Editor if you're having trouble using it.

**Comment by aadamsx** [comment]
Right, but the issue is from HTML copied from clipboard, not with Quill right?  I have html text on the screen, I have a target, and when I copy that target and examine with clipboard, there is a difference between FF and Chrome...

**Comment by zenorocha** [comment]
Are you sure that Quill doesn't generate a different string for each browser? Can you confirm that all demos from http://zenorocha.github.io/clipboard.js have the same output on Firefox and Chrome?

If you still think that this a problem with clipboard.js, please create a JSFiddle with an isolated code sample so we can fix that.

**Comment by aadamsx** [comment]
Ok -- when implementing your solution I get an error:


```  
new Clipboard('span[id^="copy-"]', {
      text: function(trigger) {
        debugger;
        var id = trigger.dataset.id;
        var clip = document.querySelector('#message-' + id).innerHTML;
        console.log('message id: ' + id + ' clip: ' + clip);
        return clip;
      }
  });
```

With multiple message all with a different Id:

```
<div id="message-{{messageId}}">{{{message}}}</div>
```

And matching targets:

```
<span id="copy-{{messageId}}" alt="Copy to clipboard" data-id="{{messageId}}"><i class="fa fa-clipboard"></i></span>
```

I get this error:

```
Uncaught Error: Missing required attributes, use either "target" or "text" : clipboard.min.js:7 
```

**Comment by zenorocha** [comment]
Again, can you put that on a JSFiddle, JSBin or something?

**Comment by aadamsx** [comment]
Yep, fixed this while trying to build a JSFiddle... thanks.

But this code:

```
new Clipboard('span[id^="copy-"]', {
      text: function(trigger) {
        debugger;
        var id = trigger.dataset.id;
        var clip = document.querySelector('#message-' + id).innerHTML;
        console.log('message id: ' + id + ' clip: ' + clip);
        return clip;
      }
  });
```
gives me the raw html and not the text with embedded html.

**Comment by zenorocha** [comment]
Cool, nice to hear that. Now you need to figure how to grab that info from Quill.

**Comment by aadamsx** [comment]
I'm just copying a div with elements and text underneath it, nothing to do with Quill yet.

This code:
```
new Clipboard('span[id^="copy-"]')
```

Along with this target on the element:
```
<span id="copy-{{messageId}}" data-clipboard-target="#message-{{messageId}}" data-id="{{messageId}}"</span>
```

Will give me **Bold** text with embedded html that I cannot see on the clipboard, and not the raw html like this ```<div><b>Bold</b>text</div>```

But calling this:
```
var clip = document.querySelector('#message-' + id).innerHTML;
```
will give me the raw on the clipboard.

**Comment by zenorocha** [comment]
clipboard.js only copies text (strings), not formatted content.

**Comment by aadamsx** [comment]
Ah, it's the difference between the target and text attribute on Clipboard.  Thanks.
